/****** Object:  StoredProcedure [dbo].[VALIDACION_SERIE]    Script Date: 06/09/2014 10:48:12 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[VALIDACION_SERIE]') AND type in (N'P', N'PC'))
DROP PROCEDURE [dbo].[VALIDACION_SERIE]
GO

CREATE PROCEDURE [dbo].[VALIDACION_SERIE]
	@IDPROCESO		NUMERIC,
	@CLIENTE_ID		VARCHAR(15),
	@NRO_BULTO		VARCHAR(100),
	@NRO_SERIE		VARCHAR(50) OUTPUT,
	@SERIE_ESP		VARCHAR(1),
	@RETORNO		VARCHAR(2)	OUTPUT
AS
BEGIN
	/*
		1.	Serie incorrecta, no empieza con 1S.
		2.	Longitud de serie incorrecta.
		3.	Serie ingresada.
		4.	Serie escaneada incorrecta.
	*/
	DECLARE @CONT	NUMERIC
	DECLARE @SRI	VARCHAR(2)
	DECLARE @SKU	VARCHAR(50)
	DECLARE @DIGITO	VARCHAR(2)
	DECLARE @SERIED	VARCHAR(50)
	DECLARE @SKUD	VARCHAR(30)
	DECLARE @2SKU	VARCHAR(2)

	SELECT	@SKU=DD.PRODUCTO_ID
	FROM	DET_DOCUMENTO DD INNER JOIN DET_DOCUMENTO_TRANSACCION DDT
			ON(DD.DOCUMENTO_ID=DDT.DOCUMENTO_ID AND DD.NRO_LINEA=DDT.NRO_LINEA_DOC)
			INNER JOIN RL_DET_DOC_TRANS_POSICION RL
			ON(DDT.DOC_TRANS_ID=RL.DOC_TRANS_ID AND DDT.NRO_LINEA_TRANS=RL.NRO_LINEA_TRANS)
	WHERE	DD.CLIENTE_ID=@CLIENTE_ID
			AND DD.NRO_BULTO=@NRO_BULTO
				
	--1.	ALGORITMO. SE QUE TIENE QUE COMENZAR CON 1S.
	IF(@SERIE_ESP='1') BEGIN
		PRINT('SERIE ESPECIFICA.')
		
		IF (LEN(@NRO_SERIE)<>16AND LEN(@NRO_SERIE)<>20)BEGIN
			SET @RETORNO='2'
			RETURN		
		END
		--SE VALIDA EL DIGITO VERIFICADOR
		SET @DIGITO=SUBSTRING(@NRO_SERIE,1,2)
		IF @DIGITO <>'1S'BEGIN
			SET @RETORNO='1'
			RETURN
		END
		
		--CASO 2.
		IF LEN(@NRO_SERIE)=16 BEGIN
			PRINT('CADENA DE 16')
			SET @SKUD=SUBSTRING(@NRO_SERIE,3,7)
			SET @SERIED=SUBSTRING(@NRO_SERIE,10,7)
			
			IF @SKU <> @SKUD BEGIN
				--LOS SKU NO PUEDEN SER DIFERENTES.
				SET @RETORNO='4';
				RETURN		
			END
		END --IF LEN(@LECTURA)=16

		IF LEN(@NRO_SERIE)=20 BEGIN
			
			SET @2SKU=SUBSTRING(@NRO_SERIE,3,4)
			
			IF (@SKU <> @SKUD)AND((@2SKU<>'10')AND(@2SKU<>'20')AND(@2SKU<>'60')AND(@2SKU<>'70')) BEGIN
				--LOS SKU NO PUEDEN SER DIFERENTES.
				SET @RETORNO='4';
				RETURN		
			END
						
			IF ((@2SKU='10')OR(@2SKU='20')OR(@2SKU='60')OR(@2SKU='70'))BEGIN
				SET @SKUD=SUBSTRING(@NRO_SERIE,3,10)
				
				IF (@SKU <> @SKUD)BEGIN
					--LOS SKU NO PUEDEN SER DIFERENTES.
					SET @RETORNO='4';
					RETURN		
				END				
				--CASO 4.
				SET @SERIED=SUBSTRING(@NRO_SERIE,13,8)
				PRINT('ESTE ES EL CASO 4.')
			END
			ELSE
			BEGIN
				SET @SKUD=SUBSTRING(@NRO_SERIE,3,8)
				IF (@SKU <> @SKUD)BEGIN
					--LOS SKU NO PUEDEN SER DIFERENTES.
					SET @RETORNO='4';
					RETURN		
				END		
				--CASO 3.
				SET @SERIED=SUBSTRING(@NRO_SERIE,11,10)
				PRINT('ESTE ES EL CASO 3.')
			END
		END		
		
		SET @NRO_SERIE=@SERIED 
	END
	--3.	SERIE REPETIDA.
	SELECT	@CONT=COUNT(*)
	FROM	DET_DOCUMENTO DD INNER JOIN DET_DOCUMENTO_TRANSACCION DDT
			ON(DD.DOCUMENTO_ID=DDT.DOCUMENTO_ID AND DD.NRO_LINEA=DDT.NRO_LINEA_DOC)
			INNER JOIN RL_DET_DOC_TRANS_POSICION RL
			ON(DDT.DOC_TRANS_ID=RL.DOC_TRANS_ID AND DDT.NRO_LINEA_TRANS=RL.NRO_LINEA_TRANS)
	WHERE	DD.CLIENTE_ID=@CLIENTE_ID
			AND DD.PRODUCTO_ID=@SKU
			AND DD.NRO_SERIE=@NRO_SERIE
	
	IF @CONT >0 BEGIN
		SET @RETORNO ='3'
		RETURN
	END 		

	SET @RETORNO ='0'

END --FIN PROCEDURE.






GO


