
ALTER TABLE [dbo].[TMP_EMPAQUE_CONTENEDORA] ADD [NRO_UCEMPAQUETADO] [varchar](100) NULL
ALTER TABLE [dbo].[TMP_EMPAQUE_CONTENEDORA] ADD [UCEMPAQUETADO_MEDIDAS] [varchar](100) NULL
ALTER TABLE [dbo].[TMP_EMPAQUE_CONTENEDORA] ADD [FECHA_UCEMPAQUETADO] [datetime] NULL
ALTER TABLE [dbo].[TMP_EMPAQUE_CONTENEDORA] ADD [UCEMPAQUETADO_PESO] [numeric](20, 5) NULL
