/****** Object:  StoredProcedure [dbo].[MOB_PICKING_DESCOMPONER_SERIE_ESPECIFICA]    Script Date: 07/03/2014 12:40:45 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[MOB_PICKING_DESCOMPONER_SERIE_ESPECIFICA]') AND type in (N'P', N'PC'))
DROP PROCEDURE [dbo].[MOB_PICKING_DESCOMPONER_SERIE_ESPECIFICA]
GO

CREATE PROCEDURE [dbo].[MOB_PICKING_DESCOMPONER_SERIE_ESPECIFICA](
	@VIAJE_ID		VARCHAR(100)	OUTPUT,
	@NRO_PALLET		VARCHAR(100)	OUTPUT,
	@NRO_SERIE		VARCHAR(100)	OUTPUT,
	@ERROR			VARCHAR(100)	OUTPUT
)AS
BEGIN

	/*	----------------------------------------
		1.	Serie incorrecta, no empieza con 1S.
		2.	Longitud de serie incorrecta.
		3.	Serie ingresada.
		4.	Serie escaneada incorrecta.
		----------------------------------------*/
	DECLARE @SKU		VARCHAR(30)
	DECLARE @SKUD		VARCHAR(30)
	DECLARE @DIGITO		VARCHAR(2)
	DECLARE @RETORNO	VARCHAR(10)
	DECLARE @SERIED		VARCHAR(100)
	
	SET @ERROR='0'
	
	SET @NRO_SERIE=REPLACE(@NRO_SERIE,'-','')
	
	SELECT	@SKU=REPLACE(PRODUCTO_ID,'-','')
	FROM	PICKING 
	WHERE	VIAJE_ID=@VIAJE_ID
			AND PROP1=@NRO_PALLET

	--DESCOMPONGO LA SERIE DEPENDIENDO DE SU LONGITUD.
	IF (LEN(@NRO_SERIE)<>16AND LEN(@NRO_SERIE)<>20)BEGIN
		SET @ERROR='2'		
		RETURN
	END
	--SE VALIDA EL DIGITO VERIFICADOR
	SET @DIGITO=SUBSTRING(@NRO_SERIE,1,2)
	IF @DIGITO <>'1S'BEGIN
		SET @ERROR='1'
		RETURN
	END
		
	--CASO 2.
	IF LEN(@NRO_SERIE)=16 BEGIN
		PRINT('CADENA DE 16')
		SET @SKUD=SUBSTRING(@NRO_SERIE,3,7)
		SET @SERIED=SUBSTRING(@NRO_SERIE,10,7)
		
		IF @SKU <> @SKUD BEGIN
			--LOS SKU NO PUEDEN SER DIFERENTES.
			SET @ERROR='4';
			RETURN		
		END
	END --IF LEN(@LECTURA)=16

	IF LEN(@NRO_SERIE)=20 BEGIN
		
		SET @SKUD=SUBSTRING(@NRO_SERIE,3,2)
		/*
		IF (@SKU <> @SKUD)AND((@SKUD<>'10')AND(@SKUD<>'20')AND(@SKUD<>'60')AND(@SKUD<>'70')) BEGIN
			--LOS SKU NO PUEDEN SER DIFERENTES.
			SET @ERROR='4';
			RETURN
		END
		*/			
		IF ((@SKUD='10')OR(@SKUD='20')OR(@SKUD='60')OR(@SKUD='70'))BEGIN
			--PRINT('ESTE ES EL CASO 4.')
			SET @SKUD=SUBSTRING(@NRO_SERIE,3,10)
			
			IF (@SKU <> @SKUD)BEGIN
				--LOS SKU NO PUEDEN SER DIFERENTES.
				SET @ERROR='4';
				RETURN
			END				
			--CASO 4.
			SET @SERIED=SUBSTRING(@NRO_SERIE,13,8)
		END
		ELSE
		BEGIN
			--PRINT('ESTE ES EL CASO 3.')
			SET @SKUD=SUBSTRING(@NRO_SERIE,3,8)
			IF (@SKU <> @SKUD)BEGIN
				--LOS SKU NO PUEDEN SER DIFERENTES.
				SET @ERROR='4';
				RETURN
			END		
			--CASO 3.
			SET @SERIED=SUBSTRING(@NRO_SERIE,11,10)

		END
	END		
		
	SET @NRO_SERIE=@SERIED 	

END

GO


