
CREATE TABLE DBO.RECEPCION_GUARDADO(
	RCP_ID			NUMERIC(20,0)	NOT NULL IDENTITY (1,1),
	ORDEN_DE_COMPRA	VARCHAR(100),
	CLIENTE_ID		VARCHAR(15)		NOT NULL,
	PRODUCTO_ID		VARCHAR(15)		NOT NULL,
	CANTIDAD		NUMERIC(20,5)	NOT NULL,
	NRO_LOTE		VARCHAR(50),
	NRO_PARTIDA		VARCHAR(50),
	F_VENCIMIENTO	DATE,
	NRO_PALLET		VARCHAR(100),
	USUARIO_ID		VARCHAR(100),
	F_INGRESO		VARCHAR(100),
	TERMINAL		VARCHAR(100),
	PROCESADO		VARCHAR(1)
)
GO

ALTER TABLE DBO.RECEPCION_GUARDADO
ADD CONSTRAINT PK_RECEPCION_GUARDADO PRIMARY KEY(RCP_ID)