
CREATE PROCEDURE [dbo].[MOB_RG_VALIDAR_OC]
@CLIENTE_ID	AS VARCHAR(15),
@ODC		AS VARCHAR(50),
@STATUS		AS CHAR(1) 			OUTPUT

AS
BEGIN
	DECLARE @PRODUCTO_ID	VARCHAR(30)
	DECLARE @CONT			SMALLINT
	DECLARE @DOC_EXT		VARCHAR(100)
	


	SELECT 	TOP 1
			@CONT=count(SD.DOC_EXT)
	FROM 	SYS_INT_DOCUMENTO SD INNER JOIN SYS_INT_DET_DOCUMENTO SDD  ON(SD.CLIENTE_ID=SDD.CLIENTE_ID AND SD.DOC_EXT=SDD.DOC_EXT)
	WHERE 	ORDEN_DE_COMPRA=@ODC
			AND SD.CLIENTE_ID=@CLIENTE_ID
			and SDD.fecha_estado_gt is null
			and SDD.estado_gt is null

	IF @CONT>0 --EXISTE EN LA ODC
	BEGIN
		set @status='1'
	END ELSE BEGIN
		SET @STATUS='0'
	END

END

