CREATE PROCEDURE DBO.MOB_RG_VALIDA_PALLET
@NRO_PALLET	VARCHAR(100),
@STATUS		VARCHAR(1)	OUTPUT
AS
BEGIN
	DECLARE @COUNT	NUMERIC(20,0)
	
	SELECT	@COUNT=COUNT(RL.RL_ID)
	FROM	DET_DOCUMENTO DD INNER JOIN DET_DOCUMENTO_TRANSACCION DDT (NOLOCK)
			ON(DD.DOCUMENTO_ID=DDT.DOCUMENTO_ID AND DD.NRO_LINEA=DDT.NRO_LINEA_DOC)
			INNER JOIN RL_DET_DOC_TRANS_POSICION RL (NOLOCK)
			ON(DDT.DOC_TRANS_ID=RL.DOC_TRANS_ID AND DDT.NRO_LINEA_TRANS=RL.NRO_LINEA_TRANS)
	WHERE	DD.PROP1=@NRO_PALLET
		
	IF @COUNT>0 BEGIN
		SET @STATUS='1'
	END ELSE BEGIN
		SET @STATUS='0'
	END
END