
/****** Object:  StoredProcedure [dbo].[MOB_RG_REGISTRO_TEMPORAL]    Script Date: 12/14/2015 12:30:50 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[MOB_RG_REGISTRO_TEMPORAL]') AND type in (N'P', N'PC'))
DROP PROCEDURE [dbo].[MOB_RG_REGISTRO_TEMPORAL]
GO

CREATE PROCEDURE [dbo].[MOB_RG_REGISTRO_TEMPORAL]
@OC				VARCHAR(100),
@CLIENTE_ID		VARCHAR(100),
@PRODUCTO_ID	VARCHAR(100),
@CANTIDAD		NUMERIC(20,5),
@NRO_LOTE		VARCHAR(100),
@NRO_PARTIDA	VARCHAR(100),
@F_VENCIMIENTO	VARCHAR(100),
@NRO_PALLET		VARCHAR(100),
@USUARIO_ID		VARCHAR(100)
AS
BEGIN
	DECLARE @F_INGRESO	DATETIME,
			@TERMINAL	VARCHAR(100),
			@PROCESADO	VARCHAR(1),
			@FVTO		DATETIME,
			@CONT		VARCHAR(1),
			@NUM_BULTO	NUMERIC(38)
			
	SET @TERMINAL=HOST_NAME()
	SET	@PROCESADO='0'
	SET @F_INGRESO=GETDATE()
	SET @FVTO = ISNULL(CAST(@F_VENCIMIENTO AS DATETIME),NULL)
	
	SELECT	@CONT=ISNULL(FLG_BULTO,'0')
	FROM	PRODUCTO
	WHERE	CLIENTE_ID=@CLIENTE_ID
			AND PRODUCTO_ID=@PRODUCTO_ID 
			
	IF @CONT='1' BEGIN
	
		EXEC dbo.GET_VALUE_FOR_SEQUENCE 'CONTENEDORA',@NUM_BULTO OUTPUT
	END
	
	INSERT INTO RECEPCION_GUARDADO (ORDEN_DE_COMPRA,CLIENTE_ID,PRODUCTO_ID,CANTIDAD,NRO_LOTE,NRO_PARTIDA,F_VENCIMIENTO,NRO_PALLET,USUARIO_ID,F_INGRESO,TERMINAL,PROCESADO,NRO_BULTO)
	VALUES(@OC, @CLIENTE_ID, @PRODUCTO_ID,@CANTIDAD, @NRO_LOTE, @NRO_PARTIDA, @FVTO, @NRO_PALLET, @USUARIO_ID,@F_INGRESO,@TERMINAL,@PROCESADO,@NUM_BULTO)

END
GO


