ALTER TABLE CLIENTE_PARAMETROS ADD FLG_EMP_LOTE_PARTIDA VARCHAR(1) DEFAULT('0')

GO
INSERT INTO SYS_DET_TABLA VALUES('CLIENTE_PARAMETROS','FLG_EMP_LOTE_PARTIDA','EMPAQUE SOLICITA LOTE-PARTIDA','S','1','0')

GO
INSERT INTO sys_tabColumns VALUES('CLIENTE_PARAMETROS',	'FLG_EMP_LOTE_PARTIDA',	24,	'CHAR',	'Y',	1,	NULL,	NULL,	1,	NULL)

GO
UPDATE CLIENTE_PARAMETROS SET FLG_EMP_LOTE_PARTIDA='0' WHERE FLG_EMP_LOTE_PARTIDA IS NULL