ALTER PROCEDURE [dbo].[VALIDA_CODIGO_RODC]

@CODIGO		AS VARCHAR(50),
@ODC			AS VARCHAR(50),
@CLIENTE_ID	AS VARCHAR(15),
@STATUS		AS CHAR(1) 			OUTPUT,
@PROD_ID		AS VARCHAR(30) 	OUTPUT,
@UNIDAD_ID	AS VARCHAR(5)		OUTPUT,
@REMANENTE	AS FLOAT			OUTPUT
AS
BEGIN
	DECLARE @PRODUCTO_ID	VARCHAR(30)
	DECLARE @CONT			SMALLINT
	DECLARE @DOC_EXT		VARCHAR(100)
	

	--Inicializo los de salida
	set @STATUS=null
	set @prod_id=null
	set @unidad_id=null

	SELECT 	@CONT=COUNT(*)
	FROM	PRODUCTO
	WHERE 	CLIENTE_ID=@CLIENTE_ID
			AND PRODUCTO_ID=@CODIGO

	IF @CONT=1 --PRODUCTO_ID
	BEGIN
		SET @PRODUCTO_ID=@CODIGO
	
		SELECT 	@PROD_ID=PRODUCTO_ID, @UNIDAD_ID=UNIDAD_ID FROM PRODUCTO WHERE CLIENTE_ID=@CLIENTE_ID AND PRODUCTO_ID=@PRODUCTO_ID

		SET @CONT=NULL

		SELECT 	@CONT=COUNT(*)
		FROM 	SYS_INT_DOCUMENTO SD INNER JOIN SYS_INT_DET_DOCUMENTO SDD  ON(SD.CLIENTE_ID=SDD.CLIENTE_ID AND SD.DOC_EXT=SDD.DOC_EXT)
		WHERE 	ORDEN_DE_COMPRA=@ODC
				AND SD.CLIENTE_ID=@CLIENTE_ID
				AND SDD.PRODUCTO_ID=@PRODUCTO_ID
				AND SDD.ESTADO_GT IS NULL
				AND SDD.FECHA_ESTADO_GT IS NULL

		SELECT 	TOP 1
				@DOC_EXT=SD.DOC_EXT
		FROM 	SYS_INT_DOCUMENTO SD INNER JOIN SYS_INT_DET_DOCUMENTO SDD  ON(SD.CLIENTE_ID=SDD.CLIENTE_ID AND SD.DOC_EXT=SDD.DOC_EXT)
		WHERE 	ORDEN_DE_COMPRA=@ODC
				AND PRODUCTO_ID=@PRODUCTO_ID
				AND SD.CLIENTE_ID=@CLIENTE_ID
				AND SDD.ESTADO_GT IS NULL

		Select 	@REMANENTE=sum(cantidad_solicitada)
		from	sys_int_det_documento
		where	doc_ext=@doc_ext
				and fecha_estado_gt is null
				and estado_gt is null


		IF @CONT>0 --EXISTE EN LA ODC
		BEGIN
			set @status='1'
			Return
		END
		ELSE
		BEGIN
			RAISERROR('El producto ingresado no existe en la orden de compra o el mismo ya fue recibido en su totalidad',16,1)
			return
		END
	END	--

	--SEGUN DEFINICION DE FO. ESTE CODIGO ES UNICO PARA CADA PRODUCTO.
	SELECT 	@PRODUCTO_ID=PRODUCTO_ID
	FROM	RL_PRODUCTO_CODIGOS
	WHERE	CLIENTE_ID=@CLIENTE_ID
			AND CODIGO=@CODIGO

	IF @PRODUCTO_ID IS NULL
	BEGIN
		RAISERROR('El codigo ingresado no corresponde a un producto o a un DUN14/EAN13',16,1)
		return	
	END
	ELSE
	BEGIN
		SET @CONT=NULL

		SELECT 	@PROD_ID=PRODUCTO_ID, @UNIDAD_ID=UNIDAD_ID FROM PRODUCTO WHERE CLIENTE_ID=@CLIENTE_ID AND PRODUCTO_ID=@PRODUCTO_ID

		SELECT 	@CONT=COUNT(*)
		FROM 	SYS_INT_DOCUMENTO SD INNER JOIN SYS_INT_DET_DOCUMENTO SDD  ON(SD.CLIENTE_ID=SDD.CLIENTE_ID AND SD.DOC_EXT=SDD.DOC_EXT)
		WHERE 	ORDEN_DE_COMPRA=@ODC
				AND SD.CLIENTE_ID=@CLIENTE_ID
				AND SDD.PRODUCTO_ID=@PRODUCTO_ID
				AND SDD.ESTADO_GT IS NULL
				AND SDD.FECHA_ESTADO_GT IS NULL

		SELECT 	TOP 1
				@DOC_EXT=SD.DOC_EXT
		FROM 	SYS_INT_DOCUMENTO SD INNER JOIN SYS_INT_DET_DOCUMENTO SDD  ON(SD.CLIENTE_ID=SDD.CLIENTE_ID AND SD.DOC_EXT=SDD.DOC_EXT)
		WHERE 	ORDEN_DE_COMPRA=@ODC
				AND PRODUCTO_ID=@PRODUCTO_ID
				AND SD.CLIENTE_ID=@CLIENTE_ID
				and SDD.fecha_estado_gt is null
				and SDD.estado_gt is null
				

		Select 	@REMANENTE=sum(cantidad_solicitada)
		from	sys_int_det_documento
		where	doc_ext=@doc_ext
				and fecha_estado_gt is null
				and estado_gt is null


		IF @CONT>0 --EXISTE EN LA ODC
		BEGIN
			set @status='1'
		END
		ELSE
		BEGIN
			RAISERROR('El producto ingresado no existe en la orden de compra o el mismo ya fue recibido en su totalidad',16,1)
			return
		END

	END
END

GO