
ALTER VIEW [dbo].[WEB_STOCK] 
AS

select a.*,pim.IMAGEN  

from (

	SELECT X.clienteid,
	X.[razon_social],
	X.[producto_id],
	X.[descr_producto],
	CONVERT(nvarchar(30),CONVERT(DECIMAL(10,2), REPLACE(SUM(X.cantidad), ',','.')))  as [cantidad],
	X.[cat_logica],
	X.[est_mercaderia],
	X.[es_egresable],
	X.[es_pickeable]
	FROM

	(SELECT	C.CLIENTE_ID									as	[clienteid],
			C.RAZON_SOCIAL									as	[razon_social],
			DD.PRODUCTO_ID									as	[producto_id],
			PROD.DESCRIPCION								as	[descr_producto],
			SUM(RL.CANTIDAD)								as  [cantidad],
			RL.CAT_LOG_ID									as  [cat_logica],
			isnull(RL.EST_MERC_ID,'-------')				as  [est_mercaderia],
			MIN(case when isnull(CAT.DISP_EGRESO,'0') = '1' AND ((EST.DISP_EGRESO IS NOT NULL AND EST.DISP_EGRESO='1') OR (EST.DISP_EGRESO IS NULL)) then '1' else '0' end) as [es_egresable],
			MIN(case when isnull(CAT.PICKING,'0') = '1' AND ((EST.PICKING IS NOT NULL AND EST.PICKING='1') OR (EST.PICKING IS NULL)) then '1' else '0' end)				  as [es_pickeable]
	FROM	RL_DET_DOC_TRANS_POSICION RL
	INNER JOIN DET_DOCUMENTO_TRANSACCION DDT ON (RL.DOC_TRANS_ID = DDT.DOC_TRANS_ID AND RL.NRO_LINEA_TRANS = DDT.NRO_LINEA_TRANS)
	INNER JOIN DET_DOCUMENTO DD ON (DDT.DOCUMENTO_ID = DD.DOCUMENTO_ID AND DDT.NRO_LINEA_DOC = DD.NRO_LINEA)
	INNER JOIN DOCUMENTO D ON (DD.DOCUMENTO_ID = D.DOCUMENTO_ID)
	INNER JOIN CLIENTE C ON (D.CLIENTE_ID = C.CLIENTE_ID)
	INNER JOIN PRODUCTO PROD ON (DD.CLIENTE_ID = PROD.CLIENTE_ID AND DD.PRODUCTO_ID = PROD.PRODUCTO_ID)
	INNER JOIN POSICION P ON (RL.POSICION_ACTUAL = P.POSICION_ID)
	INNER JOIN CATEGORIA_LOGICA CAT ON (RL.CLIENTE_ID = CAT.CLIENTE_ID AND RL.CAT_LOG_ID = CAT.CAT_LOG_ID)
	LEFT JOIN ESTADO_MERCADERIA_RL EST ON (RL.CLIENTE_ID = EST.CLIENTE_ID AND RL.EST_MERC_ID = EST.EST_MERC_ID)
	WHERE	
		d.STATUS='D40' 
		AND RL.DOC_TRANS_ID_EGR IS NULL AND RL.NRO_LINEA_TRANS_EGR IS NULL
	GROUP BY	C.CLIENTE_ID,
				C.RAZON_SOCIAL,
				DD.PRODUCTO_ID,
				PROD.DESCRIPCION,
				RL.CAT_LOG_ID,
				RL.EST_MERC_ID
				
UNION
	SELECT	C.CLIENTE_ID											as	[clienteid],
			C.RAZON_SOCIAL											as	[razon_social],
			DD.PRODUCTO_ID											as	[producto_id],
			PROD.DESCRIPCION										as	[descr_producto],
			SUM(RL.CANTIDAD)										as  [cantidad],
			RL.CAT_LOG_ID											as  [cat_logica],
			isnull(RL.EST_MERC_ID,'-------')						as  [est_mercaderia],
			MIN(case when isnull(CAT.DISP_EGRESO,'0') = '1' AND ((EST.DISP_EGRESO IS NOT NULL AND EST.DISP_EGRESO='1') OR (EST.DISP_EGRESO IS NULL)) then '1' else '0' end)	as [es_egresable],
			MIN(case when isnull(CAT.PICKING,'0') = '1' AND ((EST.PICKING IS NOT NULL AND EST.PICKING='1') OR (EST.PICKING IS NULL)) then '1' else '0' end)					as [es_pickeable]

	FROM	RL_DET_DOC_TRANS_POSICION RL
	INNER JOIN DET_DOCUMENTO_TRANSACCION DDT ON (RL.DOC_TRANS_ID = DDT.DOC_TRANS_ID AND RL.NRO_LINEA_TRANS = DDT.NRO_LINEA_TRANS)
	INNER JOIN DET_DOCUMENTO DD ON (DDT.DOCUMENTO_ID = DD.DOCUMENTO_ID AND DDT.NRO_LINEA_DOC = DD.NRO_LINEA)
	INNER JOIN DOCUMENTO D ON (DD.DOCUMENTO_ID = D.DOCUMENTO_ID)
	INNER JOIN CLIENTE C ON (D.CLIENTE_ID = C.CLIENTE_ID)
	INNER JOIN PRODUCTO PROD ON (DD.CLIENTE_ID = PROD.CLIENTE_ID AND DD.PRODUCTO_ID = PROD.PRODUCTO_ID)
	INNER JOIN NAVE N ON (RL.NAVE_ACTUAL = N.NAVE_ID)
	INNER JOIN CATEGORIA_LOGICA CAT ON (RL.CLIENTE_ID = CAT.CLIENTE_ID AND RL.CAT_LOG_ID = CAT.CAT_LOG_ID)
	LEFT JOIN ESTADO_MERCADERIA_RL EST ON (RL.CLIENTE_ID = EST.CLIENTE_ID AND RL.EST_MERC_ID = EST.EST_MERC_ID)
	WHERE	

	d.STATUS='D40' AND RL.DOC_TRANS_ID_EGR IS NULL AND RL.NRO_LINEA_TRANS_EGR IS NULL
	GROUP BY	C.CLIENTE_ID,
				C.RAZON_SOCIAL,
				DD.PRODUCTO_ID,
				PROD.DESCRIPCION,
				RL.CAT_LOG_ID,
				RL.EST_MERC_ID
) X
	GROUP BY X.clienteid,X.razon_social,X.producto_id,X.descr_producto,X.cat_logica,X.est_mercaderia,X.es_egresable,X.es_pickeable
)a

	left join PRODUCTO_IMG pim on (a.CLIENTEID=pim.CLIENTE_ID and a.PRODUCTO_ID=pim.PRODUCTO_ID)

GO
