
/****** Object:  StoredProcedure [dbo].[SYS_DEV_EGRESO_PEDIDO]    Script Date: 09/28/2015 12:48:33 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[SYS_DEV_EGRESO_PEDIDO]') AND type in (N'P', N'PC'))
DROP PROCEDURE [dbo].[SYS_DEV_EGRESO_PEDIDO]
GO

CREATE PROCEDURE [dbo].[SYS_DEV_EGRESO_PEDIDO]

	@CLIENTE_ID 		VARCHAR(50)		OUTPUT,
	@DOC_EXT			VARCHAR(100) OUTPUT
	
AS
	DECLARE @QTY 		AS NUMERIC(10,0)
	DECLARE @ERRORSAVE 	INT
	DECLARE @AUXNROLINEA BIGINT
	DECLARE @CONTROLEXPEDICION CHAR(1)
	DECLARE @TIPOCOMP	AS VARCHAR(5)
	DECLARE @USUARIO 	AS VARCHAR(20)
	DECLARE @COUNT		AS SMALLINT
	DECLARE @CONTROLA	AS CHAR(1)
	DECLARE @CUR		AS CURSOR
	DECLARE @CLI		AS VARCHAR(30)
	DECLARE @PEDIDO 	VARCHAR(100)	
	DECLARE @CURR_DOC 	CURSOR
	DECLARE @E_SP		AS VARCHAR(2)
	
BEGIN

	BEGIN TRY

		SET @QTY=0
		SELECT	@QTY=COUNT(DD.DOC_EXT) 
		FROM	SYS_INT_DET_DOCUMENTO DD 
				INNER JOIN SYS_INT_DOCUMENTO D ON (DD.CLIENTE_ID=D.CLIENTE_ID AND DD.DOC_EXT=D.DOC_EXT)		
				INNER JOIN PRODUCTO PROD ON (DD.CLIENTE_ID=PROD.CLIENTE_ID AND DD.PRODUCTO_ID=PROD.PRODUCTO_ID)
		WHERE	DD.ESTADO_GT IS NULL AND D.DOC_EXT = @DOC_EXT AND D.CLIENTE_ID=@CLI
		
		IF (@QTY>0) BEGIN	
			RAISERROR('EL PICKING/VIAJE AUN TIENE PRODUCTOS PENDIENTES POR PROCESAR',16,1)
			RETURN 	
		END --IF
		
		SET @QTY=0
		SELECT	@QTY=COUNT(DD.DOC_EXT) 
		FROM	SYS_INT_DET_DOCUMENTO DD 
				INNER JOIN SYS_INT_DOCUMENTO D ON (DD.CLIENTE_ID=D.CLIENTE_ID AND DD.DOC_EXT=D.DOC_EXT)		
		WHERE	D.DOC_EXT = @DOC_EXT AND D.CLIENTE_ID=@CLI AND DD.ESTADO_GT = 'P' AND DD.DOCUMENTO_ID IS NOT NULL
		
		IF (@QTY>0) BEGIN	
			--NO INFORMA
			RETURN 	
		END --IF		
		
		INSERT INTO SYS_DEV_DOCUMENTO
		SELECT	DISTINCT 
				SID.CLIENTE_ID, 
				CASE WHEN SID.TIPO_DOCUMENTO_ID='E04' THEN 'E05' WHEN SID.TIPO_DOCUMENTO_ID='E08' THEN 'E09' ELSE SID.TIPO_DOCUMENTO_ID END, 
				SID.CPTE_PREFIJO, 
				SID.CPTE_NUMERO, 
				GETDATE(), --FECHA_CPTE, 
				SID.FECHA_SOLICITUD_CPTE, 
				SID.AGENTE_ID, 
				DBO.GET_PESO_TOTAL(SID.CLIENTE_ID,SID.DOC_EXT), --SID.PESO_TOTAL, 
				SID.UNIDAD_PESO, 
				SID.VOLUMEN_TOTAL, 
				SID.UNIDAD_VOLUMEN, 
				DBO.GET_CANT_BULTOS(SID.CLIENTE_ID,SID.DOC_EXT), --SID.TOTAL_BULTOS, 
				SID.ORDEN_DE_COMPRA, 
				SID.OBSERVACIONES, 
				CAST(D.CPTE_PREFIJO AS VARCHAR(20)) + CAST(D.CPTE_NUMERO  AS VARCHAR(20)), 
				SID.NRO_DESPACHO_IMPORTACION, 
				SID.DOC_EXT, 
				SID.CODIGO_VIAJE, 
				SID.INFO_ADICIONAL_1, 
				SID.INFO_ADICIONAL_2, 
				SID.INFO_ADICIONAL_3, 
				D.TIPO_COMPROBANTE_ID, 	
				NULL, 
				NULL, 
				'P', 
				GETDATE(),
				NULL, --FLG_MOVIMIENTO 
				SID.CUSTOMS_1,
				SID.CUSTOMS_2,
				SID.CUSTOMS_3,
				NULL AS NRO_GUIA,
				NULL AS IMPORTE_FLETE,
				NULL AS TRANSPORTE_ID,
				SID.INFO_ADICIONAL_4,
				SID.INFO_ADICIONAL_5,
				SID.INFO_ADICIONAL_6
		FROM	SYS_INT_DOCUMENTO SID
				LEFT JOIN DOCUMENTO D ON (SID.CLIENTE_ID=D.CLIENTE_ID AND SID.DOC_EXT=D.NRO_REMITO)
		WHERE	SID.DOC_EXT = @DOC_EXT AND SID.CLIENTE_ID = @CLIENTE_ID
				AND ((D.TIPO_OPERACION_ID IS NULL) OR(D.TIPO_OPERACION_ID='EGR'))
				AND NOT EXISTS (SELECT	1 
								FROM	SYS_DEV_DOCUMENTO SD 
								WHERE	SD.CLIENTE_ID=SID.CLIENTE_ID
										AND SD.DOC_EXT=SID.DOC_EXT)
																
		IF @@ERROR <> 0 BEGIN
			SET @ERRORSAVE = @@ERROR
			RAISERROR('ERROR AL INSERTAR EN SYS_DEV_DOCUMENTO, CODIGO_ERROR: %S',16,1,@ERRORSAVE)
			RETURN
		END
												  
		INSERT INTO SYS_DEV_DET_DOCUMENTO
		SELECT	DD.DOC_EXT
				,DD.NRO_LINEA
				,DD.CLIENTE_ID
				,DD.PRODUCTO_ID
				,DD.CANTIDAD_SOLICITADA
				,0
				,DD.EST_MERC_ID
				,DD.CAT_LOG_ID
				,DD.NRO_BULTO
				,DD.DESCRIPCION
				,DD.NRO_LOTE
				,DD.NRO_PALLET
				,DD.FECHA_VENCIMIENTO
				,DD.NRO_DESPACHO
				,DD.NRO_PARTIDA
				,DD.UNIDAD_ID
				,DD.UNIDAD_CONTENEDORA_ID
				,DD.PESO
				,DD.UNIDAD_PESO
				,DD.VOLUMEN
				,DD.UNIDAD_VOLUMEN
				,DD.PROP1
				,DD.PROP2
				,DD.PROP3
				,DD.LARGO
				,DD.ALTO
				,DD.ANCHO
				,DD.DOC_BACK_ORDER
				,NULL
				,NULL
				,DD.ESTADO_GT
				,GETDATE()
				,DD.DOCUMENTO_ID
				,DD.NAVE_ID
				,DD.NAVE_COD
				,NULL --FLG_MOVIMIENTO
				,DD.CUSTOMS_1
				,DD.CUSTOMS_2
				,DD.CUSTOMS_3
				,NULL AS NRO_CMR
		FROM	SYS_INT_DET_DOCUMENTO DD
				INNER JOIN SYS_INT_DOCUMENTO D ON (D.CLIENTE_ID=DD.CLIENTE_ID AND D.DOC_EXT=DD.DOC_EXT)
		WHERE	CAST(DD.DOC_EXT + DD.PRODUCTO_ID AS VARCHAR(400))  NOT IN 
				(SELECT CAST(DOC_EXT + PRODUCTO_ID AS VARCHAR(400)) FROM SYS_DEV_DET_DOCUMENTO)
				AND D.DOC_EXT = @DOC_EXT AND D.CLIENTE_ID = @CLIENTE_ID
				AND NOT EXISTS (SELECT 1 FROM SYS_DEV_DET_DOCUMENTO WHERE SYS_DEV_DET_DOCUMENTO.CLIENTE_ID = DD.CLIENTE_ID AND SYS_DEV_DET_DOCUMENTO.DOC_EXT = DD.DOC_EXT AND SYS_DEV_DET_DOCUMENTO.NRO_LINEA = DD.NRO_LINEA)

		IF @@ERROR <> 0 BEGIN
			SET @ERRORSAVE = @@ERROR
			RAISERROR('ERROR AL INSERTAR EN SYS_DEV_DET_DOCUMENTO DE LOS PRODUCTOS SIN STOCK, CODIGO_ERROR: %S',16,1,@ERRORSAVE)
			RETURN
		END
		
        SELECT  @E_SP=ISNULL(VALOR,'0')
        FROM    SYS_PARAMETRO_PROCESO
        WHERE   PROCESO_ID='DEV'
                AND SUBPROCESO_ID='EJECUTA_SP'
                AND PARAMETRO_ID='E_SP';	

		if @e_sp='1' begin 
			BEGIN    
				--NOTIFICACION DE EGRESO PARA EL ERP       
				EXEC ERP_CARGAR_DATOS @CLIENTE_ID, @DOC_EXT  
			END
				
			IF @@ERROR <> 0 BEGIN
				SET @ERRORSAVE = @@ERROR
				RAISERROR('ERROR AL CARGAR DATOS EN ERP, CODIGO_ERROR: %S',16,1,@ERRORSAVE)
				RETURN
			END
		END
		
	END TRY
	BEGIN CATCH
		EXEC USP_RETHROWERROR
	END CATCH
END



GO


