CREATE PROCEDURE DBO.GET_CONF_POSICION
	@POSICION_DESTINO	VARCHAR(45),
	@CLIENTE_ID			VARCHAR(45),
	@PRODUCTO_ID		VARCHAR(30)
AS
BEGIN
	DECLARE	@TIENE_PALLET	AS VARCHAR(1),
			@CONTROL		AS NUMERIC,
			@TIENE_CONT		AS VARCHAR(1),
			@PALLET_OBLIG	AS VARCHAR(1),
			@CONT_OBLIG		AS VARCHAR(1)
			
	SELECT	@PALLET_OBLIG=ISNULL(PRODUCTO.PALLET_AUTOMATICO,'0'),
			@CONT_OBLIG=ISNULL(PRODUCTO.FLG_CONTENEDORA,'0')
	FROM	PRODUCTO
	WHERE	PRODUCTO.CLIENTE_ID=@CLIENTE_ID
			AND PRODUCTO.PRODUCTO_ID=@PRODUCTO_ID			
	
	SELECT	@CONTROL=COUNT(DISTINCT DD.PROP1)
	FROM	DET_DOCUMENTO DD INNER JOIN DET_DOCUMENTO_TRANSACCION DDT
			ON(DD.DOCUMENTO_ID=DDT.DOCUMENTO_ID AND DD.NRO_LINEA=DDT.NRO_LINEA_DOC)
			INNER JOIN RL_DET_DOC_TRANS_POSICION RL
			ON(DDT.DOC_TRANS_ID=RL.DOC_TRANS_ID AND DDT.NRO_LINEA_TRANS=RL.NRO_LINEA_TRANS AND RL.DISPONIBLE='1')
			LEFT JOIN POSICION P
			ON(RL.POSICION_ACTUAL=P.POSICION_ID)
			LEFT JOIN NAVE N
			ON(RL.NAVE_ACTUAL=N.NAVE_ID)
	WHERE	DD.CLIENTE_ID=@CLIENTE_ID
			AND DD.PRODUCTO_ID=@PRODUCTO_ID
			AND ((P.POSICION_COD=@POSICION_DESTINO)OR(N.NAVE_COD=@POSICION_DESTINO))	
			AND DD.PROP1 IS NOT NULL
	
	IF @CONTROL>0 BEGIN
		SET @TIENE_PALLET='1'
	END ELSE BEGIN
		SET @TIENE_PALLET='0'
	END			
	
	SET @CONTROL=NULL
	
	SELECT	@CONTROL=COUNT(DISTINCT DD.NRO_BULTO)
	FROM	DET_DOCUMENTO DD INNER JOIN DET_DOCUMENTO_TRANSACCION DDT
			ON(DD.DOCUMENTO_ID=DDT.DOCUMENTO_ID AND DD.NRO_LINEA=DDT.NRO_LINEA_DOC)
			INNER JOIN RL_DET_DOC_TRANS_POSICION RL
			ON(DDT.DOC_TRANS_ID=RL.DOC_TRANS_ID AND DDT.NRO_LINEA_TRANS=RL.NRO_LINEA_TRANS AND RL.DISPONIBLE='1')
			LEFT JOIN POSICION P
			ON(RL.POSICION_ACTUAL=P.POSICION_ID)
			LEFT JOIN NAVE N
			ON(RL.NAVE_ACTUAL=N.NAVE_ID)
	WHERE	DD.CLIENTE_ID=@CLIENTE_ID
			AND DD.PRODUCTO_ID=@PRODUCTO_ID
			AND ((P.POSICION_COD=@POSICION_DESTINO)OR(N.NAVE_COD=@POSICION_DESTINO))	
			AND DD.NRO_BULTO IS NOT NULL
			
	IF @CONTROL>0 BEGIN
		SET @TIENE_CONT='1'
	END ELSE BEGIN
		SET @TIENE_CONT='0'
	END

	SELECT	@TIENE_PALLET	AS T_PALLET,
			@TIENE_CONT		AS T_CONT,
			@PALLET_OBLIG	AS O_PALLET,
			@CONT_OBLIG		AS O_CONT
											
END			