/****** Object:  Trigger [TRG_STK_DISPONIBLE]    Script Date: 10/15/2015 12:18:52 ******/
IF  EXISTS (SELECT * FROM sys.triggers WHERE object_id = OBJECT_ID(N'[dbo].[TRG_STK_DISPONIBLE]'))
DROP TRIGGER [dbo].[TRG_STK_DISPONIBLE]
GO

CREATE TRIGGER [dbo].[TRG_STK_DISPONIBLE]
ON [dbo].[RL_DET_DOC_TRANS_POSICION]
AFTER UPDATE, INSERT
AS
BEGIN
	SET NOCOUNT ON
	DECLARE @RL_ID			NUMERIC(20,0)
	DECLARE @CAT_LOG_ID		VARCHAR(100)
	DECLARE @OLD_CAT_LOG	VARCHAR(100)
	
	SELECT	@RL_ID=RL_ID FROM INSERTED
			
	IF UPDATE(POSICION_ACTUAL) OR UPDATE(NAVE_ACTUAL) BEGIN
	
		SELECT	@RL_ID=RL_ID FROM INSERTED
			
		UPDATE	RL_DET_DOC_TRANS_POSICION
		SET		CAT_LOG_ID=CAT_LOG_ID_FINAL,
				DISPONIBLE='1'
		FROM	RL_DET_DOC_TRANS_POSICION RL LEFT JOIN POSICION P	ON(RL.POSICION_ACTUAL=P.POSICION_ID )
				LEFT JOIN NAVE N									ON(RL.NAVE_ACTUAL=N.NAVE_ID)
		WHERE	RL.RL_ID=@RL_ID
				AND ISNULL(P.intermedia,'0')='0'
				AND ISNULL(N.PRE_EGRESO,'0')='0' 
				AND ISNULL(N.PRE_INGRESO,'0')='0'
				AND RL.DISPONIBLE IS NULL
	END		

	IF UPDATE(CAT_LOG_ID) BEGIN

		SELECT @CAT_LOG_ID=CAT_LOG_ID FROM DELETED
		
		IF @CAT_LOG_ID='TRAN_EGR' BEGIN
			
			UPDATE	RL_DET_DOC_TRANS_POSICION 
			SET		CAT_LOG_ID='TRAN_EGR',
					DISPONIBLE='0'
			WHERE	RL_ID=@RL_ID
			
		END
	END
END
