
/****** Object:  StoredProcedure [dbo].[MOB_BORRAR_TMP_PENDIENTE]    Script Date: 07/16/2013 12:46:39 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[MOB_BORRAR_TMP_PENDIENTE]') AND type in (N'P', N'PC'))
DROP PROCEDURE [dbo].[MOB_BORRAR_TMP_PENDIENTE]
GO


create PROCEDURE [dbo].[MOB_BORRAR_TMP_PENDIENTE] 
		--@NRO_OC AS varchar(20) 
AS
BEGIN
	DECLARE @USUARIO			VARCHAR(20)
	
	SELECT @USUARIO=USUARIO_ID FROM #TEMP_USUARIO_LOGGIN
	
	DELETE tmp_oc
	WHERE USUARIO=@USUARIO AND PROCESADO = 0 --AND ID_OC=@NRO_OC 
		
	DELETE tmp_remito
	WHERE USUARIO=@USUARIO AND PROCESADO = 0 --AND ID_REMITO=@NRO_OC 
	
	DELETE TMP_PRODUCTO
	WHERE USUARIO=@USUARIO AND PROCESADO = 0 --AND ID=@NRO_OC 
	
END



GO


