/****** Object:  StoredProcedure [dbo].[MOB_GET_SUCURSAL]    Script Date: 07/16/2013 12:49:21 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[MOB_GET_SUCURSAL]') AND type in (N'P', N'PC'))
DROP PROCEDURE [dbo].[MOB_GET_SUCURSAL]
GO

CREATE PROCEDURE [dbo].[MOB_GET_SUCURSAL] 
	@cliente_id	varchar(15)
AS
	BEGIN
		/*SELECT distinct S.SUCURSAL_ID, S.NOMBRE FROM SUCURSAL S
		INNER JOIN SYS_INT_DOCUMENTO SD ON (SD.CLIENTE_ID = S.CLIENTE_ID AND SD.AGENTE_ID = S.SUCURSAL_ID)
		INNER JOIN SYS_INT_DET_DOCUMENTO SDD ON (SDD.CLIENTE_ID = SD.CLIENTE_ID AND SDD.DOC_EXT = SD.DOC_EXT)
		WHERE	S.CLIENTE_ID=@cliente_id
          AND S.FLG_INGRESO = '1'
				--AND S.TIPO_AGENTE_ID ='PROVEEDOR'
				AND ((SDD.ESTADO_GT IS NULL) OR (SDD.ESTADO_GT <> 'P'))*/
        
    SELECT	distinct S.SUCURSAL_ID, S.NOMBRE 
    FROM	SUCURSAL S
			INNER JOIN SYS_INT_DOCUMENTO SD ON (SD.CLIENTE_ID = S.CLIENTE_ID AND SD.AGENTE_ID = S.SUCURSAL_ID)
			INNER JOIN SYS_INT_DET_DOCUMENTO SDD ON (SDD.CLIENTE_ID = SD.CLIENTE_ID AND SDD.DOC_EXT = SD.DOC_EXT)
			INNER JOIN TIPO_AGENTE TA ON (TA.TIPO_AGENTE_ID = S.TIPO_AGENTE_ID)
	WHERE	S.CLIENTE_ID=@cliente_id
			AND ISNULL(TA.FLG_INGRESO,'0') = '1'
			AND ((SDD.ESTADO_GT IS NULL) OR (SDD.ESTADO_GT <> 'P'))
	END


