/****** Object:  StoredProcedure [dbo].[MOB_DELETE_PRODUCTO_TMP]    Script Date: 07/16/2013 12:50:22 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[MOB_DELETE_PRODUCTO_TMP]') AND type in (N'P', N'PC'))
DROP PROCEDURE [dbo].[MOB_DELETE_PRODUCTO_TMP]
GO
create PROCEDURE [dbo].[MOB_DELETE_PRODUCTO_TMP] 
	@ID				VARCHAR(20),
	@PRODUCTO_ID	VARCHAR(30),
	@cantidad		NUMERIC(12)
AS
BEGIN
	DECLARE @USUARIO		VARCHAR(20)	
	SELECT @USUARIO=USUARIO_ID FROM #TEMP_USUARIO_LOGGIN
	
	DELETE FROM tmp_Producto
	WHERE  (ID = @ID) AND (PRODUCTO_ID = @PRODUCTO_ID)
	AND USUARIO=@USUARIO and  cantidad=@cantidad		
	
END

