/****** Object:  StoredProcedure [dbo].[GET_CLIENTES_BY_USER]    Script Date: 07/16/2013 12:47:01 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[GET_CLIENTES_BY_USER]') AND type in (N'P', N'PC'))
DROP PROCEDURE [dbo].[GET_CLIENTES_BY_USER]
GO
CREATE PROCEDURE [dbo].[GET_CLIENTES_BY_USER]
@USER	VARCHAR(30)
AS
BEGIN
	SELECT	UPPER(R.CLIENTE_ID) [CLIENTE_ID], UPPER(C.RAZON_SOCIAL) AS [RAZONSOCIAL]
	FROM	SYS_USUARIO S INNER JOIN RL_SYS_CLIENTE_USUARIO R
			ON(S.USUARIO_ID=R.USUARIO_ID)
			INNER JOIN CLIENTE C
			ON(R.CLIENTE_ID=C.CLIENTE_ID)
	WHERE	R.USUARIO_ID=LTRIM(RTRIM(UPPER(@USER)))
END