/****** Object:  StoredProcedure [dbo].[MOB_GET_SUC_NOMBRE]    Script Date: 07/16/2013 16:42:23 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[MOB_GET_SUC_NOMBRE]') AND type in (N'P', N'PC'))
DROP PROCEDURE [dbo].[MOB_GET_SUC_NOMBRE]
GO

CREATE PROCEDURE [dbo].[MOB_GET_SUC_NOMBRE]
	@SUCURSAL_ID AS	VARCHAR(20),
	@CLIENTE_ID AS VARCHAR(15),
	@NOMBRE AS VARCHAR(50) OUTPUT
AS
BEGIN
	--DECLARE @RAZ_SOCIAL AS VARCHAR(60)

	SELECT	@NOMBRE=S.NOMBRE FROM SUCURSAL S
  INNER JOIN TIPO_AGENTE TA ON (TA.TIPO_AGENTE_ID = S.TIPO_AGENTE_ID)
	WHERE	ISNULL(TA.FLG_INGRESO,'0') = '1' AND SUCURSAL_ID =@SUCURSAL_ID
			AND CLIENTE_ID = @CLIENTE_ID
	
	--SELECT @RAZ_SOCIAL = RAZON_SOCIAL FROM CLIENTE WHERE CLIENTE_ID = @CLIENTE_ID
	
	if @NOMBRE is null
	Begin
		RaisError('El Proveedor no existe o no tiene OC para ingresar',16,1)
		Return
	End

END

