
/****** Object:  StoredProcedure [dbo].[INGRESO_OC_ALTA]    Script Date: 09/02/2013 16:42:18 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[INGRESO_OC_ALTA]') AND type in (N'P', N'PC'))
DROP PROCEDURE [dbo].[INGRESO_OC_ALTA]
GO

CREATE PROCEDURE [dbo].[INGRESO_OC_ALTA]
	@CLIENTE_ID			    varchar(15),
	@PRODUCTO_ID		    varchar(30),
	@ORDEN_COMPRA		    varchar(100),
	@CANTIDAD			    numeric(20,5),
	@CANT_CONTENEDORAS		numeric(20,5)=NULL,
	@FECHA				    datetime,
	@procesado			    char(1),
	@LOTEPROVEEDOR			VARCHAR(100),
	@PARTIDA			    VARCHAR(100),
	@DOC_EXT				VARCHAR(100)
AS
begin
	DECLARE @USUARIO		VARCHAR(50)
	DECLARE @TERMINAL		VARCHAR(100)
	DECLARE @CUR		    CURSOR
	DECLARE @VDOCEXT		VARCHAR(100)
	DECLARE @QTY_LIN		NUMERIC(20,5)
	DECLARE @VCANTIDAD		NUMERIC(20,5)
	DECLARE @NRO_PART_AT	CHAR(1)
	DECLARE @SEQ			NUMERIC(30,0)
	DECLARE @ISCONT			CHAR(1)
  
	if(@FECHA is null)begin
		set @fecha=getdate();
	end
	
	SET @VCANTIDAD=@CANTIDAD;
  
	SELECT @USUARIO=USUARIO_ID FROM #TEMP_USUARIO_LOGGIN
	
	SELECT	@NRO_PART_AT = ISNULL(NRO_PARTIDA_AUTOMATICO,'0'),
			@ISCONT =ISNULL(FLG_CONTENEDORA,'0')
	FROM	PRODUCTO
	WHERE	CLIENTE_ID=@CLIENTE_ID 
			AND PRODUCTO_ID= @PRODUCTO_ID;
			
	IF (@PARTIDA IS NULL) OR (LTRIM(RTRIM(@PARTIDA))='')BEGIN
		IF @NRO_PART_AT ='1' AND @ISCONT='0' BEGIN
			EXEC dbo.GET_VALUE_FOR_SEQUENCE 'NRO_PARTIDA', @SEQ OUTPUT
			SET @PARTIDA =@SEQ;
		END
	END		

	SET @TERMINAL=HOST_NAME()
		SET @CUR=CURSOR FOR
		SELECT	SDD.DOC_EXT, SDD.CANTIDAD_SOLICITADA
		FROM	SYS_INT_DOCUMENTO SD INNER JOIN SYS_INT_DET_DOCUMENTO SDD
				ON(SD.CLIENTE_ID=SDD.CLIENTE_ID AND SD.DOC_EXT=SDD.DOC_EXT)
		WHERE	SDD.CLIENTE_ID=@CLIENTE_ID
				AND SD.ORDEN_DE_COMPRA=@ORDEN_COMPRA
				AND SDD.PRODUCTO_ID=@PRODUCTO_ID
				AND SDD.ESTADO_GT IS NULL
				AND SDD.FECHA_ESTADO_GT IS NULL
		ORDER BY
				SD.FECHA_CPTE, SD.DOC_EXT;
	
	open @cur
	fetch @CUR into @VDOCEXT,@QTY_LIN
	while @@FETCH_STATUS=0 begin
		PRINT('EVALUA LAS CANTIDADES.')
		if @VCANTIDAD>=@QTY_LIN begin 
			INSERT INTO INGRESO_OC(CLIENTE_ID, PRODUCTO_ID, ORDEN_COMPRA, CANTIDAD, CANT_CONTENEDORAS, USUARIO, TERMINAL, FECHA, PROCESADO, NRO_LOTE, NRO_PARTIDA, DOC_EXT)                    
			VALUES                (@CLIENTE_ID,@PRODUCTO_ID,@ORDEN_COMPRA,@QTY_LIN,@CANT_CONTENEDORAS,@USUARIO,@TERMINAL,@FECHA,@PROCESADO, @LOTEPROVEEDOR, @PARTIDA, @VDOCEXT);
			set @VCANTIDAD=@VCANTIDAD-@QTY_LIN;          
		end
		else begin
			INSERT INTO INGRESO_OC(CLIENTE_ID, PRODUCTO_ID, ORDEN_COMPRA, CANTIDAD, CANT_CONTENEDORAS, USUARIO, TERMINAL, FECHA, PROCESADO, NRO_LOTE, NRO_PARTIDA, DOC_EXT)                    
			VALUES                (@CLIENTE_ID,@PRODUCTO_ID,@ORDEN_COMPRA,@VCANTIDAD,@CANT_CONTENEDORAS,@USUARIO,@TERMINAL,@FECHA,@PROCESADO, @LOTEPROVEEDOR, @PARTIDA, @VDOCEXT);
			SET @VCANTIDAD=0;
		end
		if @VCANTIDAD=0 begin
			break;
		end
		fetch @CUR into @VDOCEXT,@QTY_LIN  
		if @VCANTIDAD>0 begin
			update  ingreso_oc set cantidad=cantidad + @VCANTIDAD
			where   cliente_id=@CLIENTE_ID
					and PRODUCTO_ID=@PRODUCTO_ID
					and doc_ext=@VDOCEXT;
		end
	end
	CLOSE @CUR;
	DEALLOCATE @CUR;
end

GO


