DECLARE @UNIDAD_VACIA AS NUMERIC
DECLARE @USUARIO_USER AS NUMERIC

SELECT @UNIDAD_VACIA = COUNT(*) FROM UNIDAD_MEDIDA WHERE UNIDAD_ID = '';

IF (@UNIDAD_VACIA <> 1)
	BEGIN
	INSERT INTO [DBO].[UNIDAD_MEDIDA]([UNIDAD_ID],[DESCRIPCION]) VALUES ('','');
	END

SELECT @USUARIO_USER = COUNT(*) FROM SYS_USUARIO WHERE USUARIO_ID = 'USER';

IF (@USUARIO_USER <> 1)

	BEGIN
	INSERT INTO [DBO].[SYS_USUARIO]([USUARIO_ID],[NOMBRE],[PASSWORD],[ROL_ID],[F_CREACION],[F_REVOCACION],[EMAIL],[CANT_BLOQUEDA],[CUENTA_BLOQUEDA],[F_ULTI_MOD],[F_INICIO],[EXP_DIA],[DESKTOP],[HANDHELD],[PASSWORD_HANDHELD],[IMPRESORA_DEM_IMP]) VALUES('USER','USER','00000800020204','ADM',GETDATE(),NULL,NULL,'10','0',GETDATE(),GETDATE(),365,'1','1','1234','\\PC1\DELL MFP 1125 PRINTER');
	INSERT INTO [DBO].[SYS_PERFIL_USUARIO]([USUARIO_ID],[EMPLAZAMIENTO_DEFAULT],[DEPOSITO_DEFAULT]) VALUES ('USER','1','DEFAULT');
	INSERT INTO [DBO].[SYS_USU_PERMISOS]([USUARIO_ID],[PERMISO_ID],[VALOR],[DESCRIPCION]) VALUES ('USER','LOCATOR','1','LOCATOR MANUAL');
	INSERT INTO [DBO].[TRACE_DOCUMENTOS]([USUARIO_ID],[TIPO_OPERACION_ID],[TRACE_ACTIVO],[CANTIDAD],[NRO_SERIE],[NRO_SERIE_PADRE],[EST_MERC_ID],[CAT_LOG_ID],[NRO_BULTO],[DESCRIPCION],[NRO_LOTE],[FECHA_VENCIMIENTO],[NRO_DESPACHO],[NRO_PARTIDA],[UNIDAD_ID],[PESO],[UNIDAD_PESO],[VOLUMEN],[UNIDAD_VOLUMEN],[BUSC_INDIVIDUAL],[TIE_IN],[NRO_TIE_IN_PADRE],[NRO_TIE_IN],[ITEM_OK],[CAT_LOG_ID_FINAL],[MONEDA_ID],[COSTO],[PROP1],[PROP2],[PROP3],[LARGO],[ALTO],[ANCHO],[VOLUMEN_UNITARIO],[PESO_UNITARIO]) VALUES ('USER','EGR',0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'1','1');
	INSERT INTO [DBO].[TRACE_DOCUMENTOS]([USUARIO_ID],[TIPO_OPERACION_ID],[TRACE_ACTIVO],[CANTIDAD],[NRO_SERIE],[NRO_SERIE_PADRE],[EST_MERC_ID],[CAT_LOG_ID],[NRO_BULTO],[DESCRIPCION],[NRO_LOTE],[FECHA_VENCIMIENTO],[NRO_DESPACHO],[NRO_PARTIDA],[UNIDAD_ID],[PESO],[UNIDAD_PESO],[VOLUMEN],[UNIDAD_VOLUMEN],[BUSC_INDIVIDUAL],[TIE_IN],[NRO_TIE_IN_PADRE],[NRO_TIE_IN],[ITEM_OK],[CAT_LOG_ID_FINAL],[MONEDA_ID],[COSTO],[PROP1],[PROP2],[PROP3],[LARGO],[ALTO],[ANCHO],[VOLUMEN_UNITARIO],[PESO_UNITARIO]) VALUES ('USER','ING',0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'1','1');
	END
	
ALTER TABLE [dbo].[TMP_EMPAQUE_CONTENEDORA] ADD [NRO_UCEMPAQUETADO] [varchar](100) NULL
ALTER TABLE [dbo].[TMP_EMPAQUE_CONTENEDORA] ADD [UCEMPAQUETADO_MEDIDAS] [varchar](100) NULL
ALTER TABLE [dbo].[TMP_EMPAQUE_CONTENEDORA] ADD [FECHA_UCEMPAQUETADO] [datetime] NULL
ALTER TABLE [dbo].[TMP_EMPAQUE_CONTENEDORA] ADD [UCEMPAQUETADO_PESO] [numeric](20, 5) NULL
