
/****** Object:  StoredProcedure [dbo].[VERIFICA_VIAJE_CREADO]    Script Date: 04/14/2014 10:53:18 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[VERIFICA_VIAJE_CREADO]') AND type in (N'P', N'PC'))
DROP PROCEDURE [dbo].[VERIFICA_VIAJE_CREADO]
GO

CREATE PROCEDURE [dbo].[VERIFICA_VIAJE_CREADO]
@VIAJE_ID 		VARCHAR(100) OUTPUT
AS
	DECLARE @CANT AS NUMERIC
	DECLARE @CANT_HIST AS NUMERIC
	DECLARE @CANT_INT AS NUMERIC

BEGIN

  SELECT @CANT=COUNT(*) FROM PICKING WHERE VIAJE_ID = @VIAJE_ID
  
  SELECT @CANT_HIST=COUNT(*) FROM PICKING_HISTORICO WHERE VIAJE_ID = @VIAJE_ID
  
  SELECT @CANT_INT=COUNT(*) FROM SYS_INT_DOCUMENTO WHERE CODIGO_VIAJE = @VIAJE_ID
  
  SELECT @CANT + @CANT_HIST + @CANT_INT
  
END

GO


