
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[GET_REMITO_ESPECIFICO]') AND type in (N'P', N'PC'))
DROP PROCEDURE [dbo].[GET_REMITO_ESPECIFICO]
GO

CREATE PROCEDURE DBO.GET_REMITO_ESPECIFICO
@VIAJE_ID		VARCHAR(100)OUTPUT
AS
BEGIN

	SELECT * 
	FROM (	
			SELECT	DISTINCT
					C.RAZON_SOCIAL														AS REMITENTE,				--1
					(ISNULL(C.CALLE,'') + ' '+ ISNULL(CAST(C.NUMERO AS VARCHAR),'') +'')AS DIRECCIONREMITENTE,		--2
					C.LOCALIDAD															AS LOCALIDADREMITENTE,		--3
					PR.DESCRIPCION														AS PROVINCIAREMITENTE,		--4
					PA.DESCRIPCION														AS PAISREMITENTE,			--5
					S.NOMBRE + '; CUIT: ' + DBO.FN_FORMATEAR_CUIT(S.NRO_DOCUMENTO)		AS DESTINATARIO,			--6
					(ISNULL(S.CALLE,'') + ' '+ ISNULL(S.NUMERO,'') +'')					AS DIRECCIONDESTINATARIO,	--7
					S.LOCALIDAD															AS LOCALIDADDESTINATARIO,	--8
					PRD.DESCRIPCION														AS PROVINCIADESTINATARIO,	--9
					'CONTACTO: ' + S.CONTACTO											AS GET_CONTACTO,			--10
					'CODIGO DE PRODUCTO:  ' + P.PRODUCTO_ID + ' ;  CANTIDAD: ' 
					+ REPLACE(CAST(P2.QTY AS VARCHAR),'.00000','')						AS PARTNUMBER,				--11
					PIK.NRO_SERIE														AS SERIAL_NUMBER,			--12
					DD.NRO_DESPACHO														AS NROSDESPACHO,			--13
					D.NRO_DESPACHO_IMPORTACION											AS DELIVERYORDER,			--14
					SD.INFO_ADICIONAL_3													AS ORDENCOMPRA
			FROM	CLIENTE C
					LEFT JOIN PROVINCIA PR			ON(C.PROVINCIA_ID = PR.PROVINCIA_ID)
					LEFT JOIN PAIS PA				ON(C.PAIS_ID = PA.PAIS_ID)
					LEFT JOIN DOCUMENTO D			ON(C.CLIENTE_ID = D.CLIENTE_ID)
					LEFT JOIN SUCURSAL S			ON(C.CLIENTE_ID = S.CLIENTE_ID  AND D.SUCURSAL_DESTINO = S.SUCURSAL_ID)
					LEFT OUTER JOIN PROVINCIA PRD	ON(S.PROVINCIA_ID = PRD.PROVINCIA_ID)
					LEFT OUTER JOIN PAIS PAD		ON(S.PAIS_ID = PAD.PAIS_ID)
					INNER JOIN DET_DOCUMENTO DD		ON(D.DOCUMENTO_ID = DD.DOCUMENTO_ID)
					INNER JOIN PRODUCTO P			ON(P.PRODUCTO_ID = DD.PRODUCTO_ID AND P.CLIENTE_ID = DD.CLIENTE_ID)
					INNER JOIN PICKING PIK			ON(DD.DOCUMENTO_ID=PIK.DOCUMENTO_ID AND DD.NRO_LINEA=PIK.NRO_LINEA)
					INNER JOIN (SELECT	VIAJE_ID, PRODUCTO_ID,SUM(P2.CANTIDAD) QTY
								FROM	PICKING P2
								GROUP BY
										VIAJE_ID, PRODUCTO_ID
					)P2 ON(PIK.VIAJE_ID=P2.VIAJE_ID AND PIK.PRODUCTO_ID=P2.PRODUCTO_ID)
					INNER JOIN SYS_INT_DOCUMENTO SD	ON(D.CLIENTE_ID=SD.CLIENTE_ID AND D.NRO_DESPACHO_IMPORTACION=SD.DOC_EXT)
			WHERE	PIK.VIAJE_ID=@VIAJE_ID 
					AND C.CLIENTE_ID=D.CLIENTE_ID
					AND S.SUCURSAL_ID=D.SUCURSAL_DESTINO
	) X
	ORDER BY X.PARTNUMBER, X.SERIAL_NUMBER;
END