IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DOCUMENTOSEGRESOEXPO]') AND type in (N'P', N'PC'))
DROP PROCEDURE [dbo].[DOCUMENTOSEGRESOEXPO]
GO
CREATE PROCEDURE DBO.DOCUMENTOSEGRESOEXPO
	@PFECHADESDE	DATETIME OUTPUT,
	@PFECHAHASTA	DATETIME OUTPUT,
	@PDOCUMENTO_ID	NUMERIC  OUTPUT,
	@TIPO			VARCHAR	 OUTPUT
AS	
BEGIN
	IF @TIPO='C' BEGIN
	
		SELECT	DISTINCT D.DOCUMENTO_ID
		FROM	PICKING P INNER JOIN DET_DOCUMENTO DD		ON(P.DOCUMENTO_ID=DD.DOCUMENTO_ID AND P.NRO_LINEA=DD.NRO_LINEA)
				INNER JOIN DOCUMENTO D						ON(DD.DOCUMENTO_ID=D.DOCUMENTO_ID)
				INNER JOIN SYS_INT_DOCUMENTO SD				ON(D.CLIENTE_ID=SD.CLIENTE_ID AND D.NRO_DESPACHO_IMPORTACION=SD.DOC_EXT)
				INNER JOIN PRODUCTO PR						ON(DD.CLIENTE_ID=PR.CLIENTE_ID AND DD.PRODUCTO_ID=PR.PRODUCTO_ID)
		WHERE	P.CANT_CONFIRMADA>0		
				--AND D.STATUS='D40'
				AND ((@PDOCUMENTO_ID IS NULL)OR(D.DOCUMENTO_ID=@PDOCUMENTO_ID))
				AND ((@PFECHADESDE IS NULL)OR(D.FECHA_ALTA_GTW BETWEEN @PFECHADESDE AND DATEADD(D,1,@PFECHAHASTA)))
		ORDER BY
				D.DOCUMENTO_ID
	END
	
	IF @TIPO='D' BEGIN
	
		SELECT	P.NRO_LINEA * 10																AS [LINE],
				SD.DOC_EXT																		AS [DELIVERYNO],
				'351' + CAST(DATEPART(YYYY,GETDATE())AS VARCHAR) 
				+ RIGHT('00'+CONVERT(VARCHAR(2), CAST(DATEPART(DD,GETDATE())AS VARCHAR)), 2)
				+ RIGHT('00'+CONVERT(VARCHAR(2), CAST(DATEPART(MM,GETDATE())AS VARCHAR)), 2)
				+ RIGHT('0000'+CONVERT(VARCHAR(4), D.DOCUMENTO_ID), 4)							AS [3PLPALLETID],
				'PKG1000'																		AS [PACKINGMATERIAL],
				P.PRODUCTO_ID																	AS [MATERIAL],
				P.NRO_SERIE																		AS [SERIALNUMBER],
				NULL																			AS [RECEIPTPALLETID],
				P.CANT_CONFIRMADA																AS [QUANTITY],
				NULL																			AS [WEIGHT],
				NULL																			AS [LENGTH],
				NULL																			AS [WIDTH],
				NULL																			AS [HEIGHT],
				CASE WHEN P.NRO_SERIE IS NULL THEN 'CN' ELSE NULL END							AS [COO],
				'1'																				AS [SHIPPMENTGROUPNUMBER],
				NULL																			AS [CONTAINERID],
				NULL																			AS [TRUCKNUMBER],
				NULL																			AS [FATRACKINGID],
				S.LOCALIDAD 																	AS [CONTAINTYPE],
				D.CPTE_PREFIJO + '-' + D.CPTE_NUMERO  											AS [COMMENTS]
		FROM	PICKING P INNER JOIN DET_DOCUMENTO DD		ON(P.DOCUMENTO_ID=DD.DOCUMENTO_ID AND P.NRO_LINEA=DD.NRO_LINEA)
				INNER JOIN DOCUMENTO D						ON(DD.DOCUMENTO_ID=D.DOCUMENTO_ID)
				INNER JOIN SYS_INT_DOCUMENTO SD				ON(D.CLIENTE_ID=SD.CLIENTE_ID AND D.NRO_DESPACHO_IMPORTACION=SD.DOC_EXT)
				INNER JOIN PRODUCTO PR						ON(DD.CLIENTE_ID=PR.CLIENTE_ID AND DD.PRODUCTO_ID=PR.PRODUCTO_ID)
				INNER JOIN SUCURSAL S						ON(D.CLIENTE_ID=S.CLIENTE_ID AND D.SUCURSAL_DESTINO=S.SUCURSAL_ID)
		WHERE	P.CANT_CONFIRMADA>0
				AND D.DOCUMENTO_ID=@PDOCUMENTO_ID		
		ORDER BY
				D.DOCUMENTO_ID, DD.NRO_LINEA
	END		
END