BEGIN
	DECLARE @SEQ NUMERIC(38)

	SELECT	@SEQ=VALOR 
	FROM	SECUENCIA
	WHERE	NOMBRE='NROPALLET_SEQ'	
	
	IF @SEQ=0 BEGIN
		UPDATE	SECUENCIA SET VALOR=0		WHERE NOMBRE='NROPALLET_SEQ'
	END

	SELECT	@SEQ=VALOR 
	FROM	SECUENCIA
	WHERE	NOMBRE='PALLET_PICKING'	
	
	IF @SEQ=0 BEGIN	
		UPDATE	SECUENCIA SET VALOR=1000	WHERE NOMBRE='PALLET_PICKING'
	END
	
	SELECT	@SEQ=VALOR 
	FROM	SECUENCIA
	WHERE	NOMBRE='CONTENEDORA'	
	
	IF @SEQ=0 BEGIN
		UPDATE	SECUENCIA SET VALOR=2000	WHERE NOMBRE='CONTENEDORA'
	END
END