ALTER TABLE RL_PRODUCTO_POSICION_PERMITIDA ADD OCUPACION_MIN NUMERIC(20,5);
ALTER TABLE RL_PRODUCTO_POSICION_PERMITIDA ADD OCUPACION_MAX NUMERIC(20,5);

ALTER TABLE AUDITORIA_RLPPP ADD OCUPACION_MIN NUMERIC(20,5);
ALTER TABLE AUDITORIA_RLPPP ADD OCUPACION_MAX NUMERIC(20,5);