/****** OBJECT:  STOREDPROCEDURE [DBO].[ACT_COMPROBANTE_RODC]    SCRIPT DATE: 03/25/2015 14:55:55 ******/
IF  EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[DBO].[ABAST_BUSQUEDA]') AND TYPE IN (N'P', N'PC'))
DROP PROCEDURE [DBO].[ABAST_BUSQUEDA]
GO

CREATE  PROCEDURE [DBO].[ABAST_BUSQUEDA]
@CLIENTE_ID		VARCHAR(100) OUTPUT,
@PRODUCTO_ID	VARCHAR(100) OUTPUT,
@POSICION		VARCHAR(100) OUTPUT,
@TIPO			VARCHAR(2) OUTPUT
AS
BEGIN

	IF @TIPO='1' BEGIN
		SELECT	DISTINCT 
				''				AS CHK,
				POSICION_COD	
		FROM	RL_PRODUCTO_POSICION_PERMITIDA RL INNER JOIN POSICION P
				ON(RL.POSICION_ID=P.POSICION_ID)
		WHERE	((@CLIENTE_ID IS NULL)OR(RL.CLIENTE_ID=@CLIENTE_ID))
				AND ((@PRODUCTO_ID IS NULL)OR(RL.PRODUCTO_ID=@PRODUCTO_ID))			
				AND ((@POSICION IS NULL)OR(P.POSICION_COD LIKE '%' + @POSICION + '%'))
				AND P.ABASTECIBLE='1'	
	END
	
	IF @TIPO='2' BEGIN
		SELECT	''				AS CHK,
				POSICION_COD	
		FROM	RL_PRODUCTO_POSICION_PERMITIDA RL INNER JOIN POSICION P
				ON(RL.POSICION_ID=P.POSICION_ID)
		WHERE	((@CLIENTE_ID IS NULL)OR(RL.CLIENTE_ID=@CLIENTE_ID))
				AND ((@PRODUCTO_ID IS NULL)OR(RL.PRODUCTO_ID=@PRODUCTO_ID))			
				AND ((@POSICION IS NULL)OR(P.POSICION_COD LIKE '%' + @POSICION + '%'))
				AND P.ABASTECIBLE='1'
	END
END