/****** OBJECT:  STOREDPROCEDURE [DBO].[ACT_COMPROBANTE_RODC]    SCRIPT DATE: 03/25/2015 14:55:55 ******/
IF  EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[DBO].[ABAST_GEN_TAREA]') AND TYPE IN (N'P', N'PC'))
DROP PROCEDURE [DBO].[ABAST_GEN_TAREA]
GO

CREATE  PROCEDURE [DBO].[ABAST_GEN_TAREA]
	@CLIENTE_ID		VARCHAR(15)		OUTPUT,
	@PRODUCTO_ID	VARCHAR(30)		OUTPUT,
	@POSICION_COD	VARCHAR(45)		OUTPUT,
	@PRIORIDAD		NUMERIC(20,0)	OUTPUT,
	@USUARIO_ID		VARCHAR(50)		OUTPUT,
	@CANT_A_ABAST	NUMERIC(20,5)	OUTPUT
AS
BEGIN
	DECLARE @POSICION_ID	NUMERIC(20,0);
	DECLARE @CONTROL		NUMERIC(20,0);
	DECLARE @ABAST_ID		BIGINT;

		
	SELECT	@POSICION_ID=P.POSICION_ID
	FROM	POSICION P
	WHERE	POSICION_COD=@POSICION_COD
	
	SELECT	@CONTROL=COUNT(*)
	FROM	DET_ABASTECIMIENTO
	WHERE	CLIENTE_ID=@CLIENTE_ID
			AND PRODUCTO_ID=@PRODUCTO_ID
			AND POSICION_ID=@POSICION_ID 
			AND ISNULL(FINALIZADO,'0')='0'
			
	IF @CONTROL>0 BEGIN
		RAISERROR('Actualmente ya existe una tarea generada para el Cliente/Producto/Posicion.',16,1)
		RETURN
	END			

	INSERT INTO DET_ABASTECIMIENTO (CLIENTE_ID, PRODUCTO_ID, POSICION_ID, PRIORIDAD, USUARIO, CANT_A_ABASTECER)
	VALUES(@CLIENTE_ID,@PRODUCTO_ID,@POSICION_ID,@PRIORIDAD,@USUARIO_ID, @CANT_A_ABAST)
	
	SELECT @ABAST_ID=SCOPE_IDENTITY()
	
	EXEC [DBO].[ABAST_LOCATOR] @CLIENTE_ID, @PRODUCTO_ID, @CANT_A_ABAST, @ABAST_ID

END--FIN PROCEDURE.