/****** Object:  StoredProcedure [dbo].[ABAST_DEL_TAREA]   Script Date: 04/24/2015 12:08:32 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[ABAST_DEL_TAREA]') AND type in (N'P', N'PC'))
DROP PROCEDURE [dbo].[ABAST_DEL_TAREA]
GO

CREATE  PROCEDURE [dbo].[ABAST_DEL_TAREA]
	@CLIENTE_ID		VARCHAR(15)		OUTPUT,
	@PRODUCTO_ID	VARCHAR(30)		OUTPUT,
	@POSICION_COD	VARCHAR(45)		OUTPUT,
	@USUARIO_ID		VARCHAR(50)		OUTPUT
AS
BEGIN

	DECLARE @POSICION_ID	NUMERIC(20,0);
	DECLARE @CONTROL		NUMERIC(20,0);
	DECLARE @ABAST_ID		BIGINT;

	IF @USUARIO_ID IS NULL BEGIN
		SELECT 	@USUARIO_ID=USUARIO_ID FROM #TEMP_USUARIO_LOGGIN	
	END
	
	SELECT	@POSICION_ID=P.POSICION_ID
	FROM	POSICION P
	WHERE	POSICION_COD=@POSICION_COD


	SELECT	@CONTROL=COUNT(*)
	FROM	DET_ABASTECIMIENTO
	WHERE	CLIENTE_ID=@CLIENTE_ID
			AND PRODUCTO_ID=@PRODUCTO_ID
			AND POSICION_ID=@POSICION_ID
			AND ((USUARIO IS NULL) OR (USUARIO=@USUARIO_ID))
			AND EN_PROGRESO='1'
			
	IF @CONTROL>0 BEGIN
		RAISERROR('La tarea actualmente se encuentra en progreso.',16,1)
		RETURN
	END

	SELECT	@ABAST_ID=ABAST_ID	
	FROM	DET_ABASTECIMIENTO
	WHERE	CLIENTE_ID=@CLIENTE_ID
			AND PRODUCTO_ID=@PRODUCTO_ID
			AND POSICION_ID=@POSICION_ID
			AND ((USUARIO IS NULL) OR (USUARIO=@USUARIO_ID))
			AND FINALIZADO='0'
	
	UPDATE	RL_DET_DOC_TRANS_POSICION SET DISPONIBLE='1'
	FROM	RL_DET_DOC_TRANS_POSICION RL INNER JOIN ABAST_CONSUMO_LOCATOR A
			ON(RL.RL_ID=A.RL_ID)
	WHERE	A.ABAST_ID=@ABAST_ID;			
	
	DELETE FROM ABAST_CONSUMO_LOCATOR WHERE ABAST_ID=@ABAST_ID;
	
	DELETE	
	FROM	DET_ABASTECIMIENTO 
	WHERE	ABAST_ID=@ABAST_ID;
			

END
GO


