/****** OBJECT:  STOREDPROCEDURE [DBO].[ACT_COMPROBANTE_RODC]    SCRIPT DATE: 03/25/2015 14:55:55 ******/
IF  EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[DBO].[ABAST_GET_USUARIOS]') AND TYPE IN (N'P', N'PC'))
DROP PROCEDURE [DBO].[ABAST_GET_USUARIOS]
GO

CREATE PROCEDURE [DBO].[ABAST_GET_USUARIOS]
	@CLIENTE_ID		VARCHAR(15)	OUTPUT,
	@PRODUCTO_ID	VARCHAR(30)	OUTPUT,
	@POSICION_COD	VARCHAR(45)	OUTPUT
AS
BEGIN

	SELECT	S.USUARIO_ID AS [COD.USUARIO]
	FROM	SYS_USUARIO S
	WHERE	ISNULL(S.HANDHELD,'0')='1'
			AND NOT EXISTS(	SELECT	1
							FROM	DET_ABASTECIMIENTO D INNER JOIN POSICION P
									ON(D.POSICION_ID=P.POSICION_ID)
							WHERE	S.USUARIO_ID = D.USUARIO
									AND D.CLIENTE_ID=@CLIENTE_ID
									AND D.PRODUCTO_ID=@PRODUCTO_ID
									AND P.POSICION_COD=@POSICION_COD
									AND D.FINALIZADO='0');
							
END