/****** OBJECT:  STOREDPROCEDURE [DBO].[ACT_COMPROBANTE_RODC]    SCRIPT DATE: 03/25/2015 14:55:55 ******/
IF  EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[DBO].[ABAST_GET_USUARIO_ASIGNADO]') AND TYPE IN (N'P', N'PC'))
DROP PROCEDURE [DBO].[ABAST_GET_USUARIO_ASIGNADO]
GO

CREATE PROCEDURE [DBO].[ABAST_GET_USUARIO_ASIGNADO]
	@CLIENTE_ID		VARCHAR(15)	OUTPUT,
	@PRODUCTO_ID	VARCHAR(30)	OUTPUT,
	@POSICION_COD	VARCHAR(45)	OUTPUT
AS
BEGIN

	DECLARE @POSICION_ID	NUMERIC(20,0)
	
	SELECT	@POSICION_ID=POSICION_ID
	FROM	POSICION
	WHERE	POSICION_COD=@POSICION_COD 
	

	SELECT	USUARIO	AS [COD.USUARIO]
	FROM	DET_ABASTECIMIENTO
	WHERE	CLIENTE_ID=@CLIENTE_ID
			AND PRODUCTO_ID=@PRODUCTO_ID
			AND POSICION_ID=@POSICION_ID
			AND ISNULL(FINALIZADO,'0')='0'
			
END