/****** OBJECT:  STOREDPROCEDURE [DBO].[ACT_COMPROBANTE_RODC]    SCRIPT DATE: 03/25/2015 14:55:55 ******/
IF  EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[DBO].[ABAST_CAMBIARPRIORIDAD]') AND TYPE IN (N'P', N'PC'))
DROP PROCEDURE [DBO].[ABAST_CAMBIARPRIORIDAD]
GO

CREATE  PROCEDURE [DBO].[ABAST_CAMBIARPRIORIDAD]
@P_CLIENTE_ID	VARCHAR(15)		OUTPUT,
@P_PRODUCTO_ID	VARCHAR(30)		OUTPUT,
@P_POSICION_COD	VARCHAR(45)		OUTPUT,
@P_PRIORIDAD	VARCHAR(100)	OUTPUT
AS
BEGIN
	DECLARE @CONTROL	NUMERIC(20,0)
	
	SELECT	@CONTROL=COUNT(*)
	FROM	DET_ABASTECIMIENTO DA INNER JOIN POSICION P	ON(DA.POSICION_ID=P.POSICION_ID)
	WHERE	DA.CLIENTE_ID=@P_CLIENTE_ID
			AND DA.PRODUCTO_ID=@P_PRODUCTO_ID
			AND P.POSICION_COD=@P_POSICION_COD
			AND ISNULL(DA.EN_PROGRESO,'0')='1'
	
	IF @CONTROL>0 BEGIN			
		RAISERROR('La tarea de abastecimiento se encuentra actualmente en curso',16,1)
		RETURN
	END
	
	UPDATE	DET_ABASTECIMIENTO
	SET		PRIORIDAD=@P_PRIORIDAD
	FROM	DET_ABASTECIMIENTO DA INNER JOIN POSICION P	ON(DA.POSICION_ID=P.POSICION_ID)
	WHERE	DA.CLIENTE_ID=@P_CLIENTE_ID
			AND DA.PRODUCTO_ID=@P_PRODUCTO_ID
			AND P.POSICION_COD=@P_POSICION_COD
			
END