
CREATE TABLE [DBO].[ABAST_CONSUMO_LOCATOR](
	[CONSUMO_ID]	[NUMERIC](20, 0)IDENTITY(1,1) NOT NULL,
	[ABAST_ID]		[BIGINT]		NOT NULL,
	[NRO_LINEA]		[NUMERIC](20, 0)NOT NULL,
	[CLIENTE_ID]	[VARCHAR](15)	NULL,
	[PRODUCTO_ID]	[VARCHAR](30)	NULL,
	[CANTIDAD]		[NUMERIC](20, 5)NULL,
	[RL_ID]			[NUMERIC](20, 0)NULL,
	[SALDO]			[NUMERIC](20, 5)NULL,
	[TIPO]			[VARCHAR](20)	NULL,
	[FECHA]			[DATETIME]		NULL,
	[PROCESADO]		[VARCHAR](1)	NULL
)
GO

ALTER TABLE [DBO].[ABAST_CONSUMO_LOCATOR]
ADD CONSTRAINT PK_ABAST_CONS_LOCATOR PRIMARY KEY (CONSUMO_ID)
GO

ALTER TABLE [DBO].[ABAST_CONSUMO_LOCATOR]
ADD CONSTRAINT FK_CONS_LOC_PRODUCTO FOREIGN KEY (CLIENTE_ID, PRODUCTO_ID)
REFERENCES PRODUCTO (CLIENTE_ID, PRODUCTO_ID)
GO

ALTER TABLE [DBO].[ABAST_CONSUMO_LOCATOR]
ADD CONSTRAINT FK_CONS_LOC_DET_ABAST FOREIGN KEY (ABAST_ID)
REFERENCES DET_ABASTECIMIENTO (ABAST_ID)
