ALTER TABLE ABAST_CONSUMO_LOCATOR
ADD		NRO_CONTENEDORA	NUMERIC(20,0)

ALTER TABLE ABAST_CONSUMO_LOCATOR
ADD		CANT_CONFIRMADA NUMERIC(20,0)

ALTER TABLE ABAST_CONSUMO_LOCATOR
ADD		EN_CONTENEDOR NUMERIC(20,0)