/****** OBJECT:  STOREDPROCEDURE [DBO].[LOCATOREGRESO]    SCRIPT DATE: 03/30/2015 10:42:47 ******/
IF  EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[DBO].[ABAST_TAREAS_ID]') AND TYPE IN (N'P', N'PC'))
DROP PROCEDURE [DBO].[ABAST_TAREAS_ID]
GO

CREATE PROCEDURE [DBO].[ABAST_TAREAS_ID]
@ABAST_ID	BIGINT OUTPUT
AS
BEGIN

	SELECT	ISNULL(P.POSICION_COD,N.NAVE_COD) AS POSICION_COD, DD.NRO_LOTE, DD.NRO_PARTIDA, DD.NRO_SERIE, DD.NRO_BULTO, SUM(RL.CANTIDAD) CANTIDAD,
			ISNULL(SUM(ACL.CANT_CONFIRMADA),SUM(RL.CANTIDAD)) CANT_CONFIRMADA, CASE ISNULL(EN_CONTENEDOR,'0') WHEN '0' THEN 'NO' WHEN '1' THEN 'SI' END AS EN_CONTENEDOR, ACL.NRO_CONTENEDORA
	FROM	DET_ABASTECIMIENTO DA INNER JOIN ABAST_CONSUMO_LOCATOR ACL
			ON(DA.ABAST_ID=ACL.ABAST_ID)
			INNER JOIN RL_DET_DOC_TRANS_POSICION RL
			ON(ACL.RL_ID=RL.RL_ID)
			INNER JOIN DET_DOCUMENTO_TRANSACCION DDT
			ON(RL.DOC_TRANS_ID=DDT.DOC_TRANS_ID AND RL.NRO_LINEA_TRANS=DDT.NRO_LINEA_TRANS)
			INNER JOIN DET_DOCUMENTO DD
			ON(DDT.DOCUMENTO_ID=DD.DOCUMENTO_ID AND DDT.NRO_LINEA_DOC=DD.NRO_LINEA)
			LEFT JOIN POSICION P
			ON(RL.POSICION_ACTUAL=P.POSICION_ID)
			LEFT JOIN NAVE N
			ON(RL.NAVE_ACTUAL=N.NAVE_ID)
	WHERE	DA.ABAST_ID=@ABAST_ID
	GROUP BY
			ISNULL(P.POSICION_COD,N.NAVE_COD), DD.NRO_LOTE, DD.NRO_PARTIDA, DD.NRO_SERIE, DD.NRO_BULTO,CASE ISNULL(EN_CONTENEDOR,'0') WHEN '0' THEN 'NO' WHEN '1' THEN 'SI' END, ACL.NRO_CONTENEDORA

END

