IF  EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[ABAST_DESBLOQUEAR_TAREA]') AND TYPE IN (N'P', N'PC'))
DROP PROCEDURE [DBO].[ABAST_DESBLOQUEAR_TAREA]
GO

CREATE PROCEDURE [DBO].[ABAST_DESBLOQUEAR_TAREA]
@ABAST_ID		BIGINT	OUTPUT
AS
BEGIN

	SELECT	* FROM DET_ABASTECIMIENTO
	
	UPDATE	ABAST_CONSUMO_LOCATOR 
	SET		EN_PROGRESO=NULL
	WHERE	ABAST_ID=@ABAST_ID 
			AND EN_PROGRESO='1'
			AND ISNULL(FINALIZADO,'0')='0'
			
	UPDATE	DET_ABASTECIMIENTO
	SET		EN_PROGRESO='0'
	WHERE	ABAST_ID=@ABAST_ID		

END