/****** OBJECT:  STOREDPROCEDURE [DBO].[LOCATOREGRESO]    SCRIPT DATE: 03/30/2015 10:42:47 ******/
IF  EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[ABAST_MOB_VALIDAR_CONTENEDORA]') AND TYPE IN (N'P', N'PC'))
DROP PROCEDURE [DBO].[ABAST_MOB_VALIDAR_CONTENEDORA]
GO

CREATE PROCEDURE [DBO].[ABAST_MOB_VALIDAR_CONTENEDORA]
@USUARIO			VARCHAR(100),
@NRO_CONTENEDORA	BIGINT,
@RESULT				VARCHAR(1) OUTPUT
AS
BEGIN
	DECLARE @CONTADOR	NUMERIC(20,0)
	
	SELECT	@CONTADOR=COUNT(AC.CONSUMO_ID)
	FROM	ABAST_CONSUMO_LOCATOR AC INNER JOIN DET_ABASTECIMIENTO D
			ON(AC.ABAST_ID=D.ABAST_ID)
	WHERE	AC.NRO_CONTENEDORA=@NRO_CONTENEDORA
			AND D.EN_PROGRESO='1'
			AND D.FINALIZADO='0'
			AND D.USUARIO<>@USUARIO
			
	IF @CONTADOR=0 BEGIN
		SET @RESULT='1' --TODO MAS QUE BIEN, SE PUEDE USAR LA CONTENEDORA.
	END
	ELSE
	BEGIN
		SET @RESULT='0' --LA CONTENEDORA ESTA OCUPADA.
	END			
END		