
/****** OBJECT:  USERDEFINEDFUNCTION [DBO].[FX_FIN_RUTA]    SCRIPT DATE: 04/03/2015 16:06:45 ******/
IF  EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[DBO].[ABAST_TIENE_STOCK]') AND TYPE IN (N'FN', N'IF', N'TF', N'FS', N'FT'))
DROP FUNCTION [DBO].[ABAST_TIENE_STOCK]
GO

CREATE     FUNCTION [DBO].[ABAST_TIENE_STOCK](
@CLIENTE_ID		VARCHAR(15),
@PRODUCTO_ID	VARCHAR(30))RETURNS VARCHAR
AS
BEGIN

	DECLARE @CONTROL	NUMERIC(20,5)
	DECLARE @RETORNO	VARCHAR(1)
	
	SELECT	@CONTROL=SUM(X.CANTIDAD)
	FROM	(	SELECT	 DD.CLIENTE_ID
						,DD.PRODUCTO_ID AS PRODUCTO
						,RL.CANTIDAD
				FROM	RL_DET_DOC_TRANS_POSICION RL
						INNER JOIN DET_DOCUMENTO_TRANSACCION DDT ON(RL.DOC_TRANS_ID=DDT.DOC_TRANS_ID AND RL.NRO_LINEA_TRANS=DDT.NRO_LINEA_TRANS)
						INNER JOIN DET_DOCUMENTO DD ON (DDT.DOCUMENTO_ID=DD.DOCUMENTO_ID AND DDT.NRO_LINEA_DOC=DD.NRO_LINEA)
						INNER JOIN CATEGORIA_LOGICA CL ON (RL.CLIENTE_ID=CL.CLIENTE_ID AND RL.CAT_LOG_ID=CL.CAT_LOG_ID )
						INNER JOIN POSICION P ON (RL.POSICION_ACTUAL=P.POSICION_ID)
						LEFT JOIN ESTADO_MERCADERIA_RL EM ON (RL.CLIENTE_ID=EM.CLIENTE_ID AND RL.EST_MERC_ID=EM.EST_MERC_ID) 	
						INNER JOIN DOCUMENTO D ON(DD.DOCUMENTO_ID=D.DOCUMENTO_ID)
				WHERE	RL.DOC_TRANS_ID_EGR IS NULL
						AND RL.NRO_LINEA_TRANS_EGR IS NULL
						AND RL.DISPONIBLE='1'
						AND ISNULL(EM.DISP_EGRESO,'1')='1'
						AND ISNULL(EM.PICKING,'1')='1'
						AND P.POS_LOCKEADA='0' 
						AND ISNULL(P.ABASTECIBLE,'0')='0'
						AND P.PICKING='0'
						AND CL.DISP_EGRESO='1' 
						AND CL.PICKING='1'
						AND RL.CAT_LOG_ID<>'TRAN_EGR' --PARA ASEGURARME QUE NO ESTE EN PROCESO DE EGRESO
						AND D.CLIENTE_ID = @CLIENTE_ID
						AND DD.PRODUCTO_ID=@PRODUCTO_ID
				UNION
				SELECT	 DD.CLIENTE_ID
						,DD.PRODUCTO_ID AS PRODUCTO
						,RL.CANTIDAD
				FROM	RL_DET_DOC_TRANS_POSICION RL
						INNER JOIN DET_DOCUMENTO_TRANSACCION DDT ON(RL.DOC_TRANS_ID=DDT.DOC_TRANS_ID AND RL.NRO_LINEA_TRANS=DDT.NRO_LINEA_TRANS)
						INNER JOIN DET_DOCUMENTO DD ON (DDT.DOCUMENTO_ID=DD.DOCUMENTO_ID AND DDT.NRO_LINEA_DOC=DD.NRO_LINEA)
						INNER JOIN CATEGORIA_LOGICA CL ON (RL.CLIENTE_ID=CL.CLIENTE_ID AND RL.CAT_LOG_ID=CL.CAT_LOG_ID )
						INNER JOIN NAVE N ON (RL.NAVE_ACTUAL=N.NAVE_ID)
						LEFT JOIN ESTADO_MERCADERIA_RL EM ON (RL.CLIENTE_ID=EM.CLIENTE_ID AND RL.EST_MERC_ID=EM.EST_MERC_ID) 
						INNER JOIN DOCUMENTO D ON(DD.DOCUMENTO_ID=D.DOCUMENTO_ID)
				WHERE	RL.DOC_TRANS_ID_EGR IS NULL
						AND RL.NRO_LINEA_TRANS_EGR IS NULL
						AND RL.DISPONIBLE='1'
						AND ISNULL(EM.DISP_EGRESO,'1')='1'
						AND ISNULL(EM.PICKING,'1')='1'
						AND RL.CAT_LOG_ID<>'TRAN_EGR'
						AND N.DISP_EGRESO='1' 
						AND N.PRE_EGRESO='0' 
						AND N.PRE_INGRESO='0' 
						AND N.PICKING='0'
						AND CL.DISP_EGRESO='1' 
						AND CL.PICKING='1'
						AND D.CLIENTE_ID = @CLIENTE_ID
						AND DD.PRODUCTO_ID= @PRODUCTO_ID)X
	IF @CONTROL>0 BEGIN
		SET @RETORNO='1'
	END ELSE BEGIN
		SET @RETORNO='2'
	END						
	RETURN @RETORNO			
END					