/****** OBJECT:  STOREDPROCEDURE [DBO].[LOCATOREGRESO]    SCRIPT DATE: 03/30/2015 10:42:47 ******/
IF  EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[ABAST_MOB_CONFIRMAPORCONTENEDORA]') AND TYPE IN (N'P', N'PC'))
DROP PROCEDURE [DBO].[ABAST_MOB_CONFIRMAPORCONTENEDORA]
GO

CREATE PROCEDURE [DBO].[ABAST_MOB_CONFIRMAPORCONTENEDORA]
	@ABAST_ID			BIGINT,
	@CLIENTE_ID			VARCHAR(15),
	@PRODUCTO_ID		VARCHAR(30),
	@NRO_BULTO			VARCHAR(100),
	@RETORNO			VARCHAR(1)		OUTPUT,
	@CANT_CONT			NUMERIC(20,5)	OUTPUT
AS
BEGIN
	DECLARE @CANT_TOTAL	AS NUMERIC(20,0)
	DECLARE @CANT_ASIG	AS NUMERIC(20,0)
	DECLARE @SERIALIZA	AS VARCHAR(1)
	
	SELECT	@SERIALIZA=ISNULL(SERIE_ING,0)
	FROM	PRODUCTO
	WHERE	CLIENTE_ID=@CLIENTE_ID
			AND PRODUCTO_ID=@PRODUCTO_ID
	
	SELECT	@CANT_TOTAL=SUM(RL.CANTIDAD)
	FROM	DET_DOCUMENTO DD INNER JOIN DET_DOCUMENTO_TRANSACCION DDT
			ON(DD.DOCUMENTO_ID=DDT.DOCUMENTO_ID AND DD.NRO_LINEA=DDT.NRO_LINEA_DOC)
			INNER JOIN RL_DET_DOC_TRANS_POSICION RL
			ON(DDT.DOC_TRANS_ID=RL.DOC_TRANS_ID AND DDT.NRO_LINEA_TRANS=RL.NRO_LINEA_TRANS)
	WHERE	DD.CLIENTE_ID=@CLIENTE_ID
			AND DD.PRODUCTO_ID =@PRODUCTO_ID
			AND DD.NRO_BULTO=@NRO_BULTO
			

	SELECT	@CANT_ASIG=SUM(RL.CANTIDAD)
	FROM	ABAST_CONSUMO_LOCATOR A INNER JOIN RL_DET_DOC_TRANS_POSICION RL		
			ON(A.RL_ID=RL.RL_ID)
			INNER JOIN DET_DOCUMENTO_TRANSACCION DDT
			ON(RL.DOC_TRANS_ID=DDT.DOC_TRANS_ID AND RL.NRO_LINEA_TRANS=DDT.NRO_LINEA_TRANS)
			INNER JOIN DET_DOCUMENTO DD
			ON(DDT.DOCUMENTO_ID=DD.DOCUMENTO_ID AND DDT.NRO_LINEA_DOC=DD.NRO_LINEA)
	WHERE	DD.CLIENTE_ID=@CLIENTE_ID
			AND DD.PRODUCTO_ID=@PRODUCTO_ID
			AND DD.NRO_BULTO=@NRO_BULTO
			AND A.ABAST_ID=@ABAST_ID
			
	IF @CANT_ASIG<>@CANT_TOTAL
	BEGIN	
		SET @RETORNO='0'
	END
	ELSE
	BEGIN
		IF @SERIALIZA='1'
		BEGIN
			SET @CANT_CONT=@CANT_ASIG
			SET @RETORNO='1'
		END
		ELSE
		BEGIN
			SET @RETORNO='0'
		END
	END	
			
END			