/****** OBJECT:  STOREDPROCEDURE [DBO].[LOCATOREGRESO]    SCRIPT DATE: 03/30/2015 10:42:47 ******/
IF  EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[ABAST_MOB_VAL_PROD_CONTENEDORA_DESCARGA]') AND TYPE IN (N'P', N'PC'))
DROP PROCEDURE [DBO].[ABAST_MOB_VAL_PROD_CONTENEDORA_DESCARGA]
GO

CREATE PROCEDURE [DBO].[ABAST_MOB_VAL_PROD_CONTENEDORA_DESCARGA]
	@NRO_CONTENEDORA	AS BIGINT,
	@PRODUCTO_ID		AS VARCHAR(30),
	@OUTPUT				VARCHAR(1) OUTPUT
AS
BEGIN
	DECLARE @CONT	NUMERIC(20,0)

	SELECT	@CONT=COUNT(CONSUMO_ID)
	FROM	ABAST_CONSUMO_LOCATOR
	WHERE	NRO_CONTENEDORA=@NRO_CONTENEDORA
			AND PRODUCTO_ID=@PRODUCTO_ID
			AND EN_PROGRESO='1'
			AND FINALIZADO IS NULL
			AND CANT_CONFIRMADA>0
			
	IF @CONT>0 BEGIN
		SET @OUTPUT='1';
	END
	ELSE
	BEGIN
		SET @OUTPUT='0';
	END			
END