/****** OBJECT:  STOREDPROCEDURE [DBO].[LOCATOREGRESO]    SCRIPT DATE: 03/30/2015 10:42:47 ******/
IF  EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[ABAST_MOB_VAL_PRODUCTO_CONTENEDORA]') AND TYPE IN (N'P', N'PC'))
DROP PROCEDURE [DBO].[ABAST_MOB_VAL_PRODUCTO_CONTENEDORA]
GO

CREATE PROCEDURE [DBO].[ABAST_MOB_VAL_PRODUCTO_CONTENEDORA]
	@NRO_CONTENEDORA	BIGINT,
	@PRODUCTO_ID		VARCHAR(30)
AS
BEGIN

	SELECT	TOP 1
			A.ABAST_ID,								--0
			A.CLIENTE_ID,							--1
			A.PRODUCTO_ID,							--2
			P.DESCRIPCION,							--3
			SUM(A.CANT_CONFIRMADA) QTY_TOTAL,		--4
			PS.POSICION_COD,						--5
			DD.NRO_BULTO,							--6
			DD.NRO_LOTE,							--7
			DD.NRO_PARTIDA							--8
			--DD.NRO_SERIE							--9
	FROM	ABAST_CONSUMO_LOCATOR A INNER JOIN PRODUCTO P	ON(A.CLIENTE_ID=P.CLIENTE_ID AND A.PRODUCTO_ID=P.PRODUCTO_ID)
			INNER JOIN DET_ABASTECIMIENTO DA				ON(A.ABAST_ID=DA.ABAST_ID)
			INNER JOIN POSICION PS							ON(DA.POSICION_ID=PS.POSICION_ID)
			INNER JOIN RL_DET_DOC_TRANS_POSICION RL			ON(A.RL_ID=RL.RL_ID)
			INNER JOIN DET_DOCUMENTO_TRANSACCION DDT		ON(RL.DOC_TRANS_ID=DDT.DOC_TRANS_ID AND RL.NRO_LINEA_TRANS=DDT.NRO_LINEA_TRANS)
			INNER JOIN DET_DOCUMENTO DD						ON(DDT.DOCUMENTO_ID=DD.DOCUMENTO_ID AND DDT.NRO_LINEA_DOC=DD.NRO_LINEA)
	WHERE	A.NRO_CONTENEDORA=@NRO_CONTENEDORA
			AND A.PRODUCTO_ID=@PRODUCTO_ID
			AND A.EN_PROGRESO='1'
			AND A.CANT_CONFIRMADA>0
			AND A.EN_CONTENEDOR='1'
			AND ISNULL(A.FINALIZADO,'0')='0'
	GROUP BY
			A.ABAST_ID, A.CLIENTE_ID, A.PRODUCTO_ID, P.DESCRIPCION, PS.POSICION_COD, DD.NRO_BULTO, DD.NRO_LOTE, DD.NRO_PARTIDA
			--, DD.NRO_SERIE		
END			


    