/****** OBJECT:  STOREDPROCEDURE [DBO].[LOCATOREGRESO]    SCRIPT DATE: 03/30/2015 10:42:47 ******/
IF  EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[DBO].[ABAST_MOB_CONTENIDO]') AND TYPE IN (N'P', N'PC'))
DROP PROCEDURE [DBO].[ABAST_MOB_CONTENIDO]
GO

CREATE PROCEDURE [DBO].[ABAST_MOB_CONTENIDO]
@CONTENEDORA	BIGINT
AS
BEGIN
	SELECT	A.CLIENTE_ID									AS [Cod.Cliente], 
			A.PRODUCTO_ID									AS [Cod.Producto], 
			ISNULL(SUM(A.CANT_CONFIRMADA),SUM(A.CANTIDAD))	AS [Cantidad], 
			DD.NRO_LOTE										AS [Nro.Lote], 
			DD.NRO_PARTIDA									AS [Nro.Partida],
			P.POSICION_COD									AS [Posicion Abast.],
			A.ABAST_ID										AS [Nro.Tarea]
	FROM	ABAST_CONSUMO_LOCATOR A INNER JOIN RL_DET_DOC_TRANS_POSICION RL		ON(A.RL_ID=RL.RL_ID)
			INNER JOIN DET_DOCUMENTO_TRANSACCION DDT							ON(DDT.DOC_TRANS_ID=RL.DOC_TRANS_ID AND DDT.NRO_LINEA_TRANS=RL.NRO_LINEA_TRANS)
			INNER JOIN DET_DOCUMENTO DD											ON(DD.DOCUMENTO_ID=DDT.DOCUMENTO_ID AND DD.NRO_LINEA=DDT.NRO_LINEA_DOC)
			INNER JOIN DET_ABASTECIMIENTO DA									ON(A.ABAST_ID=DA.ABAST_ID)
			INNER JOIN POSICION P												ON(DA.POSICION_ID=P.POSICION_ID)
	WHERE	NRO_CONTENEDORA=@CONTENEDORA
			AND A.EN_PROGRESO='1'
			AND A.FINALIZADO IS NULL
	GROUP BY
			A.ABAST_ID,A.CLIENTE_ID, A.PRODUCTO_ID, DD.NRO_LOTE, DD.NRO_PARTIDA,P.POSICION_COD	
							
END