/****** OBJECT:  STOREDPROCEDURE [DBO].[ABAST_REPORTE]    SCRIPT DATE: 03/30/2015 10:42:47 ******/
IF  EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[DBO].[ABAST_REPORTE]') AND TYPE IN (N'P', N'PC'))
DROP PROCEDURE [DBO].[ABAST_REPORTE]
GO

CREATE PROCEDURE [DBO].[ABAST_REPORTE]
	@P_ABASTECIMIENTO	VARCHAR(4000) OUTPUT
AS
BEGIN

	SELECT	*
	FROM	(	SELECT	PDA.POSICION_COD		AS POSICION_DEST,
						DA.CLIENTE_ID + ' - ' +
						C.RAZON_SOCIAL			AS CLIENTE,
						DA.PRODUCTO_ID + ' - ' + 
						PR.DESCRIPCION			AS PRODUCTO,	
						DA.CANT_A_ABASTECER		AS CANT_A_ABASTECER,
						POS.POSICION_COD		AS UBICACION_ORIGEN,
						SUM(A.CANTIDAD)			AS CANTIDAD_ORIGEN,
						CASE 
						WHEN DD.NRO_SERIE IS NULL THEN '' 
						Else 'Nro.Serie: ' + CAST(DD.NRO_SERIE AS VARCHAR) + ', '
						END + 
						CASE 
						WHEN DD.NRO_BULTO IS NULL THEN '' 
						Else 'Nro.Bulto: ' + CAST(DD.NRO_BULTO AS VARCHAR) + ', '
						END + 
						CASE 
						WHEN DD.NRO_LOTE IS NULL THEN '' 
						Else 'Nro.Lote: ' + CAST(DD.NRO_LOTE AS VARCHAR) + ', '
						END + 
						CASE 
						WHEN DD.NRO_PARTIDA IS NULL THEN '' 
						Else 'Nro.Partida: ' + CAST(DD.NRO_PARTIDA AS VARCHAR) + ' '
						END AS[PROPIEDADES],
						A.NRO_CONTENEDORA,
						SUM(A.CANT_CONFIRMADA) CANT_CONFIRMADA,
						DA.PRIORIDAD,
						CONVERT(VARCHAR,GETDATE(),103) FECHA
				FROM	DET_ABASTECIMIENTO DA INNER JOIN ABAST_CONSUMO_LOCATOR A	ON(DA.ABAST_ID=A.ABAST_ID)
						INNER JOIN POSICION PDA										ON(DA.POSICION_ID=PDA.POSICION_ID)
						INNER JOIN RL_DET_DOC_TRANS_POSICION RL						ON(A.RL_ID=RL.RL_ID)
						INNER JOIN POSICION POS										ON(RL.POSICION_ACTUAL=POS.POSICION_ID)
						INNER JOIN DET_DOCUMENTO_TRANSACCION DDT					ON(RL.DOC_TRANS_ID=DDT.DOC_TRANS_ID AND RL.NRO_LINEA_TRANS=DDT.NRO_LINEA_TRANS)
						INNER JOIN DET_DOCUMENTO DD									ON(DDT.DOCUMENTO_ID=DD.DOCUMENTO_ID AND DDT.NRO_LINEA_DOC=DD.NRO_LINEA)
						INNER JOIN CLIENTE C										ON(DA.CLIENTE_ID=C.CLIENTE_ID)
						INNER JOIN PRODUCTO PR										ON(DA.CLIENTE_ID=PR.CLIENTE_ID AND DA.PRODUCTO_ID=PR.PRODUCTO_ID)
						INNER JOIN [DBO].[ABAST_SPLIT](@P_ABASTECIMIENTO,',') SP	ON(DA.ABAST_ID=SP.DATA)
				GROUP BY
						PDA.POSICION_COD,
						DA.CLIENTE_ID,
						DA.PRODUCTO_ID,
						DA.CANT_A_ABASTECER,
						POS.POSICION_COD,
						DD.NRO_SERIE,
						DD.NRO_LOTE,
						DD.NRO_PARTIDA,
						DD.NRO_BULTO,
						C.RAZON_SOCIAL,
						PR.DESCRIPCION,
						A.NRO_CONTENEDORA,
						DA.PRIORIDAD
						
				UNION ALL
				SELECT	PDA.POSICION_COD		AS POSICION_DEST,
						DA.CLIENTE_ID + ' - ' +
						C.RAZON_SOCIAL			AS CLIENTE,
						DA.PRODUCTO_ID + ' - ' + 
						PR.DESCRIPCION			AS PRODUCTO,	
						DA.CANT_A_ABASTECER		AS CANT_A_ABASTECER,
						N.NAVE_COD				AS UBICACION_ORIGEN,
						SUM(A.CANTIDAD)			AS CANTIDAD_ORIGEN,
						CASE 
						WHEN DD.NRO_SERIE IS NULL THEN '' 
						Else 'Nro.Serie: ' + CAST(DD.NRO_SERIE AS VARCHAR) + ', '
						END + 
						CASE 
						WHEN DD.NRO_BULTO IS NULL THEN '' 
						Else 'Nro.Bulto: ' + CAST(DD.NRO_BULTO AS VARCHAR) + ', '
						END + 
						CASE 
						WHEN DD.NRO_LOTE IS NULL THEN '' 
						Else 'Nro.Lote: ' + CAST(DD.NRO_LOTE AS VARCHAR) + ', '
						END + 
						CASE 
						WHEN DD.NRO_PARTIDA IS NULL THEN '' 
						Else 'Nro.Partida: ' + CAST(DD.NRO_PARTIDA AS VARCHAR) + ' '
						END AS[PROPIEDADES],		
						A.NRO_CONTENEDORA,
						SUM(A.CANT_CONFIRMADA) CANT_CONFIRMADA,
						DA.PRIORIDAD,
						CONVERT(VARCHAR,GETDATE(),103) FECHA
				FROM	DET_ABASTECIMIENTO DA INNER JOIN ABAST_CONSUMO_LOCATOR A	ON(DA.ABAST_ID=A.ABAST_ID)
						INNER JOIN POSICION PDA										ON(DA.POSICION_ID=PDA.POSICION_ID)
						INNER JOIN RL_DET_DOC_TRANS_POSICION RL						ON(A.RL_ID=RL.RL_ID)
						INNER JOIN NAVE N											ON(RL.NAVE_ACTUAL=N.NAVE_ID)
						INNER JOIN DET_DOCUMENTO_TRANSACCION DDT					ON(RL.DOC_TRANS_ID=DDT.DOC_TRANS_ID AND RL.NRO_LINEA_TRANS=DDT.NRO_LINEA_TRANS)
						INNER JOIN DET_DOCUMENTO DD									ON(DDT.DOCUMENTO_ID=DD.DOCUMENTO_ID AND DDT.NRO_LINEA_DOC=DD.NRO_LINEA)
						INNER JOIN CLIENTE C										ON(DA.CLIENTE_ID=C.CLIENTE_ID)
						INNER JOIN PRODUCTO PR										ON(DA.CLIENTE_ID=PR.CLIENTE_ID AND DA.PRODUCTO_ID=PR.PRODUCTO_ID)
						INNER JOIN [DBO].[ABAST_SPLIT](@P_ABASTECIMIENTO,',') SP	ON(DA.ABAST_ID=SP.DATA)
				GROUP BY
						PDA.POSICION_COD,
						DA.CLIENTE_ID,
						DA.PRODUCTO_ID,
						DA.CANT_A_ABASTECER,
						N.NAVE_COD,
						DD.NRO_SERIE,
						DD.NRO_LOTE,
						DD.NRO_PARTIDA,
						DD.NRO_BULTO,
						C.RAZON_SOCIAL,
						PR.DESCRIPCION,
						A.NRO_CONTENEDORA,
						DA.PRIORIDAD)X
	ORDER BY
		X.PRIORIDAD						

END


