

/****** Object:  StoredProcedure [dbo].[EMPAQUETADO_CIERRA_CAJA]    Script Date: 04/22/2015 16:33:21 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[EMPAQUETADO_CIERRA_CAJA]') AND type in (N'P', N'PC'))
DROP PROCEDURE [dbo].[EMPAQUETADO_CIERRA_CAJA]
GO


CREATE PROCEDURE [dbo].[EMPAQUETADO_CIERRA_CAJA]
	@MEDIDAS	AS VARCHAR(100) OUTPUT,
	@UC			AS VARCHAR(100) OUTPUT,
	@PESO		AS NUMERIC(20,5)OUTPUT,
	@ALTO		AS NUMERIC(20,5)OUTPUT,
	@ANCHO		AS NUMERIC(20,5)OUTPUT,
	@LARGO		AS NUMERIC(20,5)OUTPUT,
	@TR			AS VARCHAR(20) OUTPUT,
	@MONEDA		AS VARCHAR(20) OUTPUT,
	@VALOR		AS NUMERIC(20,5)OUTPUT,
	@OBS		AS VARCHAR(200) OUTPUT
AS
BEGIN
	DECLARE @CONTROL	BIGINT
	DECLARE @VOLUMEN	FLOAT
	
	SELECT	@CONTROL=COUNT(*)
	FROM	UC_EMPAQUE
	WHERE	UC_EMPAQUE=@UC

	SET @VOLUMEN=(@ALTO*@ANCHO*@LARGO)/1000000

	IF @CONTROL>0 
	BEGIN
		--UPDATE
		UPDATE	UC_EMPAQUE 
		SET		 ALTO=@ALTO
				,ANCHO=@ANCHO
				,LARGO=@LARGO
				,VOLUMEN=@VOLUMEN
				,TRANSPORTE_ID=@TR
				,MONEDA_ID=@MONEDA
				,VALOR=@VALOR
				,OBSERVACIONES=@OBS
		WHERE	UC_EMPAQUE=@UC

	END	
	ELSE
	BEGIN
		--INSERT
		INSERT INTO UC_EMPAQUE(UC_EMPAQUE,ALTO,ANCHO,LARGO,VOLUMEN,TRANSPORTE_ID,MONEDA_ID,VALOR, OBSERVACIONES)
		VALUES	(@UC, @ALTO, @ANCHO, @LARGO, @VOLUMEN,@TR,@MONEDA, @VALOR, @OBS)
	END

	UPDATE	PICKING
	SET		PALLET_CERRADO='1',
			FECHA_UCEMPAQUETADO=GETDATE(),
			UCEMPAQUETADO_PESO=@PESO
	WHERE	NRO_UCEMPAQUETADO=@UC
END






GO


