
IF  EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[DBO].[PRODUCTO_BORRAR_IMAGEN]') AND TYPE IN (N'P', N'PC'))
DROP PROCEDURE [DBO].[PRODUCTO_BORRAR_IMAGEN]
GO

CREATE PROC [DBO].[PRODUCTO_BORRAR_IMAGEN](
			  @CLIENTE_ID VARCHAR(15)	OUTPUT
			, @PRODUCTO_ID VARCHAR(30)	OUTPUT)
AS
BEGIN
	
	IF EXISTS (	SELECT 1 FROM PRODUCTO_IMG WHERE CLIENTE_ID = @CLIENTE_ID AND PRODUCTO_ID=@PRODUCTO_ID)
						
		DELETE	
		FROM	PRODUCTO_IMG 
		WHERE	CLIENTE_ID = @CLIENTE_ID
				AND PRODUCTO_ID=@PRODUCTO_ID

END

GO


