
IF  EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[DBO].[PRODUCTO_INSERTAR_IMAGEN]') AND TYPE IN (N'P', N'PC'))
DROP PROCEDURE [DBO].[PRODUCTO_INSERTAR_IMAGEN]
GO

CREATE PROC [DBO].[PRODUCTO_INSERTAR_IMAGEN](
			  @CLIENTE_ID VARCHAR(15)	OUTPUT
			, @PRODUCTO_ID VARCHAR(30)	OUTPUT
			, @IMAGEN IMAGE				OUTPUT)
AS
BEGIN
	
	IF EXISTS (	SELECT 1 FROM PRODUCTO_IMG WHERE CLIENTE_ID = @CLIENTE_ID AND PRODUCTO_ID=@PRODUCTO_ID)
						
		UPDATE	PRODUCTO_IMG 
		SET		IMAGEN = @IMAGEN
		WHERE	CLIENTE_ID = @CLIENTE_ID
				AND PRODUCTO_ID=@PRODUCTO_ID
				
	ELSE
	
		INSERT INTO PRODUCTO_IMG (CLIENTE_ID, PRODUCTO_ID, IMAGEN) 
		VALUES (
			 @CLIENTE_ID
			,@PRODUCTO_ID
			,@IMAGEN)

END

GO


