
/****** Object:  StoredProcedure [dbo].[SPLIT_CONTENEDORA_PICKING]    Script Date: 06/12/2015 12:29:11 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[SPLIT_CONTENEDORA_PICKING]') AND type in (N'P', N'PC'))
DROP PROCEDURE [dbo].[SPLIT_CONTENEDORA_PICKING]
GO

CREATE PROCEDURE [dbo].[SPLIT_CONTENEDORA_PICKING]
	@CLIENTE_ID		VARCHAR(100),
	@VIAJE_ID		VARCHAR(100),
	@CONTENEDORA	VARCHAR(100)
AS
BEGIN


	DECLARE @CUR_PICK		CURSOR,
			@PICKING_ID		BIGINT,
			@CANTIDAD		NUMERIC(20,5),
			@CONTADOR		NUMERIC(20,5)

	IF CURSOR_STATUS('global','@CUR_PICK')>=-1
	BEGIN
		DEALLOCATE @CUR_PICK
	END
	
	SET @CUR_PICK = CURSOR FOR
	SELECT	PICKING_ID
	FROM	PICKING P INNER JOIN DET_DOCUMENTO DD
			ON(P.DOCUMENTO_ID=DD.DOCUMENTO_ID AND P.NRO_LINEA=DD.NRO_LINEA)
	WHERE	P.CLIENTE_ID=@CLIENTE_ID
			AND P.VIAJE_ID=@VIAJE_ID
			AND DD.NRO_BULTO=@CONTENEDORA;
	
	OPEN @CUR_PICK
	FETCH @CUR_PICK INTO @PICKING_ID
	WHILE @@FETCH_STATUS=0
	BEGIN
		SET @CONTADOR=1
		
		SELECT	@CANTIDAD=CANTIDAD
		FROM	PICKING
		WHERE	PICKING_ID=@PICKING_ID;
		
		WHILE @CONTADOR<@CANTIDAD
		BEGIN

			INSERT INTO PICKING
			SELECT 	 DOCUMENTO_ID			,NRO_LINEA			,CLIENTE_ID			,PRODUCTO_ID
					,VIAJE_ID				,TIPO_CAJA			,DESCRIPCION		,1
					,NAVE_COD				,POSICION_COD		,RUTA				,PROP1
					,NULL 					,NULL				,USUARIO			,NULL		
					,NULL					,0					,'0'				,NULL		
					,'0'					,'0'				,'0'				,'0'
					,'0'					,NULL				,NULL				,NULL
					,NULL					,NULL				,NULL				,NULL
					,NULL					,NULL				,NULL				,HIJO
					,NULL					,NULL				,NULL				,NULL
					,NULL					,REMITO_IMPRESO		,NRO_REMITO_PF		,ISNULL(PICKING_ID_REF,PICKING_ID)
					,NULL					,BULTOS_NO_CONTROLADOS					,FLG_PALLET_HOMBRE
					,TRANSF_TERMINADA		,NRO_LOTE			,NRO_PARTIDA		,NULL
					,NULL AS ESTADO
					,NULL AS NRO_UCDESCONSOLIDACION
					,NULL AS FECHA_DESCONSOLIDACION
					,NULL AS USUARIO_DESCONSOLIDACION
					,NULL AS TERMINAL_DESCONSOLIDACION
					,NULL AS NRO_UEMPAQUETADO
					,NULL AS UCEMPAQUETADO_MEDIDAS
					,NULL AS FECHA_UCEMPAQUETADO
					,NULL AS UCEMPAQUETADO_PESO
			FROM	PICKING
			WHERE	PICKING_ID=@PICKING_ID		
		
			SET @CONTADOR=@CONTADOR + 1;
			
		END
		
		UPDATE PICKING SET CANTIDAD=1 WHERE PICKING_ID=@PICKING_ID;
		
	FETCH NEXT FROM @CUR_PICK INTO @PICKING_ID			
	
	END
	CLOSE @CUR_PICK
	DEALLOCATE @CUR_PICK;
	
END

GO


