
/****** Object:  StoredProcedure [dbo].[FRONTERA_VALIDACION_MULTICLIENTE]    Script Date: 06/16/2015 11:50:11 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[FRONTERA_VALIDACION_MULTICLIENTE]') AND type in (N'P', N'PC'))
DROP PROCEDURE [dbo].[FRONTERA_VALIDACION_MULTICLIENTE]
GO

--DROP PROCEDURE DBO.FRONTERA_VALIDACION_MULTICLIENTE
CREATE PROCEDURE [dbo].[FRONTERA_VALIDACION_MULTICLIENTE]
	@VIAJE_ID	VARCHAR(100) OUTPUT
AS
BEGIN
	DECLARE @CONT	NUMERIC(20,0)
	DECLARE @CANT	NUMERIC(20,0)
	DECLARE @CANT_HIST NUMERIC(20,0)
	
	SELECT	@CONT=COUNT(DISTINCT X.CONF)
	FROM	(	SELECT	CAST(ISNULL(FLG_DESCONSOLIDACION,'0')AS VARCHAR)
						+ CAST(ISNULL(TIPO_EMPAQUETADO_ID,'0')AS VARCHAR)
						+ CAST(ISNULL(FLG_EMPAQUETADO,'0')AS VARCHAR)
						+ CAST(ISNULL(FLG_DISTRIBUCION,'0')AS VARCHAR)
						+ CAST(ISNULL(FLG_CONTROL_EXP,'0')AS VARCHAR)CONF
				FROM	CLIENTE_PARAMETROS CP
				WHERE	EXISTS (SELECT	1
								FROM	SYS_INT_DOCUMENTO P
								WHERE	P.CODIGO_VIAJE=@VIAJE_ID
										AND CP.CLIENTE_ID=P.CLIENTE_ID))X
	IF @CONT>1 BEGIN										
		RAISERROR('Los clientes de la Ola %s, poseen diferentes configuraciones de egreso. Por favor verifique las mismas en la pantalla de Configuracion por Cliente.',16,1,@viaje_id)
	END
	IF @CONT=0 BEGIN										
		RAISERROR('No se encontro el Pedido: %s, presione Refrescar y vuelva a intentar la operacion.',16,1,@viaje_id)
	END	
	
	SELECT @CANT = COUNT(*) FROM PICKING WHERE VIAJE_ID = @VIAJE_ID
	SELECT @CANT_HIST  = COUNT(*) FROM PICKING_HISTORICO WHERE VIAJE_ID = @VIAJE_ID
	  
	IF @CANT + @CANT_HIST > 0 BEGIN
		RAISERROR(' El código de viaje "%s" ya existe y fue procesado, por favor modifiquelo.',16,1,@viaje_id)
	END	
	
END

GO
