
/****** Object:  StoredProcedure [dbo].[RPT_STOCK_VOLUMEN]    Script Date: 06/15/2015 15:20:01 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[RPT_STOCK_VOLUMEN]') AND type in (N'P', N'PC'))
DROP PROCEDURE [dbo].[RPT_STOCK_VOLUMEN]
GO

CREATE PROCEDURE [dbo].[RPT_STOCK_VOLUMEN]

	@FDESDE			VARCHAR(8)		OUTPUT,	--ANSI
	@FHASTA			VARCHAR(8)		OUTPUT,	--ANSI
	@CLIENTE_ID		VARCHAR(15)		OUTPUT,
	@NAVE_ID		NUMERIC(20,0)	OUTPUT
AS
BEGIN
	SET NOCOUNT ON
	
	DECLARE @XSQL		AS NVARCHAR(4000)
	DECLARE @XSQL2		AS NVARCHAR(4000)

	SET @XSQL='	
	SELECT  DISTINCT  
			 CONVERT(VARCHAR,SE.F_SNAP,103)																AS FECHA
			,C.RAZON_SOCIAL																				AS CLIENTE
			,N.NAVE_COD																					AS NAVE_COD
			,QPOS.CTN																					AS Q_POS_OCUPADAS
			,SUM((ISNULL(P.ALTO,0)*ISNULL(P.ANCHO,0)*ISNULL(P.LARGO,0)))/1000000						AS Q_VOL_POSICIONES
			,(SUM(SE.CANTIDAD * ((ISNULL(PR.ALTO,0)*ISNULL(PR.ANCHO,0)*ISNULL(PR.LARGO,0))))/1000000)	AS Q_VOL_PROD
			,(SUM((ISNULL(P.ALTO,0)*ISNULL(P.ANCHO,0)*ISNULL(P.LARGO,0)))/1000000)-
			 (SUM(SE.CANTIDAD * ((ISNULL(PR.ALTO,0)*ISNULL(PR.ANCHO,0)*ISNULL(PR.LARGO,0))))/1000000)	AS Q_VOL_DISP_M3
			,GETDATE()																					AS F_IMP
			,HOST_NAME()																				AS TERMINAL
	FROM    SNAP_EXISTENCIAS SE(NOLOCK) INNER JOIN POSICION P(NOLOCK) 
			ON(SE.POSICION_ACTUAL=P.POSICION_ID)
			INNER JOIN NAVE N									(NOLOCK)ON(P.NAVE_ID = N.NAVE_ID)
			INNER JOIN CLIENTE C								(NOLOCK)ON(SE.CLIENTE_ID=C.CLIENTE_ID)
			LEFT JOIN DET_DOCUMENTO_TRANSACCION DDT				(NOLOCK)ON(DDT.DOC_TRANS_ID=SE.DOC_TRANS_ID AND DDT.NRO_LINEA_TRANS=SE.NRO_LINEA_TRANS)
			LEFT JOIN DET_DOCUMENTO DD							(NOLOCK)ON(DDT.DOCUMENTO_ID=DD.DOCUMENTO_ID AND DDT.NRO_LINEA_DOC=DD.NRO_LINEA)
			LEFT JOIN PRODUCTO PR								(NOLOCK)ON(DD.CLIENTE_ID=PR.CLIENTE_ID AND DD.PRODUCTO_ID=PR.PRODUCTO_ID)
			-------------------------------------------------------------------------------------------------------------------
			INNER JOIN (SELECT  S.CLIENTE_ID, S.F_SNAP, P.NAVE_ID, COUNT(DISTINCT S.POSICION_ACTUAL) CTN
						FROM    SNAP_EXISTENCIAS S(NOLOCK) INNER JOIN POSICION P(NOLOCK) ON(S.POSICION_ACTUAL=P.POSICION_ID)
						WHERE   S.DISPONIBLE=' + CHAR(39) + '1' + CHAR(39) + '
						GROUP BY 
								S.CLIENTE_ID, S.F_SNAP,P.NAVE_ID)QPOS    
			ON(SE.CLIENTE_ID=QPOS.CLIENTE_ID AND SE.F_SNAP=QPOS.F_SNAP AND P.NAVE_ID=QPOS.NAVE_ID)
	WHERE   SE.DISPONIBLE=' + CHAR(39) + '1' + CHAR(39) + 
			'AND (('+ ISNULL(CHAR(39) +CAST(@FDESDE as nvarchar)+CHAR(39) ,'NULL')+ ' IS NULL)OR(SE.F_SNAP BETWEEN '+ ISNULL(CHAR(39) +CAST(@FDESDE as nvarchar)+CHAR(39),'NULL')+ ' AND DATEADD(DAY,1,'+ ISNULL(CHAR(39) +CAST(@FHASTA as nvarchar)+ CHAR(39),'NULL') +')))
			AND (('+ ISNULL(CHAR(39) +CAST(@CLIENTE_ID as nvarchar)+ CHAR(39),'NULL') +' IS NULL)OR(SE.CLIENTE_ID='+ ISNULL(CHAR(39) +CAST(@CLIENTE_ID as nvarchar)+ CHAR(39),'NULL') +'))
			AND (('+ ISNULL(CHAR(39) +CAST(@NAVE_ID as nvarchar)+ CHAR(39),'NULL') +' IS NULL)OR(N.NAVE_ID='+ ISNULL(CHAR(39) +CAST(@NAVE_ID as nvarchar)+ CHAR(39),'NULL') +'))
	GROUP BY
			CONVERT(VARCHAR,SE.F_SNAP,103), C.RAZON_SOCIAL,N.NAVE_COD,QPOS.CTN'
			
	SET @XSQL2='			
	UNION 
	SELECT  DISTINCT  
			 CONVERT(VARCHAR,SE.F_SNAP,103)		AS FECHA
			,C.RAZON_SOCIAL						AS CLIENTE
			,N.NAVE_COD							AS NAVE_COD
			,NULL								AS Q_POS_OCUPADAS
			,NULL								AS Q_VOL_POSICIONES_M3
			,PVOL.PVOL							AS Q_VOL_PROD_M3
			,NULL								AS Q_VOL_DISP_M3
			,GETDATE()							AS F_IMP
			,HOST_NAME()						AS TERMINAL			
	FROM    SNAP_EXISTENCIAS SE (NOLOCK)INNER JOIN NAVE N (NOLOCK)                        
			ON(SE.NAVE_ACTUAL=N.NAVE_ID)
			INNER JOIN CLIENTE C(NOLOCK)                      
			ON(SE.CLIENTE_ID=C.CLIENTE_ID)
			-------------------------------------------------------------------------------------------------------------------
			LEFT JOIN ( SELECT  F.CLIENTE_ID,F.F_SNAP,F.NAVE_ID,SUM(F.PVOL) AS PVOL
						FROM    (	SELECT  S.CLIENTE_ID, S.F_SNAP, N.NAVE_ID
											,S.CANTIDAD * ((ISNULL(PR.ALTO,0)*ISNULL(PR.ANCHO,0)*ISNULL(PR.LARGO,0))/1000000) AS PVOL
									FROM    SNAP_EXISTENCIAS S (NOLOCK)INNER JOIN NAVE N(NOLOCK)ON(S.NAVE_ACTUAL=N.NAVE_ID AND NAVE_TIENE_LAYOUT='+ CHAR(39) + '0' + CHAR(39) +')
											INNER JOIN DET_DOCUMENTO_TRANSACCION DDT(NOLOCK)	ON(DDT.DOC_TRANS_ID=S.DOC_TRANS_ID AND DDT.NRO_LINEA_TRANS=S.NRO_LINEA_TRANS)
											INNER JOIN DET_DOCUMENTO DD(NOLOCK)					ON(DDT.DOCUMENTO_ID=DD.DOCUMENTO_ID AND DDT.NRO_LINEA_DOC=DD.NRO_LINEA)
											INNER JOIN PRODUCTO PR(NOLOCK)						ON(DD.CLIENTE_ID=PR.CLIENTE_ID AND DD.PRODUCTO_ID=PR.PRODUCTO_ID)
									WHERE	S.DISPONIBLE='+ CHAR(39)+ '1' +CHAR(39) +'
								)F
						GROUP BY
							  F.CLIENTE_ID,F.F_SNAP,F.NAVE_ID
					  )PVOL
			ON(SE.CLIENTE_ID=PVOL.CLIENTE_ID AND SE.F_SNAP=PVOL.F_SNAP AND N.NAVE_ID=PVOL.NAVE_ID)
			-------------------------------------------------------------------------------------------------------------------
	WHERE   SE.DISPONIBLE='+ CHAR(39) + '1' + CHAR(39) + 
			'AND (('+ ISNULL(CHAR(39) +CAST(@FDESDE as nvarchar)+ CHAR(39),'NULL')+ ' IS NULL)OR(SE.F_SNAP BETWEEN '+ ISNULL(CHAR(39)+CAST(@FDESDE as nvarchar)+CHAR(39),'NULL')+' AND DATEADD(DAY,1,'+ ISNULL( CHAR(39) + CAST(@FHASTA as nvarchar)+  CHAR(39),'NULL')+')))
			AND (('+ ISNULL(CHAR(39) +CAST(@CLIENTE_ID as nvarchar)+ CHAR(39),'NULL') +' IS NULL)OR(SE.CLIENTE_ID='+ ISNULL(CHAR(39) +CAST(@CLIENTE_ID as nvarchar)+ CHAR(39),'NULL') +'))
			AND (('+ ISNULL(CHAR(39) +CAST(@NAVE_ID as nvarchar)+ CHAR(39),'NULL') +' IS NULL)OR(N.NAVE_ID='+ ISNULL(CHAR(39) +CAST(@NAVE_ID as nvarchar)+ CHAR(39),'NULL') +'))	
			
	ORDER BY 1,2,3'

	EXEC (@XSQL + @XSQL2)
	
END	

GO


