
/****** Object:  StoredProcedure [dbo].[RPT_STOCK_VOLUMEN_BY_POS]    Script Date: 06/15/2015 15:28:19 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[RPT_STOCK_VOLUMEN_BY_POS]') AND type in (N'P', N'PC'))
DROP PROCEDURE [dbo].[RPT_STOCK_VOLUMEN_BY_POS]
GO

CREATE PROCEDURE [dbo].[RPT_STOCK_VOLUMEN_BY_POS]
	@FDESDE			VARCHAR(8)		OUTPUT,	--ANSI
	@FHASTA			VARCHAR(8)		OUTPUT,	--ANSI
	@NAVE_ID		VARCHAR(15)OUTPUT,
	@POSICION_ID	VARCHAR(45)OUTPUT
AS
BEGIN
	SET NOCOUNT ON
	
	DECLARE @XSQL		AS NVARCHAR(4000)
	DECLARE @XSQL2		AS NVARCHAR(4000)

	SET @XSQL='		
	
	SELECT  DISTINCT  
			 CONVERT(VARCHAR,SE.F_SNAP,103)   AS FECHA
			,N.NAVE_COD                       AS NAVE_COD
			,P.POSICION_COD					  AS POSICION_COD
			,QVOL.VOL_POS					  AS VOL_POS       --VOLUMEN DE LA POSICION
			,ISNULL(PVOL.PVOL,0)              AS Q_VOL_PROD	   --VOLUMEN OCUPADO
			,(ISNULL(QVOL.VOL_POS,0) - ISNULL(PVOL.PVOL,0))       AS Q_VOL_DISP    --VOLUMEN DISPONIBLE
			,GETDATE()						  AS F_IMP
			,HOST_NAME()					  AS TERMINAL
	FROM    SNAP_EXISTENCIAS SE(NOLOCK) INNER JOIN POSICION P (NOLOCK)
			ON(SE.POSICION_ACTUAL=P.POSICION_ID)
			INNER JOIN NAVE N(NOLOCK)
			ON(P.NAVE_ID = N.NAVE_ID)
			INNER JOIN CLIENTE C(NOLOCK)
			ON(SE.CLIENTE_ID=C.CLIENTE_ID)
			LEFT JOIN ( SELECT  Y.CLIENTE_ID,Y.F_SNAP,Y.POSICION_ID,SUM(Y.VOL) AS VOL_POS
						FROM    ( SELECT  DISTINCT P.POSICION_ID,P.NAVE_ID, S.CLIENTE_ID, S.F_SNAP, (ISNULL(P.ALTO,0)*ISNULL(P.ANCHO,0)*ISNULL(P.LARGO,0))/1000000 AS VOL
								  FROM    SNAP_EXISTENCIAS S(NOLOCK) INNER JOIN POSICION P(NOLOCK) ON(S.POSICION_ACTUAL=P.POSICION_ID)
								  WHERE   S.DISPONIBLE=' + CHAR(39) + '1' + CHAR(39) + '
								)Y
						GROUP BY Y.CLIENTE_ID,Y.F_SNAP,Y.POSICION_ID
					   )QVOL
	                    
			ON(SE.CLIENTE_ID=QVOL.CLIENTE_ID AND SE.F_SNAP=QVOL.F_SNAP AND P.POSICION_ID=QVOL.POSICION_ID) 
			-------------------------------------------------------------------------------------------------------------------
			LEFT JOIN (  SELECT  F.CLIENTE_ID,F.F_SNAP,F.NAVE_ID, F.POSICION_ID, SUM(F.PVOL) AS PVOL
						  FROM    ( SELECT  S.CLIENTE_ID, S.F_SNAP, P.NAVE_ID, P.POSICION_ID
											,S.CANTIDAD * ((ISNULL(PR.ALTO,0)*ISNULL(PR.ANCHO,0)*ISNULL(PR.LARGO,0))/1000000) AS PVOL
									FROM    SNAP_EXISTENCIAS S INNER JOIN POSICION P(NOLOCK)  ON(S.POSICION_ACTUAL=P.POSICION_ID)
											INNER JOIN DET_DOCUMENTO_TRANSACCION DDT(NOLOCK)  ON(DDT.DOC_TRANS_ID=S.DOC_TRANS_ID AND DDT.NRO_LINEA_TRANS=S.NRO_LINEA_TRANS)
											INNER JOIN DET_DOCUMENTO DD             (NOLOCK)  ON(DDT.DOCUMENTO_ID=DD.DOCUMENTO_ID AND DDT.NRO_LINEA_DOC=DD.NRO_LINEA)
											INNER JOIN PRODUCTO PR                  (NOLOCK)  ON(DD.CLIENTE_ID=PR.CLIENTE_ID AND DD.PRODUCTO_ID=PR.PRODUCTO_ID)
								  )F
						  GROUP BY
								  F.CLIENTE_ID,F.F_SNAP,F.NAVE_ID, F.POSICION_ID
					  )PVOL
			ON(SE.CLIENTE_ID=PVOL.CLIENTE_ID AND SE.F_SNAP=PVOL.F_SNAP AND N.NAVE_ID=PVOL.NAVE_ID AND SE.POSICION_ACTUAL = PVOL.POSICION_ID)
			-------------------------------------------------------------------------------------------------------------------
	WHERE   SE.DISPONIBLE=' + CHAR(39) + '1' + CHAR(39) + '
			AND (('+ ISNULL(CHAR(39) +CAST(@FDESDE as nvarchar)+CHAR(39) ,'NULL')+ ' IS NULL)OR(dbo.trunc(SE.F_SNAP) BETWEEN '+ ISNULL(CHAR(39) +CAST(@FDESDE as nvarchar)+CHAR(39),'NULL')+ ' AND '+ ISNULL(CHAR(39) +CAST(@FHASTA as nvarchar)+ CHAR(39),'NULL') +'))
			AND (('+ ISNULL(CHAR(39) +CAST(@NAVE_ID as nvarchar)+ CHAR(39),'NULL') +' IS NULL)OR(N.NAVE_ID='+ ISNULL(CHAR(39) +CAST(@NAVE_ID as nvarchar)+ CHAR(39),'NULL') +'))
			AND (('+ ISNULL(CHAR(39) +CAST(@POSICION_ID as nvarchar)+ CHAR(39),'NULL') +' IS NULL)OR(P.POSICION_ID='+ ISNULL(CHAR(39) +CAST(@POSICION_ID as nvarchar)+ CHAR(39),'NULL') +'))'
			
	SET @XSQL2='				
	UNION ALL
	SELECT  DISTINCT  
			 CONVERT(VARCHAR,SE.F_SNAP,103)   AS FECHA
			,N.NAVE_COD                       AS NAVE_COD
			,NULL							  AS POSICION_COD
			,NULL							  AS VOL_POS
			,PVOL.PVOL                        AS Q_VOL_PROD
			,NULL							  AS Q_VOL_DISP
			,GETDATE()						  AS F_IMP
			,HOST_NAME()					  AS TERMINAL			
	FROM    SNAP_EXISTENCIAS SE INNER JOIN NAVE N                         
			ON(N.NAVE_ID = N.NAVE_ID AND NAVE_TIENE_LAYOUT='+ CHAR(39) + '0' + CHAR(39) +' AND PRE_INGRESO='+ CHAR(39) +'0'+ CHAR(39) +' AND PRE_EGRESO='+ CHAR(39) +'0'+ CHAR(39) +')
			INNER JOIN CLIENTE C                      
			ON(SE.CLIENTE_ID=C.CLIENTE_ID)
			INNER JOIN (  SELECT  F.CLIENTE_ID,F.F_SNAP,F.NAVE_ID,SUM(F.PVOL) AS PVOL
						  FROM    ( SELECT  S.CLIENTE_ID, S.F_SNAP, N.NAVE_ID
											,S.CANTIDAD * ((ISNULL(PR.ALTO,0)*ISNULL(PR.ANCHO,0)*ISNULL(PR.LARGO,0))/1000000) AS PVOL
									FROM    SNAP_EXISTENCIAS S(NOLOCK) INNER JOIN NAVE N(NOLOCK)ON(S.NAVE_ACTUAL=N.NAVE_ID)
											INNER JOIN DET_DOCUMENTO_TRANSACCION DDT(NOLOCK)	ON(DDT.DOC_TRANS_ID=S.DOC_TRANS_ID AND DDT.NRO_LINEA_TRANS=S.NRO_LINEA_TRANS)
											INNER JOIN DET_DOCUMENTO DD(NOLOCK)					ON(DDT.DOCUMENTO_ID=DD.DOCUMENTO_ID AND DDT.NRO_LINEA_DOC=DD.NRO_LINEA)
											INNER JOIN PRODUCTO PR(NOLOCK)						ON(DD.CLIENTE_ID=PR.CLIENTE_ID AND DD.PRODUCTO_ID=PR.PRODUCTO_ID)
								  )F
						  GROUP BY
								  F.CLIENTE_ID,F.F_SNAP,F.NAVE_ID
					  )PVOL
			ON(SE.CLIENTE_ID=PVOL.CLIENTE_ID AND SE.F_SNAP=PVOL.F_SNAP AND N.NAVE_ID=PVOL.NAVE_ID)
			-------------------------------------------------------------------------------------------------------------------
	WHERE   SE.DISPONIBLE='+ CHAR(39) +'1'+ CHAR(39) + 'AND
			(('+ ISNULL(CHAR(39) +CAST(@FDESDE as nvarchar)+CHAR(39) ,'NULL')+ ' IS NULL)OR(dbo.trunc(SE.F_SNAP) BETWEEN '+ ISNULL(CHAR(39) +CAST(@FDESDE as nvarchar)+CHAR(39),'NULL')+ ' AND '+ ISNULL(CHAR(39) +CAST(@FHASTA as nvarchar)+ CHAR(39),'NULL') +'))
			AND (('+ ISNULL(CHAR(39) +CAST(@NAVE_ID as nvarchar)+ CHAR(39),'NULL') +' IS NULL)OR(N.NAVE_ID='+ ISNULL(CHAR(39) +CAST(@NAVE_ID as nvarchar)+ CHAR(39),'NULL') +'))
			AND (('+ ISNULL(CHAR(39) +CAST(@POSICION_ID as nvarchar)+ CHAR(39),'NULL') +' IS NULL)OR(N.NAVE_ID=-1))'
			
			EXEC (@XSQL + @XSQL2)
END;			

GO
