
/****** Object:  Table [dbo].[MOB_TOMA_STOCK_INICIAL]    Script Date: 10/30/2014 10:27:26 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[MOB_TOMA_STOCK_INICIAL]') AND type in (N'U'))
DROP TABLE [dbo].[MOB_TOMA_STOCK_INICIAL]
GO

CREATE TABLE DBO.MOB_TOMA_STOCK_INICIAL(
	--IDENTITY PARA IDENTIFICAR LOS REGISTROS.
	STOCK_ID	NUMERIC(30,0) NOT NULL IDENTITY(1,1),
	--REFERIDO A LAS POSICIONES.
	NAVE		VARCHAR(45),
	CALLE		VARCHAR(45),
	COLUMNA		VARCHAR(45),
	NIVEL		VARCHAR(45),
	UBICACION	VARCHAR(45),
	--REFERIDO AL PRODUCTO.
	CLIENTE_ID	VARCHAR(15),
	PRODUCTO_ID	VARCHAR(30),
	CANTIDAD	NUMERIC(20,5),
	NRO_LOTE	VARCHAR(50),
	NRO_PARTIDA	VARCHAR(50),
	--REFERIDO A LA AUDITORIA.
	VALIDA_SKU	CHAR(1),
	USUARIO_ID	VARCHAR(50),
	TERMINAL	VARCHAR(100),
	F_INSERT	DATETIME,
	F_UPDATE	DATETIME
);

GO

ALTER TABLE DBO.MOB_TOMA_STOCK_INICIAL
ADD CONSTRAINT PK_STOCK_INI PRIMARY KEY(STOCK_ID);
