/****** Object:  StoredProcedure [dbo].[TOMA_INICIAL_STOCK_BORRAR_REGISTRO]    Script Date: 10/30/2014 10:33:17 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[TOMA_INICIAL_STOCK_BORRAR_REGISTRO]') AND type in (N'P', N'PC'))
DROP PROCEDURE [dbo].[TOMA_INICIAL_STOCK_BORRAR_REGISTRO]
GO

CREATE PROCEDURE [dbo].[TOMA_INICIAL_STOCK_BORRAR_REGISTRO]
	@ID	NUMERIC(30,0)
AS
BEGIN
	
	DELETE FROM dbo.MOB_TOMA_STOCK_INICIAL WHERE STOCK_ID=@ID;

END
GO
