/****** Object:  StoredProcedure [dbo].[MOB_PICKING_CALCULADOR_POR_CODIGO]    Script Date: 07/28/2014 13:13:06 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[MOB_PICKING_CALCULADOR_POR_CODIGO]') AND type in (N'P', N'PC'))
DROP PROCEDURE [dbo].[MOB_PICKING_CALCULADOR_POR_CODIGO]
GO

CREATE PROCEDURE [dbo].[MOB_PICKING_CALCULADOR_POR_CODIGO]
@CLIENTE_ID		AS VARCHAR(15),
@PRODUCTO_ID	AS VARCHAR(30),
@CANTIDAD		AS FLOAT
AS
BEGIN
	--DECLARACION DE VARIABLES.
	DECLARE @CUR		CURSOR
	DECLARE @TIPO_COD	VARCHAR(20)
	DECLARE	@CODIGO		VARCHAR(50)
	DECLARE @QTY_COD	NUMERIC(20,5)
	DECLARE	@CALCULO	AS FLOAT
	DECLARE @PARTE_ENT	AS FLOAT
	DECLARE @PARTE_DEC	AS FLOAT

	CREATE TABLE #TPROD(
		CLIENTE_ID	 VARCHAR(15),
		PRODUCTO_ID	 VARCHAR(15),
		TIPO_CODIGO	 VARCHAR(20),
		CODIGO		 VARCHAR(50),
		QTY_PARAM	 NUMERIC(20,5),
		QTY_COD		 NUMERIC(20,5),
		QTY_UN		 NUMERIC(20,0)
	)
	
	
	IF CURSOR_STATUS('global','@CUR')>=-1
	BEGIN
		DEALLOCATE @CUR;
	END	
	
	SET @CUR =CURSOR FOR
	SELECT	TIPO_CODIGO, CODIGO, CANTIDAD
	FROM	RL_PRODUCTO_CODIGOS
	WHERE	CLIENTE_ID=@CLIENTE_ID
			AND PRODUCTO_ID=@PRODUCTO_ID;
	
	OPEN @CUR
	FETCH NEXT FROM @CUR INTO @TIPO_COD,@CODIGO,@QTY_COD
	WHILE @@FETCH_STATUS=0
	BEGIN
		
		SET @CALCULO=@CANTIDAD/@QTY_COD;
		
		SET @PARTE_ENT=FLOOR(@CALCULO)
		
		SET @PARTE_DEC=@CALCULO-Round(@CALCULO,0,1);
		
		IF @PARTE_ENT=0 BEGIN
			--ESTE CODIGO NO ME SIRVE PORQUE LA PARTE ENTERA ME DA MAL.
			INSERT INTO #TPROD VALUES(@CLIENTE_ID,@PRODUCTO_ID,@TIPO_COD,@CODIGO,@QTY_COD,0,@CANTIDAD)
		END
		ELSE
		BEGIN
			IF @PARTE_DEC=0 BEGIN
				INSERT INTO #TPROD VALUES(@CLIENTE_ID,@PRODUCTO_ID,@TIPO_COD,@CODIGO,@QTY_COD,@PARTE_ENT,0)
			END
			ELSE
			BEGIN
				INSERT INTO #TPROD VALUES(@CLIENTE_ID,@PRODUCTO_ID,@TIPO_COD,@CODIGO,@QTY_COD,@PARTE_ENT,@PARTE_DEC*@QTY_COD)
			END
		END
		FETCH NEXT FROM @CUR INTO @TIPO_COD,@CODIGO,@QTY_COD
	END
	CLOSE @CUR
	DEALLOCATE @CUR
	
	SELECT	TIPO_CODIGO	AS [EAN13/DUN14],
			CODIGO		AS [CODIGO],
			QTY_COD		AS [CANT.POR CODIGO],
			QTY_UN		AS [CANT.UN.PRIMARIA]
	FROM	#TPROD;
	
END--FIN PROCEDURE.