
/****** Object:  StoredProcedure [dbo].[MOB_INGRESO_OC_SEL]    Script Date: 10/23/2014 11:46:23 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[MOB_INGRESO_OC_SEL]') AND type in (N'P', N'PC'))
DROP PROCEDURE [dbo].[MOB_INGRESO_OC_SEL]
GO

CREATE PROCEDURE [dbo].[MOB_INGRESO_OC_SEL]
	@CLIENTE_ID		varchar(15),
	@ORDEN_COMPRA	varchar(100)
AS
BEGIN

	DECLARE @USUARIO		VARCHAR(50)

	SELECT @USUARIO=USUARIO_ID FROM #TEMP_USUARIO_LOGGIN
	
	SELECT	INGRESO_OC.PRODUCTO_ID					AS PRODUCTO, 
			INGRESO_OC.CANTIDAD						AS CANTIDAD, 
			ISNULL(INGRESO_OC.CANT_CONTENEDORAS,0)	AS CANT_CONTENEDORAS, 
			PRODUCTO.DESCRIPCION					AS DESCRIPCION, 
			INGRESO_OC.NRO_LOTE						AS NRO_LOTE, 
			INGRESO_OC.NRO_PARTIDA					AS NRO_PARTIDA,
			INGRESO_OC.ING_ID						AS ING_ID
	FROM    INGRESO_OC INNER JOIN PRODUCTO 
			ON(INGRESO_OC.PRODUCTO_ID = PRODUCTO.PRODUCTO_ID AND INGRESO_OC.CLIENTE_ID = PRODUCTO.CLIENTE_ID)
	WHERE   INGRESO_OC.CLIENTE_ID = @CLIENTE_ID 
			AND INGRESO_OC.ORDEN_COMPRA = @ORDEN_COMPRA 
			AND PROCESADO ='0'
			AND USUARIO = @USUARIO
	ORDER BY 
			INGRESO_OC.PRODUCTO_ID
END;

GO


