/****** Object:  StoredProcedure [dbo].[GTW_EXTRACT#GEN_INT_COT]    Script Date: 07/04/2014 13:05:54 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[GTW_EXTRACT#GEN_INT_COT]') AND type in (N'P', N'PC'))
DROP PROCEDURE [dbo].[GTW_EXTRACT#GEN_INT_COT]
GO

CREATE procedure [dbo].[GTW_EXTRACT#GEN_INT_COT]
  @PCLIENTE varchar(20) OUTPUT,
  @PDESDE   varchar(10) OUTPUT,
  @PHASTA   varchar(10) OUTPUT
as
BEGIN
	SELECT  D.CLIENTE_ID + ';'+ isnull(D.CPTE_PREFIJO,'') +';'+ isnull(D.CPTE_NUMERO,'') +';'+DD.PRODUCTO_ID+';'
			+ REPLACE(DD.DESCRIPCION,'','') + ';' + cast (SUM(DD.CANTIDAD) as varchar) + ';' 
			+ CASE WHEN S.CATEGORIA_IMPOSITIVA_ID = 'CF' THEN '1' ELSE 
			(CASE WHEN S.TIPO_DOCUMENTO_ID = 'CUIT' THEN REPLACE(S.NRO_DOCUMENTO,'-','') ELSE '1' END) END + ';'
	FROM    DOCUMENTO D INNER JOIN DET_DOCUMENTO DD ON(D.DOCUMENTO_ID=DD.DOCUMENTO_ID)
			INNER JOIN SUCURSAL S ON (D.CLIENTE_ID=S.CLIENTE_ID AND D.SUCURSAL_DESTINO=S.SUCURSAL_ID)
	WHERE   D.STATUS='D40' AND d.CLIENTE_ID=@PCLIENTE AND D.TIPO_OPERACION_ID='EGR'
			AND FECHA_ALTA_GTW >= CONVERT(datetime,@PDESDE , 103)
			AND FECHA_ALTA_GTW < CONVERT (datetime,@PHASTA , 103)+1
	GROUP BY
			D.CLIENTE_ID, D.CPTE_PREFIJO, D.CPTE_NUMERO,DD.PRODUCTO_ID,DD.DESCRIPCION,S.CATEGORIA_IMPOSITIVA_ID,
			S.TIPO_COMPROBANTE_ID,S.NRO_DOCUMENTO,S.TIPO_DOCUMENTO_ID
	HAVING	SUM(DD.CANTIDAD)>0
	ORDER BY  D.CLIENTE_ID, D.CPTE_PREFIJO, D.CPTE_NUMERO;
end
GO


