IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[MOB_CAMBIO_PALLET]') AND type in (N'P', N'PC'))
DROP PROCEDURE [dbo].[MOB_CAMBIO_PALLET]
GO


CREATE PROCEDURE [dbo].[MOB_CAMBIO_PALLET]
	@CLIENTE_ID		VARCHAR(15),
	@VIAJE_ID		VARCHAR(100),
	@PRODUCTO_ID	VARCHAR(30),
	@CANTIDAD		NUMERIC(20,5),
	@PALLET			VARCHAR(100),
	@USR			VARCHAR(20),
	@PALLET_DESTINO	VARCHAR(100),
	@QTY_PALLET		NUMERIC(20,5)	OUTPUT,
	@UBICACION		VARCHAR(45)		OUTPUT
AS
BEGIN

	DECLARE @FECHA_INICIO		DATETIME
	DECLARE @PALLET_PICKING		VARCHAR(100)
	DECLARE @PICKING_ID			NUMERIC(20,0)
	DECLARE @CURSOR_PIK			CURSOR
	DECLARE @RUTA				VARCHAR(100)
	DECLARE @QTY_REM			NUMERIC(20,5)
	DECLARE @CANT_PIK			NUMERIC(20,5)

	DECLARE @CUR_RL				CURSOR
	DECLARE @RL_ID				NUMERIC(20,0)
	DECLARE @CANT_RL			NUMERIC(20,5)

	SET @QTY_REM=@CANTIDAD

	SELECT	@FECHA_INICIO	=PICKING.FECHA_INICIO,
			@PALLET_PICKING	=PICKING.PALLET_PICKING,
			@RUTA			=PICKING.RUTA
	FROM	PICKING 
	WHERE	PICKING.VIAJE_ID	=@VIAJE_ID
			AND PICKING.PROP1	=@PALLET 
			AND PICKING.USUARIO	=@USR 

	SELECT	* INTO #T
	FROM	PICKING
	WHERE	VIAJE_ID	=@VIAJE_ID
			AND PROP1	=@PALLET
			AND USUARIO =@USR
			AND FECHA_INICIO IS NOT NULL

	SET @CURSOR_PIK=CURSOR FOR
		SELECT	PICKING_ID, CANTIDAD
		FROM	PICKING
		WHERE	VIAJE_ID	=@VIAJE_ID
				AND PROP1	=@PALLET
				AND USUARIO =@USR

	OPEN @CURSOR_PIK

	FETCH NEXT FROM @CURSOR_PIK INTO @PICKING_ID, @CANT_PIK
	WHILE @@FETCH_STATUS=0 BEGIN

		SET @CUR_RL =CURSOR FOR 
			SELECT	RL.RL_ID, RL.CANTIDAD
			FROM	DET_DOCUMENTO DD INNER JOIN DET_DOCUMENTO_TRANSACCION DDT		ON(DD.DOCUMENTO_ID=DDT.DOCUMENTO_ID AND DD.NRO_LINEA=DDT.NRO_LINEA_DOC)
					INNER JOIN RL_DET_DOC_TRANS_POSICION RL							ON(DDT.DOC_TRANS_ID=RL.DOC_TRANS_ID AND DDT.NRO_LINEA_TRANS=RL.NRO_LINEA_TRANS)
					INNER JOIN CATEGORIA_LOGICA CL									ON(RL.CLIENTE_ID=CL.CLIENTE_ID AND RL.CAT_LOG_ID=CL.CAT_LOG_ID)
			WHERE	DD.CLIENTE_ID=@CLIENTE_ID
					AND DD.PROP1=@PALLET_DESTINO
					AND RL.DISPONIBLE='1'
					AND CL.DISP_EGRESO='1'
					AND CL.PICKING='1'
			ORDER BY
					RL.CANTIDAD DESC
		OPEN @CUR_RL

		FETCH NEXT FROM @CUR_RL INTO @RL_ID, @CANT_RL
		WHILE @@FETCH_STATUS=0 BEGIN

			EXEC [dbo].[MOB_PICKING_GENERAR_CAMBIO_PALLET] @RL_ID, @PICKING_ID
			
			SET @CANT_PIK=@CANT_PIK-@CANT_RL

			IF @CANT_PIK<=0 BEGIN
				BREAK
			END
			FETCH NEXT FROM @CUR_RL INTO @RL_ID, @CANT_RL
		END
		CLOSE @CUR_RL
		DEALLOCATE @CUR_RL

		FETCH NEXT FROM @CURSOR_PIK INTO @PICKING_ID, @CANT_PIK

	END --FIN FETCH CURSOR @CUR_PIK
	
	CLOSE @CURSOR_PIK
	DEALLOCATE @CURSOR_PIK
	
	UPDATE	DET_DOCUMENTO 
	SET		NRO_SERIE=X.NRO_SERIE,				NRO_SERIE_PADRE=X.NRO_SERIE_PADRE,			EST_MERC_ID=X.EST_MERC_ID,
			NRO_BULTO=X.NRO_BULTO,				NRO_LOTE=X.NRO_LOTE,						FECHA_VENCIMIENTO=X.FECHA_VENCIMIENTO,
			NRO_DESPACHO=X.NRO_DESPACHO,		NRO_PARTIDA=X.NRO_PARTIDA,					UNIDAD_ID=X.UNIDAD_ID,
			PESO=X.PESO,						UNIDAD_PESO=X.UNIDAD_PESO,					VOLUMEN=X.VOLUMEN,
			UNIDAD_VOLUMEN=X.UNIDAD_VOLUMEN,	BUSC_INDIVIDUAL=X.BUSC_INDIVIDUAL,			TIE_IN=X.TIE_IN,
			NRO_TIE_IN_PADRE=X.NRO_TIE_IN_PADRE,NRO_TIE_IN=X.NRO_TIE_IN,					MONEDA_ID=X.MONEDA_ID,
			COSTO=X.COSTO,						PROP1=X.PROP1,								PROP2=X.PROP2,
			PROP3=X.PROP3,						LARGO=X.LARGO,								ALTO=X.ALTO,
			ANCHO=X.ANCHO,						VOLUMEN_UNITARIO=X.VOLUMEN_UNITARIO,		PESO_UNITARIO=X.PESO_UNITARIO
	FROM	DET_DOCUMENTO DD INNER JOIN
			(	SELECT	DD.DOCUMENTO_ID,		DD.NRO_LINEA,			DD2.NRO_SERIE,
						DD2.NRO_SERIE_PADRE,	DD2.EST_MERC_ID,		DD2.NRO_BULTO,
						DD2.DESCRIPCION,		DD2.NRO_LOTE,			DD2.FECHA_VENCIMIENTO,
						DD2.NRO_DESPACHO,		DD2.NRO_PARTIDA,		DD2.UNIDAD_ID,
						DD2.PESO,				DD2.UNIDAD_PESO,		DD2.VOLUMEN,
						DD2.UNIDAD_VOLUMEN,		DD2.BUSC_INDIVIDUAL,	DD2.TIE_IN,
						DD2.NRO_TIE_IN_PADRE,	DD2.NRO_TIE_IN,			DD2.MONEDA_ID,
						DD2.COSTO,				DD2.PROP1,				DD2.PROP2,
						DD2.PROP3,				DD2.LARGO,				DD2.ALTO,
						DD2.ANCHO,				DD2.VOLUMEN_UNITARIO,	DD2.PESO_UNITARIO
				FROM	DET_DOCUMENTO DD INNER JOIN DET_DOCUMENTO_TRANSACCION DDT	ON(DD.DOCUMENTO_ID=DDT.DOCUMENTO_ID AND DD.NRO_LINEA=DDT.NRO_LINEA_DOC)
						INNER JOIN RL_DET_DOC_TRANS_POSICION RL						ON(DDT.DOC_TRANS_ID=RL.DOC_TRANS_ID_EGR AND DDT.NRO_LINEA_TRANS=RL.NRO_LINEA_TRANS_EGR)
						INNER JOIN DET_DOCUMENTO_TRANSACCION DDT2					ON(RL.DOC_TRANS_ID=DDT2.DOC_TRANS_ID AND RL.NRO_LINEA_TRANS=DDT2.NRO_LINEA_TRANS)
						INNER JOIN DET_DOCUMENTO DD2								ON(DD2.DOCUMENTO_ID=DDT2.DOCUMENTO_ID AND DD2.NRO_LINEA=DDT2.NRO_LINEA_DOC)
				WHERE	DD.DOCUMENTO_ID=(SELECT DISTINCT DOCUMENTO_ID FROM #T))X
			ON(DD.DOCUMENTO_ID=X.DOCUMENTO_ID AND DD.NRO_LINEA=X.NRO_LINEA)
	WHERE	DD.DOCUMENTO_ID=(SELECT DISTINCT DOCUMENTO_ID FROM #T)


	UPDATE	PICKING 
	SET		FECHA_INICIO=@FECHA_INICIO, USUARIO=@USR, PALLET_PICKING=@PALLET_PICKING, RUTA=@RUTA, PROP1=DD.PROP1
	FROM	PICKING P INNER JOIN DET_DOCUMENTO DD	ON(P.DOCUMENTO_ID=DD.DOCUMENTO_ID AND P.NRO_LINEA=DD.NRO_LINEA)
	WHERE	P.CLIENTE_ID=@CLIENTE_ID
			AND P.VIAJE_ID=@VIAJE_ID
			AND DD.PROP1=@PALLET_DESTINO 

	UPDATE	PICKING 
	SET		FECHA_INICIO=NULL, USUARIO=NULL, PALLET_PICKING=NULL
	FROM	PICKING P INNER JOIN DET_DOCUMENTO DD	ON(P.DOCUMENTO_ID=DD.DOCUMENTO_ID AND P.NRO_LINEA=DD.NRO_LINEA)
	WHERE	P.CLIENTE_ID=@CLIENTE_ID
			AND P.VIAJE_ID=@VIAJE_ID
			AND P.PROP1=@PALLET  

	SELECT	@QTY_PALLET=SUM(CANTIDAD), @UBICACION=POSICION_COD
	FROM	PICKING P
	WHERE	P.CLIENTE_ID=@CLIENTE_ID
			AND P.VIAJE_ID=@VIAJE_ID
			AND P.PROP1=@PALLET_DESTINO  	
	GROUP BY
			POSICION_COD
				
	DROP TABLE #T 

END--FIN DEL PROCEDIMIENTO ALMACENADO.


