ALTER TABLE PRODUCTO ADD ET_TAREA_CONF VARCHAR(1)

INSERT INTO sys_tabColumns VALUES('PRODUCTO','ET_TAREA_CONF',62,'VARCHAR2',	'N',	1,	NULL,	NULL,	1,	NULL)

INSERT INTO SYS_DET_TABLA VALUES('PRODUCTO','ET_TAREA_CONF','Etiqueta por Tarea Conf.',	'S',	50,	1)


DELETE FROM sys_tabColumns WHERE TABLE_NAME='PRODUCTO' AND COLUMN_NAME='MARCA'

DELETE FROM SYS_DET_TABLA WHERE TABLA_ID='PRODUCTO' AND CAMPO='MARCA'

