/****** Object:  Trigger [TRG_PICKING_PP]    Script Date: 06/12/2014 12:45:14 ******/
IF  EXISTS (SELECT * FROM sys.triggers WHERE object_id = OBJECT_ID(N'[dbo].[TRG_PICKING_PP]'))
DROP TRIGGER [dbo].[TRG_PICKING_PP]
GO


CREATE TRIGGER [dbo].[TRG_PICKING_PP]
ON [dbo].[PICKING]
FOR UPDATE
AS
BEGIN
	SET NOCOUNT ON

	INSERT INTO IMPRESION_APF
	SELECT	DISTINCT INSERTED.PICKING_ID, '3', '0',GETDATE(),INSERTED.USUARIO
	FROM	INSERTED INNER JOIN PRODUCTO P
			ON(INSERTED.CLIENTE_ID=P.CLIENTE_ID AND INSERTED.PRODUCTO_ID=P.PRODUCTO_ID )
	WHERE	INSERTED.FECHA_FIN IS NOT NULL
			AND ISNULL(P.ET_TAREA_CONF,'0')='1'	
			AND NOT EXISTS (SELECT	1
							FROM	IMPRESION_APF IA
							WHERE	IA.PALLET=INSERTED.PICKING_ID
									AND IA.TIPO_ETI='3')
END


GO


