/****** Object:  StoredProcedure [dbo].[PrintEtiPalletPickingGroup]    Script Date: 06/12/2014 15:42:13 ******/
IF EXISTS (SELECT *
           FROM   sys.objects
           WHERE  object_id = OBJECT_ID(N'[dbo].[PrintEtiTareaPickingGroup]')
                  AND type IN (N'P', N'PC'))
    DROP PROCEDURE [dbo].[PrintEtiTareaPickingGroup];


GO
CREATE PROCEDURE [dbo].[PrintEtiTareaPickingGroup]
@CLIENTE_ID VARCHAR (100) OUTPUT, 
@EtiquetaId VARCHAR (20) OUTPUT
--@UsuarioImp VARCHAR (20) OUTPUT -- LRojas TrackerID 3806 05/03/2012: Impresora por Usuario
AS
BEGIN
    SELECT @EtiquetaId = ISNULL(etiqueta_id, 0)
    FROM   etiqueta_producto
    WHERE  cliente_id = @CLIENTE_ID
           AND Producto_id = 'ETI_TAREA'
           AND tipo_operacion_id = 'EGR';
           
    IF @EtiquetaId IS NULL
        BEGIN
            SET @EtiquetaId = 0;
        END
    -----------------------------------------------------------------------
    --Obtengo el grupo de datos.   
    -----------------------------------------------------------------------
	SELECT	P.PALLET_PICKING	AS [PICKING.PALLET_PICKING],
			P.POSICION_COD		AS [PICKING.POSICION_COD],
			P.PROP1				AS [PICKING.PROP1] ,
			P.RUTA 				AS [PICKING.RUTA],
			P.VIAJE_ID			AS [PICKING.VIAJE_ID],
			SUM(P.CANTIDAD)		AS [PICKING.CANTIDAD],
			P.NRO_LOTE			AS [PICKING.NRO_LOTE],
			P.NRO_PARTIDA		AS [PICKING.NRO_PARTIDA],
			DD.PRODUCTO_ID		AS [DET_DOCUMENTO_EGR.PRODUCTO_ID],
			SUM(DD.CANTIDAD)	AS [DET_DOCUMENTO_EGR.CANTIDAD],
			--DD.EST_MERC_ID		AS [DET_DOCUMENTO_EGR.EST_MERC_ID],
			DD.CAT_LOG_ID		AS [DET_DOCUMENTO_EGR.CAT_LOG_ID],
			DD.DESCRIPCION		AS [DET_DOCUMENTO_EGR.DESCRIPCION],
			DD.NRO_LOTE			AS [DET_DOCUMENTO_EGR.NRO_LOTE],
			DD.FECHA_VENCIMIENTO AS[DET_DOCUMENTO_EGR.FECHA_VENCIMIENTO],
			DD.NRO_DESPACHO		AS [DET_DOCUMENTO_EGR.NRO_DESPACHO],
			DD.NRO_PARTIDA		AS [DET_DOCUMENTO_EGR.NRO_PARTIDA],
			DD.UNIDAD_ID		AS [DET_DOCUMENTO_EGR.UNIDAD_ID],
			DD.PROP1			AS [DET_DOCUMENTO_EGR.PROP1],
			DD.PROP2			AS [DET_DOCUMENTO_EGR.PROP2],
			DD.PROP3			AS [DET_DOCUMENTO_EGR.PROP3],
			S.CALLE				AS [SUCURSAL.CALLE],
			S.NOMBRE			AS [SUCURSAL.NOMBRE],
			S.SUCURSAL_ID		AS [SUCURSAL.SUCURSAL_ID],
			SU.IMPRESORA_DEM_IMP,
			P.FECHA_INICIO
	FROM	PICKING P INNER JOIN DET_DOCUMENTO DD
			ON(P.DOCUMENTO_ID=DD.DOCUMENTO_ID AND P.NRO_LINEA=DD.NRO_LINEA)
			INNER JOIN DOCUMENTO D
			ON(DD.DOCUMENTO_ID=D.DOCUMENTO_ID)
			INNER JOIN SUCURSAL S
			ON(D.CLIENTE_ID=S.CLIENTE_ID AND D.SUCURSAL_DESTINO=S.SUCURSAL_ID)
			LEFT JOIN SYS_USUARIO SU
			ON(P.USUARIO=SU.USUARIO_ID)
	WHERE	PICKING_ID IN(SELECT PALLET FROM IMPRESION_APF WHERE TIPO_ETI='3' AND IMPRESO='0')
			AND D.CLIENTE_ID=@CLIENTE_ID
	GROUP BY
			P.PALLET_PICKING,
			P.POSICION_COD,
			P.PROP1,
			P.RUTA,
			P.VIAJE_ID,
			P.NRO_LOTE,
			P.NRO_PARTIDA,
			DD.PRODUCTO_ID,
			--DD.EST_MERC_ID,
			DD.CAT_LOG_ID,
			--DD.NRO_BULTO,
			DD.DESCRIPCION,
			DD.NRO_LOTE,
			DD.FECHA_VENCIMIENTO,
			DD.NRO_DESPACHO,
			DD.NRO_PARTIDA,
			DD.UNIDAD_ID,
			DD.PROP1,
			DD.PROP2,
			DD.PROP3,
			S.CALLE,
			S.NOMBRE,
			S.SUCURSAL_ID,
			SU.IMPRESORA_DEM_IMP,
			P.FECHA_INICIO
	ORDER BY
			P.FECHA_INICIO	
			
-------------------------------------------------------------------  
END --Fin procedure.