
/****** Object:  Table [dbo].[SYS_TRADUCTOR]    Script Date: 04/28/2014 16:07:33 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[SYS_TRADUCTOR]') AND type in (N'U'))
DROP TABLE [dbo].[SYS_TRADUCTOR]
GO

CREATE TABLE [dbo].[SYS_TRADUCTOR](
	[OBJETO] [varchar](50) NOT NULL,
	[COMPONENTE] [varchar](100) NOT NULL,
	[TIPO_COMPONENTE] [varchar](50) NOT NULL,
	[SUBCOMPONENTE] [varchar](50) NULL,
	[DESCRIPCION_COMPONENTE] [varchar](50) NOT NULL,
	[IDIOMA_ESPANOL] [varchar](100) NOT NULL,
	[IDIOMA INGLES] [varchar](100) NULL,
	[IDIOMA_1] [varchar](50) NOT NULL,
	[IDIOMA_2] [varchar](50) NOT NULL,
	[USUARIO_ID] [varchar](20) NULL,
CONSTRAINT [PK_OBJETO] PRIMARY KEY CLUSTERED 
(
	[OBJETO] ASC,
	[COMPONENTE] ASC
	
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO
