ALTER TABLE CLIENTE_PARAMETROS
ADD FLG_USA_CARROS CHAR(1) NULL;
GO
INSERT INTO sys_tabColumns VALUES('CLIENTE_PARAMETROS',	'FLG_CONTROL_EXP',17,'CHAR','Y','1',NULL,NULL,'1',NULL);
GO
INSERT INTO sys_tabColumns VALUES('CLIENTE_PARAMETROS',	'FLG_USA_CARROS',18,'CHAR','Y','1',NULL,NULL,'1',NULL);
GO
INSERT INTO SYS_DET_TABLA VALUES('CLIENTE_PARAMETROS','FLG_USA_CARROS',	'Picking - Pickeo con Carros','S','1','0');
GO
INSERT INTO SYS_DET_TABLA VALUES('CLIENTE_PARAMETROS','FLG_CONTROL_EXP','Picking - Control Expedicion','S','1','0');
GO
