/****** Object:  StoredProcedure [dbo].[PICKINGUSACARRO]    Script Date: 09/12/2013 15:59:42 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PICKINGUSACARRO]') AND type in (N'P', N'PC'))
DROP PROCEDURE [dbo].[PICKINGUSACARRO]
GO

CREATE PROCEDURE [dbo].[PICKINGUSACARRO]
	@CLIENTE AS VARCHAR(15)OUTPUT,  
	@VALUE AS NUMERIC(1) OUTPUT  
AS  
	SET @VALUE = (SELECT FLG_USA_CARROS FROM cliente_parametros WHERE CLIENTE_ID = @CLIENTE)
GO