SET IDENTITY_INSERT PARAMETROS_AUDITORIA ON
insert into PARAMETROS_AUDITORIA (TIPO_AUDITORIA_ID,DESCRIPCION,AUDITABLE) values (20,'Cambio Nro. Serie' ,1)
insert into PARAMETROS_AUDITORIA (TIPO_AUDITORIA_ID,DESCRIPCION,AUDITABLE) values (21,'Cambio Nro. Despacho' ,1)
insert into PARAMETROS_AUDITORIA (TIPO_AUDITORIA_ID,DESCRIPCION,AUDITABLE) values (22,'Cambio Nro. Partida' ,1)
SET IDENTITY_INSERT PARAMETROS_AUDITORIA OFF