ALTER TABLE PICKING
ADD FECHA_DESCONSOLIDACION DATETIME
GO
ALTER TABLE PICKING
ADD USUARIO_DESCONSOLIDACION VARCHAR(20)
GO
ALTER TABLE PICKING
ADD TERMINAL_DESCONSOLIDACION VARCHAR(20)
GO
ALTER TABLE PICKING_HISTORICO
ADD FECHA_DESCONSOLIDACION DATETIME
GO
ALTER TABLE PICKING_HISTORICO
ADD USUARIO_DESCONSOLIDACION VARCHAR(20)
GO
ALTER TABLE PICKING_HISTORICO
ADD TERMINAL_DESCONSOLIDACION VARCHAR(20)