/****** Object:  StoredProcedure [dbo].[CONSOLIDACION_RPT]    Script Date: 09/18/2013 11:45:09 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[CONSOLIDACION_RPT]') AND type in (N'P', N'PC'))
DROP PROCEDURE [dbo].[CONSOLIDACION_RPT]
GO

CREATE PROCEDURE [dbo].[CONSOLIDACION_RPT]    
@VIAJE VARCHAR(100) output    
AS    
BEGIN    
	SELECT  CONVERT(VARCHAR, GETDATE(),103) AS  [FECHA_IMPRESION]    
			,D.NRO_REMITO AS       [NRO_PEDIDO]    
			,S.SUCURSAL_ID + ' - ' + S.NOMBRE AS [AGENTE]    
			,CASE X.INFO_ADICIONAL_3 WHEN 1 THEN 'Si'     
			WHEN 0 THEN 'No'     
			WHEN NULL THEN 'No' END    [FACTURABLE]    
			,P.NRO_UCDESCONSOLIDACION    [NRO_CONTENEDORA]    
			,P.PRODUCTO_ID       [COD_PRODUCTO]    
			,P.DESCRIPCION       [DESCRIPCION]    
			,SUM(P.CANT_CONFIRMADA)     [CANTIDAD]    
			,P.VIAJE_ID        [COD_VIAJE]    
			,HOST_NAME()       [TERMINAL]    
			,TC.TIPO_COMPROBANTE_ID + ' - ' + TC.DESCRIPCION AS TIPO_DOCUMENTO
			,sd.CLASE_PEDIDO as [CLASE_PEDIDO]
			, sd.observaciones
			, 'Loc.: ' + S.LOCALIDAD + ', Prov.: ' + PRV.DESCRIPCION as LOCALIDAD
			,T.NOMBRE AS TRANSPORTE
	FROM	PICKING P 
			INNER JOIN DOCUMENTO D ON(P.DOCUMENTO_ID=D.DOCUMENTO_ID)    
			INNER JOIN SUCURSAL S ON(D.CLIENTE_ID=S.CLIENTE_ID AND D.SUCURSAL_DESTINO=S.SUCURSAL_ID)    
			INNER JOIN     
			(	SELECT	INFO_ADICIONAL_3,CLIENTE_ID, DOC_EXT 
				FROM	SYS_INT_DOCUMENTO)X ON(D.CLIENTE_ID=X.CLIENTE_ID AND D.NRO_REMITO=X.DOC_EXT)    
			INNER JOIN SYS_INT_DOCUMENTO SD ON SD.DOC_EXT = D.NRO_REMITO AND SD.CLIENTE_ID = D.CLIENTE_ID
			LEFT JOIN TIPO_COMPROBANTE TC ON TC.TIPO_COMPROBANTE_ID = SD.TIPO_DOCUMENTO_ID 
			LEFT JOIN PROVINCIA PRV ON (PRV.PAIS_ID = ISNULL(S.PAIS_ID,'AR') AND PRV.PROVINCIA_ID = S.PROVINCIA_ID)
			LEFT JOIN TRANSPORTE T ON (T.TRANSPORTE_ID = SD.TRANSPORTE_ID)
	WHERE	VIAJE_ID=@viaje--'PED1'    
			AND P.NRO_UCDESCONSOLIDACION  IS NOT NULL  
			AND P.CANT_CONFIRMADA > 0  
	GROUP BY    
			D.NRO_REMITO, S.SUCURSAL_ID,S.NOMBRE,X.INFO_ADICIONAL_3,P.NRO_UCDESCONSOLIDACION,
			P.PRODUCTO_ID,P.DESCRIPCION,P.VIAJE_ID,  TC.TIPO_COMPROBANTE_ID ,TC.DESCRIPCION,
			sd.CLASE_PEDIDO,sd.observaciones, S.LOCALIDAD,PRV.DESCRIPCION,T.NOMBRE

END

