alter table cliente_parametros
add FLG_DESCONSOLIDACION CHAR(1);
GO
INSERT INTO sys_tabColumns VALUES('CLIENTE_PARAMETROS',	'FLG_DESCONSOLIDACION',19,'CHAR','Y','1',NULL,NULL,'1',NULL);
GO
INSERT INTO SYS_DET_TABLA VALUES('CLIENTE_PARAMETROS','FLG_DESCONSOLIDACION',	'Desconsolidacion obligatoria','S','1','0');

