
/****** Object:  StoredProcedure [dbo].[SETNROCMR]    Script Date: 09/24/2013 12:02:14 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[SETNROCMR]') AND type in (N'P', N'PC'))
DROP PROCEDURE [dbo].[SETNROCMR]
GO

CREATE PROCEDURE [dbo].[SETNROCMR]
@NRO_CMR AS VARCHAR(40) OUTPUT, 
@DOCUMENTO_ID AS NUMERIC(13) OUTPUT,
@CLIENTE_ID AS VARCHAR(15) OUTPUT,
@NRO_LINEA AS NUMERIC(9) OUTPUT

AS
BEGIN
	INSERT INTO NROCMR_POR_DOCUMENTO (NRO_CMR,DOCUMENTO_ID,CLIENTE_ID,NRO_LINEA)
	VALUES
	(@NRO_CMR,@DOCUMENTO_ID,@CLIENTE_ID,@NRO_LINEA)
END



GO


