INSERT INTO SYS_TABCOLUMNS VALUES('TIPO_CAJA','TIPO_CAJA_ID',1,'VARCHAR2','N',20,NULL,NULL,20,'Y');
INSERT INTO SYS_TABCOLUMNS VALUES('TIPO_CAJA','DESCRIPCION',2,'VARCHAR2','N',50,NULL,NULL,50,NULL);
INSERT INTO SYS_TABCOLUMNS VALUES('TIPO_CAJA','ALTO',3,'NUMBER','N',20,20,5,0,NULL);
INSERT INTO SYS_TABCOLUMNS VALUES('TIPO_CAJA','ANCHO',4,'NUMBER','N',20,20,5,0,NULL);
INSERT INTO SYS_TABCOLUMNS VALUES('TIPO_CAJA','LARGO',5,'NUMBER','N',20,20,5,0,NULL);
INSERT INTO SYS_TABCOLUMNS VALUES('TIPO_CAJA','ACTIVO',6,'VARCHAR2','N',1,NULL,NULL,1,NULL);