INSERT INTO SYS_DET_TABLA VALUES('TIPO_CAJA',	'ACTIVO',		'Activo',		'S',	1,	'0');
INSERT INTO SYS_DET_TABLA VALUES('TIPO_CAJA',	'ALTO',			'Alto',			'S',	10,	'0');
INSERT INTO SYS_DET_TABLA VALUES('TIPO_CAJA',	'ANCHO',		'Ancho',		'S',	10,	'0');
INSERT INTO SYS_DET_TABLA VALUES('TIPO_CAJA',	'DESCRIPCION',	'Descripcion',	'S',	50,	'0');
INSERT INTO SYS_DET_TABLA VALUES('TIPO_CAJA',	'LARGO',		'Largo',		'S',	10,	'0');
INSERT INTO SYS_DET_TABLA VALUES('TIPO_CAJA',	'TIPO_CAJA_ID',	'Tipo Caja',	'S',	20,	'0');