
CREATE TABLE [dbo].[DOCKS](
	[DOCK_ID] [numeric](20, 0) IDENTITY(1,1) NOT NULL,
	[DOCK_COD] [varchar](50) NOT NULL,
	[DESCRIPCION] [varchar](100) NOT NULL,
	[ACTIVO] [char](1) NOT NULL,
 CONSTRAINT [PK_DOCKS] PRIMARY KEY CLUSTERED 
(
	[DOCK_ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

