CREATE TABLE [dbo].[UC_EMPAQUE](
	[UC_EMPAQUE] [varchar](100) NOT NULL,
	[ALTO] [numeric](20, 5) NULL,
	[ANCHO] [numeric](20, 5) NULL,
	[LARGO] [numeric](20, 5) NULL,
	[VOLUMEN] [numeric](20, 5) NULL,
	[TRANSPORTE_ID] [varchar](20) NULL,
	[MONEDA_ID] [varchar](20) NULL,
	[VALOR] [numeric](20, 5) NULL,
	[NRO_GUIA] [varchar](20) NULL,
	[DOCK_ID] [numeric](20, 0) NULL,
	[NRO_HOJACARGA] [numeric](20, 0) NULL,
	[FECHA_HOJACARGA] [datetime] NULL,
PRIMARY KEY CLUSTERED 
(
	[UC_EMPAQUE] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[UC_EMPAQUE]  WITH CHECK ADD FOREIGN KEY([DOCK_ID])
REFERENCES [dbo].[DOCKS] ([DOCK_ID])
GO

ALTER TABLE [dbo].[UC_EMPAQUE]  WITH CHECK ADD FOREIGN KEY([TRANSPORTE_ID])
REFERENCES [dbo].[TRANSPORTE] ([TRANSPORTE_ID])
GO


