ALTER TABLE PICKING
ADD UCEMPAQUETADO_MEDIDAS VARCHAR(100)
GO
ALTER TABLE PICKING
ADD FECHA_UCEMPAQUETADO DATETIME
GO
ALTER TABLE PICKING
ADD UCEMPAQUETADO_PESO NUMERIC(20,5)
GO

ALTER TABLE PICKING_HISTORICO
ADD UCEMPAQUETADO_MEDIDAS VARCHAR(100)
GO
ALTER TABLE PICKING_HISTORICO
ADD FECHA_UCEMPAQUETADO DATETIME
GO
ALTER TABLE PICKING_HISTORICO
ADD UCEMPAQUETADO_PESO NUMERIC(20,5)
GO

