/****** Object:  StoredProcedure [dbo].[EMPAQUE_GET_PEDIDOS]    Script Date: 09/26/2013 10:30:24 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[EMPAQUE_GET_PEDIDOS]') AND type in (N'P', N'PC'))
DROP PROCEDURE [dbo].[EMPAQUE_GET_PEDIDOS]
GO

CREATE PROCEDURE [dbo].[EMPAQUE_GET_PEDIDOS]
 @REMITOS VARCHAR(400) OUTPUT
AS
BEGIN
	SELECT	DISTINCT
			'0' AS CHK
			,S.SUCURSAL_ID
			,S.NOMBRE
			,D.NRO_REMITO
			,CASE WHEN P.FECHA_UCEMPAQUETADO > 0 THEN 'EMPAQUETADO' ELSE 'PENDIENTE' END AS [Estado del Pedido]
			,C.RAZON_SOCIAL AS PROPIETARIO
			,dbo.GetClasePedido(D.NRO_REMITO) as [CLASE DE PEDIDO]
 	FROM PICKING P
	INNER JOIN DOCUMENTO D ON(P.DOCUMENTO_ID=D.DOCUMENTO_ID)
	INNER JOIN SUCURSAL S ON(D.CLIENTE_ID=S.CLIENTE_ID AND D.SUCURSAL_DESTINO=S.SUCURSAL_ID)
	INNER JOIN CLIENTE C ON (C.CLIENTE_ID = D.CLIENTE_ID)
	WHERE	P.ESTADO='2'
			AND P.FACTURADO='0'
			AND P.CANT_CONFIRMADA > 0
			AND NOT EXISTS (SELECT 1
							FROM #TMP_EMPAQUE_CAB T
							WHERE	T.PEDIDO=D.NRO_REMITO
									AND S.SUCURSAL_ID=T.SUCURSAL_ID)
END