/****** Object:  StoredProcedure [dbo].[INSERTPEDIDOS]    Script Date: 09/26/2013 10:34:12 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[INSERTPEDIDOS]') AND type in (N'P', N'PC'))
DROP PROCEDURE [dbo].[INSERTPEDIDOS]
GO

CREATE PROCEDURE [dbo].[INSERTPEDIDOS]  
 @SUCURSAL_ID VARCHAR(20) OUTPUT,  
 @PEDIDO   VARCHAR(20) OUTPUT  
AS  
BEGIN  
 DECLARE @CONTROL NUMERIC(20,0)  
 DECLARE @CTRL  NUMERIC(20,0)  
 DECLARE @CTRLCLI NUMERIC(20,0)
  
 SELECT @CTRL=COUNT(*)  
 FROM #TMP_EMPAQUE_CAB  
 WHERE SUCURSAL_ID<>@SUCURSAL_ID  
   
 IF @CTRL>0  
 BEGIN  
  RAISERROR('Tiene Diferentes destinatarios seleccionados.',16,1)  
  RETURN  
 END  
  
 SELECT @CONTROL=COUNT(*)  
 FROM #TMP_EMPAQUE_CAB  
 WHERE SUCURSAL_ID=@SUCURSAL_ID  
   AND PEDIDO=@PEDIDO  
   
  
 IF @CONTROL=0   
 BEGIN  
  INSERT INTO #TMP_EMPAQUE_CAB  
  SELECT  D.CLIENTE_ID  
    ,S.SUCURSAL_ID  
    ,D.NRO_REMITO  
  FROM PICKING P INNER JOIN DOCUMENTO D  
    ON(P.DOCUMENTO_ID=D.DOCUMENTO_ID)  
    INNER JOIN SUCURSAL S  
    ON(D.CLIENTE_ID=S.CLIENTE_ID AND D.SUCURSAL_DESTINO=S.SUCURSAL_ID)  
  WHERE P.ESTADO='2'  
    AND D.NRO_REMITO=@PEDIDO  
    AND D.SUCURSAL_DESTINO=@SUCURSAL_ID 
		AND P.CANT_CONFIRMADA > 0 
		AND P.NRO_UCDESCONSOLIDACION IS NOT NULL 
 END  
END


GO


