/****** Object:  UserDefinedFunction [dbo].[FECHA_CORTE]    Script Date: 10/01/2013 14:44:23 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[FECHA_CORTE]') AND type in (N'FN', N'IF', N'TF', N'FS', N'FT'))
DROP FUNCTION [dbo].[FECHA_CORTE]
GO

CREATE FUNCTION [dbo].[FECHA_CORTE](@FECHA AS DATETIME)RETURNS CHAR(20)
AS
BEGIN
	DECLARE @VFECHA_COMP AS DATETIME
	DECLARE @RET AS CHAR(20)
	
	SET @VFECHA_COMP=	CAST(CAST(DATEPART(YYYY,@FECHA)AS VARCHAR) + '-' + 
						CAST(DATEPART(MONTH,@FECHA) AS VARCHAR) + '-' +  
						CAST(DATEPART(DAY,@FECHA)AS VARCHAR) + ' ' + '16:30:00' AS DATETIME)

	IF @FECHA>@VFECHA_COMP BEGIN
		SET @RET= CONVERT(char(20),DATEADD(DAY,1,@FECHA),103)
	END ELSE BEGIN
		SET @RET= CONVERT(char(20),@FECHA,103)
	END
	RETURN @RET;
END


GO


