/****** Object:  StoredProcedure [dbo].[EMPAQUE_PENDIENTES]    Script Date: 10/03/2013 12:19:45 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[EMPAQUE_PENDIENTES]') AND type in (N'P', N'PC'))
DROP PROCEDURE [dbo].[EMPAQUE_PENDIENTES]
GO


CREATE PROCEDURE [dbo].[EMPAQUE_PENDIENTES]
AS
BEGIN
	SELECT	SUM(SIN_EMPAQUETAR) SIN_EMPAQUETAR, SUM(EMPAQUETADOS) EMPAQUETADOS
	FROM	(	SELECT	 ISNULL(DBO.FX_EMPAQUETADO_SN('1',D.NRO_REMITO, P.PRODUCTO_ID),0) SIN_EMPAQUETAR
						,ISNULL(DBO.FX_EMPAQUETADO_SN('2',D.NRO_REMITO, P.PRODUCTO_ID),0) EMPAQUETADOS
				FROM	PICKING P INNER JOIN DOCUMENTO D
						ON(P.DOCUMENTO_ID=D.DOCUMENTO_ID)
				WHERE	ESTADO='2'
						AND EXISTS (SELECT	1
									FROM	#TMP_EMPAQUE_CAB T
									WHERE	T.PEDIDO=D.NRO_REMITO)
				GROUP BY
						P.PRODUCTO_ID,P.DESCRIPCION,D.NRO_REMITO)X
END


GO


