/****** Object:  UserDefinedFunction [dbo].[FX_EMPAQUETADO_SN]    Script Date: 10/03/2013 12:21:22 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[FX_EMPAQUETADO_SN]') AND type in (N'FN', N'IF', N'TF', N'FS', N'FT'))
DROP FUNCTION [dbo].[FX_EMPAQUETADO_SN]
GO


CREATE FUNCTION [dbo].[FX_EMPAQUETADO_SN](
@TIPO		VARCHAR(1),
@REMITO		VARCHAR(100),
@PRODUCTO	VARCHAR(30))
RETURNS BIGINT
AS
BEGIN
	DECLARE @RETORNO BIGINT
	IF @TIPO='1'
	BEGIN
		--LOS QUE NO ESTAN EMPAQUETADOS.
		SELECT	@RETORNO=ISNULL(SUM(CANT_CONFIRMADA),0)
		FROM	PICKING P2 INNER JOIN DOCUMENTO D
				ON(P2.DOCUMENTO_ID=D.DOCUMENTO_ID)
		WHERE	D.NRO_REMITO=@REMITO
				AND P2.PRODUCTO_ID=@PRODUCTO
				AND NRO_UCEMPAQUETADO IS NULL
		GROUP BY
				PRODUCTO_ID
		IF @RETORNO IS NULL
		BEGIN
			SET @RETORNO=0
		END
	END
	
	IF @TIPO='2'
	BEGIN
		--LOS QUE ESTAN EMPAQUETADOS.
		SELECT	@RETORNO=ISNULL(SUM(CANT_CONFIRMADA),0)
		FROM	PICKING P2 INNER JOIN DOCUMENTO D
				ON(P2.DOCUMENTO_ID=D.DOCUMENTO_ID)
		WHERE	D.NRO_REMITO=@REMITO
				AND P2.PRODUCTO_ID=@PRODUCTO
				AND NRO_UCEMPAQUETADO IS NOT NULL
		GROUP BY
				PRODUCTO_ID
		IF @RETORNO IS NULL
		BEGIN
			SET @RETORNO=0
		END
	END
	RETURN @RETORNO
END
GO


