/****** Object:  StoredProcedure [dbo].[EMPAQUE_PENDIENTE_POR_UC]    Script Date: 10/03/2013 12:22:20 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[EMPAQUE_PENDIENTE_POR_UC]') AND type in (N'P', N'PC'))
DROP PROCEDURE [dbo].[EMPAQUE_PENDIENTE_POR_UC]
GO



CREATE PROCEDURE [dbo].[EMPAQUE_PENDIENTE_POR_UC]
@UC_DESC	VARCHAR(100)OUTPUT,
@QTY		BIGINT OUTPUT
AS
BEGIN
	SELECT	@QTY=SUM(CANT_CONFIRMADA)
	FROM	PICKING 
	WHERE	NRO_UCDESCONSOLIDACION=@UC_DESC
			AND NRO_UCEMPAQUETADO IS NULL
	IF @QTY IS NULL
	BEGIN
		SET @QTY=0
	END
END



GO


