
CREATE TABLE [dbo].[USUARIO_EMPAQUE](
	[NRO_UCEMPAQUETADO] [varchar](100) NOT NULL,
	[FECHA_UCEMPAQUETADO] [datetime] NOT NULL,
	[USUARIO_EMPAQUETADO] [varchar](20) NOT NULL,
	[TERMINAL_EMPAQUETADO] [varchar](100) NOT NULL,
 CONSTRAINT [PK_USU_EMP] PRIMARY KEY CLUSTERED 
(
	[NRO_UCEMPAQUETADO] ASC,
	[USUARIO_EMPAQUETADO] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]


