/****** Object:  StoredProcedure [dbo].[VALIDAR_PEDIDOS_CONTENEDORA_EMP]    Script Date: 10/03/2013 13:46:10 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[VALIDAR_PEDIDOS_CONTENEDORA_EMP]') AND type in (N'P', N'PC'))
DROP PROCEDURE [dbo].[VALIDAR_PEDIDOS_CONTENEDORA_EMP]
GO

create procedure [dbo].[VALIDAR_PEDIDOS_CONTENEDORA_EMP] 
As
begin
  
	SELECT PEDIDO
  FROM
  (
    (
      SELECT D.NRO_REMITO AS PEDIDO FROM DOCUMENTO D
      INNER JOIN PICKING P ON (P.CLIENTE_ID = D.CLIENTE_ID AND P.DOCUMENTO_ID = D.DOCUMENTO_ID)
      INNER JOIN
      (
      SELECT DISTINCT P.NRO_UCEMPAQUETADO
      FROM PICKING P
      INNER JOIN DOCUMENTO D ON (D.CLIENTE_ID = P.CLIENTE_ID AND D.DOCUMENTO_ID = P.DOCUMENTO_ID)
      INNER JOIN #TMP_EMPAQUE_CAB TMP ON (TMP.PEDIDO = D.NRO_REMITO)
      WHERE P.NRO_UCEMPAQUETADO IS NOT NULL
      ) CN ON (CN.NRO_UCEMPAQUETADO = P.NRO_UCEMPAQUETADO)
      EXCEPT
      SELECT DISTINCT PEDIDO FROM #TMP_EMPAQUE_CAB
    )
  ) dv
END

GO


