/****** Object:  StoredProcedure [dbo].[CERRAR_GUIA]    Script Date: 10/03/2013 13:47:52 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[CERRAR_GUIA]') AND type in (N'P', N'PC'))
DROP PROCEDURE [dbo].[CERRAR_GUIA]
GO


CREATE PROCEDURE [dbo].[CERRAR_GUIA]    
@IMPORTE_FLETE NUMERIC(9,2) output, 
@PESO_TOTAL NUMERIC(15,3) output,
@TOTAL_BULTOS NUMERIC(10) output
    
AS    
BEGIN    
	DECLARE @NRO_GUIA AS VARCHAR(20)    

	EXEC GET_VALUE_FOR_SEQUENCE 'NRO_GUIA', @NRO_GUIA OUTPUT

	SET @NRO_GUIA = LTRIM(RTRIM(@NRO_GUIA))
	--hago update.    
	UPDATE UC_EMPAQUE    
	SET NRO_GUIA = @NRO_GUIA
	WHERE UC_EMPAQUE IN (SELECT DISTINCT NRO_UCEMPAQUETADO FROM PICKING P     
						INNER JOIN DOCUMENTO D ON(P.DOCUMENTO_ID=D.DOCUMENTO_ID)      
						INNER JOIN UC_EMPAQUE U ON(P.NRO_UCEMPAQUETADO=U.UC_EMPAQUE)      
						WHERE	PALLET_CERRADO='1'      
								AND EXISTS (SELECT 1 FROM #TMP_EMPAQUE_CAB T WHERE T.PEDIDO=D.NRO_REMITO)      
								AND NRO_UCEMPAQUETADO IS NOT NULL)    
	  
	EXEC SYS_DEV_EGRESO_CON_GUIA @NRO_GUIA, @IMPORTE_FLETE, @PESO_TOTAL, @TOTAL_BULTOS

END



GO


