/****** Object:  StoredProcedure [dbo].[EMPAQUE_ETIQUETA_IMPRESA]    Script Date: 10/03/2013 15:26:51 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[EMPAQUE_ETIQUETA_IMPRESA]') AND type in (N'P', N'PC'))
DROP PROCEDURE [dbo].[EMPAQUE_ETIQUETA_IMPRESA]
GO

CREATE PROCEDURE [dbo].[EMPAQUE_ETIQUETA_IMPRESA]
@UC	VARCHAR(100) OUTPUT
AS
BEGIN
	UPDATE	PICKING SET ST_ETIQUETAS='1'
	WHERE	NRO_UCEMPAQUETADO=@UC
END


GO


