/****** Object:  StoredProcedure [dbo].[RPT_ESTADISTICA_CLIENTE]    Script Date: 10/22/2013 14:39:58 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[RPT_ESTADISTICA_CLIENTE]') AND type in (N'P', N'PC'))
DROP PROCEDURE [dbo].[RPT_ESTADISTICA_CLIENTE]
GO

CREATE PROCEDURE [dbo].[RPT_ESTADISTICA_CLIENTE]
	@FDESDE			VARCHAR(8)		OUTPUT,	--ANSI
	@FHASTA			VARCHAR(8)		OUTPUT,	--ANSI
	@CLIENTE_ID		VARCHAR(15)OUTPUT	
AS
BEGIN
	

	SELECT	ZZZ.CLIENTE						AS CLIENTE,
			ZZZ.FECHA						AS FECHA,
			SUM(ZZZ.Q_POS_OCUPADAS)			AS Q_POS_OCUPADAS,	
			SUM(ZZZ.Q_VOL_PROD)				AS Q_VOL_PROD,
			SUM(ZZZ.QTY_DOC_ING)			AS QTY_DOC_ING,
			SUM(ZZZ.PRODUCTOS_DIST_ING)		AS PRODUCTOS_DIST_ING,
			SUM(ZZZ.VOL_ING)				AS VOL_ING,
			SUM(ZZZ.CANTIDAD_INGRESO)		AS CANTIDAD_INGRESO,
			SUM(ZZZ.QTY_DOC_EGR)			AS QTY_DOC_EGR,
			SUM(ZZZ.PRODUCTOS_DIST_EGR)		AS PRODUCTOS_DIST_EGR,
			SUM(ZZZ.VOL_EGR)				AS VOL_EGR,
			SUM(ZZZ.CANTIDAD_EGRESO)		AS CANTIDAD_EGRESO,
			GETDATE()						AS F_IMP,
			HOST_NAME()						AS TERMINAL			
	FROM	(


		SELECT  X.FECHA					AS FECHA,
				X.CLIENTE				AS CLIENTE,				
				0						AS QTY_DOC_ING,
				0						AS PRODUCTOS_DIST_ING,
				0						AS VOL_ING,
				0						AS CANTIDAD_INGRESO,
				0						AS QTY_DOC_EGR,
				0						AS PRODUCTOS_DIST_EGR,
				0						AS VOL_EGR,
				0						AS CANTIDAD_EGRESO,				
				SUM(X.Q_POS_OCUPADAS)	AS Q_POS_OCUPADAS,
				SUM(X.Q_VOL_PROD)		AS Q_VOL_PROD
		FROM
		(
			SELECT  DISTINCT  
						 CONVERT(VARCHAR,SE.F_SNAP,103)		AS FECHA
						,C.RAZON_SOCIAL						AS CLIENTE
						,QPOS.CTN							AS Q_POS_OCUPADAS			
						,PVOL.PVOL							AS Q_VOL_PROD
				FROM    SNAP_EXISTENCIAS SE INNER JOIN POSICION P 
						ON(SE.POSICION_ACTUAL=P.POSICION_ID)
						INNER JOIN NAVE N                         
						ON(P.NAVE_ID = N.NAVE_ID)
						INNER JOIN CLIENTE C                      
						ON(SE.CLIENTE_ID=C.CLIENTE_ID)
						-------------------------------------------------------------------------------------------------------------------
						LEFT JOIN ( SELECT  COUNT(DISTINCT S.POSICION_ACTUAL) CTN, S.CLIENTE_ID, S.F_SNAP, P.NAVE_ID
									FROM    SNAP_EXISTENCIAS S INNER JOIN POSICION P ON(S.POSICION_ACTUAL=P.POSICION_ID)
									WHERE   S.DISPONIBLE='1'
									GROUP BY S.CLIENTE_ID, S.F_SNAP,P.NAVE_ID)QPOS    
						ON(SE.CLIENTE_ID=QPOS.CLIENTE_ID AND SE.F_SNAP=QPOS.F_SNAP AND P.NAVE_ID=QPOS.NAVE_ID)
						-------------------------------------------------------------------------------------------------------------------
						LEFT JOIN ( SELECT  Y.CLIENTE_ID,Y.F_SNAP,Y.NAVE_ID,SUM(Y.VOL) AS VOL_POS
									FROM    (	SELECT  DISTINCT P.POSICION_ID,P.NAVE_ID, S.CLIENTE_ID, S.F_SNAP, (ISNULL(P.ALTO,0)*ISNULL(P.ANCHO,0)*ISNULL(P.LARGO,0))/1000000 AS VOL
											  FROM    SNAP_EXISTENCIAS S INNER JOIN POSICION P ON(S.POSICION_ACTUAL=P.POSICION_ID)
											  WHERE   S.DISPONIBLE='1'
											)Y
									GROUP BY Y.CLIENTE_ID,Y.F_SNAP,Y.NAVE_ID
								   )QVOL
				                    
						ON(SE.CLIENTE_ID=QVOL.CLIENTE_ID AND SE.F_SNAP=QVOL.F_SNAP AND P.NAVE_ID=QVOL.NAVE_ID) 
						-------------------------------------------------------------------------------------------------------------------
						LEFT JOIN (  SELECT  F.CLIENTE_ID,F.F_SNAP,F.NAVE_ID,SUM(F.PVOL) AS PVOL
									  FROM    ( SELECT  S.CLIENTE_ID, S.F_SNAP, P.NAVE_ID
														,S.CANTIDAD * ((ISNULL(PR.ALTO,0)*ISNULL(PR.ANCHO,0)*ISNULL(PR.LARGO,0))/1000000) AS PVOL
												FROM    SNAP_EXISTENCIAS S INNER JOIN POSICION P  ON(S.POSICION_ACTUAL=P.POSICION_ID)
														INNER JOIN DET_DOCUMENTO_TRANSACCION DDT  ON(DDT.DOC_TRANS_ID=S.DOC_TRANS_ID AND DDT.NRO_LINEA_TRANS=S.NRO_LINEA_TRANS)
														INNER JOIN DET_DOCUMENTO DD               ON(DDT.DOCUMENTO_ID=DD.DOCUMENTO_ID AND DDT.NRO_LINEA_DOC=DD.NRO_LINEA)
														INNER JOIN PRODUCTO PR                    ON(DD.CLIENTE_ID=PR.CLIENTE_ID AND DD.PRODUCTO_ID=PR.PRODUCTO_ID)
												WHERE	NAVE_ACTUAL NOT IN (1,2)											
											  )F
									  GROUP BY
											  F.CLIENTE_ID,F.F_SNAP,F.NAVE_ID
								  )PVOL
						ON(SE.CLIENTE_ID=PVOL.CLIENTE_ID AND SE.F_SNAP=PVOL.F_SNAP AND N.NAVE_ID=PVOL.NAVE_ID)
						-------------------------------------------------------------------------------------------------------------------
				WHERE   SE.DISPONIBLE='1'
						AND ((@FDESDE IS NULL)OR(dbo.trunc(SE.F_SNAP) BETWEEN @FDESDE AND @FHASTA))
						AND ((@CLIENTE_ID IS NULL)OR(SE.CLIENTE_ID= @CLIENTE_ID))			
				UNION ALL
				SELECT  DISTINCT  
						 CONVERT(VARCHAR,SE.F_SNAP,103)		AS FECHA
						,C.RAZON_SOCIAL						AS CLIENTE
						,NULL								AS Q_POS_OCUPADAS
						,PVOL.PVOL							AS Q_VOL_PROD
				FROM    SNAP_EXISTENCIAS SE INNER JOIN NAVE N                         
						ON(SE.NAVE_ACTUAL=N.NAVE_ID)
						INNER JOIN CLIENTE C                      
						ON(SE.CLIENTE_ID=C.CLIENTE_ID)
						-------------------------------------------------------------------------------------------------------------------
						LEFT JOIN ( SELECT  F.CLIENTE_ID,F.F_SNAP,F.NAVE_ID,SUM(F.PVOL) AS PVOL
									FROM    (	SELECT  S.CLIENTE_ID, S.F_SNAP, N.NAVE_ID
														,S.CANTIDAD * ((ISNULL(PR.ALTO,0)*ISNULL(PR.ANCHO,0)*ISNULL(PR.LARGO,0))/1000000) AS PVOL
												FROM    SNAP_EXISTENCIAS S INNER JOIN NAVE N	  ON(S.NAVE_ACTUAL=N.NAVE_ID AND NAVE_TIENE_LAYOUT='0')
														INNER JOIN DET_DOCUMENTO_TRANSACCION DDT  ON(DDT.DOC_TRANS_ID=S.DOC_TRANS_ID AND DDT.NRO_LINEA_TRANS=S.NRO_LINEA_TRANS)
														INNER JOIN DET_DOCUMENTO DD               ON(DDT.DOCUMENTO_ID=DD.DOCUMENTO_ID AND DDT.NRO_LINEA_DOC=DD.NRO_LINEA)
														INNER JOIN PRODUCTO PR                    ON(DD.CLIENTE_ID=PR.CLIENTE_ID AND DD.PRODUCTO_ID=PR.PRODUCTO_ID)
												WHERE	S.DISPONIBLE='1' AND NAVE_ACTUAL NOT IN (1,2)	
											)F
									GROUP BY
										  F.CLIENTE_ID,F.F_SNAP,F.NAVE_ID
								  )PVOL
						ON(SE.CLIENTE_ID=PVOL.CLIENTE_ID AND SE.F_SNAP=PVOL.F_SNAP AND N.NAVE_ID=PVOL.NAVE_ID)
						-------------------------------------------------------------------------------------------------------------------
				WHERE   SE.DISPONIBLE='1'
						AND ((@FDESDE IS NULL)OR(DBO.TRUNC(SE.F_SNAP) BETWEEN @FDESDE AND @FHASTA))
						AND ((@CLIENTE_ID IS NULL)OR(SE.CLIENTE_ID= @CLIENTE_ID))
		) X				
		GROUP BY X.FECHA, X.CLIENTE
		
	UNION ALL
	--CANTIDAD DE DOCUMENTOS DE INGRESO.
	SELECT	C.RAZON_SOCIAL AS CLIENTE,
			DBO.TRUNC(D.FECHA_FIN_GTW) AS FECHA,
			COUNT(D.DOCUMENTO_ID) AS QTY_DOC_ING,
			0 AS PRODUCTOS_DIST_ING,
			0 AS VOL_ING,
			0 AS CANTIDAD_INGRESO,
			0 AS QTY_DOC_EGR,
			0 AS PRODUCTOS_DIST_EGR,
			0 AS VOL_EGR,
			0 AS CANTIDAD_EGRESO,
			0 AS Q_POS_OCUPADAS,
			0 AS Q_VOL_PROD
	FROM	DOCUMENTO D INNER JOIN DET_DOCUMENTO DD		ON(D.DOCUMENTO_ID=DD.DOCUMENTO_ID)
			INNER JOIN DET_DOCUMENTO_TRANSACCION DDT	ON(DD.DOCUMENTO_ID=DDT.DOCUMENTO_ID AND DD.NRO_LINEA=DDT.NRO_LINEA_DOC)
			INNER JOIN CLIENTE C						ON(D.CLIENTE_ID = C.CLIENTE_ID)
	WHERE	DBO.TRUNC(D.FECHA_FIN_GTW) BETWEEN @FDESDE AND @FHASTA
			AND TIPO_OPERACION_ID='ING'
			AND D.STATUS = 'D40'
			AND ((@CLIENTE_ID IS NULL)OR(D.CLIENTE_ID=@CLIENTE_ID))	
	GROUP BY DBO.TRUNC(D.FECHA_FIN_GTW), C.RAZON_SOCIAL
	
	UNION ALL		
	--VOLUMEN INGRESADO.
	SELECT	X.RAZON_SOCIAL AS CLIENTE,
			DBO.TRUNC(X.FECHA_FIN_GTW) AS FECHA,
			0 AS QTY_DOC_ING,
			COUNT(DISTINCT X.PRODUCTO_ID) AS PRODUCTOS_DIST_ING,
			SUM(X.VOL_ING) AS VOL_ING, 
			SUM(X.CANTIDAD) AS CANTIDAD_INGRESO,
			0 AS QTY_DOC_EGR,
			0 AS PRODUCTOS_DIST_EGR,
			0 AS VOL_EGR,
			0 AS CANTIDAD_EGRESO,
			0 AS Q_POS_OCUPADAS,
			0 AS Q_VOL_PROD				
	FROM	(	SELECT	DD.PRODUCTO_ID, (ISNULL(P.ALTO,0)*ISNULL(P.LARGO,0)*ISNULL(P.ANCHO,0))/1000000 AS VOL_ING,DD.CANTIDAD, D.FECHA_FIN_GTW, C.RAZON_SOCIAL
				FROM	DOCUMENTO D INNER JOIN DET_DOCUMENTO DD		ON(D.DOCUMENTO_ID=DD.DOCUMENTO_ID)
						INNER JOIN DET_DOCUMENTO_TRANSACCION DDT	ON(DD.DOCUMENTO_ID=DDT.DOCUMENTO_ID AND DD.NRO_LINEA=DDT.NRO_LINEA_DOC)
						INNER JOIN PRODUCTO P						ON(DD.CLIENTE_ID=P.CLIENTE_ID AND DD.PRODUCTO_ID=P.PRODUCTO_ID)
						INNER JOIN CLIENTE C						ON(D.CLIENTE_ID = C.CLIENTE_ID)
				WHERE	DBO.TRUNC(D.FECHA_FIN_GTW) BETWEEN @FDESDE AND @FHASTA
						AND TIPO_OPERACION_ID='ING'
						AND D.STATUS = 'D40' 
						AND ((@CLIENTE_ID IS NULL)OR(D.CLIENTE_ID=@CLIENTE_ID))	
						)X
	GROUP BY DBO.TRUNC(X.FECHA_FIN_GTW), X.RAZON_SOCIAL
	
	UNION ALL						
	--CANTIDAD DE DOCUMENTOS DE EGRESO.
	SELECT	C.RAZON_SOCIAL AS CLIENTE,
			DBO.TRUNC(D.FECHA_FIN_GTW) AS FECHA,
			0 AS QTY_DOC_ING,
			0 AS PRODUCTOS_DIST_ING,
			0 AS VOL_ING,
			0 AS CANTIDAD_INGRESO,
			COUNT(D.DOCUMENTO_ID) AS QTY_DOC_EGR,
			0 AS PRODUCTOS_DIST_EGR,
			0 AS VOL_EGR,
			0 AS CANTIDAD_EGRESO,
			0 AS Q_POS_OCUPADAS,
			0 AS Q_VOL_PROD
	FROM	DOCUMENTO D INNER JOIN DET_DOCUMENTO DD		ON(D.DOCUMENTO_ID=DD.DOCUMENTO_ID)
			INNER JOIN DET_DOCUMENTO_TRANSACCION DDT	ON(DD.DOCUMENTO_ID=DDT.DOCUMENTO_ID AND DD.NRO_LINEA=DDT.NRO_LINEA_DOC)
			INNER JOIN PICKING P						ON(P.DOCUMENTO_ID=DD.DOCUMENTO_ID AND P.NRO_LINEA=DD.NRO_LINEA)
			INNER JOIN CLIENTE C						ON(D.CLIENTE_ID = C.CLIENTE_ID)
	WHERE	DBO.TRUNC(D.FECHA_FIN_GTW) BETWEEN @FDESDE AND @FHASTA
			AND TIPO_OPERACION_ID='EGR'
			AND D.STATUS = 'D40'
			AND ((@CLIENTE_ID IS NULL)OR(D.CLIENTE_ID=@CLIENTE_ID))	
	GROUP BY DBO.TRUNC(D.FECHA_FIN_GTW), C.RAZON_SOCIAL		
	
	UNION ALL		
	--VOLUMEN EGRESADO.
	SELECT	X.RAZON_SOCIAL AS CLIENTE,
			DBO.TRUNC(X.FECHA_FIN_GTW) AS FECHA,
			0 AS QTY_DOC_ING,
			0 AS PRODUCTOS_DIST_ING,
			0 AS VOL_ING, 
			0 AS CANTIDAD_INGRESO,
			0 AS QTY_DOC_EGR,
			COUNT(DISTINCT X.PRODUCTO_ID) AS PRODUCTOS_DIST_EGR,
			SUM(X.VOL_ING) AS VOL_EGR,
			SUM(X.CANTIDAD) AS CANTIDAD_EGRESO,
			0 AS Q_POS_OCUPADAS,
			0 AS Q_VOL_PROD				
	FROM	(	SELECT	DD.PRODUCTO_ID, (ISNULL(P.ALTO,0)*ISNULL(P.LARGO,0)*ISNULL(P.ANCHO,0))/1000000 AS VOL_ING,DD.CANTIDAD, D.FECHA_FIN_GTW, C.RAZON_SOCIAL
				FROM	DOCUMENTO D INNER JOIN DET_DOCUMENTO DD		ON(D.DOCUMENTO_ID=DD.DOCUMENTO_ID)
						INNER JOIN DET_DOCUMENTO_TRANSACCION DDT	ON(DD.DOCUMENTO_ID=DDT.DOCUMENTO_ID AND DD.NRO_LINEA=DDT.NRO_LINEA_DOC)
						INNER JOIN PRODUCTO P						ON(DD.CLIENTE_ID=P.CLIENTE_ID AND DD.PRODUCTO_ID=P.PRODUCTO_ID)
						INNER JOIN PICKING PIC						ON(PIC.DOCUMENTO_ID=DD.DOCUMENTO_ID AND PIC.NRO_LINEA=DD.NRO_LINEA)
						INNER JOIN CLIENTE C						ON(D.CLIENTE_ID = C.CLIENTE_ID)
				WHERE	DBO.TRUNC(D.FECHA_FIN_GTW) BETWEEN @FDESDE AND @FHASTA
						AND TIPO_OPERACION_ID='EGR'
						AND D.STATUS = 'D40'
						AND ((@CLIENTE_ID IS NULL)OR(D.CLIENTE_ID=@CLIENTE_ID))	
						)X
	GROUP BY DBO.TRUNC(X.FECHA_FIN_GTW), X.RAZON_SOCIAL			
										
) ZZZ				
GROUP BY ZZZ.FECHA, ZZZ.CLIENTE


END;





GO


