/*
1. ENTRADA EN EL MENU. Ok
2. PERMISOS DEL MENU. Ok
3. TABLA SYS_TABCOLUMNS.
4. DDT.
*/

--1. menu
INSERT INTO SYS_MENU VALUES('mnu_Docks','Docks');
--2. sys_tabcolumns
INSERT INTO SYS_TABCOLUMNS VALUES('DOCKS','DOCK_ID','1','NUMBER','N','20','20','0','0','Y');
INSERT INTO SYS_TABCOLUMNS VALUES('DOCKS','DOCK_COD','2','VARCHAR2','N',NULL,NULL,'0','50',NULL);
INSERT INTO SYS_TABCOLUMNS VALUES('DOCKS','DESCRIPCION','3','VARCHAR2','N',NULL,NULL,'0','50',NULL);
INSERT INTO SYS_TABCOLUMNS VALUES('DOCKS','ACTIVO','4','CHAR','N',NULL,NULL,'0','1',NULL);
--3. SYS_DET_TABLA
INSERT INTO SYS_DET_TABLA VALUES('DOCKS','DOCK_ID','Dock ID','S',20,'0');
INSERT INTO SYS_DET_TABLA VALUES('DOCKS','DOCK_COD','Codigo Dock','S',50,'1');
INSERT INTO SYS_DET_TABLA VALUES('DOCKS','DESCRIPCION','Descripcion','S',50,'1');
INSERT INTO SYS_DET_TABLA VALUES('DOCKS','ACTIVO','Dock Activo','S',1,'0');
