/****** Object:  StoredProcedure [dbo].[RPT_OCUP_CLIENTE]    Script Date: 10/22/2013 14:38:56 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[RPT_OCUP_CLIENTE]') AND type in (N'P', N'PC'))
DROP PROCEDURE [dbo].[RPT_OCUP_CLIENTE]
GO

CREATE PROCEDURE [dbo].[RPT_OCUP_CLIENTE]
	@CLIENTE_ID		VARCHAR(15)OUTPUT
AS
BEGIN


SELECT	W.CLIENTE AS CLIENTE, 
		COUNT(W.POSICION) AS POS_OCUPADAS, 
		SUM(W.VOL_00) AS VOL_OCUPADO
FROM	(
		SELECT	Q.CLIENTE,Q.POSICION,SUM(Q.VOLUMEN) AS VOL_00
		FROM	(
				SELECT C.RAZON_SOCIAL AS CLIENTE, DD.PRODUCTO_ID AS PRODUCTO, RL.POSICION_ACTUAL AS POSICION, (SUM( ISNULL(P.LARGO,0) * ISNULL(P.ALTO,0) * ISNULL(P.ANCHO,0))/1000000) VOLUMEN
				FROM RL_DET_DOC_TRANS_POSICION RL
					INNER JOIN DET_DOCUMENTO_TRANSACCION DDT ON (RL.DOC_TRANS_ID = DDT.DOC_TRANS_ID AND RL.NRO_LINEA_TRANS = DDT.NRO_LINEA_TRANS)
					INNER JOIN DET_DOCUMENTO DD ON (DDT.DOCUMENTO_ID = DD.DOCUMENTO_ID AND DDT.NRO_LINEA_DOC = DD.NRO_LINEA)
					INNER JOIN DOCUMENTO D ON (DD.DOCUMENTO_ID = D.DOCUMENTO_ID)
					INNER JOIN PRODUCTO P ON (P.PRODUCTO_ID = DD.PRODUCTO_ID AND P.CLIENTE_ID = DD.CLIENTE_ID)
					INNER JOIN CLIENTE C ON (DD.CLIENTE_ID = C.CLIENTE_ID)
				WHERE	RL.POSICION_ACTUAL IS NOT NULL 
						AND ((@CLIENTE_ID IS NULL)OR(DD.CLIENTE_ID=@CLIENTE_ID))												
				GROUP BY C.RAZON_SOCIAL, DD.PRODUCTO_ID, RL.POSICION_ACTUAL ) Q
		GROUP BY Q.CLIENTE, Q.POSICION
		UNION ALL
		SELECT	Q.CLIENTE,Q.POSICION,SUM(Q.VOLUMEN) AS VOL_00
		FROM	(
				SELECT C.RAZON_SOCIAL AS CLIENTE, DD.PRODUCTO_ID AS PRODUCTO, RL.NAVE_ACTUAL AS POSICION, (SUM( ISNULL(P.LARGO,0) * ISNULL(P.ALTO,0) * ISNULL(P.ANCHO,0))/1000000) VOLUMEN
				FROM RL_DET_DOC_TRANS_POSICION RL
					INNER JOIN DET_DOCUMENTO_TRANSACCION DDT ON (RL.DOC_TRANS_ID = DDT.DOC_TRANS_ID AND RL.NRO_LINEA_TRANS = DDT.NRO_LINEA_TRANS)
					INNER JOIN DET_DOCUMENTO DD ON (DDT.DOCUMENTO_ID = DD.DOCUMENTO_ID AND DDT.NRO_LINEA_DOC = DD.NRO_LINEA)
					INNER JOIN DOCUMENTO D ON (DD.DOCUMENTO_ID = D.DOCUMENTO_ID)
					INNER JOIN PRODUCTO P ON (P.PRODUCTO_ID = DD.PRODUCTO_ID AND P.CLIENTE_ID = DD.CLIENTE_ID)
					INNER JOIN CLIENTE C ON (DD.CLIENTE_ID = C.CLIENTE_ID)
				WHERE	RL.NAVE_ACTUAL IS NOT NULL 
						AND ((@CLIENTE_ID IS NULL)OR(DD.CLIENTE_ID=@CLIENTE_ID))						
				GROUP BY C.RAZON_SOCIAL, DD.PRODUCTO_ID, RL.NAVE_ACTUAL ) Q
		GROUP BY Q.CLIENTE, Q.POSICION
		) W
GROUP BY W.CLIENTE


	
END;



GO


