/****** Object:  StoredProcedure [dbo].[GetGrillaDespachados]    Script Date: 10/07/2013 17:08:30 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[GetGrillaDespachados]') AND type in (N'P', N'PC'))
DROP PROCEDURE [dbo].[GetGrillaDespachados]
GO

CREATE procedure [dbo].[GetGrillaDespachados]  
@DOCK VARCHAR(50)  output
AS  
  
SELECT  
 U.NRO_GUIA,  
 COUNT(UC_EMPAQUE) AS [CANTIDAD DE BULTOS],  
 T.TRANSPORTE_ID AS [COD. TRANSPORTE],  
 T.NOMBRE AS [DESCRIPCION TRANSPORTE],  
 S.NOMBRE AS [CLIENTE DESTINATARIO]  
FROM UC_EMPAQUE U  
INNER JOIN PICKING P  
 ON P.NRO_UCEMPAQUETADO = U.UC_EMPAQUE  
INNER JOIN DOCUMENTO D  
 ON D.DOCUMENTO_ID = P.DOCUMENTO_ID  
INNER JOIN TRANSPORTE T  
 ON U.TRANSPORTE_ID = T.TRANSPORTE_ID  
INNER JOIN SUCURSAL S  
 ON S.SUCURSAL_ID = D.SUCURSAL_DESTINO  
  
WHERE  
U.DOCK_ID = (SELECT DOCK_ID FROM DOCKS WHERE DOCK_COD = @dock )  
and U.NRO_HOJACARGA  IS NOT NULL
  
GROUP BY U.NRO_GUIA,T.TRANSPORTE_ID,T.NOMBRE,S.NOMBRE


GO


