/****** Object:  StoredProcedure [dbo].[RPTHojadeCarga]    Script Date: 10/10/2013 11:28:15 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[RPTHojadeCarga]') AND type in (N'P', N'PC'))
DROP PROCEDURE [dbo].[RPTHojadeCarga]
GO

CREATE PROCEDURE [dbo].[RPTHojadeCarga]      
@Transporte varchar(200) output,       
@Transportista varchar (200)output,       
@Patente varchar(200) output,    
@HOJACARGA VARCHAR(13) OUTPUT    
      
as      
begin 
		select	U.NRO_HOJACARGA      
				,U.NRO_GUIA      
				,U.UC_EMPAQUE      
				,CAST(P.UCEMPAQUETADO_PESO AS NUMERIC(13,2)) AS PESO      
				,CAST(CAST(U.ALTO AS NUMERIC(13,2)) AS VARCHAR) + 'x' + CAST(CAST(U.ANCHO AS NUMERIC(13,2)) AS VARCHAR) + 'x' + CAST(CAST(U.LARGO AS NUMERIC(13,2))AS VARCHAR) AS MEDIDAS      
				,CAST(U.VOLUMEN AS NUMERIC(13,2)) AS VOLUMEN    
				,@Transporte as TRANSPORTE      
				,@Transportista as TRANSPORTISTA      
				,@Patente as PATENTE      
				,D.DESCRIPCION AS DOCK
				,(SELECT Imagen FROM Imagenes_Reporte WHERE CLIENTE=DOC.CLIENTE_ID AND REPORTE='REPORTES') AS LOGO
				,S.NOMBRE AS CLIENTE_DESTINATARIO
				,isnull(rtrim(PROV.DESCRIPCION),'') + ' - ' + isnull(rtrim(s.LOCALIDAD),'')  + ' - ' + ISNULL(rtrim(s.calle),'') + ' - ' + ' ' + ISNULL(S.NUMERO,'') as DIRECCION
				,(SELECT COUNT(*) FROM UC_EMPAQUE WHERE NRO_HOJACARGA = @HOJACARGA) AS TOTAL_BULTOS
				,U.FECHA_HOJACARGA
		from	UC_EMPAQUE U INNER JOIN PICKING P		ON (U.UC_EMPAQUE = P.NRO_UCEMPAQUETADO)
				INNER JOIN DOCUMENTO DOC				ON (P.DOCUMENTO_ID = DOC.DOCUMENTO_ID)
				LEFT JOIN DOCKS D						ON (U.DOCK_ID = D.DOCK_ID)
				INNER JOIN CLIENTE C					ON (P.CLIENTE_ID = C.CLIENTE_ID)
				INNER JOIN SUCURSAL S					ON (DOC.CLIENTE_ID = S.CLIENTE_ID and  DOC.SUCURSAL_DESTINO = S.SUCURSAL_ID)
				LEFT JOIN PROVINCIA PROV				ON (S.PROVINCIA_ID = PROV.PROVINCIA_ID AND S.PAIS_ID = PROV.PAIS_ID)
		where   U.NRO_HOJACARGA = @HOJACARGA
		GROUP BY
				U.NRO_HOJACARGA, U.NRO_GUIA ,U.UC_EMPAQUE, CAST(P.UCEMPAQUETADO_PESO AS NUMERIC(13,2))
				,CAST(CAST(U.ALTO AS NUMERIC(13,2)) AS VARCHAR) + 'x' + CAST(CAST(U.ANCHO AS NUMERIC(13,2)) AS VARCHAR) + 'x' + CAST(CAST(U.LARGO AS NUMERIC(13,2))AS VARCHAR)
				,CAST(U.VOLUMEN AS NUMERIC(13,2)),D.DESCRIPCION,S.NOMBRE,U.FECHA_HOJACARGA,DOC.CLIENTE_ID
				,isnull(rtrim(PROV.DESCRIPCION),'') + ' - ' + isnull(rtrim(s.LOCALIDAD),'')  + ' - ' + ISNULL(rtrim(s.calle),'') + ' - ' + ' ' + ISNULL(S.NUMERO,'')		
		ORDER BY
				S.NOMBRE,U.UC_EMPAQUE
end

GO


