/****** Object:  StoredProcedure [dbo].[EMPAQUE_PRINT_ETIQUETA]    Script Date: 10/10/2013 11:29:57 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[EMPAQUE_PRINT_ETIQUETA]') AND type in (N'P', N'PC'))
DROP PROCEDURE [dbo].[EMPAQUE_PRINT_ETIQUETA]
GO


CREATE PROCEDURE [dbo].[EMPAQUE_PRINT_ETIQUETA]
@GUIA AS VARCHAR(50) output
AS
BEGIN

	SELECT	UC_EMPAQUE
			,CAST(CAST(U.ALTO AS NUMERIC(20,2)) AS VARCHAR) + ' x ' + CAST(CAST(U.ANCHO AS NUMERIC(20,2)) AS VARCHAR) + ' x ' + CAST(CAST(U.LARGO AS NUMERIC(20,2)) AS VARCHAR) MEDIDAS --
			,VOLUMEN
			,T.TRANSPORTE_ID + ' - ' + T.NOMBRE AS TRANSPORTE
			,VALOR
			,SUM(CANT_CONFIRMADA) BULTOS
			,ROW_NUMBER() OVER(ORDER BY UC_EMPAQUE ASC) CAJA
			,DBO.GetRtosXGuia(@GUIA)AS NRO_REMITO
			,P.UCEMPAQUETADO_PESO
			,S.SUCURSAL_ID
			,S.NOMBRE
			,ISNULL(s.CALLE,'') + ', ' + ISNULL(s.NUMERO,'') + ', ' + ISNULL(s.LOCALIDAD,'') DOMICILIO
			,MAX(P.FECHA_UCEMPAQUETADO) FECHA_UCEMPAQUETADO
			,U.NRO_GUIA
			,(SELECT IMAGEN FROM Imagenes_Reporte WHERE Cliente =D.CLIENTE_ID AND Reporte='Ar_EtiquetaEmpaque')LOGO
	FROM	PICKING P INNER JOIN UC_EMPAQUE U	ON(P.NRO_UCEMPAQUETADO=U.UC_EMPAQUE)
			LEFT JOIN TRANSPORTE T				ON(U.TRANSPORTE_ID=T.TRANSPORTE_ID)
			INNER JOIN DOCUMENTO D				ON(D.DOCUMENTO_ID=P.DOCUMENTO_ID)
			INNER JOIN SUCURSAL S				ON(D.CLIENTE_ID=S.CLIENTE_ID AND D.SUCURSAL_DESTINO=S.SUCURSAL_ID)
	WHERE	U.NRO_GUIA = @guia
	GROUP BY
			UC_EMPAQUE,VOLUMEN, T.NOMBRE,U.ALTO, U.ANCHO, U.LARGO,VALOR,P.UCEMPAQUETADO_PESO,S.SUCURSAL_ID,S.NOMBRE
			,T.TRANSPORTE_ID, T.NOMBRE, s.CALLE,s.NUMERO, s.LOCALIDAD, U.NRO_GUIA,D.CLIENTE_ID
END