CREATE TABLE [dbo].[STOCK_BY_DEP](
	[CLIENTE_ID] [varchar](15) NOT NULL,
	[PRODUCTO_ID] [varchar](30) NOT NULL,
	[DEP1] [numeric](20, 5) NULL,
	[DEP2] [numeric](20, 5) NULL,
	[DEP3] [numeric](20, 5) NULL,
	[DEP4] [numeric](20, 5) NULL,
	[DEP5] [numeric](20, 5) NULL,
	[AUX_1] [varchar](100) NULL,
	[AUX_2] [varchar](100) NULL,
	[AUX_3] [varchar](100) NULL,
 CONSTRAINT [PK_STOCK_BY_DEP] PRIMARY KEY CLUSTERED 
(
	[CLIENTE_ID] ASC,
	[PRODUCTO_ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[STOCK_BY_DEP]  WITH CHECK ADD  CONSTRAINT [FK_STOCK_BY_DEP] FOREIGN KEY([CLIENTE_ID], [PRODUCTO_ID])
REFERENCES [dbo].[PRODUCTO] ([CLIENTE_ID], [PRODUCTO_ID])
GO

ALTER TABLE [dbo].[STOCK_BY_DEP] CHECK CONSTRAINT [FK_STOCK_BY_DEP]
GO


