ALTER TABLE CLIENTE_PARAMETROS
ADD FLG_EMPAQUETADO CHAR(1)
GO

ALTER TABLE CLIENTE_PARAMETROS
ADD FLG_DISTRIBUCION CHAR(1)
GO

INSERT INTO SYS_TABCOLUMNS VALUES('CLIENTE_PARAMETROS',	'FLG_EMPAQUETADO',	22,	'CHAR',	'Y',	1,	NULL,	NULL,	1,	NULL)
INSERT INTO SYS_TABCOLUMNS VALUES('CLIENTE_PARAMETROS',	'FLG_DISTRIBUCION',	23,	'CHAR',	'Y',	1,	NULL,	NULL,	1,	NULL)

INSERT INTO SYS_DET_TABLA VALUES('CLIENTE_PARAMETROS',	'FLG_EMPAQUETADO',	'Empaquetado Obligatorio',	'S',	1,	0)
INSERT INTO SYS_DET_TABLA VALUES('CLIENTE_PARAMETROS',	'FLG_DISTRIBUCION',	'Distribucion Obligatoria',	'S',	1,	0)
