/****** OBJECT:  STOREDPROCEDURE [DBO].[ACTIVAR_PRIORIDAD_PICKEADORES]    SCRIPT DATE: 10/18/2013 15:34:38 ******/
IF  EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[DBO].[ACTIVAR_PRIORIDAD_PICKEADORES]') AND TYPE IN (N'P', N'PC'))
DROP PROCEDURE [DBO].[ACTIVAR_PRIORIDAD_PICKEADORES]
GO

CREATE PROCEDURE   [DBO].[ACTIVAR_PRIORIDAD_PICKEADORES]
											 
AS
BEGIN 
	DECLARE @USUARIO_ACTIVACION VARCHAR(20)
	DECLARE @TERMINAL_ACTIVACION VARCHAR(20)

	SELECT @USUARIO_ACTIVACION  = USUARIO_ID, @TERMINAL_ACTIVACION = TERMINAL  FROM #TEMP_USUARIO_LOGGIN

	INSERT INTO  PRIORIDADES_PICKEADORES 
	(PROCESO_ACTIVO,USUARIO_ACTIVACION,TERMINAL_ACTIVACION,FECHA_ACTIVACION)
	VALUES (1,@USUARIO_ACTIVACION,@TERMINAL_ACTIVACION,GETDATE()) 
END
GO


