INSERT INTO SYS_MENU VALUES('FRONTERA.EGRESO.PRIORIDADES AT.','BOTON PRIORIDADES AT.');
INSERT INTO SYS_MENU VALUES('FRONTERA.EGRESO.CONSULTA','BOTON CONSULTA RAPIDA STOCK');
INSERT INTO SYS_MENU VALUES('FRONTERA.PICKPROCESO.CONSULTA','BOTON CONSULTA RAPIDA STOCK');
INSERT INTO SYS_MENU VALUES('FRONTERA.PICKFINALIZADOS.CONSULTA','BOTON CONSULTA RAPIDA STOCK');
