
INSERT INTO SYS_MENU VALUES('FRONTERA.PICKPROCESO.DESCONSOLIDACION','DESCONSOLIDACION')
INSERT INTO SYS_MENU VALUES('FRONTERA.PICKPROCESO.EMPAQUETAR','EMPAQUETAR')
INSERT INTO SYS_MENU VALUES('FRONTERA.PICKPROCESO.DISTRIBUCION','DISTRIBUCION')