
/****** Object:  UserDefinedFunction [dbo].[FX_REMITOS]    Script Date: 10/23/2013 11:48:37 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[FX_REMITOS]') AND type in (N'FN', N'IF', N'TF', N'FS', N'FT'))
DROP FUNCTION [dbo].[FX_REMITOS]
GO


CREATE FUNCTION	[dbo].[FX_REMITOS] (@REM	VARCHAR(50))
		RETURNS VARCHAR(4000)
AS
BEGIN
	DECLARE @CUR		CURSOR
	DECLARE @RETORNO	VARCHAR(4000)
	DECLARE @VREM		VARCHAR(50)

	SET @CUR=CURSOR FOR
		SELECT	REPLICATE('0', 13-DATALENGTH(t.REMITO))+ t.remito 
		FROM	DOCUMENTO D INNER JOIN TMP_REMITO T
				ON(D.NRO_REMITO=T.ID_REMITO)
		WHERE	ID_REMITO=@REM

	SET @RETORNO=''

	OPEN @CUR
	FETCH NEXT FROM @CUR INTO @VREM
	WHILE @@FETCH_STATUS=0
	BEGIN
		SET @RETORNO=@RETORNO +  ISNULL(@VREM,'') + '|'

		FETCH NEXT FROM @CUR INTO @VREM
	END
	CLOSE @CUR
	DEALLOCATE @CUR
	RETURN @RETORNO
END--FIN FX

GO


