UPDATE TIPO_EMPAQUETADO SET DESCRIPCION='EMPAQUETADO SIMPLE' WHERE TIPO_EMPAQUETADO_ID='1'
UPDATE TIPO_EMPAQUETADO SET DESCRIPCION='CONTROL DE PEDIDO Y EMPAQUETADO' WHERE TIPO_EMPAQUETADO_ID='2'
UPDATE TIPO_EMPAQUETADO SET DESCRIPCION='EMPAQUETADO PARA DISTRIBUCION' WHERE TIPO_EMPAQUETADO_ID='3'