

CREATE FUNCTION DBO.MOB_TR_BULTO_VALIDA_SERIE(
	@POSICION		VARCHAR(45),
	@CLIENTE_ID		VARCHAR(15),
	@PRODUCTO_ID	VARCHAR(30),
	@NRO_SERIE		VARCHAR(100)
)RETURNS VARCHAR(1)
AS
BEGIN
	DECLARE @CONT	SMALLINT
	DECLARE @RET	VARCHAR(1)
	
	SELECT	@CONT=COUNT(DD.NRO_SERIE)
	FROM	DET_DOCUMENTO DD INNER JOIN DET_DOCUMENTO_TRANSACCION DDT
			ON(DD.DOCUMENTO_ID=DDT.DOCUMENTO_ID AND DD.NRO_LINEA=DDT.NRO_LINEA_DOC)
			INNER JOIN RL_DET_DOC_TRANS_POSICION RL
			ON(DDT.DOC_TRANS_ID=RL.DOC_TRANS_ID AND DDT.NRO_LINEA_TRANS=RL.NRO_LINEA_TRANS)
			LEFT JOIN POSICION P
			ON(RL.POSICION_ACTUAL=P.POSICION_ID)
			LEFT JOIN NAVE N
			ON(RL.NAVE_ACTUAL=N.NAVE_ID)
	WHERE	DD.CLIENTE_ID=@CLIENTE_ID
			AND DD.PRODUCTO_ID=@PRODUCTO_ID
			AND DD.NRO_SERIE=@NRO_SERIE
			AND ((P.POSICION_COD=@POSICION) OR (N.NAVE_COD=@POSICION))
			
	IF @CONT>0 BEGIN
		SET @RET='1'
	END ELSE BEGIN
		SET @RET='0'
	END
	
	RETURN @RET
END