/****** Object:  Trigger [TRG_STK_DISPONIBLE]    Script Date: 11/10/2015 17:27:58 ******/
IF  EXISTS (SELECT * FROM sys.triggers WHERE object_id = OBJECT_ID(N'[dbo].[TRG_STK_DISPONIBLE]'))
DROP TRIGGER [dbo].[TRG_STK_DISPONIBLE]
GO

CREATE TRIGGER [dbo].[TRG_STK_DISPONIBLE]
ON [dbo].[RL_DET_DOC_TRANS_POSICION]
AFTER UPDATE, INSERT
AS
BEGIN
	SET NOCOUNT ON
	DECLARE @RL_ID				NUMERIC(20,0)
	DECLARE @CAT_LOG_ID			VARCHAR(100)
	DECLARE @OLD_CAT_LOG		VARCHAR(100)
	DECLARE @DISPONIBLE			VARCHAR(100)
	DECLARE @NEW_CAT_LOG		VARCHAR(100)
	DECLARE @CAT_LOG_ID_FINAL	VARCHAR(100)
	DECLARE @STATUS				VARCHAR(100)
	DECLARE @DOC_TRANS_TR		NUMERIC(20,0)
	DECLARE @MSG				VARCHAR(1000)
	DECLARE @NRO_LINEA			NUMERIC(10,0)
	
	IF CURSOR_STATUS('global','TRG_CURSOR')>=-1  BEGIN
		DEALLOCATE TRG_CURSOR
	END
	
	DECLARE TRG_CURSOR CURSOR FOR
	SELECT RL_ID,DOC_TRANS_ID_TR, NRO_LINEA_TRANS FROM INSERTED
	
	
	OPEN TRG_CURSOR
	FETCH NEXT FROM TRG_CURSOR INTO @RL_ID,  @DOC_TRANS_TR, @NRO_LINEA
	
	WHILE @@FETCH_STATUS=0 BEGIN
	
		SELECT	DISTINCT @STATUS=D.STATUS
		FROM	DET_DOCUMENTO DD INNER JOIN DET_DOCUMENTO_TRANSACCION DDT
				ON(DD.DOCUMENTO_ID=DDT.DOCUMENTO_ID AND DD.NRO_LINEA=DDT.NRO_LINEA_DOC)
				INNER JOIN RL_DET_DOC_TRANS_POSICION RL 
				ON(DDT.DOC_TRANS_ID=RL.DOC_TRANS_ID AND DDT.NRO_LINEA_TRANS=RL.NRO_LINEA_TRANS)
				INNER JOIN DOCUMENTO D 
				ON(DD.DOCUMENTO_ID=D.DOCUMENTO_ID)
		WHERE	RL.RL_ID=@RL_ID
		
		IF (UPDATE(POSICION_ACTUAL) OR UPDATE(NAVE_ACTUAL))AND(@DOC_TRANS_TR IS NULL) BEGIN
			
			UPDATE	RL_DET_DOC_TRANS_POSICION
			SET		CAT_LOG_ID=CAT_LOG_ID_FINAL,
					DISPONIBLE='1'
			FROM	RL_DET_DOC_TRANS_POSICION RL LEFT JOIN POSICION P ON(RL.POSICION_ACTUAL=P.POSICION_ID )
					LEFT JOIN NAVE N         ON(RL.NAVE_ACTUAL=N.NAVE_ID)
			WHERE	RL.RL_ID=@RL_ID
					AND ISNULL(P.intermedia,'0')='0'
					AND ISNULL(N.PRE_EGRESO,'0')='0' 
					AND ISNULL(N.PRE_INGRESO,'0')='0'
					AND isnull(RL.DISPONIBLE,'0')='0'
		END  


		IF @STATUS='D30' BEGIN

			SELECT @CAT_LOG_ID=CAT_LOG_ID,@DISPONIBLE=DISPONIBLE FROM DELETED WHERE RL_ID=@RL_ID

			SELECT @NEW_CAT_LOG=CAT_LOG_ID,@CAT_LOG_ID_FINAL=CAT_LOG_ID_FINAL,@NRO_LINEA=NRO_LINEA_TRANS FROM INSERTED WHERE RL_ID=@RL_ID
			
			/*
			-- SIRVE PARA DEBUG.
			SET @MSG=	'DISP: ' + @DISPONIBLE + ', NEW_CAT_LOG: ' + @NEW_CAT_LOG + ', CAT_FINAL: ' + @CAT_LOG_ID_FINAL + 
						', STATUS: ' + @STATUS + ', RL_ID= ' + CAST(@RL_ID AS VARCHAR) + ', NRO_LINEA: ' + CAST(@NRO_LINEA AS VARCHAR)
						
			PRINT(@MSG)						
			*/
			
			IF @DISPONIBLE='1' AND @NEW_CAT_LOG=@CAT_LOG_ID_FINAL AND @STATUS='D30' BEGIN
			
				UPDATE	RL_DET_DOC_TRANS_POSICION 
				SET		CAT_LOG_ID=@CAT_LOG_ID
				WHERE	RL_ID=@RL_ID		

			END ELSE BEGIN
			
				IF @CAT_LOG_ID='TRAN_EGR' BEGIN

					UPDATE	RL_DET_DOC_TRANS_POSICION 
					SET		CAT_LOG_ID='TRAN_EGR',
							DISPONIBLE='0'
					WHERE	RL_ID=@RL_ID
					
				END
			END
			
		END	
		
		FETCH NEXT FROM TRG_CURSOR INTO @RL_ID,  @DOC_TRANS_TR, @NRO_LINEA
	END
	CLOSE TRG_CURSOR
	DEALLOCATE TRG_CURSOR
		

END



GO


