ALTER TABLE CLIENTE_PARAMETROS ADD FLG_ING_VOL_PESO VARCHAR(1)
GO

INSERT INTO SYS_TABCOLUMNS VALUES('CLIENTE_PARAMETROS',	'FLG_ING_VOL_PESO',	24,	'CHAR',	'Y',	'1',	NULL,	NULL,	'1',	NULL)
GO

INSERT INTO SYS_DET_TABLA VALUES('CLIENTE_PARAMETROS','FLG_ING_VOL_PESO','Ingreso - Por Volumen / Peso','S','1','0')
GO

UPDATE CLIENTE_PARAMETROS SET FLG_ING_VOL_PESO='0'