/****** Object:  StoredProcedure [dbo].[MOB_INFORMAR_EMPAQUE_ERP]    Script Date: 11/13/2015 12:09:32 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[MOB_INFORMAR_EMPAQUE_ERP]') AND type in (N'P', N'PC'))
DROP PROCEDURE [dbo].[MOB_INFORMAR_EMPAQUE_ERP]
GO

CREATE PROCEDURE [dbo].[MOB_INFORMAR_EMPAQUE_ERP]
(
	@CLIENTE_ID		VARCHAR(15),
	@VIAJE_ID		VARCHAR(100),
	@USUARIO		VARCHAR(20)
)
AS
BEGIN

	DECLARE @DOCUMENTO_ID		AS NUMERIC(20,0)
	DECLARE @VIAJEIDANTERIOR	AS VARCHAR(100)
	DECLARE @TERMINAL			AS VARCHAR(100)
	
	SET @TERMINAL = HOST_NAME();

	--INSERTO EN LA TABLA DE PEDIDOS INFORMADOS AL ERP
	INSERT INTO INFORME_PEDIDOS_EMPAQUE_ERP
	VALUES (@CLIENTE_ID, @VIAJE_ID, GETDATE(), @USUARIO, @TERMINAL)

	--SEPARO PEDIDO DE LA OLA
	SELECT @DOCUMENTO_ID = DOCUMENTO_ID, @VIAJEIDANTERIOR = NRO_REMITO 
	FROM DOCUMENTO WHERE CLIENTE_ID = @CLIENTE_ID AND NRO_REMITO = @VIAJE_ID

	UPDATE SYS_INT_DOCUMENTO SET CODIGO_VIAJE = DOC_EXT WHERE DOC_EXT = @VIAJEIDANTERIOR

	UPDATE DOCUMENTO SET NRO_DESPACHO_IMPORTACION = NRO_REMITO WHERE DOCUMENTO_ID = @DOCUMENTO_ID

	UPDATE PICKING SET VIAJE_ID = @VIAJEIDANTERIOR WHERE DOCUMENTO_ID = @DOCUMENTO_ID

	--INFORMO DEVOLUCION
	EXEC SYS_DEV_EGRESO_EMPAQUE @CLIENTE_ID, @VIAJE_ID

	--EJECUTO SP DEL CLIENTE PARA INFORMAR AL ERP.	
	UPDATE	PICKING 
	SET		VIAJE_ID=D.NRO_REMITO,
			PALLET_FINAL=NULL,
			FECHA_UCEMPAQUETADO=GETDATE()
	FROM	PICKING P INNER JOIN DOCUMENTO D
			ON(P.DOCUMENTO_ID=D.DOCUMENTO_ID)
	WHERE	P.VIAJE_ID=@VIAJE_ID
	
	UPDATE	SYS_INT_DOCUMENTO
	SET		CODIGO_VIAJE=DOC_EXT
	WHERE	CLIENTE_ID=@CLIENTE_ID
			AND CODIGO_VIAJE=@VIAJE_ID
				
END


GO


