UPDATE SYS_HANDHELD_MENU SET DESCRIPCION='TRANSF.PALLET' WHERE CODIGO_ID=8
GO
UPDATE SYS_HANDHELD_MENU SET DESCRIPCION='TRANSF.PALLET GUIADA' WHERE CODIGO_ID=13
GO
UPDATE SYS_HANDHELD_MENU SET DESCRIPCION='TRANSF.UNIDADES' WHERE CODIGO_ID=22
GO
UPDATE SYS_HANDHELD_MENU SET DESCRIPCION='TRANSF.CONTENEDORA' WHERE CODIGO_ID=32
GO
UPDATE SYS_HANDHELD_MENU SET DESCRIPCION='TRANSF.CONTENEDORA GUIADA' WHERE CODIGO_ID=31