/****** Object:  StoredProcedure [dbo].[INFORMAR_EMPAQUE_ERP]    Script Date: 11/25/2015 17:37:29 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[INFORMAR_EMPAQUE_ERP]') AND type in (N'P', N'PC'))
DROP PROCEDURE [dbo].[INFORMAR_EMPAQUE_ERP]
GO

CREATE PROCEDURE [dbo].[INFORMAR_EMPAQUE_ERP]
(
	@CLIENTE_ID		VARCHAR(15)		OUTPUT,
	@VIAJE_ID		VARCHAR(100)	OUTPUT,
	@USUARIO		VARCHAR(20)		OUTPUT,
	@TERMINAL		VARCHAR(100)	OUTPUT
)
AS
BEGIN
	DECLARE @DOCUMENTO_ID AS NUMERIC(20,0)
	DECLARE @VIAJEIDANTERIOR AS VARCHAR(100)
	
	--INSERTO EN LA TABLA DE PEDIDOS INFORMADOS AL ERP
	INSERT INTO INFORME_PEDIDOS_EMPAQUE_ERP
	VALUES (@CLIENTE_ID, @VIAJE_ID, GETDATE(), @USUARIO, @TERMINAL)

	--SEPARO PEDIDO DE LA OLA
	SELECT @DOCUMENTO_ID = DOCUMENTO_ID, @VIAJEIDANTERIOR = NRO_REMITO FROM DOCUMENTO WHERE CLIENTE_ID = @CLIENTE_ID AND NRO_REMITO = @VIAJE_ID

	UPDATE SYS_INT_DOCUMENTO SET CODIGO_VIAJE = DOC_EXT WHERE CLIENTE_ID = @CLIENTE_ID AND DOC_EXT = @VIAJEIDANTERIOR

	UPDATE DOCUMENTO SET NRO_DESPACHO_IMPORTACION = NRO_REMITO WHERE DOCUMENTO_ID = @DOCUMENTO_ID 

	UPDATE PICKING SET VIAJE_ID = @VIAJEIDANTERIOR, FECHA_UCEMPAQUETADO=GETDATE(),USUARIO_PF=@USUARIO WHERE DOCUMENTO_ID = @DOCUMENTO_ID

	--INFORMO DEVOLUCION
	EXEC SYS_DEV_EGRESO_EMPAQUE @CLIENTE_ID,@VIAJEIDANTERIOR
	--EJECUTO SP DEL CLIENTE PARA INFORMAR AL ERP.
END


GO


