
GO

/*
Script created by Quest Change Director for SQL Server at 13/12/2012 03:54 p.m.
Please back up your database before running this script
*/

PRINT N'Synchronizing objects from V9 to CORAL'
GO

IF @@TRANCOUNT > 0 COMMIT TRANSACTION
GO

SET NUMERIC_ROUNDABORT OFF
SET ANSI_PADDING, ANSI_NULLS, ANSI_WARNINGS, CONCAT_NULL_YIELDS_NULL, ARITHABORT, QUOTED_IDENTIFIER ON
GO

IF EXISTS (SELECT * FROM tempdb..sysobjects WHERE id=OBJECT_ID('tempdb..#tmpErrors')) DROP TABLE #tmpErrors
GO

CREATE TABLE #tmpErrors (Error int)
GO

SET XACT_ABORT OFF
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
GO

BEGIN TRANSACTION
GO

DROP TRIGGER [dbo].[Tr_cliente_parametros]
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

DROP TRIGGER [dbo].[FECHA_VTO]
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

DROP TRIGGER [dbo].[send_mail]
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

DROP TRIGGER [dbo].[TRG_HIST_POS_OCUPADAS]
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

DROP TRIGGER [dbo].[TRG_HISTORICO_SALDOS_STOCK]
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

DROP TRIGGER [dbo].[IMPRESION]
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

DROP TRIGGER [dbo].[IMPRESO_1]
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

DROP TRIGGER [dbo].[Tr_nave]
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

DROP TRIGGER [dbo].[RL_ACT_STOCK_DELETE]
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

DROP TRIGGER [dbo].[RL_ACT_STOCK_INSERT]
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

DROP TRIGGER [dbo].[RL_ACT_STOCK_UPDATE]
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

DROP TRIGGER [dbo].[TR_AGRUPA_SYS_INT_DET_DOC]
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

DROP TRIGGER [dbo].[usu_permisos_trg_DEL]
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

DROP TRIGGER [dbo].[usu_permisos_trg_INS]
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

DROP TRIGGER [dbo].[sys_usuario_insert_trg]
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

ALTER TABLE [dbo].[PICKING]
DROP CONSTRAINT [DET_DOCUMENTO#PICKING]
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

ALTER TABLE [dbo].[RL_DET_DOC_TRANS_POSICION]
DROP CONSTRAINT [fk_rl_det_doc_trans_pos_doc]
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

ALTER TABLE [dbo].[HISTORICO_PRODUCTO_RL]
DROP CONSTRAINT [fk_HPRL_rl_det_doc_trans_pos_doc]
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

ALTER TABLE [dbo].[DET_DOCUMENTO_TRANSACCION]
DROP CONSTRAINT [fk_det_doc_trans_det_doc]
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

ALTER TABLE [dbo].[SYS_LOCATOR_ING]
DROP CONSTRAINT [FK_DOCUMENTO_SYS_LOCATOR]
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

ALTER TABLE [dbo].[RL_DET_DOC_TRANS_POSICION]
DROP CONSTRAINT [fk_rl_doctregr]
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

ALTER TABLE [dbo].[RL_DET_DOC_TRANS_POSICION]
DROP CONSTRAINT [fk_rl_doctrtr]
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

ALTER TABLE [dbo].[HISTORICO_PRODUCTO_RL]
DROP CONSTRAINT [fk_HPRL_rl_doctregr]
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

ALTER TABLE [dbo].[HISTORICO_PRODUCTO_RL]
DROP CONSTRAINT [fk_HPRL_rl_doctrtr]
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

ALTER TABLE [dbo].[DET_DOCUMENTO]
DROP CONSTRAINT [fk_det_doc_documento]
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

ALTER TABLE [dbo].[EVENTO_DOC_TRANS]
DROP CONSTRAINT [fk_ev_doc_trans_doc_trans]
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

ALTER TABLE [dbo].[DET_DOCUMENTO_TRANSACCION]
DROP CONSTRAINT [fk_det_doc_trans_doc_trans]
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

ALTER TABLE [dbo].[INVENTARIO]
DROP CONSTRAINT [fk_inventario_doc_trans]
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

ALTER TABLE [dbo].[SYS_AUDITORIA_CAT_MERC]
DROP CONSTRAINT [FK_SYS_AUDITORIA_CAT_MERC_NAVE_ID]
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

ALTER TABLE [dbo].[CLIENTE_PARAMETROS]
DROP CONSTRAINT [FK_CL_NAV_CROSSDOCK]
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

ALTER TABLE [dbo].[HISTORICO_POSICION_OCUPADAS]
DROP CONSTRAINT [fk_hist_posicion_ocup_nave]
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

ALTER TABLE [dbo].[POSICION]
DROP CONSTRAINT [fk_posicion_nave]
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

ALTER TABLE [dbo].[RL_CRITERIO_UBIC_PRODUCTO]
DROP CONSTRAINT [fk_rl_crit_ubic_prod_nave1]
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

ALTER TABLE [dbo].[RL_CRITERIO_UBIC_PRODUCTO]
DROP CONSTRAINT [fk_rl_crit_ubic_prod_nave2]
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

ALTER TABLE [dbo].[RL_CRITERIO_UBIC_PRODUCTO]
DROP CONSTRAINT [fk_rl_crit_ubic_prod_nave3]
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

ALTER TABLE [dbo].[DET_INVENTARIO_AJU]
DROP CONSTRAINT [fk_DET_INVENTARIO_AJU_nave]
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

ALTER TABLE [dbo].[HISTORICO_POSICION]
DROP CONSTRAINT [fk_hist_pos_nave]
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

ALTER TABLE [dbo].[RL_PRODUCTO_PICKING]
DROP CONSTRAINT [fk_rl_producto_picking_nave]
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

ALTER TABLE [dbo].[RL_PRODUCTO_NAVEPOS_PICKING]
DROP CONSTRAINT [fk_rl_prod_navepos_pick_nave]
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

ALTER TABLE [dbo].[DET_INVENTARIO]
DROP CONSTRAINT [fk_det_inventario_nave]
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

ALTER TABLE [dbo].[DET_CONTEO]
DROP CONSTRAINT [fk_det_conteo_nave]
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

ALTER TABLE [dbo].[RL_DET_DOC_TRANS_POSICION]
DROP CONSTRAINT [fk_rl_det_doc_trans_pos_nave]
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

ALTER TABLE [dbo].[RL_DET_DOC_TRANS_POSICION]
DROP CONSTRAINT [fk_rl_det_doc_trans_pos_nave2]
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

ALTER TABLE [dbo].[RL_TRANSACCION_ESTACION]
DROP CONSTRAINT [fk_rl_trans_nave_default]
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

ALTER TABLE [dbo].[GM_SUCURSAL_NAVE]
DROP CONSTRAINT [FK_GM_SUCURSAL_NAVE_NAVE]
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

ALTER TABLE [dbo].[HISTORICO_PRODUCTO_RL]
DROP CONSTRAINT [fk_HPRL_rl_det_doc_trans_pos_nave]
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

ALTER TABLE [dbo].[HISTORICO_PRODUCTO_RL]
DROP CONSTRAINT [fk_HPRL_rl_det_doc_trans_pos_nave2]
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

ALTER TABLE [dbo].[RL_NAVE_TIPO_UC]
DROP CONSTRAINT [rl_nave_tipo_uc_nave]
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

ALTER TABLE [dbo].[RL_VEHICULO_POSICION]
DROP CONSTRAINT [FK_NAVE_RL]
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

ALTER TABLE [dbo].[rl_doc_tr_egreso]
DROP CONSTRAINT [fk_rl_doc_tr_egr_nave1]
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

ALTER TABLE [dbo].[rl_doc_tr_egreso]
DROP CONSTRAINT [fk_rl_doc_tr_egr_nave2]
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

ALTER TABLE [dbo].[calle_nave]
DROP CONSTRAINT [fk_calle_nave_nave]
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

ALTER TABLE [dbo].[COLUMNA_NAVE]
DROP CONSTRAINT [fk_columna_nave_nave]
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

ALTER TABLE [dbo].[RL_PRODUCTO_POSICION_PERMITIDA]
DROP CONSTRAINT [fk_rlppp_nave]
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

ALTER TABLE [dbo].[RL_USUARIO_NAVE]
DROP CONSTRAINT [fk_rl_nave]
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

ALTER TABLE [dbo].[NIVEL_NAVE]
DROP CONSTRAINT [fk_nivel_nave_nave]
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

ALTER TABLE [dbo].[HISTORICO_POS_OCUPADAS]
DROP CONSTRAINT [fk_hist_pos_ocup_nave]
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

ALTER TABLE [dbo].[SYS_AUDITORIA_CAT_MERC]
DROP CONSTRAINT [FK_SYS_AUDITORIA_CAT_MERC_POSICION_ID]
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

ALTER TABLE [dbo].[RL_POSICION_PROHIBIDA_CLIENTE]
DROP CONSTRAINT [fk_rl_pos_prohib_pos]
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

ALTER TABLE [dbo].[HISTORICO_POSICION_OCUPADAS]
DROP CONSTRAINT [fk_historico_posicion_ID]
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

ALTER TABLE [dbo].[DET_INVENTARIO_AJU]
DROP CONSTRAINT [fk_DET_INVENTARIO_AJU_posicion]
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

ALTER TABLE [dbo].[HISTORICO_POSICION]
DROP CONSTRAINT [fk_hist_pos_posicion]
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

ALTER TABLE [dbo].[RL_PRODUCTO_PICKING]
DROP CONSTRAINT [fk_rl_prod_picking_posicion]
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

ALTER TABLE [dbo].[RL_PRODUCTO_NAVEPOS_PICKING]
DROP CONSTRAINT [fk_rl_prod_navepos_pick_pos]
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

ALTER TABLE [dbo].[HISTORICO_PRODUCTO]
DROP CONSTRAINT [fk_hist_prod_posicion]
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

ALTER TABLE [dbo].[DET_INVENTARIO]
DROP CONSTRAINT [fk_det_invent_posicion]
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

ALTER TABLE [dbo].[DET_CONTEO]
DROP CONSTRAINT [fk_det_conteo_posicion]
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

ALTER TABLE [dbo].[RL_DET_DOC_TRANS_POSICION]
DROP CONSTRAINT [fk_rl_det_doctr_posicion1]
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

ALTER TABLE [dbo].[RL_DET_DOC_TRANS_POSICION]
DROP CONSTRAINT [fk_rl_det_doctr_posicion2]
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

ALTER TABLE [dbo].[HISTORICO_PRODUCTO_RL]
DROP CONSTRAINT [fk_HPRL_rl_det_doctr_posicion1]
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

ALTER TABLE [dbo].[HISTORICO_PRODUCTO_RL]
DROP CONSTRAINT [fk_HPRL_rl_det_doctr_posicion2]
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

ALTER TABLE [dbo].[SYS_LOCATOR_ING]
DROP CONSTRAINT [FK_POSICION_SYS_LOCATOR_ING]
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

ALTER TABLE [dbo].[RL_VEHICULO_POSICION]
DROP CONSTRAINT [FK_POSICION_RL]
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

ALTER TABLE [dbo].[rl_doc_tr_egreso]
DROP CONSTRAINT [fk_rl_doc_tr_egr_posicion1]
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

ALTER TABLE [dbo].[rl_doc_tr_egreso]
DROP CONSTRAINT [fk_rl_doc_tr_egr_posicion2]
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

ALTER TABLE [dbo].[RL_PRODUCTO_POSICION_PERMITIDA]
DROP CONSTRAINT [fk_rlppp_posicion]
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

ALTER TABLE [dbo].[UNIDAD_CONTENEDORA]
DROP CONSTRAINT [fk_uc_posicion]
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

ALTER TABLE [dbo].[SYS_INT_DET_DOCUMENTO]
DROP CONSTRAINT [FK_SYSINTDET#SYSINTDETDOC]
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

ALTER TABLE [dbo].[SYS_INT_DET_DOCUMENTO]
DROP CONSTRAINT [FK_SYSINTDET#SYSINTDETDOC_MAXI]
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

ALTER TABLE [dbo].[SYS_USU_PERMISOS]
DROP CONSTRAINT [fk_sys_permisos]
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

ALTER TABLE [dbo].[SYS_AUDITORIA_CAT_MERC]
DROP CONSTRAINT [FK_SYS_AUDITORIA_CAT_MERC_USUARIO_ID]
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

ALTER TABLE [dbo].[SYS_AUDITORIA]
DROP CONSTRAINT [fk_sys_auditoria_sys_usu]
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

ALTER TABLE [dbo].[LOCKEO_POSICION]
DROP CONSTRAINT [FK_LP_SYS_USUARIO]
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

ALTER TABLE [dbo].[SYS_PERMISOS_HH]
DROP CONSTRAINT [FK_SYS_PERMISOS_HH_SYS_USUARIO]
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

ALTER TABLE [dbo].[TRACE_DOCUMENTOS]
DROP CONSTRAINT [fk_trace_doc_sys_uusuarios]
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

ALTER TABLE [dbo].[HISTORICO_POSICION]
DROP CONSTRAINT [pk_hist_pos_usuario]
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

ALTER TABLE [dbo].[HISTORICO_PRODUCTO]
DROP CONSTRAINT [fk_hist_usuario]
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

ALTER TABLE [dbo].[DOCUMENTO_TRANSACCION]
DROP CONSTRAINT [pk_doc_trans_usuario]
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

ALTER TABLE [dbo].[RL_INVENTARIO_USUARIO]
DROP CONSTRAINT [fk_rl_usuario_inv]
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

ALTER TABLE [dbo].[RL_USUARIO_VEHICULO]
DROP CONSTRAINT [FK_SU_UV]
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

ALTER TABLE [dbo].[SYS_PERFIL_USUARIO]
DROP CONSTRAINT [fk_sys_perfil_usu_usu]
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

ALTER TABLE [dbo].[SYS_USU_PERMISOS]
DROP CONSTRAINT [fk_sys_usuario]
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

ALTER TABLE [dbo].[RL_USUARIO_NAVE]
DROP CONSTRAINT [fk_rl_usuario]
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

ALTER TABLE [dbo].[RL_DET_CONTEO_USUARIO]
DROP CONSTRAINT [fk_rl_det_cont_user_user]
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

DROP STATISTICS [dbo].[APF_BULTOS_POR_PALLET].[_dta_stat_610869293_1]
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

DROP STATISTICS [dbo].[APF_BULTOS_POR_PALLET].[_dta_stat_610869293_3_5_9_8]
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

DROP STATISTICS [dbo].[APF_BULTOS_POR_PALLET].[_dta_stat_610869293_6_8_3_5_9]
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

DROP STATISTICS [dbo].[APF_BULTOS_POR_PALLET].[_dta_stat_610869293_8_5_2_3_4_7]
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

DROP STATISTICS [dbo].[DET_DOCUMENTO].[_dta_stat_2146106686_1_2_3_4]
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

DROP STATISTICS [dbo].[DET_DOCUMENTO].[_dta_stat_2146106686_1_2_3_4_29_6_10_12_14]
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

DROP STATISTICS [dbo].[DET_DOCUMENTO].[_dta_stat_2146106686_1_2_6_10_12_14_15_30_31_13_17_18_19_20_22_16]
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

DROP STATISTICS [dbo].[DET_DOCUMENTO].[_dta_stat_2146106686_2_29]
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

DROP STATISTICS [dbo].[DET_DOCUMENTO].[_dta_stat_2146106686_3_4_1]
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

DROP STATISTICS [dbo].[DET_DOCUMENTO].[_dta_stat_2146106686_3_4_29]
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

DROP STATISTICS [dbo].[DET_DOCUMENTO].[_dta_stat_2146106686_3_4_29_6_10_12_14]
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

DROP STATISTICS [dbo].[DET_DOCUMENTO].[_dta_stat_2146106686_3_4_6_10_12_14_15_29_30_31_13_17_18_19_20_22]
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

DROP STATISTICS [dbo].[DET_DOCUMENTO].[_dta_stat_2146106686_35_29_1_2]
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

DROP STATISTICS [dbo].[DET_DOCUMENTO].[_dta_stat_2146106686_4_1_3_6_10_12_14_15_29_30_31_13_17_18_19_20]
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

DROP STATISTICS [dbo].[DET_DOCUMENTO].[_dta_stat_2146106686_4_29]
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

DROP STATISTICS [dbo].[DET_DOCUMENTO].[_dta_stat_2146106686_4_3_2_1_6_10_12_14_15_29_30_31_13_17_18_19]
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

DROP STATISTICS [dbo].[DET_DOCUMENTO].[_dta_stat_2146106686_4_6_10_12_14_15_29_30_31_13_17_18_19_20_22_16]
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

DROP STATISTICS [dbo].[DET_DOCUMENTO].[_dta_stat_2146106686_4_6_10_12_14_15_29_30_31_13_17_18_19_20_22_23]
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

DROP STATISTICS [dbo].[DET_DOCUMENTO].[_dta_stat_2146106686_6_10_12_14_15_29_30_31_13_17_18_19_20_22_16_27]
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

DROP STATISTICS [dbo].[DET_DOCUMENTO].[_dta_stat_2146106686_6_10_12_14_15_29_30_31_13_17_18_19_20_22_23_24]
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

DROP STATISTICS [dbo].[DET_DOCUMENTO].[_dta_stat_2146106686_6_10_12_14_15_30_31_13_17_18_19_20_22_16_27_28]
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

DROP STATISTICS [dbo].[DET_DOCUMENTO_TRANSACCION].[_dta_stat_117575457_3_4_1]
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

DROP STATISTICS [dbo].[DOCUMENTO].[_dta_stat_1108198998_1_23]
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

DROP STATISTICS [dbo].[DOCUMENTO].[_dta_stat_1108198998_10_2_1_23_4]
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

DROP STATISTICS [dbo].[DOCUMENTO].[_dta_stat_1108198998_10_2_1_8_23_4]
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

DROP STATISTICS [dbo].[DOCUMENTO].[_dta_stat_1108198998_2_1]
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

DROP STATISTICS [dbo].[DOCUMENTO].[_dta_stat_1108198998_2_11_1]
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

DROP STATISTICS [dbo].[DOCUMENTO].[_dta_stat_1108198998_23_4_1_10]
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

DROP STATISTICS [dbo].[DOCUMENTO].[_dta_stat_1108198998_23_4_10_2]
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

DROP STATISTICS [dbo].[DOCUMENTO].[_dta_stat_1108198998_4_10_2_1]
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

DROP STATISTICS [dbo].[DOCUMENTO].[_dta_stat_1108198998_8_23_4]
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

DROP STATISTICS [dbo].[DOCUMENTO_TRANSACCION].[_dta_stat_1794105432_11_1_6]
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

DROP STATISTICS [dbo].[DOCUMENTO_TRANSACCION].[_dta_stat_1794105432_6_11]
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

DROP STATISTICS [dbo].[POSICION].[_dta_stat_1589580701_1_3_2]
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

DROP STATISTICS [dbo].[POSICION].[_dta_stat_1589580701_1_6_3_2_26]
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

DROP STATISTICS [dbo].[POSICION].[_dta_stat_1589580701_2_6_1]
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

DROP STATISTICS [dbo].[POSICION].[_dta_stat_1589580701_23_6]
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

DROP STATISTICS [dbo].[POSICION].[_dta_stat_1589580701_3_2]
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

DROP STATISTICS [dbo].[POSICION].[_dta_stat_1589580701_3_6]
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

DROP STATISTICS [dbo].[POSICION].[_dta_stat_1589580701_4_1_2_3_5]
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

DROP STATISTICS [dbo].[POSICION].[_dta_stat_1589580701_5_1_2_3]
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

DROP STATISTICS [dbo].[PRIORIDAD_VIAJE].[_dta_stat_1485964370_1_2]
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

DROP STATISTICS [dbo].[RL_DET_DOC_TRANS_POSICION].[_dta_stat_78623323_1_10_11_4_2_3_5_15_16_19_20]
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

DROP STATISTICS [dbo].[RL_DET_DOC_TRANS_POSICION].[_dta_stat_78623323_1_14_19_20_22]
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

DROP STATISTICS [dbo].[RL_DET_DOC_TRANS_POSICION].[_dta_stat_78623323_1_15_16_10_4_11_2_3]
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

DROP STATISTICS [dbo].[RL_DET_DOC_TRANS_POSICION].[_dta_stat_78623323_1_19_20_10_4_11_2_3_5_15]
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

DROP STATISTICS [dbo].[RL_DET_DOC_TRANS_POSICION].[_dta_stat_78623323_1_19_20_22]
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

DROP STATISTICS [dbo].[RL_DET_DOC_TRANS_POSICION].[_dta_stat_78623323_1_2]
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

DROP STATISTICS [dbo].[RL_DET_DOC_TRANS_POSICION].[_dta_stat_78623323_10_11]
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

DROP STATISTICS [dbo].[RL_DET_DOC_TRANS_POSICION].[_dta_stat_78623323_10_4_11_1_19]
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

DROP STATISTICS [dbo].[RL_DET_DOC_TRANS_POSICION].[_dta_stat_78623323_11_1_2]
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

DROP STATISTICS [dbo].[RL_DET_DOC_TRANS_POSICION].[_dta_stat_78623323_11_10_4_2]
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

DROP STATISTICS [dbo].[RL_DET_DOC_TRANS_POSICION].[_dta_stat_78623323_11_14]
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

DROP STATISTICS [dbo].[RL_DET_DOC_TRANS_POSICION].[_dta_stat_78623323_11_2_3_5_15_16_1_10]
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

DROP STATISTICS [dbo].[RL_DET_DOC_TRANS_POSICION].[_dta_stat_78623323_14_1_11_2_3_19_20_5_15_16_22]
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

DROP STATISTICS [dbo].[RL_DET_DOC_TRANS_POSICION].[_dta_stat_78623323_14_1_2]
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

DROP STATISTICS [dbo].[RL_DET_DOC_TRANS_POSICION].[_dta_stat_78623323_14_20]
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

DROP STATISTICS [dbo].[RL_DET_DOC_TRANS_POSICION].[_dta_stat_78623323_15_1_10_4_11_2_3]
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

DROP STATISTICS [dbo].[RL_DET_DOC_TRANS_POSICION].[_dta_stat_78623323_15_16_14_2_1_3_19_20_11]
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

DROP STATISTICS [dbo].[RL_DET_DOC_TRANS_POSICION].[_dta_stat_78623323_15_16_5_11_3_20_19]
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

DROP STATISTICS [dbo].[RL_DET_DOC_TRANS_POSICION].[_dta_stat_78623323_19_20_14_1_2]
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

DROP STATISTICS [dbo].[RL_DET_DOC_TRANS_POSICION].[_dta_stat_78623323_2_1_3_19_20_11_5_14_22_15]
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

DROP STATISTICS [dbo].[RL_DET_DOC_TRANS_POSICION].[_dta_stat_78623323_2_1_3_19_20_11_5_15_16]
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

DROP STATISTICS [dbo].[RL_DET_DOC_TRANS_POSICION].[_dta_stat_78623323_2_14_5_11_3_20]
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

DROP STATISTICS [dbo].[RL_DET_DOC_TRANS_POSICION].[_dta_stat_78623323_2_3_1_19_20_5_11_22]
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

DROP STATISTICS [dbo].[RL_DET_DOC_TRANS_POSICION].[_dta_stat_78623323_2_3_1_5_11_14_19]
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

DROP STATISTICS [dbo].[RL_DET_DOC_TRANS_POSICION].[_dta_stat_78623323_2_3_10_4_11_5_15_16]
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

DROP STATISTICS [dbo].[RL_DET_DOC_TRANS_POSICION].[_dta_stat_78623323_2_3_5]
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

DROP STATISTICS [dbo].[RL_DET_DOC_TRANS_POSICION].[_dta_stat_78623323_2_3_6_5]
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

DROP STATISTICS [dbo].[RL_DET_DOC_TRANS_POSICION].[_dta_stat_78623323_20_19_14_5_11]
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

DROP STATISTICS [dbo].[RL_DET_DOC_TRANS_POSICION].[_dta_stat_78623323_22_20_11_14_2_15_16]
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

DROP STATISTICS [dbo].[RL_DET_DOC_TRANS_POSICION].[_dta_stat_78623323_22_20_11_14_5_2_3_15_16]
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

DROP STATISTICS [dbo].[RL_DET_DOC_TRANS_POSICION].[_dta_stat_78623323_22_20_11_5_2_3]
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

DROP STATISTICS [dbo].[RL_DET_DOC_TRANS_POSICION].[_dta_stat_78623323_3_14_5_11_20_19_2_15_16_22]
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

DROP STATISTICS [dbo].[RL_DET_DOC_TRANS_POSICION].[_dta_stat_78623323_4_1_10]
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

DROP STATISTICS [dbo].[RL_DET_DOC_TRANS_POSICION].[_dta_stat_78623323_4_10]
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

DROP STATISTICS [dbo].[RL_DET_DOC_TRANS_POSICION].[_dta_stat_78623323_5_1_2_3]
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

DROP STATISTICS [dbo].[RL_DET_DOC_TRANS_POSICION].[_dta_stat_78623323_5_10_4_11_2]
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

DROP STATISTICS [dbo].[RL_DET_DOC_TRANS_POSICION].[_dta_stat_78623323_5_11_3_20_19_2_14_22_15]
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

DROP STATISTICS [dbo].[RL_DET_DOC_TRANS_POSICION].[_dta_stat_78623323_5_11_3_20_19_2_15_16]
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

DROP STATISTICS [dbo].[RL_DET_DOC_TRANS_POSICION].[_dta_stat_78623323_5_14_11]
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

DROP STATISTICS [dbo].[RL_DET_DOC_TRANS_POSICION].[_dta_stat_78623323_5_2_3_1_14_19]
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

DROP STATISTICS [dbo].[RL_DET_DOC_TRANS_POSICION].[_dta_stat_78623323_6_2]
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

DROP STATISTICS [dbo].[RL_DET_DOC_TRANS_POSICION].[_dta_stat_78623323_6_5_2]
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

DROP STATISTICS [dbo].[RL_PRODUCTO_POSICION_PERMITIDA].[_dta_stat_82099333_3_1_2]
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

DROP STATISTICS [dbo].[RL_VEHICULO_POSICION].[_dta_stat_1495728431_3_2]
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

DROP STATISTICS [dbo].[RL_VEHICULO_POSICION].[_dta_stat_1495728431_3_4]
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

DROP STATISTICS [dbo].[RL_VIAJE_USUARIO].[_dta_stat_1581964712_1_2]
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

DROP STATISTICS [dbo].[SYS_INT_DET_DOCUMENTO].[_dta_stat_1460916276_1_31_4_3]
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

DROP STATISTICS [dbo].[SYS_INT_DET_DOCUMENTO].[_dta_stat_1460916276_31_3_4]
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

DROP STATISTICS [dbo].[SYS_INT_DOCUMENTO].[_dta_stat_1508916447_17_2_18]
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

DROP STATISTICS [dbo].[SYS_INT_DOCUMENTO].[_dta_stat_1508916447_18_1_7_17]
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

DROP STATISTICS [dbo].[SYS_INT_DOCUMENTO].[_dta_stat_1508916447_18_17_2_1]
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

DROP STATISTICS [dbo].[SYS_INT_DOCUMENTO].[_dta_stat_1508916447_18_2_7]
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

DROP STATISTICS [dbo].[SYS_INT_DOCUMENTO].[_dta_stat_1508916447_18_7_17_2]
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

DROP STATISTICS [dbo].[SYS_INT_DOCUMENTO].[_dta_stat_1508916447_2_18]
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

DROP STATISTICS [dbo].[SYS_INT_DOCUMENTO].[_dta_stat_1508916447_7_2]
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

ALTER TABLE [dbo].[NAVE]
 ADD [C_MOSTRADOR] char(1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

ALTER TABLE [dbo].[SYS_DEV_DET_DOCUMENTO]
 ADD CONSTRAINT [pk_sys_DEV_det_documento] PRIMARY KEY ([CLIENTE_ID] ASC, [DOC_EXT] ASC, [NRO_LINEA] ASC) ON [PRIMARY]
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

ALTER TABLE [dbo].[SYS_DEV_DOCUMENTO]
 ADD CONSTRAINT [pk_sys_DEV_documento] PRIMARY KEY ([CLIENTE_ID] ASC, [DOC_EXT] ASC) ON [PRIMARY]
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

ALTER TABLE [dbo].[PICKING]
 ADD CONSTRAINT [DET_DOCUMENTO#PICKING] FOREIGN KEY ([DOCUMENTO_ID], [NRO_LINEA]) REFERENCES [dbo].[DET_DOCUMENTO] ([DOCUMENTO_ID], [NRO_LINEA]) 
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

ALTER TABLE [dbo].[RL_DET_DOC_TRANS_POSICION]
 ADD CONSTRAINT [fk_rl_det_doc_trans_pos_doc] FOREIGN KEY ([DOCUMENTO_ID], [NRO_LINEA]) REFERENCES [dbo].[DET_DOCUMENTO] ([DOCUMENTO_ID], [NRO_LINEA]) 
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

ALTER TABLE [dbo].[HISTORICO_PRODUCTO_RL]
 ADD CONSTRAINT [fk_HPRL_rl_det_doc_trans_pos_doc] FOREIGN KEY ([DOCUMENTO_ID], [NRO_LINEA]) REFERENCES [dbo].[DET_DOCUMENTO] ([DOCUMENTO_ID], [NRO_LINEA]) 
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

ALTER TABLE [dbo].[DET_DOCUMENTO_TRANSACCION]
 ADD CONSTRAINT [fk_det_doc_trans_det_doc] FOREIGN KEY ([DOCUMENTO_ID], [NRO_LINEA_DOC]) REFERENCES [dbo].[DET_DOCUMENTO] ([DOCUMENTO_ID], [NRO_LINEA]) 
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

ALTER TABLE [dbo].[SYS_LOCATOR_ING]
 ADD CONSTRAINT [FK_DOCUMENTO_SYS_LOCATOR] FOREIGN KEY ([DOCUMENTO_ID], [NRO_LINEA]) REFERENCES [dbo].[DET_DOCUMENTO] ([DOCUMENTO_ID], [NRO_LINEA]) 
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

ALTER TABLE [dbo].[RL_DET_DOC_TRANS_POSICION]
 ADD CONSTRAINT [fk_rl_doctregr] FOREIGN KEY ([DOC_TRANS_ID_EGR], [NRO_LINEA_TRANS_EGR]) REFERENCES [dbo].[DET_DOCUMENTO_TRANSACCION] ([DOC_TRANS_ID], [NRO_LINEA_TRANS]) 
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

ALTER TABLE [dbo].[RL_DET_DOC_TRANS_POSICION]
 ADD CONSTRAINT [fk_rl_doctrtr] FOREIGN KEY ([DOC_TRANS_ID_TR], [NRO_LINEA_TRANS_TR]) REFERENCES [dbo].[DET_DOCUMENTO_TRANSACCION] ([DOC_TRANS_ID], [NRO_LINEA_TRANS]) 
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

ALTER TABLE [dbo].[HISTORICO_PRODUCTO_RL]
 ADD CONSTRAINT [fk_HPRL_rl_doctregr] FOREIGN KEY ([DOC_TRANS_ID_EGR], [NRO_LINEA_TRANS_EGR]) REFERENCES [dbo].[DET_DOCUMENTO_TRANSACCION] ([DOC_TRANS_ID], [NRO_LINEA_TRANS]) 
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

ALTER TABLE [dbo].[HISTORICO_PRODUCTO_RL]
 ADD CONSTRAINT [fk_HPRL_rl_doctrtr] FOREIGN KEY ([DOC_TRANS_ID_TR], [NRO_LINEA_TRANS_TR]) REFERENCES [dbo].[DET_DOCUMENTO_TRANSACCION] ([DOC_TRANS_ID], [NRO_LINEA_TRANS]) 
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

ALTER TABLE [dbo].[DET_DOCUMENTO]
 ADD CONSTRAINT [fk_det_doc_documento] FOREIGN KEY ([DOCUMENTO_ID]) REFERENCES [dbo].[DOCUMENTO] ([DOCUMENTO_ID]) 
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

ALTER TABLE [dbo].[EVENTO_DOC_TRANS]
 ADD CONSTRAINT [fk_ev_doc_trans_doc_trans] FOREIGN KEY ([DOC_TRANS_ID]) REFERENCES [dbo].[DOCUMENTO_TRANSACCION] ([DOC_TRANS_ID]) 
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

ALTER TABLE [dbo].[DET_DOCUMENTO_TRANSACCION]
 ADD CONSTRAINT [fk_det_doc_trans_doc_trans] FOREIGN KEY ([DOC_TRANS_ID]) REFERENCES [dbo].[DOCUMENTO_TRANSACCION] ([DOC_TRANS_ID]) 
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

ALTER TABLE [dbo].[INVENTARIO]
 ADD CONSTRAINT [fk_inventario_doc_trans] FOREIGN KEY ([DOC_TRANS_ID]) REFERENCES [dbo].[DOCUMENTO_TRANSACCION] ([DOC_TRANS_ID]) 
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

ALTER TABLE [dbo].[SYS_AUDITORIA_CAT_MERC]
 ADD CONSTRAINT [FK_SYS_AUDITORIA_CAT_MERC_NAVE_ID] FOREIGN KEY ([NAVE_ID]) REFERENCES [dbo].[NAVE] ([NAVE_ID]) 
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

ALTER TABLE [dbo].[CLIENTE_PARAMETROS]
 ADD CONSTRAINT [FK_CL_NAV_CROSSDOCK] FOREIGN KEY ([NAVE_ID_CROSSDOCK]) REFERENCES [dbo].[NAVE] ([NAVE_ID]) 
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

ALTER TABLE [dbo].[HISTORICO_POSICION_OCUPADAS]
 ADD CONSTRAINT [fk_hist_posicion_ocup_nave] FOREIGN KEY ([NAVE_ID]) REFERENCES [dbo].[NAVE] ([NAVE_ID]) 
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

ALTER TABLE [dbo].[POSICION]
 ADD CONSTRAINT [fk_posicion_nave] FOREIGN KEY ([NAVE_ID]) REFERENCES [dbo].[NAVE] ([NAVE_ID]) 
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

ALTER TABLE [dbo].[RL_CRITERIO_UBIC_PRODUCTO]
 ADD CONSTRAINT [fk_rl_crit_ubic_prod_nave1] FOREIGN KEY ([NAVE_1]) REFERENCES [dbo].[NAVE] ([NAVE_ID]) 
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

ALTER TABLE [dbo].[RL_CRITERIO_UBIC_PRODUCTO]
 ADD CONSTRAINT [fk_rl_crit_ubic_prod_nave2] FOREIGN KEY ([NAVE_2]) REFERENCES [dbo].[NAVE] ([NAVE_ID]) 
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

ALTER TABLE [dbo].[RL_CRITERIO_UBIC_PRODUCTO]
 ADD CONSTRAINT [fk_rl_crit_ubic_prod_nave3] FOREIGN KEY ([NAVE_3]) REFERENCES [dbo].[NAVE] ([NAVE_ID]) 
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

ALTER TABLE [dbo].[DET_INVENTARIO_AJU]
 ADD CONSTRAINT [fk_DET_INVENTARIO_AJU_nave] FOREIGN KEY ([NAVE_ID]) REFERENCES [dbo].[NAVE] ([NAVE_ID]) 
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

ALTER TABLE [dbo].[HISTORICO_POSICION]
 ADD CONSTRAINT [fk_hist_pos_nave] FOREIGN KEY ([NAVE_ID]) REFERENCES [dbo].[NAVE] ([NAVE_ID]) 
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

ALTER TABLE [dbo].[RL_PRODUCTO_PICKING]
 ADD CONSTRAINT [fk_rl_producto_picking_nave] FOREIGN KEY ([NAVE_ID]) REFERENCES [dbo].[NAVE] ([NAVE_ID]) 
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

ALTER TABLE [dbo].[RL_PRODUCTO_NAVEPOS_PICKING]
 ADD CONSTRAINT [fk_rl_prod_navepos_pick_nave] FOREIGN KEY ([NAVE_ID]) REFERENCES [dbo].[NAVE] ([NAVE_ID]) 
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

ALTER TABLE [dbo].[DET_INVENTARIO]
 ADD CONSTRAINT [fk_det_inventario_nave] FOREIGN KEY ([NAVE_ID]) REFERENCES [dbo].[NAVE] ([NAVE_ID]) 
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

ALTER TABLE [dbo].[DET_CONTEO]
 ADD CONSTRAINT [fk_det_conteo_nave] FOREIGN KEY ([NAVE_ID]) REFERENCES [dbo].[NAVE] ([NAVE_ID]) 
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

ALTER TABLE [dbo].[RL_DET_DOC_TRANS_POSICION]
 ADD CONSTRAINT [fk_rl_det_doc_trans_pos_nave] FOREIGN KEY ([NAVE_ANTERIOR]) REFERENCES [dbo].[NAVE] ([NAVE_ID]) 
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

ALTER TABLE [dbo].[RL_DET_DOC_TRANS_POSICION]
 ADD CONSTRAINT [fk_rl_det_doc_trans_pos_nave2] FOREIGN KEY ([NAVE_ACTUAL]) REFERENCES [dbo].[NAVE] ([NAVE_ID]) 
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

ALTER TABLE [dbo].[RL_TRANSACCION_ESTACION]
 ADD CONSTRAINT [fk_rl_trans_nave_default] FOREIGN KEY ([NAVE_DEFAULT]) REFERENCES [dbo].[NAVE] ([NAVE_ID]) 
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

ALTER TABLE [dbo].[GM_SUCURSAL_NAVE]
 ADD CONSTRAINT [FK_GM_SUCURSAL_NAVE_NAVE] FOREIGN KEY ([NAVE_ID]) REFERENCES [dbo].[NAVE] ([NAVE_ID]) 
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

ALTER TABLE [dbo].[HISTORICO_PRODUCTO_RL]
 ADD CONSTRAINT [fk_HPRL_rl_det_doc_trans_pos_nave] FOREIGN KEY ([NAVE_ANTERIOR]) REFERENCES [dbo].[NAVE] ([NAVE_ID]) 
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

ALTER TABLE [dbo].[HISTORICO_PRODUCTO_RL]
 ADD CONSTRAINT [fk_HPRL_rl_det_doc_trans_pos_nave2] FOREIGN KEY ([NAVE_ACTUAL]) REFERENCES [dbo].[NAVE] ([NAVE_ID]) 
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

ALTER TABLE [dbo].[RL_NAVE_TIPO_UC]
 ADD CONSTRAINT [rl_nave_tipo_uc_nave] FOREIGN KEY ([NAVE_ID]) REFERENCES [dbo].[NAVE] ([NAVE_ID]) 
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

ALTER TABLE [dbo].[RL_VEHICULO_POSICION]
 ADD CONSTRAINT [FK_NAVE_RL] FOREIGN KEY ([NAVE_ID]) REFERENCES [dbo].[NAVE] ([NAVE_ID]) 
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

ALTER TABLE [dbo].[rl_doc_tr_egreso]
 ADD CONSTRAINT [fk_rl_doc_tr_egr_nave1] FOREIGN KEY ([nave_origen]) REFERENCES [dbo].[NAVE] ([NAVE_ID]) 
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

ALTER TABLE [dbo].[rl_doc_tr_egreso]
 ADD CONSTRAINT [fk_rl_doc_tr_egr_nave2] FOREIGN KEY ([nave_destino]) REFERENCES [dbo].[NAVE] ([NAVE_ID]) 
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

ALTER TABLE [dbo].[calle_nave]
 ADD CONSTRAINT [fk_calle_nave_nave] FOREIGN KEY ([nave_id]) REFERENCES [dbo].[NAVE] ([NAVE_ID]) 
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

ALTER TABLE [dbo].[COLUMNA_NAVE]
 ADD CONSTRAINT [fk_columna_nave_nave] FOREIGN KEY ([NAVE_ID]) REFERENCES [dbo].[NAVE] ([NAVE_ID]) 
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

ALTER TABLE [dbo].[RL_PRODUCTO_POSICION_PERMITIDA]
 ADD CONSTRAINT [fk_rlppp_nave] FOREIGN KEY ([NAVE_ID]) REFERENCES [dbo].[NAVE] ([NAVE_ID]) 
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

ALTER TABLE [dbo].[RL_USUARIO_NAVE]
 ADD CONSTRAINT [fk_rl_nave] FOREIGN KEY ([NAVE_ID]) REFERENCES [dbo].[NAVE] ([NAVE_ID]) 
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

ALTER TABLE [dbo].[NIVEL_NAVE]
 ADD CONSTRAINT [fk_nivel_nave_nave] FOREIGN KEY ([NAVE_ID]) REFERENCES [dbo].[NAVE] ([NAVE_ID]) 
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

ALTER TABLE [dbo].[HISTORICO_POS_OCUPADAS]
 ADD CONSTRAINT [fk_hist_pos_ocup_nave] FOREIGN KEY ([NAVE_ID]) REFERENCES [dbo].[NAVE] ([NAVE_ID]) 
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

ALTER TABLE [dbo].[SYS_AUDITORIA_CAT_MERC]
 ADD CONSTRAINT [FK_SYS_AUDITORIA_CAT_MERC_POSICION_ID] FOREIGN KEY ([POSICION_ID]) REFERENCES [dbo].[POSICION] ([POSICION_ID]) 
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

ALTER TABLE [dbo].[RL_POSICION_PROHIBIDA_CLIENTE]
 ADD CONSTRAINT [fk_rl_pos_prohib_pos] FOREIGN KEY ([POSICION_ID]) REFERENCES [dbo].[POSICION] ([POSICION_ID]) 
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

ALTER TABLE [dbo].[HISTORICO_POSICION_OCUPADAS]
 ADD CONSTRAINT [fk_historico_posicion_ID] FOREIGN KEY ([POSICION_ID]) REFERENCES [dbo].[POSICION] ([POSICION_ID]) 
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

ALTER TABLE [dbo].[DET_INVENTARIO_AJU]
 ADD CONSTRAINT [fk_DET_INVENTARIO_AJU_posicion] FOREIGN KEY ([POSICION_ID]) REFERENCES [dbo].[POSICION] ([POSICION_ID]) 
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

ALTER TABLE [dbo].[HISTORICO_POSICION]
 ADD CONSTRAINT [fk_hist_pos_posicion] FOREIGN KEY ([POSICION_ID]) REFERENCES [dbo].[POSICION] ([POSICION_ID]) 
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

ALTER TABLE [dbo].[RL_PRODUCTO_PICKING]
 ADD CONSTRAINT [fk_rl_prod_picking_posicion] FOREIGN KEY ([POSICION_ID]) REFERENCES [dbo].[POSICION] ([POSICION_ID]) 
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

ALTER TABLE [dbo].[RL_PRODUCTO_NAVEPOS_PICKING]
 ADD CONSTRAINT [fk_rl_prod_navepos_pick_pos] FOREIGN KEY ([POSICION_ID]) REFERENCES [dbo].[POSICION] ([POSICION_ID]) 
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

ALTER TABLE [dbo].[HISTORICO_PRODUCTO]
 ADD CONSTRAINT [fk_hist_prod_posicion] FOREIGN KEY ([POSICION_ID]) REFERENCES [dbo].[POSICION] ([POSICION_ID]) 
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

ALTER TABLE [dbo].[DET_INVENTARIO]
 ADD CONSTRAINT [fk_det_invent_posicion] FOREIGN KEY ([POSICION_ID]) REFERENCES [dbo].[POSICION] ([POSICION_ID]) 
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

ALTER TABLE [dbo].[DET_CONTEO]
 ADD CONSTRAINT [fk_det_conteo_posicion] FOREIGN KEY ([POSICION_ID]) REFERENCES [dbo].[POSICION] ([POSICION_ID]) 
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

ALTER TABLE [dbo].[RL_DET_DOC_TRANS_POSICION]
 ADD CONSTRAINT [fk_rl_det_doctr_posicion1] FOREIGN KEY ([POSICION_ACTUAL]) REFERENCES [dbo].[POSICION] ([POSICION_ID]) 
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

ALTER TABLE [dbo].[RL_DET_DOC_TRANS_POSICION]
 ADD CONSTRAINT [fk_rl_det_doctr_posicion2] FOREIGN KEY ([POSICION_ANTERIOR]) REFERENCES [dbo].[POSICION] ([POSICION_ID]) 
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

ALTER TABLE [dbo].[HISTORICO_PRODUCTO_RL]
 ADD CONSTRAINT [fk_HPRL_rl_det_doctr_posicion1] FOREIGN KEY ([POSICION_ACTUAL]) REFERENCES [dbo].[POSICION] ([POSICION_ID]) 
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

ALTER TABLE [dbo].[HISTORICO_PRODUCTO_RL]
 ADD CONSTRAINT [fk_HPRL_rl_det_doctr_posicion2] FOREIGN KEY ([POSICION_ANTERIOR]) REFERENCES [dbo].[POSICION] ([POSICION_ID]) 
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

ALTER TABLE [dbo].[SYS_LOCATOR_ING]
 ADD CONSTRAINT [FK_POSICION_SYS_LOCATOR_ING] FOREIGN KEY ([POSICION_ID]) REFERENCES [dbo].[POSICION] ([POSICION_ID]) 
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

ALTER TABLE [dbo].[RL_VEHICULO_POSICION]
 ADD CONSTRAINT [FK_POSICION_RL] FOREIGN KEY ([POSICION_ID]) REFERENCES [dbo].[POSICION] ([POSICION_ID]) 
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

ALTER TABLE [dbo].[rl_doc_tr_egreso]
 ADD CONSTRAINT [fk_rl_doc_tr_egr_posicion1] FOREIGN KEY ([posicion_origen]) REFERENCES [dbo].[POSICION] ([POSICION_ID]) 
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

ALTER TABLE [dbo].[rl_doc_tr_egreso]
 ADD CONSTRAINT [fk_rl_doc_tr_egr_posicion2] FOREIGN KEY ([posicion_destino]) REFERENCES [dbo].[POSICION] ([POSICION_ID]) 
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

ALTER TABLE [dbo].[RL_PRODUCTO_POSICION_PERMITIDA]
 ADD CONSTRAINT [fk_rlppp_posicion] FOREIGN KEY ([POSICION_ID]) REFERENCES [dbo].[POSICION] ([POSICION_ID]) 
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

ALTER TABLE [dbo].[UNIDAD_CONTENEDORA]
 ADD CONSTRAINT [fk_uc_posicion] FOREIGN KEY ([POSICION_ID]) REFERENCES [dbo].[POSICION] ([POSICION_ID]) 
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO
/*
ALTER TABLE [dbo].[SYS_DEV_DET_DOCUMENTO]
 ADD CONSTRAINT [FK_SDD#SDDD] FOREIGN KEY ([CLIENTE_ID], [DOC_EXT]) REFERENCES [dbo].[SYS_DEV_DOCUMENTO] ([CLIENTE_ID], [DOC_EXT]) 
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

ALTER TABLE [dbo].[SYS_INT_DET_DOCUMENTO]
 ADD CONSTRAINT [FK_SYSINTDET#SYSINTDETDOC] FOREIGN KEY ([CLIENTE_ID], [DOC_EXT]) REFERENCES [dbo].[SYS_INT_DOCUMENTO] ([CLIENTE_ID], [DOC_EXT]) 
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

ALTER TABLE [dbo].[SYS_INT_DET_DOCUMENTO]
 ADD CONSTRAINT [FK_SYSINTDET#SYSINTDETDOC_MAXI] FOREIGN KEY ([CLIENTE_ID], [DOC_EXT]) REFERENCES [dbo].[SYS_INT_DOCUMENTO] ([CLIENTE_ID], [DOC_EXT]) 
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

ALTER TABLE [dbo].[SYS_USU_PERMISOS]
 ADD CONSTRAINT [fk_sys_permisos] FOREIGN KEY ([PERMISO_ID]) REFERENCES [dbo].[SYS_PERMISOS] ([PERMISO_ID]) 
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

ALTER TABLE [dbo].[SYS_AUDITORIA_CAT_MERC]
 ADD CONSTRAINT [FK_SYS_AUDITORIA_CAT_MERC_USUARIO_ID] FOREIGN KEY ([USUARIO_ID]) REFERENCES [dbo].[SYS_USUARIO] ([USUARIO_ID]) 
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

ALTER TABLE [dbo].[SYS_AUDITORIA]
 ADD CONSTRAINT [fk_sys_auditoria_sys_usu] FOREIGN KEY ([USUARIO_ID]) REFERENCES [dbo].[SYS_USUARIO] ([USUARIO_ID]) 
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

ALTER TABLE [dbo].[LOCKEO_POSICION]
 ADD CONSTRAINT [FK_LP_SYS_USUARIO] FOREIGN KEY ([USR_LCK]) REFERENCES [dbo].[SYS_USUARIO] ([USUARIO_ID]) 
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

ALTER TABLE [dbo].[SYS_PERMISOS_HH]
 ADD CONSTRAINT [FK_SYS_PERMISOS_HH_SYS_USUARIO] FOREIGN KEY ([USUARIO_ID]) REFERENCES [dbo].[SYS_USUARIO] ([USUARIO_ID]) 
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

ALTER TABLE [dbo].[TRACE_DOCUMENTOS]
 ADD CONSTRAINT [fk_trace_doc_sys_uusuarios] FOREIGN KEY ([USUARIO_ID]) REFERENCES [dbo].[SYS_USUARIO] ([USUARIO_ID]) 
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

ALTER TABLE [dbo].[HISTORICO_POSICION]
 ADD CONSTRAINT [pk_hist_pos_usuario] FOREIGN KEY ([USUARIO_ID]) REFERENCES [dbo].[SYS_USUARIO] ([USUARIO_ID]) 
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

ALTER TABLE [dbo].[HISTORICO_PRODUCTO]
 ADD CONSTRAINT [fk_hist_usuario] FOREIGN KEY ([USUARIO_ID]) REFERENCES [dbo].[SYS_USUARIO] ([USUARIO_ID]) 
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

ALTER TABLE [dbo].[DOCUMENTO_TRANSACCION]
 ADD CONSTRAINT [pk_doc_trans_usuario] FOREIGN KEY ([USUARIO_ID]) REFERENCES [dbo].[SYS_USUARIO] ([USUARIO_ID]) 
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

ALTER TABLE [dbo].[RL_INVENTARIO_USUARIO]
 ADD CONSTRAINT [fk_rl_usuario_inv] FOREIGN KEY ([USUARIO_ID]) REFERENCES [dbo].[SYS_USUARIO] ([USUARIO_ID]) 
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

ALTER TABLE [dbo].[RL_USUARIO_VEHICULO]
 ADD CONSTRAINT [FK_SU_UV] FOREIGN KEY ([USUARIO_ID]) REFERENCES [dbo].[SYS_USUARIO] ([USUARIO_ID]) 
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

ALTER TABLE [dbo].[SYS_PERFIL_USUARIO]
 ADD CONSTRAINT [fk_sys_perfil_usu_usu] FOREIGN KEY ([USUARIO_ID]) REFERENCES [dbo].[SYS_USUARIO] ([USUARIO_ID]) 
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

ALTER TABLE [dbo].[SYS_USU_PERMISOS]
 ADD CONSTRAINT [fk_sys_usuario] FOREIGN KEY ([USUARIO_ID]) REFERENCES [dbo].[SYS_USUARIO] ([USUARIO_ID]) 
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

ALTER TABLE [dbo].[RL_USUARIO_NAVE]
 ADD CONSTRAINT [fk_rl_usuario] FOREIGN KEY ([USUARIO_ID]) REFERENCES [dbo].[SYS_USUARIO] ([USUARIO_ID]) 
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

ALTER TABLE [dbo].[RL_DET_CONTEO_USUARIO]
 ADD CONSTRAINT [fk_rl_det_cont_user_user] FOREIGN KEY ([USUARIO_ID]) REFERENCES [dbo].[SYS_USUARIO] ([USUARIO_ID]) 
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO
*/
IF @@TRANCOUNT > 0
BEGIN
   IF EXISTS (SELECT * FROM #tmpErrors)
       ROLLBACK TRANSACTION
   ELSE
       COMMIT TRANSACTION
END
GO

DROP TABLE #tmpErrors
GO