
GO

/*
Script created by Quest Change Director for SQL Server at 14/12/2012 04:33 p.m.
Please back up your database before running this script
*/

PRINT N'Synchronizing objects from V9 to CORAL'
GO

IF @@TRANCOUNT > 0 COMMIT TRANSACTION
GO

SET NUMERIC_ROUNDABORT OFF
SET ANSI_PADDING, ANSI_NULLS, ANSI_WARNINGS, CONCAT_NULL_YIELDS_NULL, ARITHABORT, QUOTED_IDENTIFIER ON
GO

IF EXISTS (SELECT * FROM tempdb..sysobjects WHERE id=OBJECT_ID('tempdb..#tmpErrors')) DROP TABLE #tmpErrors
GO

CREATE TABLE #tmpErrors (Error int)
GO

SET XACT_ABORT OFF
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
GO

BEGIN TRANSACTION
GO

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO

ALTER procedure [dbo].[FUNCIONES_INVENTARIO_API#SAVE_CANT_AJU]
@P_INVENTARIO_ID NUMERIC(20) OUTPUT,
@P_MARBETE NUMERIC(20) OUTPUT,
@P_CANT_AJU NUMERIC(20,5) OUTPUT
AS
BEGIN
	UPDATE DET_INVENTARIO_AJU SET CANT_AJU = @P_CANT_AJU WHERE INVENTARIO_ID = @P_INVENTARIO_ID AND MARBETE = @P_MARBETE 
END
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO

ALTER PROCEDURE [dbo].[GET_AGENTESBYVIAJE]
@VIAJE AS VARCHAR(100) OUTPUT
AS
BEGIN

	SELECT 	DISTINCT
			D.SUCURSAL_DESTINO, S.NOMBRE
	FROM	DOCUMENTO D(NOLOCK) INNER JOIN SUCURSAL S (NOLOCK)
			ON(D.CLIENTE_ID=S.CLIENTE_ID AND D.SUCURSAL_DESTINO=S.SUCURSAL_ID)
	WHERE	D.NRO_DESPACHO_IMPORTACION=@VIAJE

END -- FIN PROCEDURE
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER OFF
GO

ALTER PROCEDURE [dbo].[GET_CANT_STOCK_ENVASES]
@CLIENTE_ID 	AS VARCHAR(15),
@PRODUCTO_ID 	AS VARCHAR(30),
@CANTIDAD		AS FLOAT OUTPUT
AS
BEGIN

	SELECT 	@CANTIDAD=X.A - ISNULL(X.B,0)
	FROM
	(	
		SELECT 	SUM(RL.CANTIDAD)AS A,
				(
						SELECT 	SUM(DD2.CANTIDAD)
						FROM	DET_DOCUMENTO DD2 
								INNER JOIN DOCUMENTO D
								ON(DD2.DOCUMENTO_ID=D.DOCUMENTO_ID)
						WHERE	D.STATUS='D20' AND DD2.PRODUCTO_ID=Ltrim(Rtrim(Upper(@PRODUCTO_ID))) and 
								D.CLIENTE_ID=Ltrim(Rtrim(Upper(@CLIENTE_ID)))
				) AS B
		FROM	RL_DET_DOC_TRANS_POSICION RL
				INNER JOIN DET_DOCUMENTO_TRANSACCION DDT
				ON(DDT.DOC_TRANS_ID=RL.DOC_TRANS_ID AND DDT.NRO_LINEA_TRANS=RL.NRO_LINEA_TRANS)
				INNER JOIN DET_DOCUMENTO DD
				ON(DD.DOCUMENTO_ID=DDT.DOCUMENTO_ID AND DD.NRO_LINEA=DDT.NRO_LINEA_DOC)
		WHERE	DD.PRODUCTO_ID=Ltrim(Rtrim(Upper(@PRODUCTO_ID))) AND RL.CAT_LOG_ID='DISPONIBLE' AND RL.DOC_TRANS_ID_EGR IS NULL 
				AND DOC_TRANS_ID_TR IS NULL and DD.CLIENTE_ID=Ltrim(Rtrim(Upper(@CLIENTE_ID)))
	) AS X

END
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO

-- ESTE PROCEDURE SE ULITIZA CUANDO ES NECESARIO VERIFICAR LA CANTIDAD

ALTER   PROCEDURE [dbo].[GET_CANTIDAD_SOLICITADA]
@DOCUMENTOID NUMERIC(20,0),
@NROLINEA  NUMERIC(10,0)
AS

BEGIN
	SELECT 	CANT_SOLICITADA
	FROM	DET_DOCUMENTO
	WHERE 	DOCUMENTO_ID=@DOCUMENTOID
			AND
			NRO_LINEA=@NROLINEA
END
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO

ALTER    PROCEDURE	[dbo].[Get_CargaDocumento] 
						@DOC_EXT varchar(100) output
AS
BEGIN

	
	SELECT	SD.DOC_EXT
			,SD.CODIGO_VIAJE
			,UPPER(S.NOMBRE) AS SUCURSAL
			,UPPER(SDD.PRODUCTO_ID) AS PRODUCTO_ID
			,SDD.CANTIDAD_SOLICITADA AS CANTIDAD
			,SDD.UNIDAD_ID
			,SDD.DESCRIPCION
		 	,Su.nombre AS USOINTERNOUsuario
	 		,tul.Terminal AS USOINTERNOTerminal
	FROM    SYS_INT_DOCUMENTO SD
			INNER JOIN SYS_INT_DET_DOCUMENTO SDD ON(SD.DOC_EXT=SDD.DOC_EXT) 
			INNER JOIN SUCURSAL S ON(S.SUCURSAL_ID=SD.AGENTE_ID) 
			,#TEMP_USUARIO_LOGGIN TUL 
			INNER JOIN SYS_USUARIO SU ON (TUL.USUARIO_ID = SU.USUARIO_ID)
	WHERE	SD.DOC_EXT = @DOC_EXT
	/*
	GROUP BY SD.DOC_EXT
			,SD.CODIGO_VIAJE
			,SUCURSAL_ID 
			,S.NOMBRE
			,PRODUCTO_ID
			,SDD.CANTIDAD_SOLICITADA
			,SDD.UNIDAD_ID
			,SDD.DESCRIPCION
			,Su.nombre
			,tul.Terminal */

END
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO

ALTER PROCEDURE [dbo].[GET_CLIENTES_BY_USER]
@USER	VARCHAR(30)
AS
BEGIN
	SELECT	UPPER(R.CLIENTE_ID) [CLIENTE_ID], UPPER(C.RAZON_SOCIAL) AS [RAZONSOCIAL]
	FROM	SYS_USUARIO S INNER JOIN RL_SYS_CLIENTE_USUARIO R
			ON(S.USUARIO_ID=R.USUARIO_ID)
			INNER JOIN CLIENTE C
			ON(R.CLIENTE_ID=C.CLIENTE_ID)
	WHERE	R.USUARIO_ID=LTRIM(RTRIM(UPPER(@USER)))
END
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO

ALTER PROCEDURE [dbo].[GET_CLIENTES_FOR_RODC]
AS
BEGIN
	DECLARE @USR	VARCHAR(50)
	
	SELECT @USR=USUARIO_ID FROM #TEMP_USUARIO_LOGGIN

	SELECT 	CLIENTE_ID
	FROM 	RL_SYS_CLIENTE_USUARIO 
	WHERE	USUARIO_ID=@USR

END
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO

-- =============================================
-- Author:		<Author,,Name>
-- Create date: <Create Date,,>
-- Description:	<Description,,>
-- =============================================
ALTER PROCEDURE [dbo].[Get_Contenedoras]
	-- Add the parameters for the stored procedure here
	@cliente_id	varchar(15),
	@nro_remito varchar(30)	
AS
BEGIN

	SET NOCOUNT ON;

	SELECT	distinct pallet_picking
	FROM	PICKING P INNER JOIN DOCUMENTO D
			ON(D.DOCUMENTO_ID=P.DOCUMENTO_ID)
	WHERE	TIPO_OPERACION_ID='EGR' 
			AND P.FACTURADO='0'
			AND P.ST_CAMION='0'
			AND P.PALLET_CONTROLADO='1'
			AND P.CLIENTE_ID = @cliente_id
			AND D.NRO_REMITO = @nro_remito
END
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO

ALTER PROCEDURE [dbo].[GET_COT]
@FECHA	AS VARCHAR(15)
AS
BEGIN

	SELECT	
			P.PALLET_FINAL, 
			CONVERT(VARCHAR,GETDATE(),103) AS FECHA, 
			S.SUCURSAL_ID,
			P.PRODUCTO_ID, 
			SUM(CANT_CONFIRMADA) AS CANTIDAD,
			d.nro_despacho_importacion
	FROM    PICKING P INNER JOIN DET_DOCUMENTO DD ON(P.DOCUMENTO_ID=DD.DOCUMENTO_ID AND P.NRO_LINEA=DD.NRO_LINEA)
			INNER JOIN DOCUMENTO D ON(D.DOCUMENTO_ID=DD.DOCUMENTO_ID)
			INNER JOIN SUCURSAL S ON(S.CLIENTE_ID=D.CLIENTE_ID AND S.SUCURSAL_ID=D.SUCURSAL_DESTINO)
			INNER JOIN SYS_INT_DOCUMENTO SD ON(SD.CLIENTE_ID=D.CLIENTE_ID AND SD.DOC_EXT=D.NRO_REMITO)
	WHERE	PALLET_FINAL IS NOT NULL
			AND PALLET_CERRADO='1'
			AND CONVERT(VARCHAR,FECHA_SOLICITUD_CPTE,103)=CONVERT(VARCHAR,CAST(@FECHA AS DATETIME),103)
	GROUP BY
			P.PALLET_FINAL, S.SUCURSAL_ID, P.PRODUCTO_ID, D.NRO_DESPACHO_IMPORTACION
END
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO

ALTER PROCEDURE [dbo].[GET_DATA_CONNECTION_RODC]
@IP		AS VARCHAR(13) OUTPUT,
@PORT	AS VARCHAR(5) OUTPUT
AS
BEGIN
	SELECT 	@IP=VALOR 
	FROM 	SYS_PARAMETRO_PROCESO 
	WHERE 	PROCESO_ID='WARP' AND SUBPROCESO_ID='LISTENER'	 AND PARAMETRO_ID='IP_SERVER'

	SELECT 	@PORT=VALOR 
	FROM 	SYS_PARAMETRO_PROCESO 
	WHERE 	PROCESO_ID='WARP' AND SUBPROCESO_ID='LISTENER'	 AND PARAMETRO_ID='PORT'

END
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO

ALTER Procedure [dbo].[Get_Default_Envase]
@Documento_id		as Numeric(20,0),
@Nro_Linea			as Numeric(10,0)
As
Begin
	Declare	@Count 			as Int
	Declare @Cliente_id		as Varchar(15)
	Declare @Producto_id	as Varchar(30)

	Select 	@Cliente_id=Cliente_id, @Producto_id=Producto_id
	from	det_documento
	where	documento_id=@Documento_id
			and nro_linea=@Nro_Linea
	
	SELECT 	NAVE_ID,
			POSICION_ID
	FROM	RL_PRODUCTO_POSICION_PERMITIDA
	WHERE	CLIENTE_ID=@CLIENTE_ID
			AND PRODUCTO_ID=@PRODUCTO_ID

	IF @@ROWCOUNT =0
	BEGIN
		RAISERROR('No hay ubicacion default para el envase %s .',16,1,@Producto_id)
	END
End
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO

ALTER procedure [dbo].[GET_DESCRIPCION_UNIDAD_PRODUCTO]
@CLIENTE_ID		VARCHAR(20),
@PRODUCTO_ID	VARCHAR(30),
@DESCRIPCION	VARCHAR(200) OUTPUT,
@UNIDAD			VARCHAR(50)  OUTPUT,
@USA_NROLOTE	VARCHAR(1)   OUTPUT,
@USA_NROPARTIDA VARCHAR(1)   OUTPUT
AS
BEGIN

SELECT @DESCRIPCION = P.DESCRIPCION,@UNIDAD = UM.DESCRIPCION, @USA_NROLOTE = ingLoteProveedor, @USA_NROPARTIDA = ingPartida
FROM PRODUCTO P
INNER JOIN UNIDAD_MEDIDA UM ON(P.UNIDAD_ID = UM.UNIDAD_ID)
WHERE CLIENTE_ID = @CLIENTE_ID
AND PRODUCTO_ID = @PRODUCTO_ID

END
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO

ALTER Procedure [dbo].[Get_Documento_Trans_Lock]
As
Begin

	SELECT 	DD.DOC_TRANS_ID,	U.NOMBRE, DD.TERMINAL, DD.ESTACION_ACTUAL
			,CASE 	DD.TIPO_OPERACION_ID 
					WHEN 'ING' 	THEN 'INGRESO' 
					WHEN 'EGR' 	THEN 'EGRESO'
					WHEN 'TR' 	THEN 'TRANSFERENCIA'
					WHEN 'INV'	THEN 'INVENTARIO'
			END AS TIPO_OPERACION
	FROM 	DOCUMENTO_TRANSACCION DD
			INNER JOIN SYS_USUARIO U
			ON(DD.USUARIO_ID=U.USUARIO_ID)
	WHERE	DD.TR_ACTIVO=1 AND DD.STATUS NOT IN ('T40')
End
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO

ALTER PROCEDURE [dbo].[GET_INFO_INV_INICIAL]
AS
BEGIN
		
		SELECT 	 Count(mob_id) AS [CONTEOS REALIZADOS]
				, POSICION_COD AS [CODIGO DE POSICION]
				, PRODUCTO_ID AS [PRODUCTO ID]
				, NRO_LOTE AS [NRO LOTE]
				,NRO_PALLET AS [NRO PALLET]
				,F_VTO AS [FECHA VENCIMIENTO]
				,QTY AS [CANTIDAD]
				,LOTE_PROVEEDOR AS [LOTE DEL PROVEEDOR]
				,(PRODUCTO_ID + NRO_PALLET + NRO_LOTE + LOTE_PROVEEDOR) AS [KEY]
		FROM	MOB_EXISTENCIA_INICIAL
		GROUP BY 
				POSICION_COD, PRODUCTO_ID, NRO_LOTE, NRO_PALLET,F_VTO,QTY,LOTE_PROVEEDOR


END
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO

ALTER PROCEDURE [dbo].[GET_LOCK_RECEPCION]
AS
BEGIN
	
	SELECT 	L.CLIENTE_ID, L.DOC_EXT, L.USUARIO_ID, U.NOMBRE, L.TERMINAL
			, CONVERT(VARCHAR,FECHA_LOCK,103) + ' ' + CAST(DATEPART(HH,FECHA_LOCK) AS VARCHAR(2)) + ':' 
			  + CAST(DATEPART(MI,FECHA_LOCK) AS VARCHAR(2))
			AS FECHA
	FROM 	SYS_LOCK_RECEPCION L (NOLOCK) INNER JOIN SYS_INT_DOCUMENTO S(NOLOCK)
			ON(L.CLIENTE_ID=S.CLIENTE_ID AND L.DOC_EXT=S.DOC_EXT)
			INNER JOIN SYS_INT_DET_DOCUMENTO SDD
			ON(S.CLIENTE_ID=SDD.CLIENTE_ID AND S.DOC_EXT=SDD.DOC_EXT)
			INNER JOIN SYS_USUARIO U (NOLOCK)
			ON(L.USUARIO_ID=U.USUARIO_ID)
	WHERE	SDD.ESTADO_GT IS NULL AND SDD.FECHA_ESTADO_GT IS NULL
			AND L.LOCK='1'

END
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO

ALTER PROCEDURE [dbo].[GET_MONITORPOSICIONES]
AS
BEGIN
	SET NOCOUNT ON
	SELECT    P.POSICION_ID
			,0 					AS [CHECK]
			,P.POSICION_COD	AS [POSICION]
			,PL.MOTIVO_ID		
			,ML.DESCRIPCION 	AS [DESC_MOTIVO]
			,S.NOMBRE			AS [USER_NAME]
			,PL.TRM_LCK			AS [TERMINAL]
			,PL.F_LCK			AS [FECHA_LOCK]
			,PL.OBS_LCK			AS [OBSERVACIONES]
	FROM 	POSICION P INNER JOIN LOCKEO_POSICION PL
			ON(P.POSICION_ID=PL.POSICION_ID)
			INNER JOIN MOTIVO_LOCKEO ML
			ON(PL.MOTIVO_ID=ML.MOTIVO_ID)
			INNER JOIN SYS_USUARIO S
			ON(PL.USR_LCK=S.USUARIO_ID)
	WHERE	P.POS_LOCKEADA='1'
END
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO

-- =============================================
-- Author:		<Author,,Name>
-- Create date: <Create Date,,>
-- Description:	<Description,,>
-- =============================================
ALTER PROCEDURE [dbo].[GET_nroRemitos]
	-- Add the parameters for the stored procedure here
	@cliente_id	varchar(15)
AS
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;

	SELECT	DISTINCT 
			NRO_REMITO 
	FROM	DOCUMENTO D INNER JOIN DET_DOCUMENTO DD
			ON(D.DOCUMENTO_ID=DD.DOCUMENTO_ID)
			INNER JOIN PICKING P
			ON(DD.DOCUMENTO_ID=P.DOCUMENTO_ID AND DD.NRO_LINEA=P.NRO_LINEA)
	WHERE	TIPO_OPERACION_ID='EGR' 
			AND NRO_REMITO IS NOT NULL
			AND P.FACTURADO='0'
			AND P.ST_CAMION='0'
			AND P.CLIENTE_ID=@cliente_id
END
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO

ALTER   Procedure [dbo].[Get_Picking_Wave]
@Doc_trans_id	as Numeric(20,0) Output
As
Begin
	Declare @Wave 	As Numeric(20,0)

	Select Distinct @Wave=Wave_Id From Sys_Picking_Wave Where Doc_Trans_Id=@Doc_Trans_Id

	Select 
		 	 P.Posicion_cod
			,P.Documento_id
			,P.Nro_Linea
			,P.Cliente_id
			,P.Producto_Id
			,P.Descripcion
			,P.Cantidad
			,DD.Nro_Serie
			,DD.Nro_Bulto
			,DD.Nro_Lote
			,DD.Nro_Despacho
			,DD.Nro_Partida
			,DD.Unidad_Id
			,DD.Fecha_Vencimiento
			,DD.Moneda_id
			,DD.Prop1
			,DD.Prop2
			,DD.Prop3
	From	Picking P Inner Join Det_Documento DD
			On(P.Documento_id=DD.Documento_id And P.Nro_linea=DD.Nro_linea)
			Inner Join Det_Documento_Transaccion DDT
			On(DD.Documento_Id=DDT.Documento_Id And DD.Nro_Linea=DDT.Nro_Linea_Doc)
	Where	DDT.Doc_Trans_Id In(
									Select 	Doc_Trans_Id
									From	Sys_Picking_Wave
									Where	Wave_id=@Wave
									)
	Order By
			P.Posicion_Cod, P.Producto_Id
End;
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO

ALTER     Procedure [dbo].[Get_Picking_Wave_Rpt] 
@WaveId	as Numeric(20,0) Output
As
Begin
	Declare 	@Usuario			as varchar(30)
	Declare @FechaImpresion	as Varchar(15)
	Declare @Terminal			as varchar(100)


	Select 	@Usuario=Usuario_id From #Temp_Usuario_Loggin
	Select 	@FechaImpresion=	CAST(DAY(GETDATE()) AS  VARCHAR(2)) 
								+ '/' + CAST(MONTH(GETDATE()) AS VARCHAR(2))
								+ '/' + CAST(YEAR(GETDATE()) AS VARCHAR(4))
	Select  	@Terminal=Host_Name()

	Select 
		 	 P.Posicion_cod --
			,P.Documento_id --
			,P.Nro_Linea
			,P.Cliente_id --
			,P.Producto_Id --
			,P.Descripcion --
			,P.Cantidad --
			,isnull(DD.Nro_Serie,'-') 			as Nro_Serie--
			,isnull(DD.Nro_Bulto,'-')			as Nro_Bulto--
			,isnull(DD.Nro_Lote,'-')			as Nro_Lote--
			,isnull(DD.Nro_Despacho,'-')		as Nro_Despacho--
			,isnull(DD.Nro_Partida,'-')			as Nro_Partida--
			,isnull(DD.Unidad_Id,'-')			as Unidad_Id--
			,isnull(Cast(DD.Fecha_Vencimiento as varchar),'-')	as Fecha_Vencimiento--
			,isnull(DD.Prop1,'-')				as Prop1
			,isnull(DD.Prop2,'-')				as Prop2
			,isnull(DD.Prop3,'-')				as Prop3
			,@Usuario 						as Usuario
			,@FechaImpresion 				as FechaImpresion
			,@Terminal 						as Terminal
			,PW.Wave_Id
	From	Picking P Inner Join Det_Documento DD
			On(P.Documento_id=DD.Documento_id And P.Nro_linea=DD.Nro_linea)
			Inner Join Det_Documento_Transaccion DDT
			On(DD.Documento_Id=DDT.Documento_Id And DD.Nro_Linea=DDT.Nro_Linea_Doc)
			inner Join Sys_Picking_Wave PW
			On(DDT.Doc_trans_id=PW.Doc_trans_id)
	Where	Wave_id=@WaveId
	Order By
			P.Posicion_Cod, p.Documento_id, p.Nro_linea
End;
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO

ALTER      Procedure [dbo].[Get_Picking_Wave_Rpt_Cons] 
@WaveId	as Numeric(20,0) Output
As
Begin
	Declare 	@Usuario			as varchar(30)
	Declare @FechaImpresion	as Varchar(15)
	Declare @Terminal			as varchar(100)


	Select 	@Usuario=Usuario_id From #Temp_Usuario_Loggin
	Select 	@FechaImpresion=	CAST(DAY(GETDATE()) AS  VARCHAR(2)) 
								+ '/' + CAST(MONTH(GETDATE()) AS VARCHAR(2))
								+ '/' + CAST(YEAR(GETDATE()) AS VARCHAR(4))
	Select  	@Terminal=Host_Name()

	Select 
		 	 P.Posicion_cod --
			,P.Cliente_id --
			,P.Producto_Id --
			,P.Descripcion --
			,sum(P.Cantidad) 				as Cantidad				--
			,isnull(DD.Nro_Serie,'-') 			as Nro_Serie				--
			,isnull(DD.Nro_Bulto,'-')			as Nro_Bulto				--
			,isnull(DD.Nro_Lote,'-')			as Nro_Lote				--
			,isnull(DD.Nro_Despacho,'-')		as Nro_Despacho		--
			,isnull(DD.Nro_Partida,'-')			as Nro_Partida			--
			,isnull(DD.Unidad_Id,'-')			as Unidad_Id			--
			,isnull(Cast(DD.Fecha_Vencimiento as varchar),'-')	as Fecha_Vencimiento--
			,isnull(DD.Prop1,'-')				as Prop1
			,isnull(DD.Prop2,'-')				as Prop2
			,isnull(DD.Prop3,'-')				as Prop3
			,@Usuario 						as Usuario
			,@FechaImpresion 				as FechaImpresion
			,@Terminal 						as Terminal
			,PW.Wave_Id
	From	Picking P Inner Join Det_Documento DD
			On(P.Documento_id=DD.Documento_id And P.Nro_linea=DD.Nro_linea)
			Inner Join Det_Documento_Transaccion DDT
			On(DD.Documento_Id=DDT.Documento_Id And DD.Nro_Linea=DDT.Nro_Linea_Doc)
			inner Join Sys_Picking_Wave PW
			On(DDT.Doc_trans_id=PW.Doc_trans_id)
	Where	Wave_id=@WaveId
	Group By 
			P.Posicion_Cod, P.CLiente_id, P.Producto_id, P.Descripcion, DD.Nro_Serie, DD.Nro_Bulto, DD.Nro_lote, DD.Nro_Despacho, DD.Nro_Partida,
			DD.Unidad_Id, DD.Fecha_Vencimiento, DD.Prop1, DD.Prop2, DD.Prop3, PW.Wave_Id
	Order By
			P.Posicion_Cod
End;
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO

ALTER   procedure [dbo].[Get_PickingByViaje]
@Viaje_id		as Varchar(100) output
As	
Begin
	Declare @Usuario 	as varchar(20)
	Declare @sString	as varchar (200) 
	
	Select	@Usuario=Usuario_Id
	From	#temp_usuario_loggin

	SELECT 		
		SP.VIAJE_ID					AS [CODIGO VIAJE]
		,dbo.CLIENTE_VIAJERUTA(SP.VIAJE_ID,SP.RUTA) 	AS [CADENA_CLIENTE]
		,SP.PRODUCTO_ID				AS [PRODUCTO]
		,SP.DESCRIPCION					AS [DESCRIPCION]
		,SUM(SP.CANTIDAD)				AS [CANTIDAD]
		,SP.PROP1					AS [PALLET]
		,SP.POSICION_COD				AS [UBICACION]
		,SP.RUTA					AS [RUTA]
		,SP.TIPO_CAJA					AS [TIPO CAJA]
		,CAST(DAY(Dd.Fecha_Vencimiento)		AS VARCHAR(2)) 
			+'/'+ CAST(MONTH(Dd.Fecha_Vencimiento) AS VARCHAR(2)) 
			+'/'+CAST(YEAR(Dd.Fecha_Vencimiento) AS VARCHAR(4)) 	AS [FECHA VTO]
		,SPV.PRIORIDAD					AS [PRIORIDAD]
		,@Usuario			AS [USUARIO]
		,HOST_NAME()			AS [TERMINAL]
		,CAST(DAY(GETDATE()) AS VARCHAR(2)) 
			+'/'+ CAST(MONTH(GETDATE()) AS VARCHAR(2)) 
			+'/'+CAST(YEAR(GETDATE()) AS VARCHAR(4)) 		AS [FECHA]
	FROM	PICKING SP (nolock)
		left JOIN PRIORIDAD_VIAJE SPV (nolock) ON(LTRIM(RTRIM(UPPER(SPV.VIAJE_ID)))=LTRIM(RTRIM(UPPER(SP.VIAJE_ID))))
		INNER JOIN PRODUCTO PROD (nolock) ON(PROD.CLIENTE_ID=SP.CLIENTE_ID AND PROD.PRODUCTO_ID=SP.PRODUCTO_ID)
		INNER JOIN DET_DOCUMENTO DD (nolock) ON(SP.DOCUMENTO_ID=DD.DOCUMENTO_ID AND DD.NRO_LINEA=SP.NRO_LINEA)
		LEFT JOIN POSICION POS (nolock) ON(POS.POSICION_COD=SP.POSICION_COD)
		LEFT JOIN NAVE NAV (nolock) ON(SP.POSICION_COD=NAV.NAVE_COD)
	WHERE	LTRIM(RTRIM(UPPER(SP.VIAJE_ID)))=UPPER(LTRIM(RTRIM(@Viaje_id)))
	GROUP BY	
		SP.VIAJE_ID ,SP.PRODUCTO_ID
		,SP.DESCRIPCION ,SP.RUTA
		,SP.POSICION_COD ,SP.TIPO_CAJA
		,SP.PROP1 ,PROD.UNIDAD_ID ,DD.FECHA_VENCIMIENTO
		,SPV.PRIORIDAD ,POS.ORDEN_PICKING
	ORDER BY	
		SP.RUTA, CAST(ISNULL(SP.TIPO_CAJA,0) AS NUMERIC(10,1)) DESC,POS.ORDEN_PICKING, SP.POSICION_COD ASC
		
End
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO

ALTER       PROCEDURE [dbo].[Get_PickingWaveGen]
@PTransaccion_ID	as Varchar(15) Output
As
Begin

	Declare 	@Usuario 	as varchar(30)

	Select 	@Usuario=Usuario_Id From #Temp_Usuario_Loggin
	SELECT	DISTINCT
			'0' as [check],
			D.CLIENTE_ID,
			(SELECT RAZON_SOCIAL FROM  CLIENTE WHERE CLIENTE_ID=D.CLIENTE_ID) AS [CLIENTE_DESC],
			D.DOCUMENTO_ID,
			DT.TRANSACCION_ID,
			TR.DESCRIPCION AS TRANSACCION,
			DT.DOC_TRANS_ID,
			D.TIPO_COMPROBANTE_ID [TIPO_COMPROBANTE_ID],
			IsNull(D.TIPO_OPERACION_ID, DT.TIPO_OPERACION_ID) [TIPO_OPERACION_ID],
			DT.STATUS AS STATUS_TR,
			WP.WAVE_ID
	FROM 	DET_DOCUMENTO_TRANSACCION DDT
			INNER JOIN DOCUMENTO_TRANSACCION DT 	ON (DT.DOC_TRANS_ID=DDT.DOC_TRANS_ID)
			INNER JOIN DET_DOCUMENTO         DD 			ON DDT.DOCUMENTO_ID=DD.DOCUMENTO_ID AND DDT.NRO_LINEA_DOC=DD.NRO_LINEA
			LEFT JOIN DOCUMENTO               D 				ON DDT.DOCUMENTO_ID=D.DOCUMENTO_ID
			INNER JOIN TRANSACCION              TR 			ON (TR.TRANSACCION_ID = DT.TRANSACCION_ID)
			INNER JOIN RL_TRANSACCION_ESTACION  R1 	ON (DT.ESTACION_ACTUAL = R1.ESTACION_ID AND DT.TRANSACCION_ID = R1.TRANSACCION_ID)
			INNER JOIN SYS_PICKING_WAVE WP			ON(DT.DOC_TRANS_ID=WP.DOC_TRANS_ID)
	WHERE 	1 <> 0  AND DT.ESTACION_ACTUAL =LTRIM(RTRIM(UPPER(@PTransaccion_ID)))
			AND DT.TIPO_OPERACION_ID = 'EGR'
			AND DDT.CLIENTE_ID IN 	(	SELECT 	CLIENTE_ID 
										FROM	CLIENTE
										WHERE  (	SELECT 	CASE WHEN (Count(cliente_id)) > 0 THEN 1 ELSE 0 END
													FROM   	rl_sys_cliente_usuario
													WHERE  	cliente_id = dd.cliente_id
															And    usuario_id =@Usuario) = 1)
	ORDER BY 1,3,4


End
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO

ALTER PROCEDURE [dbo].[Get_PickingWaveProdDesc]
@DOC_TRANS_ID	numeric(20,0) output
As
Begin

	SELECT     P.PRODUCTO_ID
	   ,DESCRIPCION
	   ,CANTIDAD
	   ,PROP1 AS NRO_PALLET
	   ,POSICION_COD AS UBICACION
	   ,RUTA
	FROM    DET_DOCUMENTO_TRANSACCION DDT INNER JOIN PICKING P
	   ON(DDT.DOCUMENTO_ID=P.DOCUMENTO_ID AND DDT.NRO_LINEA_DOC=P.NRO_LINEA)
	WHERE    DDT.DOC_TRANS_ID=@DOC_TRANS_ID
	ORDER BY
	   P.RUTA, POSICION_COD 

End
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO

ALTER Procedure [dbo].[Get_Remanente_CrossDock]
@Documento_Id Numeric(20,0)
As
Begin
	SELECT	dd.documento_id, dd.nro_linea, dd.prop1
	FROM 	rl_det_doc_trans_posicion rl
	        	inner join det_documento_transaccion ddt on(rl.doc_trans_id=ddt.doc_trans_id and rl.nro_linea_trans=ddt.nro_linea_trans)
	        	inner join det_documento dd ON (ddt.documento_id=dd.documento_id AND ddt.nro_linea_doc=dd.nro_linea)
			left join nave n on(rl.nave_actual=n.nave_id)
			left join posicion p on(rl.posicion_actual=p.posicion_id)
	WHERE	dd.documento_id=@Documento_id
			and n.pre_ingreso='1'
End
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER OFF
GO

ALTER        PROCEDURE [dbo].[GET_VALUE_FOR_SEQUENCE]
@SECUENCIA AS VARCHAR(50)OUTPUT,
@VALUE AS NUMERIC(38) OUTPUT
AS

DECLARE @VARAUX AS NUMERIC(38)

SET TRANSACTION ISOLATION LEVEL REPEATABLE READ
BEGIN TRANSACTION
		SET @VALUE=0
		SELECT @VARAUX=	VALOR
		FROM SECUENCIA
		WHERE UPPER(NOMBRE)=UPPER(LTRIM(RTRIM(@SECUENCIA)))
		if @VARAUX IS NOT NULL 
			BEGIN
				SET @VALUE=@VARAUX + 1
				UPDATE SECUENCIA SET VALOR=@VALUE WHERE NOMBRE=UPPER(LTRIM(RTRIM(@SECUENCIA)))
			END
		ELSE
			BEGIN
				ROLLBACK TRANSACTION
				RAISERROR ('LA SEQUENCIA NO EXISTE EN LA TABLA. SQLSERVER', 16, 1)
	
			END
COMMIT TRANSACTION	
RETURN
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO

ALTER   PROCEDURE [dbo].[GET_VALUES_FOR_WARPEI]
AS BEGIN

	SET LANGUAGE ESPAÑOL

	SELECT 	PRODUCTO_ID	AS [PRODUCTO], 
			NRO_LOTE	AS [NRO. LOTE], 
			NRO_PALLET	AS [NRO. PALLET],  
			cast(CAST(DAY(F_VTO) AS VARCHAR(2)) + '/' + CAST(MONTH(F_VTO) AS VARCHAR(2)) + '/' +	CAST(YEAR(F_VTO) AS VARCHAR(4)) as varchar(10)) AS [FECHA VENCIMIENTO],
			QTY AS [CANTIDAD],
			LOTE_PROVEEDOR AS [L. PROV.],
			ISNULL(N.NAVE_COD,N2.NAVE_COD) AS [NAVE],
			CNAV.CALLE_COD AS [CALLE],
			CN.COLUMNA_COD	AS [COLUMNA] ,
			NN.NIVEL_COD AS [NIVEL]
	FROM	MOB_EXISTENCIA_INICIAL M
			LEFT JOIN POSICION P
			ON(M.POSICION_COD=P.POSICION_COD)
			LEFT JOIN NIVEL_NAVE NN
			ON(P.NIVEL_ID=NN.NIVEL_ID)
			LEFT JOIN COLUMNA_NAVE CN
			ON(P.COLUMNA_ID=CN.COLUMNA_ID)
			LEFT JOIN CALLE_NAVE CNAV
			ON(P.CALLE_ID=CNAV.CALLE_ID)
			LEFT JOIN NAVE N
			ON(P.NAVE_ID=N.NAVE_ID)
			LEFT JOIN NAVE N2
			ON(M.POSICION_COD=N2.NAVE_COD)
			
END
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO

ALTER PROCEDURE [dbo].[Get_Values_PickingWave]
@PTransaccion_ID	as Varchar(15) Output
As
Begin

	Declare 	@Usuario 	as varchar(30)

	Select 	@Usuario=Usuario_Id From #Temp_Usuario_Loggin

	SELECT	DISTINCT
			'0' as [check],
			D.CLIENTE_ID,
			(SELECT RAZON_SOCIAL FROM  CLIENTE WHERE CLIENTE_ID=D.CLIENTE_ID) AS [CLIENTE_DESC],
			D.DOCUMENTO_ID,
			DT.TRANSACCION_ID,
			TR.DESCRIPCION AS TRANSACCION,
			DT.DOC_TRANS_ID,
			D.TIPO_COMPROBANTE_ID [TIPO_COMPROBANTE_ID],
			IsNull(D.TIPO_OPERACION_ID, DT.TIPO_OPERACION_ID) [TIPO_OPERACION_ID],
			DT.STATUS AS STATUS_TR,
			P.RUTA 
	FROM 	DET_DOCUMENTO_TRANSACCION DDT
			INNER JOIN DOCUMENTO_TRANSACCION DT 	ON (DT.DOC_TRANS_ID=DDT.DOC_TRANS_ID)
			INNER JOIN DET_DOCUMENTO         DD 			ON DDT.DOCUMENTO_ID=DD.DOCUMENTO_ID AND DDT.NRO_LINEA_DOC=DD.NRO_LINEA
			LEFT JOIN DOCUMENTO               D 				ON DDT.DOCUMENTO_ID=D.DOCUMENTO_ID
			INNER JOIN TRANSACCION              TR 			ON (TR.TRANSACCION_ID = DT.TRANSACCION_ID)
			INNER JOIN RL_TRANSACCION_ESTACION  R1 	ON (DT.ESTACION_ACTUAL = R1.ESTACION_ID AND DT.TRANSACCION_ID = R1.TRANSACCION_ID)
			LEFT JOIN PICKING P ON (DD.DOCUMENTO_ID = P.DOCUMENTO_ID AND DD.NRO_LINEA = P.NRO_LINEA)
	WHERE 	1 <> 0  AND DT.ESTACION_ACTUAL =LTRIM(RTRIM(UPPER(@PTransaccion_ID)))
			AND DT.TIPO_OPERACION_ID = 'EGR'
			AND DDT.CLIENTE_ID IN 	(	SELECT 	CLIENTE_ID 
										FROM	CLIENTE
										WHERE  (	SELECT 	CASE WHEN (Count(cliente_id)) > 0 THEN 1 ELSE 0 END
													FROM   	rl_sys_cliente_usuario
													WHERE  	cliente_id = dd.cliente_id
															And    usuario_id =@Usuario) = 1)
			And DT.DOC_TRANS_ID NOT IN(	SELECT	DOC_TRANS_ID FROM SYS_PICKING_WAVE)
	ORDER BY 1,3,4


End
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO

ALTER   PROCEDURE [dbo].[GET_VALUESFORETIBULTOEGR]
AS
BEGIN
	SELECT 	DD.*, C.*, D.*, S.*, DBO.GETPICKINGID(P.VIAJE_ID, P.PRODUCTO_ID, P.POSICION_COD,P.PROP1,P.RUTA) AS ID
	FROM 	#TEMP_ETIQUETA TE (NOLOCK)INNER JOIN DET_DOCUMENTO DD (NOLOCK)
			ON(TE.DOCUMENTO_ID=DD.DOCUMENTO_ID AND TE.NRO_LINEA=DD.NRO_LINEA)
			INNER JOIN DOCUMENTO D(NOLOCK)
			ON(DD.DOCUMENTO_ID=D.DOCUMENTO_ID)
			INNER JOIN CLIENTE C(NOLOCK) 
			ON(D.CLIENTE_ID=C.CLIENTE_ID)
			INNER JOIN SUCURSAL S (NOLOCK)
			ON(D.CLIENTE_ID=S.CLIENTE_ID AND D.SUCURSAL_DESTINO=S.SUCURSAL_ID)
			INNER JOIN PICKING P (NOLOCK)
			ON(DD.DOCUMENTO_ID=P.DOCUMENTO_ID AND DD.NRO_LINEA=P.NRO_LINEA)


END
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO

ALTER  PROCEDURE [dbo].[GET_VEHICULOPOSICION]
@VEHICULO_ID	VARCHAR(50) OUTPUT
AS
BEGIN
	SELECT 	RL_ID, R.POSICION_ID, R.NAVE_ID,P.POSICION_COD, N.NAVE_COD,
        CASE 
		WHEN R.NAVE_ID IS NULL THEN 'CON LAYOUT' 
		ELSE 'SIN LAYOUT' 
	END AS SL
	FROM	RL_VEHICULO_POSICION R (NOLOCK)LEFT JOIN POSICION P(NOLOCK)
			ON(R.POSICION_ID=P.POSICION_ID)
			LEFT JOIN NAVE N (NOLOCK)
			ON(R.NAVE_ID=N.NAVE_ID)
	WHERE	VEHICULO_ID=@VEHICULO_ID
	ORDER BY N.NAVE_COD, P.POSICION_COD

END
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO

ALTER   PROCEDURE [dbo].[GETDATAFORPALLET]
@NROPALLET AS VARCHAR(100),
@USUARIO AS VARCHAR(20)
AS
DECLARE @DOCUMENTO_ID AS NUMERIC(20,0)
DECLARE @NRO_LINEA   AS NUMERIC(10,0)
DECLARE @TRANSACCION_ID   AS VARCHAR(15)
DECLARE @TIPO_OPERACION_ID AS VARCHAR(5)
DECLARE @DOC_TRANS_ID AS NUMERIC(20,0)
DECLARE @VCANT AS NUMERIC(20)
DECLARE @ESTACION AS VARCHAR(15)

	BEGIN
		SELECT @DOCUMENTO_ID=X.DOCUMENTO_ID,@NRO_LINEA=NRO_LINEA, @DOC_TRANS_ID=DOC_TRANS_ID
		FROM(
			SELECT 
					DD.PROP1,DD.DOCUMENTO_ID,DD.NRO_LINEA,RL.POSICION_ACTUAL,RL.NAVE_ACTUAL, DDT.DOC_TRANS_ID
			FROM 	DET_DOCUMENTO DD INNER JOIN DOCUMENTO D
					ON(DD.DOCUMENTO_ID=D.DOCUMENTO_ID)
					INNER JOIN DET_DOCUMENTO_TRANSACCION DDT
					ON(DD.DOCUMENTO_ID=DDT.DOCUMENTO_ID AND DD.NRO_LINEA =DDT.NRO_LINEA_DOC)
					INNER JOIN RL_DET_DOC_TRANS_POSICION RL
					ON(DDT.DOC_TRANS_ID=RL.DOC_TRANS_ID AND DDT.NRO_LINEA_TRANS = RL.NRO_LINEA_TRANS)
					INNER JOIN NAVE N
					ON(RL.NAVE_ACTUAL = N.NAVE_ID)
			WHERE 	DD.PROP1=UPPER(LTRIM(RTRIM(@NROPALLET))) AND D.STATUS IN ('D30','D35')
					AND N.PRE_INGRESO='1'
		
			UNION ALL
		
			SELECT 
					DD.PROP1,DD.DOCUMENTO_ID,DD.NRO_LINEA,RL.POSICION_ACTUAL,RL.NAVE_ACTUAL, DDT.DOC_TRANS_ID
			FROM 	DET_DOCUMENTO DD INNER JOIN DOCUMENTO D
					ON(DD.DOCUMENTO_ID=D.DOCUMENTO_ID)
					INNER JOIN DET_DOCUMENTO_TRANSACCION DDT
					ON(DD.DOCUMENTO_ID=DDT.DOCUMENTO_ID AND DD.NRO_LINEA =DDT.NRO_LINEA_DOC)
					INNER JOIN RL_DET_DOC_TRANS_POSICION RL
					ON(DDT.DOC_TRANS_ID=RL.DOC_TRANS_ID AND DDT.NRO_LINEA_TRANS = RL.NRO_LINEA_TRANS)
					INNER JOIN POSICION P
					ON(RL.POSICION_ACTUAL=P.POSICION_ID)
			WHERE 	DD.PROP1=UPPER(LTRIM(RTRIM(@NROPALLET))) AND D.STATUS IN ('D30','D35')
					AND	P.INTERMEDIA='1'
		
			UNION ALL
		
			SELECT 
					DD.PROP1,DD.DOCUMENTO_ID,DD.NRO_LINEA,RL.POSICION_ACTUAL,RL.NAVE_ACTUAL, DDT.DOC_TRANS_ID
			FROM 	DET_DOCUMENTO DD INNER JOIN DOCUMENTO D
					ON(DD.DOCUMENTO_ID=D.DOCUMENTO_ID)
					INNER JOIN DET_DOCUMENTO_TRANSACCION DDT
					ON(DD.DOCUMENTO_ID=DDT.DOCUMENTO_ID AND DD.NRO_LINEA =DDT.NRO_LINEA_DOC)
					INNER JOIN RL_DET_DOC_TRANS_POSICION RL
					ON(DDT.DOC_TRANS_ID=RL.DOC_TRANS_ID AND DDT.NRO_LINEA_TRANS = RL.NRO_LINEA_TRANS)
					INNER JOIN NAVE N
					ON(N.NAVE_ID=RL.NAVE_ACTUAL)
			WHERE 	DD.PROP1=UPPER(LTRIM(RTRIM(@NROPALLET))) AND D.STATUS IN ('D30','D35')
					AND	N.INTERMEDIA='1'
		) AS X

	END
---Acá validamos que el usuario tenga permiso para tomar el pallet

	IF @@ROWCOUNT =0
		BEGIN
			RAISERROR ('EL PALLET SOLICITADO NO ESTA DISPONIBLE.', 16, 1)
		END

	ELSE
	BEGIN

	SELECT 	@TRANSACCION_ID=DT.TRANSACCION_ID,@TIPO_OPERACION_ID=DT.TIPO_OPERACION_ID,@ESTACION=DT.ESTACION_ACTUAL
	FROM 	DET_DOCUMENTO DD INNER JOIN DET_DOCUMENTO_TRANSACCION DDT
			ON(DD.DOCUMENTO_ID= DDT.DOCUMENTO_ID AND DD.NRO_LINEA=DDT.NRO_LINEA_DOC)
			INNER JOIN DOCUMENTO_TRANSACCION DT
			ON(DDT.DOC_TRANS_ID=DT.DOC_TRANS_ID)
	WHERE 	DD.DOCUMENTO_ID=@DOCUMENTO_ID 
			AND DD.NRO_LINEA=@NRO_LINEA
	
					
	

	SELECT 	@VCANT=COUNT(D.DOCUMENTO_ID)
	FROM 	DET_DOCUMENTO_TRANSACCION DDT
			INNER JOIN DOCUMENTO_TRANSACCION DT ON (DT.DOC_TRANS_ID=DDT.DOC_TRANS_ID)
			INNER JOIN DET_DOCUMENTO         DD ON DDT.DOCUMENTO_ID=DD.DOCUMENTO_ID AND DDT.NRO_LINEA_DOC=DD.NRO_LINEA
			LEFT JOIN DOCUMENTO               D ON DDT.DOCUMENTO_ID=D.DOCUMENTO_ID
			INNER JOIN TRANSACCION              TR ON (TR.TRANSACCION_ID = DT.TRANSACCION_ID)
			INNER JOIN RL_TRANSACCION_ESTACION  R1 ON (DT.ESTACION_ACTUAL = R1.ESTACION_ID AND DT.TRANSACCION_ID = R1.TRANSACCION_ID)
	WHERE 	1 <> 0
			AND DT.ESTACION_ACTUAL IN	(
										SELECT 	RLS.ESTACION_ID
										FROM 	SYS_USUARIO SU INNER JOIN 
												RL_SYS_ROL_TRANS_ESTACION RLS
												ON(SU.ROL_ID=RLS.ROL_ID)
										WHERE 	SU.USUARIO_ID=@USUARIO
												AND RLS.TRANSACCION_ID=@TRANSACCION_ID
										)
			AND DT.TIPO_OPERACION_ID = @TIPO_OPERACION_ID
			AND DD.DOCUMENTO_ID=@DOCUMENTO_ID
			AND DD.NRO_LINEA=@NRO_LINEA
			AND DDT.CLIENTE_ID IN (
									SELECT CLIENTE_ID 	
									FROM CLIENTE
									WHERE
											(
												SELECT CASE WHEN (Count(cliente_id)) > 0 THEN 1 ELSE 0 END
												FROM   rl_sys_cliente_usuario
												WHERE  cliente_id = dd.cliente_id
												And    usuario_id = @USUARIO
											) = 1
									)


		IF @VCANT=0 --@@ROWCOUNT =0
		BEGIN
			RAISERROR ('NO TIENE PERMISOS SOBRE EL PALLET SELECCIONADO', 16, 1)
		END
		ELSE
		BEGIN 
		SELECT @DOCUMENTO_ID AS DOCUMENTO_ID, @NRO_LINEA AS NRO_LINEA --FROM X
		END

	END
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

IF @@TRANCOUNT > 0
BEGIN
   IF EXISTS (SELECT * FROM #tmpErrors)
       ROLLBACK TRANSACTION
   ELSE
       COMMIT TRANSACTION
END
GO

DROP TABLE #tmpErrors
GO