
GO

/*
Script created by Quest Change Director for SQL Server at 14/12/2012 05:34 p.m.
Please back up your database before running this script
*/

PRINT N'Synchronizing objects from V9 to CORAL'
GO

IF @@TRANCOUNT > 0 COMMIT TRANSACTION
GO

SET NUMERIC_ROUNDABORT OFF
SET ANSI_PADDING, ANSI_NULLS, ANSI_WARNINGS, CONCAT_NULL_YIELDS_NULL, ARITHABORT, QUOTED_IDENTIFIER ON
GO

IF EXISTS (SELECT * FROM tempdb..sysobjects WHERE id=OBJECT_ID('tempdb..#tmpErrors')) DROP TABLE #tmpErrors
GO

CREATE TABLE #tmpErrors (Error int)
GO

SET XACT_ABORT OFF
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
GO

BEGIN TRANSACTION
GO

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO

-- =============================================
-- Author:		LRojas
-- Create date: 19/04/2012
-- Description:	Procedimiento para quitar unidades empaquetadas
-- =============================================
ALTER PROCEDURE [dbo].[quitar_producto_empaque]
	@CLIENTE_ID         as varchar(15) OUTPUT,
	@PEDIDO_ID          as varchar(30) OUTPUT,
	@NRO_LOTE			AS VARCHAR(100) OUTPUT,
	@NRO_PARTIDA		AS VARCHAR(100) OUTPUT,
	@NRO_SERIE			AS VARCHAR(50) OUTPUT,
	@PRODUCTO_ID        as varchar(30) OUTPUT,
    @NRO_CONTENEDORA    as numeric(20) OUTPUT,
    @CANT_CONTROLADA    as numeric(20,5) OUTPUT
AS
BEGIN
	SET NOCOUNT ON;
    
    DECLARE @NRO_LINEA as numeric(10),
            @CANT_CONFIRMADA as numeric(20,5),
            @CANTIDAD_EMPAQUE as numeric(20,5),
            @CANTIDAD as numeric(20,5)
    
    DELETE TMP_EMPAQUE_CONTENEDORA WHERE CLIENTE_ID = @CLIENTE_ID AND NRO_REMITO = @PEDIDO_ID AND PRODUCTO_ID = @PRODUCTO_ID AND ISNULL(NRO_LOTE,'') = ISNULL(@NRO_LOTE,'') AND ISNULL(NRO_PARTIDA,'') = ISNULL(@NRO_PARTIDA,'') AND ISNULL(NRO_SERIE,'') = ISNULL(@NRO_SERIE,'')
    
    INSERT INTO TMP_EMPAQUE_CONTENEDORA
    SELECT D.NRO_REMITO, P.*
    FROM DOCUMENTO D INNER JOIN PICKING P ON(D.DOCUMENTO_ID = P.DOCUMENTO_ID) 
    WHERE D.CLIENTE_ID = @CLIENTE_ID AND D.NRO_REMITO = @PEDIDO_ID AND P.PRODUCTO_ID = @PRODUCTO_ID
    AND P.PALLET_PICKING = @NRO_CONTENEDORA AND ISNULL(NRO_LOTE,'') = ISNULL(@NRO_LOTE,'') AND ISNULL(NRO_PARTIDA,'') = ISNULL(@NRO_PARTIDA,'') AND ISNULL(NRO_SERIE,'') = ISNULL(@NRO_SERIE,'')
	UNION
    SELECT D.NRO_REMITO, P.*
    FROM DOCUMENTO D INNER JOIN PICKING P ON(D.DOCUMENTO_ID = P.DOCUMENTO_ID) 
    WHERE D.CLIENTE_ID = @CLIENTE_ID AND D.NRO_REMITO = @PEDIDO_ID AND P.PRODUCTO_ID = @PRODUCTO_ID
    AND P.PALLET_CONTROLADO = '0' AND ISNULL(NRO_LOTE,'') = ISNULL(@NRO_LOTE,'') AND ISNULL(NRO_PARTIDA,'') = ISNULL(@NRO_PARTIDA,'') AND ISNULL(NRO_SERIE,'') = ISNULL(@NRO_SERIE,'')
	
    DECLARE cur_linea CURSOR FOR
    SELECT DISTINCT NRO_LINEA, CANT_CONFIRMADA
    FROM TMP_EMPAQUE_CONTENEDORA
    WHERE CLIENTE_ID = @CLIENTE_ID AND NRO_REMITO = @PEDIDO_ID AND PRODUCTO_ID = @PRODUCTO_ID
    AND PALLET_CONTROLADO <> '0' AND ISNULL(NRO_LOTE,'') = ISNULL(@NRO_LOTE,'') AND ISNULL(NRO_PARTIDA,'') = ISNULL(@NRO_PARTIDA,'') AND ISNULL(NRO_SERIE,'') = ISNULL(@NRO_SERIE,'')
    
    OPEN cur_linea 
    FETCH cur_linea
    INTO @NRO_LINEA, @CANT_CONFIRMADA
    
    WHILE (@@FETCH_STATUS = 0 AND @CANT_CONTROLADA > 0)
        BEGIN
            
            IF @CANT_CONTROLADA > @CANT_CONFIRMADA
                BEGIN
                    SET @CANTIDAD_EMPAQUE = @CANT_CONFIRMADA
                    SET @CANT_CONTROLADA = @CANT_CONTROLADA - @CANT_CONFIRMADA
                END
            ELSE
                BEGIN
                    SET @CANTIDAD_EMPAQUE = @CANT_CONTROLADA
                    SET @CANT_CONTROLADA = @CANT_CONTROLADA - @CANT_CONFIRMADA
                END
            
            UPDATE TMP_EMPAQUE_CONTENEDORA
            SET CANTIDAD = CANT_CONFIRMADA - @CANTIDAD_EMPAQUE,
                CANT_CONFIRMADA = CANT_CONFIRMADA - @CANTIDAD_EMPAQUE
            WHERE NRO_LINEA = @NRO_LINEA AND CLIENTE_ID = @CLIENTE_ID AND NRO_REMITO = @PEDIDO_ID 
            AND PRODUCTO_ID = @PRODUCTO_ID AND PALLET_PICKING = @NRO_CONTENEDORA AND PALLET_CONTROLADO <> '0'
            
            SELECT @CANTIDAD = CANTIDAD
            FROM TMP_EMPAQUE_CONTENEDORA
            WHERE NRO_LINEA = @NRO_LINEA AND CLIENTE_ID = @CLIENTE_ID AND NRO_REMITO = @PEDIDO_ID 
            AND PRODUCTO_ID = @PRODUCTO_ID AND PALLET_PICKING = @NRO_CONTENEDORA AND PALLET_CONTROLADO <> '0'
            AND CANT_CONFIRMADA = 0
            
            IF @CANTIDAD IS NULL
				SET @CANTIDAD = 0
            
            IF EXISTS(
                    SELECT 1 FROM TMP_EMPAQUE_CONTENEDORA 
                    WHERE NRO_LINEA = @NRO_LINEA AND CLIENTE_ID = @CLIENTE_ID 
                    AND NRO_REMITO = @PEDIDO_ID AND PRODUCTO_ID = @PRODUCTO_ID  
                    AND PALLET_CONTROLADO = '0'
                )
                BEGIN
                    UPDATE TMP_EMPAQUE_CONTENEDORA
                    SET CANTIDAD = CANTIDAD + @CANTIDAD_EMPAQUE + @CANTIDAD,
                        CANT_CONFIRMADA = CANT_CONFIRMADA + @CANTIDAD_EMPAQUE
                    WHERE NRO_LINEA = @NRO_LINEA AND CLIENTE_ID = @CLIENTE_ID 
                    AND NRO_REMITO = @PEDIDO_ID AND PRODUCTO_ID = @PRODUCTO_ID 
                    AND PALLET_CONTROLADO = '0'
                END
            ELSE
                INSERT INTO TMP_EMPAQUE_CONTENEDORA
                SELECT D.NRO_REMITO, P.PICKING_ID, P.DOCUMENTO_ID, P.NRO_LINEA, P.CLIENTE_ID, P.PRODUCTO_ID, P.VIAJE_ID, P.TIPO_CAJA, P.DESCRIPCION, 
                       P.CANTIDAD - (P.CANT_CONFIRMADA - @CANTIDAD_EMPAQUE) [CANTIDAD], 
                       P.NAVE_COD, P.POSICION_COD, P.RUTA, P.PROP1, P.FECHA_INICIO, P.FECHA_FIN, P.USUARIO, 
                       @CANTIDAD_EMPAQUE [CANT_CONFIRMADA], -- Cantidad Controlada
                       @NRO_CONTENEDORA [PALLET_PICKING], -- Nro Contenedora
                       P.SALTO_PICKING, 
                       '0' [PALLET_CONTROLADO], -- No esta en Contenedora
                       P.USUARIO_CONTROL_PICK, P.ST_ETIQUETAS, P.ST_CAMION, P.FACTURADO, P.FIN_PICKING, P.ST_CONTROL_EXP, P.FECHA_CONTROL_PALLET, 
                       P.TERMINAL_CONTROL_PALLET, P.FECHA_CONTROL_EXP, P.USUARIO_CONTROL_EXP, P.TERMINAL_CONTROL_EXP, P.FECHA_CONTROL_FAC, 
                       P.USUARIO_CONTROL_FAC, P.TERMINAL_CONTROL_FAC, P.VEHICULO_ID, P.PALLET_COMPLETO, P.HIJO, P.QTY_CONTROLADO, P.PALLET_FINAL, 
                       P.PALLET_CERRADO, P.USUARIO_PF, P.TERMINAL_PF, P.REMITO_IMPRESO, P.NRO_REMITO_PF, P.PICKING_ID_REF, P.BULTOS_CONTROLADOS, 
                       P.BULTOS_NO_CONTROLADOS, P.FLG_PALLET_HOMBRE, P.TRANSF_TERMINADA,P.NRO_LOTE,P.NRO_PARTIDA,P.NRO_SERIE
                FROM DOCUMENTO D INNER JOIN PICKING P ON(D.DOCUMENTO_ID = P.DOCUMENTO_ID) 
                WHERE P.NRO_LINEA = @NRO_LINEA AND D.CLIENTE_ID = @CLIENTE_ID AND D.NRO_REMITO = @PEDIDO_ID AND P.PRODUCTO_ID = @PRODUCTO_ID 
                AND PALLET_PICKING = @NRO_CONTENEDORA AND P.PALLET_CONTROLADO <> '0'
            
            DELETE PICKING
            WHERE CLIENTE_ID = @CLIENTE_ID AND PRODUCTO_ID = @PRODUCTO_ID 
            AND PALLET_PICKING = @NRO_CONTENEDORA AND PALLET_CONTROLADO <> '0'
            AND PICKING_ID IN(SELECT PICKING_ID FROM TMP_EMPAQUE_CONTENEDORA 
                            WHERE NRO_LINEA = @NRO_LINEA AND CLIENTE_ID = @CLIENTE_ID 
                            AND NRO_REMITO = @PEDIDO_ID AND PRODUCTO_ID = @PRODUCTO_ID 
                            AND PALLET_PICKING = @NRO_CONTENEDORA AND PALLET_CONTROLADO <> '0' 
                            AND CANT_CONFIRMADA = 0)
            
            UPDATE PICKING
            SET CANTIDAD = TMP.CANTIDAD,
                CANT_CONFIRMADA = TMP.CANT_CONFIRMADA
            FROM TMP_EMPAQUE_CONTENEDORA TMP 
            WHERE TMP.NRO_LINEA = @NRO_LINEA AND TMP.CLIENTE_ID = @CLIENTE_ID AND TMP.NRO_REMITO = @PEDIDO_ID
            AND TMP.PRODUCTO_ID = @PRODUCTO_ID AND TMP.PALLET_CONTROLADO <> '0'
            AND PICKING.PICKING_ID = TMP.PICKING_ID
            
            IF NOT EXISTS(SELECT 1 
                            FROM DOCUMENTO D INNER JOIN PICKING P ON(D.DOCUMENTO_ID = P.DOCUMENTO_ID) 
                            WHERE P.NRO_LINEA = @NRO_LINEA AND D.CLIENTE_ID = @CLIENTE_ID 
                            AND D.NRO_REMITO = @PEDIDO_ID AND PRODUCTO_ID = @PRODUCTO_ID 
                            AND P.PALLET_CONTROLADO = '0')
                INSERT INTO PICKING(DOCUMENTO_ID, NRO_LINEA, CLIENTE_ID, PRODUCTO_ID, VIAJE_ID, TIPO_CAJA, DESCRIPCION, CANTIDAD, NAVE_COD, 
                POSICION_COD, RUTA, PROP1, FECHA_INICIO, FECHA_FIN, USUARIO, CANT_CONFIRMADA, PALLET_PICKING, SALTO_PICKING, PALLET_CONTROLADO, 
                USUARIO_CONTROL_PICK, ST_ETIQUETAS, ST_CAMION, FACTURADO, FIN_PICKING, ST_CONTROL_EXP, FECHA_CONTROL_PALLET, 
                TERMINAL_CONTROL_PALLET, FECHA_CONTROL_EXP, USUARIO_CONTROL_EXP, TERMINAL_CONTROL_EXP, FECHA_CONTROL_FAC, USUARIO_CONTROL_FAC, 
                TERMINAL_CONTROL_FAC, VEHICULO_ID, PALLET_COMPLETO, HIJO, QTY_CONTROLADO, PALLET_FINAL, PALLET_CERRADO, USUARIO_PF, TERMINAL_PF, 
                REMITO_IMPRESO, NRO_REMITO_PF, PICKING_ID_REF, BULTOS_CONTROLADOS, BULTOS_NO_CONTROLADOS, FLG_PALLET_HOMBRE, TRANSF_TERMINADA,NRO_LOTE,NRO_PARTIDA,NRO_SERIE)
                SELECT DOCUMENTO_ID, NRO_LINEA, CLIENTE_ID, PRODUCTO_ID, VIAJE_ID, TIPO_CAJA, DESCRIPCION, CANTIDAD, NAVE_COD, POSICION_COD, 
                RUTA, PROP1, FECHA_INICIO, FECHA_FIN, USUARIO, CANT_CONFIRMADA, PALLET_PICKING, SALTO_PICKING, PALLET_CONTROLADO, USUARIO_CONTROL_PICK, 
                ST_ETIQUETAS, ST_CAMION, FACTURADO, FIN_PICKING, ST_CONTROL_EXP, FECHA_CONTROL_PALLET, TERMINAL_CONTROL_PALLET, FECHA_CONTROL_EXP, 
                USUARIO_CONTROL_EXP, TERMINAL_CONTROL_EXP, FECHA_CONTROL_FAC, USUARIO_CONTROL_FAC, TERMINAL_CONTROL_FAC, VEHICULO_ID, PALLET_COMPLETO, 
                HIJO, QTY_CONTROLADO, PALLET_FINAL, PALLET_CERRADO, USUARIO_PF, TERMINAL_PF, REMITO_IMPRESO, NRO_REMITO_PF, PICKING_ID_REF, 
                BULTOS_CONTROLADOS, BULTOS_NO_CONTROLADOS, FLG_PALLET_HOMBRE, TRANSF_TERMINADA,NRO_LOTE,NRO_PARTIDA,NRO_SERIE
                FROM TMP_EMPAQUE_CONTENEDORA
                WHERE NRO_LINEA = @NRO_LINEA AND CLIENTE_ID = @CLIENTE_ID 
                AND NRO_REMITO = @PEDIDO_ID AND PRODUCTO_ID = @PRODUCTO_ID 
                AND PALLET_PICKING = @NRO_CONTENEDORA AND PALLET_CONTROLADO = '0'
            ELSE
                UPDATE PICKING
                SET CANTIDAD = TMP.CANTIDAD,
                    CANT_CONFIRMADA = TMP.CANT_CONFIRMADA
                FROM TMP_EMPAQUE_CONTENEDORA TMP 
                WHERE TMP.NRO_LINEA = @NRO_LINEA AND TMP.CLIENTE_ID = @CLIENTE_ID 
                AND TMP.NRO_REMITO = @PEDIDO_ID AND TMP.PRODUCTO_ID = @PRODUCTO_ID 
                AND PICKING.PICKING_ID = TMP.PICKING_ID AND PICKING.PALLET_PICKING = TMP.PALLET_PICKING
                AND PICKING.PALLET_CONTROLADO = '0'
        
            FETCH cur_linea
            INTO @NRO_LINEA, @CANT_CONFIRMADA
        END
    
    CLOSE cur_linea 
    DEALLOCATE cur_linea
    
    DELETE TMP_EMPAQUE_CONTENEDORA WHERE CLIENTE_ID = @CLIENTE_ID AND NRO_REMITO = @PEDIDO_ID AND PRODUCTO_ID = @PRODUCTO_ID AND ISNULL(NRO_LOTE,'') = ISNULL(@NRO_LOTE,'') AND ISNULL(NRO_PARTIDA,'') = ISNULL(@NRO_PARTIDA,'') AND ISNULL(NRO_SERIE,'') = ISNULL(@NRO_SERIE,'')

END
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO

-- =============================================
-- Author:		<Author,,Name>
-- Create date: <Create Date,,>
-- Description:	<Description,,>
-- =============================================
ALTER PROCEDURE [dbo].[reAbrirProductoEnContenedora]
	-- Add the parameters for the stored procedure here
	@cliente_id		varchar(15) OUTPUT,
	@nro_remito		varchar(30) OUTPUT,
	@producto_id	varchar(30) OUTPUT,
	@cant_elegida	numeric(20,5) OUTPUT,
	@contenedora	numeric(20,0) OUTPUT,
	@check			char(1) OUTPUT

AS
BEGIN

	DECLARE @picking_id			numeric(20,0)
	DECLARE @cant_confirmada	numeric(20,5)
	DECLARE @CANT_A_LIBERAR		NUMERIC(20,5)
	DECLARE @CANT_A_CERRAR		NUMERIC(20,5)
	DECLARE @cursorFREE			cursor
	
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;


    
	IF @check = '1'
	BEGIN
		--TENGO QUE CONTROLAR SI AUMENTO O DISMINUYO LA CANTIDAD ELEJIDA A EMPACAR
		--SELECCIONO LOS PRODUCTOS DENTRO DEL EMPAQUE
		SELECT	@CANT_CONFIRMADA = SUM(CANT_CONFIRMADA)
		FROM	PICKING
		WHERE	PALLET_PICKING = @CONTENEDORA
				AND PALLET_CONTROLADO='1'
				AND PRODUCTO_ID = @PRODUCTO_ID
				AND CLIENTE_ID = @CLIENTE_ID	

		--IF @CANT_ELEGIDA > @CANT_CONFIRMADA
		--BEGIN
			--SE AUMENTO LA CANTIDAD DE UN PRODUCTO AL REABRIR EL CONTENEDOR
			--SET @CANT_A_CERRAR = @CANT_ELEGIDA - @CANT_CONFIRMADA
			--SE AGREGA LA CANTIDAD RESTANTE AL EMPAQUE
			--EXEC CerrarProductoEnContenedora @cliente_id, @nro_remito, @producto_id, @CANT_A_CERRAR, @contenedora
		--END
		IF (@CANT_ELEGIDA = @CANT_CONFIRMADA)
		BEGIN
		--SELECCIONO EL PRODUCTO COMPLETO PARA LIBERAR
			UPDATE	PICKING
			SET		PALLET_CONTROLADO = '0'
			WHERE	PALLET_PICKING = @contenedora
					and producto_id = @producto_id
		END
		ELSE
		BEGIN
			IF @CANT_ELEGIDA < @CANT_CONFIRMADA
			BEGIN
				--SE DISMINUYO LA CANTIDAD DE UN PRODUCTO AL REABRIR EL CONTENEDOR
				--SET @CANT_A_LIBERAR = @CANT_CONFIRMADA - @CANT_ELEGIDA

				SET @CANT_A_LIBERAR = @CANT_ELEGIDA
				
				SET @cursorFREE = cursor FOR
				SELECT	PICKING_ID,
						CANT_CONFIRMADA
				FROM	PICKING
				WHERE	PALLET_PICKING = @CONTENEDORA
						AND PALLET_CONTROLADO = '1'
						AND PRODUCTO_ID = @PRODUCTO_ID
						AND CLIENTE_ID = @CLIENTE_ID
				ORDER BY CANT_CONFIRMADA

				OPEN @cursorFREE
				FETCH NEXT FROM @cursorFREE INTO @picking_id, @cant_confirmada

				WHILE ((@@FETCH_STATUS = 0) AND (@CANT_A_LIBERAR - @cant_confirmada >= 0))
				BEGIN
						SET @CANT_A_LIBERAR = @CANT_A_LIBERAR - @cant_confirmada

						UPDATE	picking
						SET		pallet_picking = @contenedora,
								pallet_controlado = '0'
						WHERE	picking_id = @picking_id

					FETCH NEXT FROM @cursorFREE INTO @picking_id, @cant_confirmada
				END
			

				--en este punto si @cant_elegida_AUX < 0 entonces tenemos seleccionado el producto que hay que "partir"
					IF ((@CANT_A_LIBERAR - @cant_confirmada < 0) AND (@cant_a_liberar > 0) AND (@@fetch_status=0))
					BEGIN
						insert into picking 
						(DOCUMENTO_ID, NRO_LINEA, CLIENTE_ID, PRODUCTO_ID, VIAJE_ID, TIPO_CAJA, DESCRIPCION, CANTIDAD, NAVE_COD, POSICION_COD, RUTA, PROP1, FECHA_INICIO, FECHA_FIN, USUARIO, CANT_CONFIRMADA, PALLET_PICKING, SALTO_PICKING, PALLET_CONTROLADO, USUARIO_CONTROL_PICK, ST_ETIQUETAS, ST_CAMION, FACTURADO, FIN_PICKING, ST_CONTROL_EXP, FECHA_CONTROL_PALLET, TERMINAL_CONTROL_PALLET, FECHA_CONTROL_EXP, USUARIO_CONTROL_EXP, TERMINAL_CONTROL_EXP, FECHA_CONTROL_FAC, USUARIO_CONTROL_FAC, TERMINAL_CONTROL_FAC, VEHICULO_ID, PALLET_COMPLETO, HIJO, QTY_CONTROLADO, PALLET_FINAL, PALLET_CERRADO, USUARIO_PF, TERMINAL_PF, REMITO_IMPRESO, NRO_REMITO_PF, PICKING_ID_REF, BULTOS_CONTROLADOS, BULTOS_NO_CONTROLADOS, FLG_PALLET_HOMBRE, TRANSF_TERMINADA,NRO_LOTE,NRO_PARTIDA,NRO_SERIE ) 
						select	DOCUMENTO_ID,
								NRO_LINEA,
								CLIENTE_ID,
								PRODUCTO_ID,
								VIAJE_ID,
								TIPO_CAJA,
								DESCRIPCION,
								@CANT_A_LIBERAR,--CANTIDAD,     LO COMENTADO ES LO QUE ESTABA ANTES
								NAVE_COD,
								POSICION_COD,
								RUTA,
								PROP1,
								FECHA_INICIO,
								FECHA_FIN,
								USUARIO,
								@CANT_A_LIBERAR, --CANT_CONFIRMADA
								PALLET_PICKING,
								SALTO_PICKING,
								'0', --PALLET_CONTROLADO
								USUARIO_CONTROL_PICK,
								ST_ETIQUETAS,
								ST_CAMION,
								FACTURADO,
								FIN_PICKING,
								ST_CONTROL_EXP,
								FECHA_CONTROL_PALLET,
								TERMINAL_CONTROL_PALLET,
								FECHA_CONTROL_EXP,
								USUARIO_CONTROL_EXP,
								TERMINAL_CONTROL_EXP,
								FECHA_CONTROL_FAC,
								USUARIO_CONTROL_FAC,
								TERMINAL_CONTROL_FAC,
								VEHICULO_ID,
								PALLET_COMPLETO,
								HIJO,
								QTY_CONTROLADO,
								PALLET_FINAL,
								PALLET_CERRADO,
								USUARIO_PF,
								TERMINAL_PF,
								REMITO_IMPRESO,
								NRO_REMITO_PF,
								PICKING_ID_REF,
								BULTOS_CONTROLADOS,
								BULTOS_NO_CONTROLADOS,
								FLG_PALLET_HOMBRE,
								TRANSF_TERMINADA,NRO_LOTE,NRO_PARTIDA,NRO_SERIE
						from picking where picking_id = @picking_id

						UPDATE PICKING SET	CANT_CONFIRMADA = CANT_CONFIRMADA - @CANT_A_LIBERAR, 
											CANTIDAD = CANT_CONFIRMADA - @CANT_A_LIBERAR --ESTA LINEA ESTA CORREGIDA, CUALQUIER COSA BORRARLA
						WHERE PICKING_ID = @PICKING_ID
					END

				CLOSE @cursorFREE
				DEALLOCATE @cursorFREE
			END
		END
	END
END
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO

ALTER PROCEDURE [dbo].[REGENERAR_STOCK]
AS
BEGIN

	DISABLE TRIGGER [RL_ACT_STOCK_DELETE] ON [RL_DET_DOC_TRANS_POSICION];

	DISABLE TRIGGER [RL_ACT_STOCK_INSERT] ON [RL_DET_DOC_TRANS_POSICION];

	DISABLE TRIGGER [RL_ACT_STOCK_UPDATE] ON [RL_DET_DOC_TRANS_POSICION];



	begin tran
	delete AGUAS_DESA_STOCK.DBO.STOCK

	insert into AGUAS_DESA_STOCK.DBO.STOCK
	SELECT [COD. CLIENTE] AS CLIENTE_ID, [COD. PRODUCTO]  AS PRODUCTO_ID , DESCRIPCION, SUM(CANTIDAD) AS CANTIDAD, NAVE, NAVEID, [CAT. LOG.] AS CAT_LOG_ID 
	FROM 
		(SELECT 	 T2.CLIENTEID								[COD. CLIENTE]
			,C.RAZON_SOCIAL								[RAZON SOCIAL]
			,T2.PRODUCTOID								[COD. PRODUCTO]
			,P.DESCRIPCION								[DESCRIPCION]
			,T2.UNIDAD_ID								[UNIDAD]
			,SUM(ISNULL(T2.CANTIDAD,0))					[CANTIDAD]
			,T2.STORAGE									[NAVE]
			,T2.NAVEID
			,T2.CALLECOD								[CALLE]
			,T2.COLUMNACOD								[COLUMNA]
			,T2.NIVELCOD								[NIVEL]
			,T2.EST_MERC_ID								[EST. MERC.]
			,T2.CATEGLOGID								[CAT. LOG.]
			,T2.NRO_SERIE								[NRO. SERIE]
			,T2.NRO_BULTO								[NRO. BULTO]
			,T2.NRO_LOTE								[NRO. LOTE]
			,T2.NRO_DESPACHO							[NRO. DESPACHO]
			,T2.NRO_PARTIDA								[NRO. PARTIDA]
			,T2.PROP1									[NRO_PALLET]
			,T2.PROP2									[LOTE_PROVEEDOR]
			,T2.PROP3 									[NRO. ANALISIS]
			,CONVERT(VARCHAR,T2.FECHA_VENCIMIENTO,103)	[FECHA_VENCIMIENTO]
			,T2.PESO									[PESO]
			,T2.UNIDAD_PESO								[UNIDAD PESO]
			,T2.VOLUMEN									[VOLUMEN]
			,T2.UNIDAD_VOLUMEN							[UNIDAD VOLUMEN]
			,T2.MONEDA_ID								[MONEDA]
			,T2.COSTO									[COSTO]
			,T2.NOMBRE									[PROVEEDOR]
			,T2.FAMILIA_ID								[FAMILIA]
			,T2.SUB_FAMILIA_ID							[SUB-FAMILIA]
			,CONVERT(VARCHAR,T2.FECHA_CPTE,103)			[FECHA CPTE.]
	FROM    CLIENTE C (NOLOCK),PRODUCTO P (NOLOCK)
			,(	SELECT	 T2.CLIENTEID 			,T2.PRODUCTOID 			,SUM(T2.CANTIDAD) AS CANTIDAD 
						,T2.NRO_SERIE 			,T2.NRO_LOTE 			,T2.NRO_PARTIDA 
						,T2.FECHA_VENCIMIENTO 	,T2.NRO_DESPACHO		,T2.NRO_BULTO 
						,T2.PESO 				,T2.VOLUMEN 			,T2.TIE_IN 
						,T2.EST_MERC_ID 		,T2.UNIDAD_PESO 		,T2.UNIDAD_VOLUMEN 
						,T2.PROP1 				,T2.PROP2 				,T2.PROP3 
						,T2.UNIDAD_ID 			,T2.MONEDA_ID 			,T2.COSTO 
						,T2.CAT_LOG_ID_FINAL	,T2.DESCRIPCION 
				FROM	(SELECT	 DD.CLIENTE_ID CLIENTEID			,DD.PRODUCTO_ID PRODUCTOID 
								,SUM(ISNULL(DD.CANTIDAD,0))AS CANTIDAD 
								,DD.NRO_SERIE 						,DD.NRO_LOTE 
								,DD.NRO_PARTIDA 					,DD.FECHA_VENCIMIENTO 
								,DD.NRO_DESPACHO					,DD.NRO_BULTO 
								,DD.PESO 							,DD.UNIDAD_PESO 
								,DD.VOLUMEN 						,DD.UNIDAD_VOLUMEN 
								,DD.TIE_IN							,DD.EST_MERC_ID 
								,DD.PROP1 							,DD.PROP2 
								,DD.PROP3 							,DD.UNIDAD_ID 
								,DD.MONEDA_ID						,DD.COSTO 
								,DD.CAT_LOG_ID_FINAL 				,DD.DESCRIPCION 
						FROM	DOCUMENTO D (NOLOCK),DET_DOCUMENTO DD (NOLOCK)
						WHERE	D.DOCUMENTO_ID = DD.DOCUMENTO_ID 
								AND D.STATUS = 'D20'
								AND D.TIPO_OPERACION_ID = 'EGR'
						GROUP BY 
								 DD.CLIENTE_ID 		,DD.PRODUCTO_ID 		,DD.NRO_SERIE 
								,DD.NRO_LOTE 		,DD.NRO_PARTIDA 		,DD.FECHA_VENCIMIENTO 
								,DD.NRO_DESPACHO 	,DD.NRO_BULTO 			,DD.PESO 
								,DD.UNIDAD_PESO 	,DD.VOLUMEN 			,DD.UNIDAD_VOLUMEN 
								,DD.TIE_IN 			,DD.EST_MERC_ID 		,DD.PROP1 
								,DD.PROP2			,DD.PROP3 				,DD.UNIDAD_ID 
								,DD.MONEDA_ID 		,DD.COSTO 				,DD.CAT_LOG_ID_FINAL 
								,DD.DESCRIPCION 
						UNION ALL 
						SELECT   DD.CLIENTE_ID CLIENTEID ,DD.PRODUCTO_ID PRODUCTOID 
								,SUM(ISNULL(DD.CANTIDAD,0)) AS CANTIDAD 
								,DD.NRO_SERIE 
								,DD.NRO_LOTE 			,DD.NRO_PARTIDA 
								,DD.FECHA_VENCIMIENTO 	,DD.NRO_DESPACHO 
								,DD.NRO_BULTO 			,DD.PESO 
								,DD.UNIDAD_PESO 		,DD.VOLUMEN 
								,DD.UNIDAD_VOLUMEN		,DD.TIE_IN 
								,DD.EST_MERC_ID 		,DD.PROP1 
								,DD.PROP2 				,DD.PROP3 
								,DD.UNIDAD_ID 			,DD.MONEDA_ID  
								,DD.COSTO				,DD.CAT_LOG_ID_FINAL 
								,DD.DESCRIPCION 
						FROM    DET_DOCUMENTO DD (NOLOCK),DET_DOCUMENTO_TRANSACCION DDT (NOLOCK)
								,DOCUMENTO_TRANSACCION DT (NOLOCK)
						WHERE	1<>0 
								AND DDT.DOCUMENTO_ID = DD.DOCUMENTO_ID 
								AND DDT.NRO_LINEA_DOC = DD.NRO_LINEA 
								AND DT.DOC_TRANS_ID = DDT.DOC_TRANS_ID 
								AND DT.STATUS = 'T10'
								AND DT.TIPO_OPERACION_ID = 'EGR'
								AND NOT EXISTS  (	SELECT	RL_ID 
													FROM	RL_DET_DOC_TRANS_POSICION RL (NOLOCK)
													WHERE	RL.DOC_TRANS_ID_EGR = DDT.DOC_TRANS_ID 
															AND RL.NRO_LINEA_TRANS_EGR = DDT.NRO_LINEA_TRANS )
						GROUP BY 
								 DD.CLIENTE_ID	,DD.PRODUCTO_ID ,DD.NRO_SERIE 
								,DD.NRO_LOTE 	,DD.NRO_PARTIDA ,DD.FECHA_VENCIMIENTO 
								,DD.NRO_DESPACHO,DD.NRO_BULTO 	,DD.PESO 
								,DD.UNIDAD_PESO ,DD.VOLUMEN 	,DD.UNIDAD_VOLUMEN 
								,DD.TIE_IN 		,DD.EST_MERC_ID ,DD.PROP1 
								,DD.PROP2 		,DD.PROP3 		,DD.UNIDAD_ID 
								,DD.MONEDA_ID 	,DD.COSTO 		,DD.CAT_LOG_ID_FINAL 
								,DD.DESCRIPCION 
					) T2  
			WHERE 1<>0  
			GROUP BY  
				   T2.CLIENTEID 
				   ,T2.PRODUCTOID 
				   ,T2.NRO_SERIE  
				   ,T2.NRO_LOTE 
				   ,T2.NRO_PARTIDA 
				   ,T2.FECHA_VENCIMIENTO 
				   ,T2.NRO_DESPACHO 
				   ,T2.NRO_BULTO 
				   ,T2.PESO 
				   ,T2.UNIDAD_PESO 
				   ,T2.VOLUMEN 
				   ,T2.UNIDAD_VOLUMEN 
				   ,T2.TIE_IN 
				   ,T2.EST_MERC_ID 
				   ,T2.PROP1 
				   ,T2.PROP2 
				   ,T2.PROP3 
				   ,T2.UNIDAD_ID 
				   ,T2.MONEDA_ID 
				   ,T2.COSTO 
				   ,T2.CAT_LOG_ID_FINAL 
				   ,T2.DESCRIPCION 
		   ) T1 RIGHT OUTER JOIN 
				  (SELECT RL.CAT_LOG_ID AS CATEGLOGID 
			  ,DD.CLIENTE_ID AS CLIENTEID 
			  ,DD.PRODUCTO_ID AS PRODUCTOID 
			  ,SUM(ISNULL(RL.CANTIDAD,0)) AS CANTIDAD 
			  ,DD.NRO_SERIE 
			  ,DD.NRO_LOTE 
			  ,DD.FECHA_VENCIMIENTO 
			  ,DD.NRO_DESPACHO 
			  ,DD.NRO_BULTO 
			  ,DD.NRO_PARTIDA 
			  ,DD.PESO AS PESO 
			  ,DD.UNIDAD_PESO 
			  ,DD.VOLUMEN AS VOLUMEN 
			  ,DD.UNIDAD_VOLUMEN  
			  ,PROD.KIT AS KIT  
			  ,DD.TIE_IN AS TIE_IN 
			  ,DD.NRO_TIE_IN_PADRE AS TIE_IN_PADRE 
			  ,DD.NRO_TIE_IN AS NRO_TIE_IN 
			  ,RL.EST_MERC_ID 
			  ,ISNULL(N.NAVE_COD,N2.NAVE_COD) AS STORAGE 
			  ,ISNULL(RL.NAVE_ACTUAL,P.NAVE_ID) AS NAVEID 
			  ,CALN.CALLE_COD AS CALLECOD 
			  ,CALN.CALLE_ID AS CALLEID 
			  ,COLN.COLUMNA_COD AS COLUMNACOD 
			  ,COLN.COLUMNA_ID AS COLUMNAID 
			  ,NN.NIVEL_COD AS NIVELCOD 
			  ,NN.NIVEL_ID AS NIVELID 
			  ,DD.PROP1 
			  ,DD.PROP2 
			  ,DD.PROP3 
			  ,DD.UNIDAD_ID 
			  ,DD.MONEDA_ID 
			  ,DD.COSTO 
			  ,S.NOMBRE 
			  ,DD.DESCRIPCION 
			  ,PROD.FAMILIA_ID  
			  ,PROD.SUB_FAMILIA_ID 
			  ,D.FECHA_CPTE 
		FROM  RL_DET_DOC_TRANS_POSICION RL (NOLOCK)
			  LEFT OUTER JOIN NAVE N (NOLOCK)            ON RL.NAVE_ACTUAL = N.NAVE_ID 
			  LEFT OUTER JOIN POSICION P  (NOLOCK)       ON RL.POSICION_ACTUAL = P.POSICION_ID 
			  LEFT OUTER JOIN NAVE N2   (NOLOCK)         ON P.NAVE_ID = N2.NAVE_ID 
			  LEFT OUTER JOIN CALLE_NAVE CALN (NOLOCK)   ON P.CALLE_ID = CALN.CALLE_ID 
			  LEFT OUTER JOIN COLUMNA_NAVE COLN (NOLOCK) ON P.COLUMNA_ID = COLN.COLUMNA_ID
			  LEFT OUTER JOIN NIVEL_NAVE NN  (NOLOCK)    ON P.NIVEL_ID = NN.NIVEL_ID
			  ,DET_DOCUMENTO_TRANSACCION DDT (NOLOCK)
			  ,DET_DOCUMENTO DD (NOLOCK) INNER JOIN DOCUMENTO D (NOLOCK) ON(DD.DOCUMENTO_ID=D.DOCUMENTO_ID) LEFT JOIN SUCURSAL S 
			  ON(S.SUCURSAL_ID=D.SUCURSAL_ORIGEN AND S.CLIENTE_ID=D.CLIENTE_ID)
			  ,CLIENTE C (NOLOCK)
			  ,PRODUCTO PROD (NOLOCK)
			  ,CATEGORIA_LOGICA CL (NOLOCK)
			  ,DOCUMENTO_TRANSACCION DT (NOLOCK)
		WHERE 1<>0 
			  AND RL.DOC_TRANS_ID = DDT.DOC_TRANS_ID 
			  AND RL.NRO_LINEA_TRANS = DDT.NRO_LINEA_TRANS 
			  AND DDT.DOCUMENTO_ID = DD.DOCUMENTO_ID 
			  AND DDT.DOC_TRANS_ID = DT.DOC_TRANS_ID 
						 AND DDT.NRO_LINEA_DOC = DD.NRO_LINEA 
			  AND DD.CLIENTE_ID = C.CLIENTE_ID 
			  AND DD.PRODUCTO_ID = PROD.PRODUCTO_ID 
			  AND DD.CLIENTE_ID = PROD.CLIENTE_ID 
			  AND RL.CAT_LOG_ID = CL.CAT_LOG_ID 
			  AND RL.CLIENTE_ID = CL.CLIENTE_ID 
			  AND RL.DISPONIBLE= '1'
			  AND ISNULL(P.POS_LOCKEADA,'0')='0'
			  AND ISNULL(N.DEPOSITO_ID,N2.DEPOSITO_ID)='DEFAULT'
			  AND 0 =(SELECT (CASE WHEN (COUNT (POSICION_ID))> 0 THEN 1 ELSE 0 END) AS VALOR
					  FROM RL_POSICION_PROHIBIDA_CLIENTE (NOLOCK)
					  WHERE POSICION_ID = ISNULL(P.NIVEL_ID,0)
							AND CLIENTE_ID= DD.CLIENTE_ID)
				/*
			  AND 1 = (SELECT (CASE WHEN (COUNT (CLIENTE_ID))> 0 THEN 1 ELSE 0 END) AS VALOR 
					   FROM   RL_SYS_CLIENTE_USUARIO (NOLOCK)
					   WHERE  CLIENTE_ID = DD.CLIENTE_ID
							  AND USUARIO_ID='SGOMEZ')*/
		 GROUP BY RL.CAT_LOG_ID 
				 ,DD.CLIENTE_ID 
				 ,DD.PRODUCTO_ID 
				 ,DD.NRO_SERIE 
				 ,DD.NRO_LOTE 
				 ,DD.FECHA_VENCIMIENTO 
				 ,DD.NRO_DESPACHO 
				 ,DD.NRO_BULTO 
				 ,DD.NRO_PARTIDA 
				 ,DD.PESO 
				 ,DD.UNIDAD_PESO 
				 ,DD.VOLUMEN 
				 ,DD.UNIDAD_VOLUMEN 
				 ,RL.NAVE_ACTUAL 
				 ,P.NAVE_ID 
				 ,N.NAVE_COD  
				 ,N2.NAVE_COD 
				 ,CALN.CALLE_COD 
				 ,CALN.CALLE_ID 
				 ,COLN.COLUMNA_COD 
				 ,COLN.COLUMNA_ID 
				 ,NN.NIVEL_COD 
				 ,NN.NIVEL_ID 
				 ,PROD.KIT 
				 ,DD.TIE_IN 
				 ,DD.NRO_TIE_IN_PADRE 
				 ,DD.NRO_TIE_IN 
				 ,RL.EST_MERC_ID 
				 ,DD.PROP1 
				 ,DD.PROP2 
				 ,DD.PROP3 
				 ,DD.UNIDAD_ID 
				 ,DD.MONEDA_ID 
				 ,DD.COSTO 
				 ,S.NOMBRE 
				 ,DD.DESCRIPCION 
				 ,PROD.FAMILIA_ID 
				 ,PROD.SUB_FAMILIA_ID 
				 ,D.FECHA_CPTE 
				 ) T2 ON (	ISNULL(T2.CLIENTEID,0) = ISNULL(T1.CLIENTEID,0)
							AND ISNULL(T2.PRODUCTOID,0) = ISNULL(T1.PRODUCTOID,0) 
							AND ISNULL(T2.NRO_SERIE,0) = ISNULL(T1.NRO_SERIE,0)
							AND ISNULL(T2.NRO_LOTE,0) = ISNULL(T1.NRO_LOTE,0)
							AND ISNULL(T2.NRO_DESPACHO,0) = ISNULL(T1.NRO_DESPACHO,0)
							AND ISNULL(T2.NRO_BULTO,0) = ISNULL(T1.NRO_BULTO,0)
							AND ISNULL(T2.NRO_PARTIDA,0) = ISNULL(T1.NRO_PARTIDA,0)
							AND ISNULL(T2.PROP1,0) = ISNULL(T1.PROP1,0)
							AND ISNULL(T2.PROP2,0) = ISNULL(T1.PROP2,0)
							AND ISNULL(T2.PROP3,0) = ISNULL(T1.PROP3,0)
							AND ISNULL(T2.UNIDAD_ID,0) = ISNULL(T1.UNIDAD_ID,0)
							AND ISNULL(T2.FECHA_VENCIMIENTO,'01/01/1900') = ISNULL(T1.FECHA_VENCIMIENTO,'01/01/1900')
							AND ISNULL(T2.EST_MERC_ID,0) = ISNULL(T1.EST_MERC_ID,0) 
							AND ISNULL(T2.CATEGLOGID,0) = ISNULL(T1.CAT_LOG_ID_FINAL,0)
				  ) 
				LEFT OUTER JOIN ESTADO_MERCADERIA_RL EMRL (NOLOCK)
					ON (T2.CLIENTEID = EMRL.CLIENTE_ID 
						AND T2.EST_MERC_ID = EMRL.EST_MERC_ID) 
		 WHERE 1<>0 
			  AND T2.CLIENTEID = C.CLIENTE_ID 
			  AND T2.CLIENTEID = P.CLIENTE_ID 
			  AND T2.PRODUCTOID = P.PRODUCTO_ID 

	GROUP BY T2.CLIENTEID
			 ,T2.PRODUCTOID 
			 ,T2.STORAGE 
			 ,T2.NAVEID 
			 ,T2.CALLECOD 
			 ,T2.CALLEID 
			 ,T2.COLUMNACOD 
			 ,T2.COLUMNAID 
			 ,T2.NIVELCOD 
			 ,T2.NIVELID 
			 ,T2.EST_MERC_ID 
			 ,T2.CATEGLOGID 
			 ,T2.NRO_SERIE 
			 ,T2.NRO_BULTO 
			 ,T2.NRO_LOTE 
			 ,T2.NRO_DESPACHO 
			 ,T2.NRO_PARTIDA 
			 ,T2.PROP1 
			 ,T2.PROP2 
			 ,T2.PROP3 
			 ,T2.FECHA_VENCIMIENTO 
			 ,T2.PESO 
			 ,T2.UNIDAD_PESO 
			 ,T2.VOLUMEN 
			 ,T2.UNIDAD_VOLUMEN 
			 ,T2.KIT 
			 ,T2.TIE_IN 
			 ,T2.TIE_IN_PADRE 
			 ,T2.NRO_TIE_IN 
			 ,C.RAZON_SOCIAL 
			 ,P.DESCRIPCION 
			 ,T2.UNIDAD_ID 
			 ,T2.MONEDA_ID 
			 ,T2.COSTO 
			 ,T2.NOMBRE 
			 ,T2.DESCRIPCION 
			 ,T2.FAMILIA_ID 
			 ,T2.SUB_FAMILIA_ID 
			 ,T2.FECHA_CPTE) X
	GROUP BY X.[COD. CLIENTE] ,X.[COD. PRODUCTO] ,X.DESCRIPCION, X.NAVEID, X.NAVE, X.[CAT. LOG.];


	ENABLE TRIGGER [RL_ACT_STOCK_DELETE] ON [RL_DET_DOC_TRANS_POSICION];

	ENABLE TRIGGER [RL_ACT_STOCK_INSERT] ON [RL_DET_DOC_TRANS_POSICION];

	ENABLE TRIGGER [RL_ACT_STOCK_UPDATE] ON [RL_DET_DOC_TRANS_POSICION];

	COMMIT
END
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO

-- =============================================
-- Author:		LRojas
-- Create date: 18/04/2012
-- Description:	Procedimiento para buscar pedidos para empaquetar
-- =============================================
ALTER PROCEDURE [dbo].[registra_tmp_producto_empaque]
	@CLIENTE_ID         as varchar(15) OUTPUT,
	@PEDIDO_ID          as varchar(30) OUTPUT,
	@PRODUCTO_ID        as varchar(30) OUTPUT,
    @NRO_CONTENEDORA    as numeric(20) OUTPUT,
    @CANT_CONTROLADA    as numeric(20,5) OUTPUT,
	@NRO_LOTE			AS VARCHAR(100) OUTPUT,
	@NRO_PARTIDA		AS VARCHAR(100) OUTPUT,
	@NRO_SERIE			AS VARCHAR(50) OUTPUT
AS
BEGIN
SET NOCOUNT ON;
    
	if not exists (	select	1
					FROM	PICKING P
					INNER JOIN DET_DOCUMENTO DD ON (P.DOCUMENTO_ID = DD.DOCUMENTO_ID AND P.NRO_LINEA = DD.NRO_LINEA)
					INNER JOIN DOCUMENTO D ON (DD.DOCUMENTO_ID = D.DOCUMENTO_ID)
					where	P.cliente_id = @CLIENTE_ID
							and D.NRO_REMITO = @pedido_id
							and P.producto_id = @producto_id
							and ((P.nro_lote = @nro_lote) or (@nro_lote IS NULL OR @NRO_LOTE = ''))
							and ((P.nro_partida = @nro_partida) or (@nro_partida IS NULL OR @NRO_PARTIDA = ''))
							and ((P.nro_serie = @nro_serie) or (@nro_serie IS NULL OR @NRO_SERIE = '')))
		raiserror('No hay pendientes de empaquetado para el producto ingresado.',16,1) 

    DECLARE @CantPickeada as numeric(20,5),
            @CantControlada as numeric(20,5),
            @CantPendiente as numeric(20,5),
            @NRO_LINEA as numeric(10),
            @CANT_CONFIRMADA as numeric(20,5),
            @CANTIDAD_EMPAQUE as numeric(20,5),
			@PICKING_ID AS NUMERIC(20,0)
    
    DECLARE cur_linea CURSOR FOR
    SELECT P.PICKING_ID, 
    P.CANT_CONFIRMADA - ISNULL((SELECT TMP.CANT_CONFIRMADA FROM TMP_EMPAQUE_CONTENEDORA TMP 
                                WHERE PICKING_ID = P.PICKING_ID AND TMP.PALLET_CONTROLADO = '1'), 0) CANT_CONFIRMADA
    FROM DOCUMENTO D INNER JOIN PICKING P ON (D.DOCUMENTO_ID = P.DOCUMENTO_ID AND D.CLIENTE_ID = P.CLIENTE_ID) 
    WHERE D.CLIENTE_ID = @CLIENTE_ID AND D.NRO_REMITO = @PEDIDO_ID AND P.PRODUCTO_ID = @PRODUCTO_ID 
    AND P.CANT_CONFIRMADA - ISNULL((SELECT TMP.CANT_CONFIRMADA FROM TMP_EMPAQUE_CONTENEDORA TMP 
                                    WHERE PICKING_ID = P.PICKING_ID AND TMP.PALLET_CONTROLADO = '1'), 0) > 0
    AND P.PALLET_CONTROLADO = '0'
	AND
		(
			(P.NRO_LOTE=@NRO_LOTE AND P.NRO_PARTIDA=@NRO_PARTIDA AND P.NRO_SERIE=@NRO_SERIE)
		OR
		(
			(@NRO_LOTE IS NOT NULL OR @NRO_PARTIDA IS NOT NULL OR @NRO_SERIE IS NOT NULL)
			AND ((P.NRO_LOTE=@NRO_LOTE) OR (ISNULL(@NRO_LOTE,'')=''))
			AND ((P.NRO_PARTIDA=@NRO_PARTIDA) OR (ISNULL(@NRO_PARTIDA,'')=''))
			AND ((P.NRO_SERIE=@NRO_SERIE) OR (ISNULL(@NRO_SERIE,'')='')))
		)
    ORDER BY P.PICKING_ID
    
    OPEN cur_linea
    FETCH cur_linea
    INTO @PICKING_ID, @CANT_CONFIRMADA
    
    WHILE (@@FETCH_STATUS = 0 AND @CANT_CONTROLADA > 0)
        BEGIN
            IF NOT EXISTS(SELECT 1 FROM TMP_EMPAQUE_CONTENEDORA WHERE PICKING_ID = @PICKING_ID)
                BEGIN
                    INSERT INTO TMP_EMPAQUE_CONTENEDORA
                    SELECT D.NRO_REMITO, P.*
                    FROM DOCUMENTO D INNER JOIN PICKING P ON(D.DOCUMENTO_ID = P.DOCUMENTO_ID AND D.CLIENTE_ID = P.CLIENTE_ID) 
                    WHERE D.CLIENTE_ID = @CLIENTE_ID AND D.NRO_REMITO = @PEDIDO_ID AND P.PRODUCTO_ID = @PRODUCTO_ID
                END
            
            IF @CANT_CONTROLADA > @CANT_CONFIRMADA
                BEGIN
                    SET @CANTIDAD_EMPAQUE = @CANT_CONFIRMADA
                    SET @CANT_CONTROLADA = @CANT_CONTROLADA - @CANT_CONFIRMADA
                END
            ELSE
                BEGIN
                    SET @CANTIDAD_EMPAQUE = @CANT_CONTROLADA
                    SET @CANT_CONTROLADA = @CANT_CONTROLADA - @CANT_CONFIRMADA
                END
            
            UPDATE TMP_EMPAQUE_CONTENEDORA
            SET CANTIDAD = CANTIDAD - @CANTIDAD_EMPAQUE,
                CANT_CONFIRMADA = CANT_CONFIRMADA - @CANTIDAD_EMPAQUE
            WHERE PICKING_ID = @PICKING_ID AND PALLET_CONTROLADO = '0'
            
            IF EXISTS(
                    SELECT 1 FROM TMP_EMPAQUE_CONTENEDORA 
                    WHERE PICKING_ID = @PICKING_ID AND PALLET_PICKING = @NRO_CONTENEDORA AND PALLET_CONTROLADO <> '0'
                )
                UPDATE TMP_EMPAQUE_CONTENEDORA
                SET CANTIDAD = CANTIDAD + @CANTIDAD_EMPAQUE,
                    CANT_CONFIRMADA = CANT_CONFIRMADA + @CANTIDAD_EMPAQUE
                WHERE PICKING_ID = @PICKING_ID AND PALLET_PICKING = @NRO_CONTENEDORA AND PALLET_CONTROLADO <> '0'
            ELSE
                INSERT INTO TMP_EMPAQUE_CONTENEDORA
                SELECT D.NRO_REMITO, P.PICKING_ID, P.DOCUMENTO_ID, P.NRO_LINEA, P.CLIENTE_ID, P.PRODUCTO_ID, P.VIAJE_ID, P.TIPO_CAJA, P.DESCRIPCION, 
                       @CANTIDAD_EMPAQUE [CANTIDAD], -- Cantidad 
                       P.NAVE_COD, P.POSICION_COD, P.RUTA, P.PROP1, P.FECHA_INICIO, P.FECHA_FIN, P.USUARIO, 
                       @CANTIDAD_EMPAQUE [CANT_CONFIRMADA], -- Cantidad Controlada
                       @NRO_CONTENEDORA [PALLET_PICKING], -- Nro Contenedora
                       P.SALTO_PICKING, 
                       '1' [PALLET_CONTROLADO], -- Esta en Contenedora
                       P.USUARIO_CONTROL_PICK, P.ST_ETIQUETAS, P.ST_CAMION, P.FACTURADO, P.FIN_PICKING, P.ST_CONTROL_EXP, 
                       P.FECHA_CONTROL_PALLET, P.TERMINAL_CONTROL_PALLET, P.FECHA_CONTROL_EXP, P.USUARIO_CONTROL_EXP, P.TERMINAL_CONTROL_EXP, 
                       P.FECHA_CONTROL_FAC, P.USUARIO_CONTROL_FAC, P.TERMINAL_CONTROL_FAC, P.VEHICULO_ID, P.PALLET_COMPLETO, P.HIJO, 
                       P.QTY_CONTROLADO, P.PALLET_FINAL, P.PALLET_CERRADO, P.USUARIO_PF, P.TERMINAL_PF, P.REMITO_IMPRESO, P.NRO_REMITO_PF, 
                       P.PICKING_ID_REF, P.BULTOS_CONTROLADOS, P.BULTOS_NO_CONTROLADOS, P.FLG_PALLET_HOMBRE, P.TRANSF_TERMINADA,P.NRO_LOTE,P.NRO_PARTIDA,P.NRO_SERIE
                FROM DOCUMENTO D INNER JOIN PICKING P ON(D.DOCUMENTO_ID = P.DOCUMENTO_ID) 
                WHERE P.PICKING_ID = @PICKING_ID AND P.PALLET_CONTROLADO = '0'
            
            DELETE TMP_EMPAQUE_CONTENEDORA 
            WHERE PICKING_ID = @PICKING_ID AND CANTIDAD = 0 AND CANT_CONFIRMADA = 0 AND PALLET_CONTROLADO = '0'
            
            -- Si aun existe CANT_CONFIRMADA = 0, es porque hay residuo en CANTIDAD
            IF EXISTS(SELECT 1 FROM TMP_EMPAQUE_CONTENEDORA 
                      WHERE PICKING_ID = @PICKING_ID AND CANT_CONFIRMADA = 0 AND PALLET_CONTROLADO = '0')
                BEGIN
                    -- Para que no se pierda, guaro el residuo
                     UPDATE TMP_EMPAQUE_CONTENEDORA
                     SET CANTIDAD = CANTIDAD + ( 
                                                 SELECT TMP.CANTIDAD
                                                 FROM TMP_EMPAQUE_CONTENEDORA TMP
                                                 WHERE TMP.PICKING_ID = @PICKING_ID AND TMP.CANT_CONFIRMADA = 0 AND TMP.PALLET_CONTROLADO = '0'
                                                 )
                     WHERE PICKING_ID = @PICKING_ID AND PALLET_PICKING = @NRO_CONTENEDORA AND PALLET_CONTROLADO <> '0'
                    
                    -- Ahora si... A borrar!
                    DELETE TMP_EMPAQUE_CONTENEDORA 
                    WHERE PICKING_ID = @PICKING_ID AND CANT_CONFIRMADA = 0 AND PALLET_CONTROLADO = '0'
                END
            
            FETCH cur_linea
            INTO @PICKING_ID, @CANT_CONFIRMADA
        END
    CLOSE cur_linea
    DEALLOCATE cur_linea
	
	
    SELECT @CantPickeada = SUM(CANT_CONFIRMADA) 
    FROM TMP_EMPAQUE_CONTENEDORA 
    WHERE CLIENTE_ID = @CLIENTE_ID AND NRO_REMITO = @PEDIDO_ID AND PRODUCTO_ID = @PRODUCTO_ID AND ISNULL(NRO_LOTE,'') = ISNULL(@NRO_LOTE,'') AND ISNULL(NRO_PARTIDA,'') = ISNULL(@NRO_PARTIDA,'') AND ISNULL(NRO_SERIE,'') = ISNULL(@NRO_SERIE,'')
    
    SELECT @CantControlada = SUM(CANT_CONFIRMADA) 
    FROM TMP_EMPAQUE_CONTENEDORA 
    WHERE	CLIENTE_ID = @CLIENTE_ID AND NRO_REMITO = @PEDIDO_ID AND PRODUCTO_ID = @PRODUCTO_ID AND PALLET_CONTROLADO <> '0'
			AND ISNULL(NRO_LOTE,'') = ISNULL(@NRO_LOTE,'') AND ISNULL(NRO_PARTIDA,'') = ISNULL(@NRO_PARTIDA,'') AND ISNULL(NRO_SERIE,'') = ISNULL(@NRO_SERIE,'')
    
    SELECT @CantPendiente = @CantPickeada - @CantControlada
    
    SELECT @CantPickeada CantPickeada, @CantControlada CantControlada, @CantPendiente CantPendiente
END
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO

ALTER               PROCEDURE [dbo].[RPT_MOVIMIENTOS]
	@CLIENTE_ID		VARCHAR(15)	OUTPUT,
	@PRODUCTO_ID	VARCHAR(30)		OUTPUT,
	@NRO_PALLET		VARCHAR(100)	OUTPUT,
	@NRO_PARTIDA	VARCHAR(50)		OUTPUT,
	@FECHA_VTO		VARCHAR(8)		OUTPUT,	--ANSI
	@F_DESDE		VARCHAR(8)			OUTPUT,	--ANSI
	@F_HASTA		VARCHAR(8)			OUTPUT,	--ANSI
	@NRO_LOTE		VARCHAR(50)		OUTPUT,
	@PROP2			VARCHAR(100)		OUTPUT,
	@PROP3			VARCHAR(100)		OUTPUT,
	@USUARIO		VARCHAR(20) 		OUTPUT,
	@COD_PEDIDO	VARCHAR(30)		OUTPUT,
	@COD_VIAJE	VARCHAR(100)		OUTPUT
AS
BEGIN
	/*
	----------------------------------------------------------------------
	CREATE TABLE #TEMP_CRITERIOS_RPT(
		TIPO_AUDITORIA_ID NUMERIC(20,0)
	)
	INSERT INTO #TEMP_CRITERIOS_RPT
	SELECT 	TIPO_AUDITORIA_ID
	FROM	PARAMETROS_AUDITORIA
	*/
	----------------------------------------------------------------------
	--					DECLARACION DE VARIABLES.
	----------------------------------------------------------------------
	DECLARE @SALDO_INICIAL	FLOAT
	DECLARE @TERMINAL_RTP	VARCHAR(100)
	DECLARE @USUARIO_RTP	VARCHAR(20)
	DECLARE @P_FECHA_I		VARCHAR(8)
	DECLARE @CONT			FLOAT
	
	DECLARE @PICK			NUMERIC(20,0)
	DECLARE @SERIE			VARCHAR(100)
	DECLARE @PICK_ANT			NUMERIC(20,0)
	DECLARE @SERIE_ACUM			VARCHAR(3000)
	----------------------------------------------------------------------
	SET 	@TERMINAL_RTP	=HOST_NAME()
	SELECT	@USUARIO_RTP	=USUARIO_ID FROM #TEMP_USUARIO_LOGGIN
	--SET	@USUARIO_RTP	='USER'
	
	SELECT 	@CONT=COUNT(*)
	FROM	#TEMP_CRITERIOS_RPT
	WHERE	TIPO_AUDITORIA_ID IN(4,15,16)

	IF @CONT=3
	BEGIN
		SET @P_FECHA_I=@F_DESDE
	END
	IF (@NRO_PALLET IS NOT NULL) OR(@NRO_PARTIDA IS NOT NULL)OR (@FECHA_VTO IS NOT NULL)
	    OR(@NRO_LOTE IS NOT NULL) OR (@PROP2 IS NOT NULL) OR(@PROP3 IS NOT NULL)OR(@USUARIO IS NOT NULL)
	BEGIN
	       SET @P_FECHA_I=NULL
	END
	
	SELECT 	 DBO.GET_SALDO_INICIAL(AH.CLIENTE_ID,AH.PRODUCTO_ID,@P_FECHA_I,@F_HASTA)	AS [SD_INICIAL]
			,AH.CLIENTE_ID + ' - ' +C.RAZON_SOCIAL										AS [CLIENTE_RZ]
			,AH.PRODUCTO_ID																AS [PRODUCTO_ID]
			,PA.DESCRIPCION																AS [DESC_OP]
			,'Usuario: ' + @USUARIO_RTP													AS [USOINTERNOUSUARIO]
			,'Terminal: ' + @TERMINAL_RTP												AS [USOINTERNOTERMINAL]
			,AH.FECHA_AUDITORIA															AS [FECHA_AUDITORIA]
			,CONVERT(VARCHAR,AH.FECHA_AUDITORIA,103) 									AS [FECHA]
			,TC.DESCRIPCION	+ ' - ' + D.NRO_DESPACHO_IMPORTACION						AS [DESC_TIPO_COMPROBANTE]
			,AH.USUARIO_ID +' - '+ SU.NOMBRE											AS [USUARIO_OPERACION]
			,AH.TERMINAL																AS [TERMINAL_OPERACION]
			,CAST(CASE WHEN P.POSICION_COD IS NULL THEN ISNULL(N2.NAVE_COD,ISNULL(N.NAVE_COD,'PREING')) ELSE P.POSICION_COD END AS VARCHAR) AS [UBICACION]
			,AH.CANTIDAD																AS [CANTIDAD]
			,AH.DOC_EXT																	AS [DOC_EXT]
			,AH.CAT_LOG_ID																AS [CAT_LOG_ID]
			,DD.PRODUCTO_ID + ' - ' + DD.DESCRIPCION									AS [PROD_DESC]
			,AH.CLIENTE_ID																AS [CLIENTE_ID]
			,CASE 
			  	WHEN AH.NRO_SERIE IS NULL THEN '' 
			  	Else 'Nro.Serie: ' + CAST(AH.NRO_SERIE AS VARCHAR) + ', '
			 END + 
			 CASE 
			    WHEN AH.NRO_BULTO IS NULL THEN '' 
			    Else 'Nro.Bulto: ' + CAST(AH.NRO_BULTO AS VARCHAR) + ', '
			 END + 
			 CASE 
			    WHEN AH.NRO_LOTE IS NULL THEN '' 
			    Else 'Nro.Lote: ' + CAST(AH.NRO_LOTE AS VARCHAR) + ', '
			 END + 
			 CASE 
			    WHEN AH.NRO_DESPACHO IS NULL THEN '' 
			    Else 'Nro.Despacho: ' + CAST(AH.NRO_DESPACHO AS VARCHAR) + ', '
			 END + 
			 CASE 
			    WHEN AH.NRO_PARTIDA IS NULL THEN '' 
			    Else 'Nro.Partida: ' + CAST(AH.NRO_PARTIDA AS VARCHAR) + ', '
			 END + 
			 CASE 
			    WHEN AH.PROP1 IS NULL THEN '' 
			    Else 'Nro.Pallet: ' + CAST(AH.PROP1 AS VARCHAR) + ', '
			 END + 
			 CASE 
			    WHEN AH.PROP2 IS NULL THEN '' 
			    Else 'Lote Prov.: ' + CAST(AH.PROP2 AS VARCHAR) + ', '
			 END + 
			 CASE 
			    WHEN AH.PROP3 IS NULL THEN '' 
			    Else 'Property 3: ' + CAST(AH.PROP3 AS VARCHAR) + ', '
			 END + 
			 CASE 
			    WHEN AH.FECHA_VENCIMIENTO IS NULL THEN '' 
			    Else 'Fecha Vencimiento: ' + CONVERT(VARCHAR,AH.FECHA_VENCIMIENTO,103) + ', '
			 END +
			 CASE
				WHEN D.SUCURSAL_ORIGEN IS NULL THEN ''
				ELSE 'Proveedor: ' +CAST(D.SUCURSAL_ORIGEN AS VARCHAR) + ' - ' +CAST(S.NOMBRE AS VARCHAR)+', '
			 END +
			 CASE
				WHEN AH.EST_MERC_ID IS NULL THEN ''
				ELSE 'Est.Merc. : ' + CAST(AH.EST_MERC_ID AS VARCHAR)
			 END +
			 CASE
				WHEN D.NRO_REMITO IS NULL THEN ''
				ELSE 'Nro. Remito : ' + CAST(D.NRO_REMITO AS VARCHAR)
			 END AS [PROPIEDADES]
			,AH.NRO_SERIE
			,AH.NRO_BULTO
			,AH.NRO_LOTE
			,AH.NRO_DESPACHO
			,AH.NRO_PARTIDA				
			,AH.PROP1						[NRO_PALLET]
			,AH.PROP2						[LOTE_PROVEEDOR]
			,AH.FECHA_VENCIMIENTO			[FECHA_VENCIMIENTO]
			,D.SUCURSAL_ORIGEN				[ORIGEN_DESTINO]
			,S.NOMBRE		
			,AH.EST_MERC_ID				
			,AH.AUDITORIA_ID				[AUDITORIA_ID]
	FROM	AUDITORIA_HISTORICOS AH (NOLOCK)
			INNER JOIN vDOCUMENTO D	(NOLOCK)						ON(AH.DOCUMENTO_ID=D.DOCUMENTO_ID)
			LEFT JOIN TIPO_COMPROBANTE TC (NOLOCK)					ON(D.TIPO_COMPROBANTE_ID=TC.TIPO_COMPROBANTE_ID)
			LEFT JOIN POSICION P (NOLOCK)							ON(AH.POSICION_ID_FINAL=P.POSICION_ID)
			LEFT JOIN NAVE	N 	(NOLOCK)							ON(AH.NAVE_ID_FINAL=N.NAVE_ID)
			LEFT JOIN NAVE  N2	(NOLOCK)							ON(P.POSICION_ID=N2.NAVE_ID)
			INNER JOIN PARAMETROS_AUDITORIA PA (NOLOCK) 			ON(AH.TIPO_AUDITORIA_ID=PA.TIPO_AUDITORIA_ID)
			INNER JOIN #TEMP_CRITERIOS_RPT TMPC (NOLOCK)			ON(AH.TIPO_AUDITORIA_ID=TMPC.TIPO_AUDITORIA_ID)
			INNER JOIN CLIENTE C (NOLOCK)							ON(AH.CLIENTE_ID=C.CLIENTE_ID)
			INNER JOIN vDET_DOCUMENTO DD(NOLOCK)					ON(AH.DOCUMENTO_ID=DD.DOCUMENTO_ID AND AH.NRO_LINEA_DOC=DD.NRO_LINEA)
			LEFT JOIN SYS_USUARIO SU (NOLOCK)						ON(AH.USUARIO_ID=SU.USUARIO_ID)
			LEFT JOIN SUCURSAL S(NOLOCK)							ON(D.CLIENTE_ID=S.CLIENTE_ID AND D.SUCURSAL_ORIGEN=S.SUCURSAL_ID)
	WHERE	((@NRO_PALLET IS NULL)OR(AH.PROP1=@NRO_PALLET))
			AND((@F_DESDE IS NULL)OR(AH.FECHA_AUDITORIA BETWEEN @F_DESDE AND DATEADD(DD,1,@F_HASTA)))
			AND((@CLIENTE_ID IS NULL) OR (AH.CLIENTE_ID=@CLIENTE_ID))
			AND((@PRODUCTO_ID IS NULL) OR(AH.PRODUCTO_ID=@PRODUCTO_ID))
			AND((@NRO_PARTIDA IS NULL) OR (AH.NRO_PARTIDA=@NRO_PARTIDA))
			AND((@FECHA_VTO IS NULL) OR(AH.FECHA_VENCIMIENTO=@FECHA_VTO))
			AND((@USUARIO IS NULL) OR (AH.USUARIO_ID=@USUARIO))
			AND((@NRO_LOTE IS NULL) OR (AH.NRO_LOTE=@NRO_LOTE))
			AND((@PROP2 IS NULL) OR (AH.PROP2=@PROP2))
			AND((@PROP3 IS NULL) OR (AH.PROP3=@PROP3))
	UNION	
	--Egresos
	SELECT 
			 DBO.GET_SALDO_INICIAL(P.CLIENTE_ID,P.PRODUCTO_ID,@P_FECHA_I,@F_HASTA) AS [SD_INICIAL]
			,P.CLIENTE_ID + ' - ' +C.RAZON_SOCIAL			AS [CLIENTE_RZ]
			,P.PRODUCTO_ID									AS [PRODUCTO_ID]
			,'Egresos'										AS [DESC_OP]
			,'Usuario: ' + @USUARIO_RTP						AS [USOINTERNOUSUARIO]
			,'Terminal:' + @TERMINAL_RTP					AS [USOINTERNOTERMINAL]
			,P.FECHA_CONTROL_FAC							AS [FECHA_AUDITORIA]
			,CONVERT(VARCHAR,P.FECHA_CONTROL_FAC,103) 		AS [FECHA]
			,CASE 
			  	WHEN D.NRO_REMITO IS NULL THEN TC.DESCRIPCION	+ ' - ' + CAST(DD.DOCUMENTO_ID AS VARCHAR)
			  	Else TC.DESCRIPCION	+ ' - ' + D.NRO_REMITO
			 END AS [DESC_TIPO_COMPROBANTE]
			--,TC.DESCRIPCION	+ ' - ' + D.NRO_REMITO			AS [DESC_TIPO_COMPROBANTE]
			,P.USUARIO_CONTROL_FAC + ' - ' +SU.NOMBRE AS [USUARIO_OPERACION]
			,NULL											AS [TERMINAL_OPERACION]
			,P.POSICION_COD									AS [UBICACION]
			,ISNULL((P.CANT_CONFIRMADA *(-1)),0)			AS [CANTIDAD]
			,D.NRO_REMITO									AS [DOC_EXT]
			,DD.CAT_LOG_ID_FINAL							AS [CAT_LOG_ID]
			,P.PRODUCTO_ID + ' - ' + P.DESCRIPCION		AS [PROD_DESC]
			,P.CLIENTE_ID								AS [CLIENTE_ID]
			,CASE 
			  	WHEN DD.NRO_SERIE IS NULL THEN '' 
			  	Else 'Nro.Serie: ' + CAST(DD.NRO_SERIE AS VARCHAR) + ', '
			 END + 
			 CASE 
			    WHEN DD.NRO_BULTO IS NULL THEN '' 
			    Else 'Nro.Bulto: ' + CAST(DD.NRO_BULTO AS VARCHAR) + ', '
			 END + 
			 CASE 
			    WHEN DD.NRO_LOTE IS NULL THEN '' 
			    Else 'Nro.Lote: ' + CAST(DD.NRO_LOTE AS VARCHAR) + ', '
			 END + 
			 CASE 
			    WHEN DD.NRO_DESPACHO IS NULL THEN '' 
			    Else 'Nro.Despacho: ' + CAST(DD.NRO_DESPACHO AS VARCHAR) + ', '
			 END + 
			 CASE 
			    WHEN DD.NRO_PARTIDA IS NULL THEN '' 
			    Else 'Nro.Partida: ' + CAST(DD.NRO_PARTIDA AS VARCHAR) + ', '
			 END + 
			 CASE 
			    WHEN DD.PROP1 IS NULL THEN '' 
			    Else 'Nro.Pallet: ' + CAST(DD.PROP1 AS VARCHAR) + ', '
			 END + 
			 CASE 
			    WHEN DD.PROP2 IS NULL THEN '' 
			    Else 'Lote Prov.: ' + CAST(DD.PROP2 AS VARCHAR) + ', '
			 END + 
			 CASE 
			    WHEN DD.PROP3 IS NULL THEN '' 
			    Else 'PROPERTY 3: ' + CAST(DD.PROP3 AS VARCHAR) + ', '
			 END + 
			 CASE 
			    WHEN DD.FECHA_VENCIMIENTO IS NULL THEN '' 
			    Else 'Fecha Vencimiento: ' + CONVERT(VARCHAR,DD.FECHA_VENCIMIENTO,103) + ' '
			 END +
			 CASE
				WHEN D.SUCURSAL_DESTINO IS NULL THEN ''
				ELSE 'Destino: ' + CAST(D.SUCURSAL_DESTINO AS VARCHAR) + ' - ' + CAST(S.NOMBRE AS VARCHAR)+', '
			 END +
			 CASE
				WHEN DD.EST_MERC_ID IS NULL THEN ''
				ELSE 'Est.Merc. : ' + CAST(DD.EST_MERC_ID AS VARCHAR) + ', '
			 END +
			 CASE
				WHEN D.NRO_REMITO IS NULL THEN ''
				ELSE 'Nro. Remito : ' + CAST(D.NRO_REMITO AS VARCHAR)
			 END +
			 CASE 
				WHEN D.TIPO_COMPROBANTE_ID IN('E02','E01','E03','E04','AJE')
				THEN ISNULL(DBO.GET_USUARIO_PEDIDO(P.CLIENTE_ID,D.NRO_DESPACHO_IMPORTACION),'')
			 END +
			 CASE 
				WHEN NOT SP.PICKING_ID IS NULL THEN ',  Núm. Series : ' + CAST(SP.SERIES AS VARCHAR)
				ELSE ''
			END
			 AS [PROPIEDADES]
			,DD.NRO_SERIE
			,DD.NRO_BULTO
			,DD.NRO_LOTE
			,DD.NRO_DESPACHO
			,DD.NRO_PARTIDA				
			,DD.PROP1						[NRO_PALLET]
			,DD.PROP2						[LOTE_PROVEEDOR]
			,DD.FECHA_VENCIMIENTO			[FECHA_VENCIMIENTO]
			,D.SUCURSAL_DESTINO			[ORIGEN_DESTINO]
			,S.NOMBRE	
			,DD.EST_MERC_ID					
			,P.PICKING_ID [AUDITORIA_ID]
	FROM	vPICKING P (NOLOCK) INNER JOIN vDET_DOCUMENTO DD	(NOLOCK) ON(P.DOCUMENTO_ID=DD.DOCUMENTO_ID AND P.NRO_LINEA=DD.NRO_LINEA)
			INNER JOIN vDOCUMENTO D 				(NOLOCK) ON(DD.DOCUMENTO_ID=D.DOCUMENTO_ID)
			INNER JOIN TIPO_COMPROBANTE TC 			(NOLOCK) ON(D.TIPO_COMPROBANTE_ID=TC.TIPO_COMPROBANTE_ID)
			INNER JOIN CLIENTE C					(NOLOCK) ON(C.CLIENTE_ID=P.CLIENTE_ID)
			LEFT JOIN SYS_USUARIO SU				(NOLOCK) ON(P.USUARIO_CONTROL_FAC=SU.USUARIO_ID)
			LEFT JOIN SUCURSAL	S					(NOLOCK) ON(S.CLIENTE_ID=D.CLIENTE_ID AND S.SUCURSAL_ID=D.SUCURSAL_DESTINO)
		    LEFT JOIN tmpSeriesPicking SP         (NOLOCK) ON(SP.PICKING_ID = P.PICKING_ID)
	WHERE	((@NRO_PALLET IS NULL)OR(P.PROP1=@NRO_PALLET))
			AND((@F_DESDE IS NULL)OR(d.FECHA_ALTA_GTW BETWEEN @F_DESDE AND DATEADD(DD,1,@F_HASTA)))
			AND ((P.FACTURADO='1') OR((P.FACTURADO='0') AND (TC.TIPO_COMPROBANTE_ID = 'AJE')))
			AND 16 In (Select Tipo_Auditoria_Id from #TEMP_CRITERIOS_RPT)
			AND((@CLIENTE_ID IS NULL) OR (P.CLIENTE_ID=@CLIENTE_ID))
			AND((@PRODUCTO_ID IS NULL) OR (P.PRODUCTO_ID=@PRODUCTO_ID))
			AND((@NRO_PARTIDA IS NULL) OR (DD.NRO_PARTIDA=@NRO_PARTIDA))
			AND((@FECHA_VTO IS NULL) OR (DD.FECHA_VENCIMIENTO=@FECHA_VTO))
			AND((@USUARIO IS NULL) OR (P.USUARIO_CONTROL_FAC=@USUARIO))
			AND((@NRO_LOTE IS NULL) OR (DD.NRO_LOTE=@NRO_LOTE))
			AND((@PROP2 IS NULL) OR (DD.PROP2=@PROP2))
			AND((@PROP3 IS NULL) OR (DD.PROP3=@PROP3))
			AND((@COD_PEDIDO IS NULL) OR(D.NRO_REMITO LIKE  '%'+ @COD_PEDIDO +  '%'))
			AND((@COD_VIAJE IS NULL) OR(D.NRO_DESPACHO_IMPORTACION LIKE '%' + @COD_VIAJE + '%'))
	ORDER BY 3,7,30
	--DROP TABLE #tmpSeriesPicking
END
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO

ALTER                          procedure [dbo].[Sys_Int_Ingresa_Productos]
As
Begin


	-------------------------------------------------
	--TABLA SYS_INT_PRODUCTO.
	-------------------------------------------------
	Declare @Cliente_id			as varchar(15)			
	Declare @Producto_id			as varchar(30)
	Declare @Codigo_producto		as varchar(50)
	Declare @SubCodigo_1			as varchar(50)
	Declare @SubCodigo_2			as varchar(50)	
	Declare @Descripcion			as varchar(200)
	Declare @Marca				as varchar(60)		
	Declare @Fraccionable			as varchar(1)
	Declare @Unidad_Fraccion		as varchar(5)		
	Declare @Costo				as numeric(10,3)
	Declare @Unidad_id			as varchar(5)		
	Declare @SubFamilia_id			as varchar(30)
	Declare @Familia_id			as varchar(30)
	Declare @Observaciones			as varchar(400)
	Declare @Posiciones_Puras		as varchar(1)
	Declare @Moneda_Costo_Id		as varchar(20)
	Declare @Largo				as numeric(10,3)
	Declare @Alto				as numeric(10,3)
	Declare @Ancho				as numeric(10,3)
	Declare @Unidad_Volumen			as varchar(5)
	Declare @Peso				as numeric(20,5)
	Declare @Unidad_peso			as varchar(5)
	Declare @Lote_Automatico		as varchar(1)
	Declare @Pallet_Automatico		as varchar(1)
	Declare @Tolerancia_Min_Ingreso		as numeric(10,2)
	Declare @Tolerancia_Max_Ingreso		as numeric(10,2)
	Declare @Genera_Back_Order		as varchar(1)
	Declare @Clasificacion_Cot		as varchar(20)
	Declare @Codigo_Barra			as varchar(100)
	Declare @Ing_Cat_log_id			as varchar(50)
	Declare @Egr_Cat_log_id			as varchar(50)
	Declare @Producto_activo		as varchar(1)
	Declare @Cod_Tipo_Producto		as varchar(30)
	-------------------------------------------------
	--PRODUCTO.
	-------------------------------------------------
	Declare @IngresoT			as varchar(15)
	Declare	@EgresoT			as varchar(15)
	Declare @InventarioT			as varchar(15)
	Declare @Transferencia			as varchar(15)
	Declare @Ing_Cat_log_idP		as varchar(50)
	Declare @Egr_Cat_log_idP		as varchar(50)
	Declare @Pais_Id			as varchar(5)
	Declare @GrupoProducto			as varchar(5)
	Declare @TipoContenedora		as varchar(100)
	-------------------------------------------------
	--GENERICAS
	-------------------------------------------------
	Declare @Int				as Int
	Declare @Existe				as int
	-------------------------------------------------
	--CURSORES.
	-------------------------------------------------
	Declare @CurIngProd Cursor

		
	Set @CurIngProd=Cursor For
		Select 	 Cliente_id				,Producto_id
				,Codigo_producto		,SubCodigo_1
				,SubCodigo_2			,Descripcion
				,Marca				,Fraccionable
				,Unidad_Fraccion		,Costo
				,Unidad_id			,SubFamilia_id
				,Familia_id			,Observaciones
				,Posiciones_Puras		,Moneda_Costo_Id
				,Largo				,Alto
				,Ancho				,Unidad_Volumen
				,Peso				,Unidad_peso
				,Lote_Automatico		,Pallet_Automatico
				,Tolerancia_Min_Ingreso		,Tolerancia_Max_Ingreso
				,Genera_Back_Order		,Clasificacion_Cot
				,Codigo_Barra			,Ing_Cat_log_id
				,Egr_Cat_log_id			,Producto_activo
				,Cod_Tipo_Producto
		From	Sys_Int_Producto
		Where	(Ingresado='0' or Ingresado IS Null) --and fecha_carga is null

	Open @CurIngProd

	Fetch Next From @CurIngProd into @Cliente_id,@Producto_id,@Codigo_producto,@SubCodigo_1,@SubCodigo_2
									,@Descripcion,@Marca,@Fraccionable,@Unidad_Fraccion,@Costo,@Unidad_id
									,@SubFamilia_id,@Familia_id,@Observaciones,@Posiciones_Puras,@Moneda_Costo_Id
									,@Largo,@Alto,@Ancho,@Unidad_Volumen,@Peso,@Unidad_peso,@Lote_Automatico
									,@Pallet_Automatico,@Tolerancia_Min_Ingreso,@Tolerancia_Max_Ingreso
									,@Genera_Back_Order,@Clasificacion_Cot,@Codigo_Barra,@Ing_Cat_log_id
									,@Egr_Cat_log_id,@Producto_activo,@Cod_Tipo_Producto
	While @@Fetch_Status=0
	Begin
		select @Existe=dbo.Exist_Product(@Producto_id,@Cliente_id)
		
		if @Existe=0
		--Si el producto no existe, comienza la carga del mismo.
		Begin
			Select	@Int=Count(*)
			From	Producto
			where	Cliente_id=@Cliente_id and Producto_id=@SubFamilia_id
	
			if @Int > 0
			Begin
				Select 	 @IngresoT			= Ingreso
						,@EgresoT		= Egreso
						,@InventarioT		= Inventario
						,@Transferencia		= Transferencia
						,@Ing_Cat_log_idP	= Ing_Cat_log_Id
						,@Egr_Cat_log_idP	= Egr_Cat_log_id
						,@Pais_Id		= Pais_id
						,@GrupoProducto		= Grupo_Producto
						,@TipoContenedora	= Tipo_Contenedora
				From	Producto
				Where	Cliente_id=@Cliente_id and Producto_id=@SubFamilia_id
			End		
			Else
			Begin
				Select 	 @IngresoT			= Ingreso
						,@EgresoT		= Egreso
						,@InventarioT		= Inventario
						,@Transferencia		= Transferencia
						,@Ing_Cat_log_id	= Ing_Cat_log_Id
						,@Egr_Cat_log_id	= Egr_Cat_log_id
						,@Pais_Id		= Pais_id
						,@GrupoProducto		= Grupo_Producto
						,@TipoContenedora	= Tipo_Contenedora
				From	Producto
				Where	Cliente_id=@Cliente_id and Producto_id=@Familia_id;
			End
			IF LTRIM(RTRIM(@GrupoProducto))=''
			BEGIN
				SET @GrupoProducto=Null
			END
			Insert Into Producto (	 Cliente_id
									,Producto_id
									,Codigo_Producto
									,SubCodigo_1
									,SubCodigo_2
									,Descripcion
									,Nombre
									,Marca
									,Fraccionable
									,Unidad_Fraccion
									,Costo
									,Unidad_id
									,Tipo_Producto_id
									,Pais_Id
									,Familia_id
									,Criterio_id
									,Observaciones
									,Posiciones_Puras
									,Kit
									,Serie_Egr
									,Moneda_id
									,No_Agrupa_Items
									,Largo
									,Alto
									,Ancho
									,Unidad_Volumen
									,Volumen_Unitario
									,Peso
									,Unidad_peso
									,Peso_Unitario
									,Lote_Automatico
									,Pallet_Automatico
									,Ingreso
									,Egreso
									,Inventario
									,Transferencia
									,Tolerancia_Min
									,Tolerancia_Max
									,Back_Order
									,Clasificacion_Cot
									,Codigo_Barra
									,Ing_Cat_log_Id
									,Egr_Cat_log_id
									,Sub_Familia_id
									,Tipo_Contenedora
									,Grupo_Producto
									,Envase)
			Values(
									 @Cliente_id
									,@Producto_id
									,@Codigo_producto
									,@SubCodigo_1
									,@SubCodigo_2
									,@Descripcion
									,Null
									,@Marca
									,@Fraccionable
									,@Unidad_Fraccion
									,@Costo
									,@Unidad_id
									,@Cod_Tipo_Producto
									,isnull(@Pais_Id,'AR')
									,isnull(@Familia_id,'DEFAULT')
									,Null
									,@Observaciones
									,@Posiciones_Puras
									,0
									,0
									,@Moneda_Costo_Id
									,0
									,@Largo
									,@Alto
									,@Ancho
									,'M3'
									,0
									,@Peso
									,'KG'
									,0
									,ISNULL(@Lote_Automatico,'1')
									,ISNULL(@Pallet_Automatico,'1')
									,ISNULL(@IngresoT,'ING_PT')
									,ISNULL(@EgresoT,'PICK_PT')
									,ISNULL(@InventarioT,'INVENTARIO')
									,ISNULL(@Transferencia,'TRANSFERENCIAS')
									,@Tolerancia_Min_Ingreso
									,@Tolerancia_Max_Ingreso
									,ISNULL(@Genera_Back_Order,'1')
									,@Clasificacion_Cot
									,@Codigo_Barra
									,ISNULL(@Ing_Cat_log_idP,'CUA')
									,@Egr_Cat_log_idP
									,@SubFamilia_id
									,@TipoContenedora
									,ISNULL(@GrupoProducto,'SG')
									,'0'
					)

			--CRITERIOS DE LOCATOR.		
			Select	@Int=Count(*)
			From	Sys_Criterio_Locator
			where	Cliente_id=@Cliente_id and Producto_id=@SubFamilia_id;
			if @Int > 0
			Begin
				Insert into Sys_Criterio_Locator
					Select	@Cliente_id,@Producto_Id,Criterio_Id,Order_id,Forma_Id,Posicion_id
					from	Sys_Criterio_Locator
					where	Cliente_id=@Cliente_id and Producto_id=@SubFamilia_id;
			End		
			Else
			Begin
				Insert into Sys_Criterio_Locator
					Select	@Cliente_id,@Producto_Id,Criterio_Id,Order_id,Forma_Id,Posicion_id
					from	Sys_Criterio_Locator
					where	Cliente_id=@Cliente_id and Producto_id=@Familia_id
				-- Si no encuentra nada levanta esto.
				If @@Rowcount=0 
				Begin
					Insert into Sys_criterio_Locator Values(@Cliente_Id, @Producto_Id, 'FECHA_VENCIMIENTO','ASC','TO_DATE', 1)
					Insert into Sys_criterio_Locator Values(@Cliente_Id, @Producto_Id, 'ORDEN_PICKING', 'ASC','TO_NUMBER', 2)
				End
				
			End
			--FIN CRITERIOS DE LOCATOR.
	
			--POSICIONES Y NAVES.
			Select	@Int=Count(*)
			From	rl_producto_posicion_permitida
			where	Cliente_id=@Cliente_id and Producto_id=@SubFamilia_id;
			if @Int > 0
			Begin
				Insert into rl_producto_posicion_permitida
					Select	@Cliente_id,@Producto_id,nave_id,Posicion_id
					From	rl_producto_posicion_permitida
					where	Cliente_id=@Cliente_id and Producto_id=@SubFamilia_id;
			End		
			Else
			Begin
				Insert into rl_producto_posicion_permitida
					Select	@Cliente_id,@Producto_id,nave_id,Posicion_id
					From	rl_producto_posicion_permitida
					where	Cliente_id=@Cliente_id and Producto_id=@Familia_id
			End
			--mandatorios producto
			Select	@Int=Count(*)
			From	mandatorio_producto
			where	Cliente_id=@Cliente_id and Producto_id=@SubFamilia_id;
			if @Int > 0
			Begin
				Insert into mandatorio_producto
					Select	@Cliente_id,@Producto_id,tipo_operacion,campo
					From	mandatorio_producto
					where	Cliente_id=@Cliente_id and Producto_id=@SubFamilia_id;

			End		
			Else
			Begin
				Insert into mandatorio_producto
					Select	@Cliente_id,@Producto_id,tipo_operacion,campo
					From	mandatorio_producto
					where	Cliente_id=@Cliente_id and Producto_id=@Familia_id
				--Si no hay mandatorios heredables Carga por default.
				If @@RowCount=0
				Begin
					Insert into Mandatorio_Producto Values(@Cliente_Id,@Producto_Id,'EGR','CANTIDAD')
					Insert into Mandatorio_Producto Values(@Cliente_Id,@Producto_Id,'ING','CANTIDAD')
				End
			End
			--Producto Tratamiento
			Select	@Int=Count(*)
			From	rl_producto_tratamiento
			where	Cliente_id=@Cliente_id and Producto_id=@SubFamilia_id;
			if @Int > 0
			Begin
				Insert into rl_producto_tratamiento(cliente_id,producto_id,tipo_operacion_id,tipo_comprobante_id,transaccion_id)
					Select	@Cliente_id,@Producto_id,tipo_operacion_id,tipo_comprobante_id,transaccion_id
					From	rl_producto_tratamiento
					where	Cliente_id=@Cliente_id and Producto_id=@SubFamilia_id;

			End		
			Else
			Begin
				Insert into rl_producto_tratamiento(cliente_id,producto_id,tipo_operacion_id,tipo_comprobante_id,transaccion_id)
					Select	@Cliente_id,@Producto_id,tipo_operacion_id,tipo_comprobante_id,transaccion_id
					From	rl_producto_tratamiento
					where	Cliente_id=@Cliente_id and Producto_id=@Familia_id;

				If @@RowCount=0
				Begin
					Insert into Rl_Producto_Tratamiento(Cliente_Id,Producto_Id,Tipo_Operacion_Id, Tipo_Comprobante_Id,Transaccion_Id)
												Values(	@Cliente_Id, @Producto_Id,'EGR','E04','PICK_PT')

				
				End
			End

			--producto categoria logica
			Select	@Int=Count(*)
			From	rl_producto_tratamiento
			where	Cliente_id=@Cliente_id and Producto_id=@SubFamilia_id;
			if @Int > 0
			Begin
				Insert into rl_producto_catlog(cliente_id,producto_id,tipo_operacion_id,tipo_comprobante_id,Cat_log_id)
					Select	@Cliente_id,@Producto_id,tipo_operacion_id,tipo_comprobante_id,Cat_log_id
					From	rl_producto_catlog
					where	Cliente_id=@Cliente_id and Producto_id=@SubFamilia_id;

			End		
			Else
			Begin
				Insert into rl_producto_catlog(cliente_id,producto_id,tipo_operacion_id,tipo_comprobante_id,Cat_log_id)
					Select	@Cliente_id,@Producto_id,tipo_operacion_id,tipo_comprobante_id,Cat_log_id
					From	rl_producto_catlog
					where	Cliente_id=@Cliente_id and Producto_id=@Familia_id;
			End

			--Levanto la configuracion de las etiquetas
			Select	@Int=Count(*)
			From	Etiqueta_Producto
			Where	cliente_Id=@Cliente_Id and Producto_Id=@SubFamilia_id;

			If @Int>0
			Begin
				Insert into Etiqueta_Producto 
					Select 	 @Cliente_Id, @Producto_Id, Tipo_Operacion_Id, Margh, Margv, Alto, Ancho, Impresora
							,Copias, Distentreetiquetas, QTYxLinea, Modo_Impresion,Terminal_Id
					From 	Etiqueta_Producto
					Where	Cliente_Id=@Cliente_Id and Producto_Id=@SubFamilia_id;
			End
			Else
			Begin
				Insert into Etiqueta_Producto 
					Select 	 @Cliente_Id, @Producto_Id, Tipo_Operacion_Id, Margh, Margv, Alto, Ancho, Impresora
							,Copias, Distentreetiquetas, QTYxLinea, Modo_Impresion,Terminal_Id
					From 	Etiqueta_Producto
					Where	Cliente_Id=@Cliente_Id and Producto_Id=@Familia_id;
			End
		End
		Else	--Desde aca es para los productos que ya estan ingresados.
		Begin

			Select	@Int=Count(*)
			From	Producto
			where	Cliente_id=@Cliente_id and Producto_id=@SubFamilia_id
	
			if @Int > 0
			Begin
				Select 	 @IngresoT			= Ingreso
						,@EgresoT		= Egreso
						,@InventarioT		= Inventario
						,@Transferencia		= Transferencia
						,@Ing_Cat_log_idP	= Ing_Cat_log_Id
						,@Egr_Cat_log_idP	= Egr_Cat_log_id
						,@Pais_Id		= Pais_id
						,@GrupoProducto		= Grupo_Producto
						,@TipoContenedora	= Tipo_Contenedora
				From	Producto
				Where	Cliente_id=@Cliente_id and Producto_id=@SubFamilia_id
			End		
			Else
			Begin
				Select 	 @IngresoT			= Ingreso
						,@EgresoT		= Egreso
						,@InventarioT		= Inventario
						,@Transferencia		= Transferencia
						,@Ing_Cat_log_id	= Ing_Cat_log_Id
						,@Egr_Cat_log_id	= Egr_Cat_log_id
						,@Pais_Id		= Pais_id
						,@GrupoProducto		= Grupo_Producto
						,@TipoContenedora	= Tipo_Contenedora
				From	Producto
				Where	Cliente_id=@Cliente_id and Producto_id=@Familia_id;
			End
			IF LTRIM(RTRIM(@GrupoProducto))=''
			BEGIN
				SET @GrupoProducto=Null
			END
			
			Update producto Set
					 Codigo_Producto	=	@Codigo_producto
					,SubCodigo_1		=	@SubCodigo_1
					,SubCodigo_2		=	@SubCodigo_2
					,Descripcion			=	@Descripcion
					,Nombre				=	Null
					,Marca				=	@Marca
					,Fraccionable		=	@Fraccionable
					,Unidad_Fraccion	=	@Unidad_Fraccion
					,Costo				=	@Costo
					,Unidad_id			=	@Unidad_id
					,Tipo_Producto_id	=	@Cod_Tipo_Producto
					,Pais_Id				=	ISNULL(@Pais_Id,'AR')
					,Familia_id			=	ISNULL(@Familia_id,'DEFAULT')
					,Criterio_id			=	Null
					,Observaciones		=	@Observaciones
					,Posiciones_Puras	=	@Posiciones_Puras
					,Kit					=	0
					,Serie_Egr			=	0
					,Moneda_id			=	@Moneda_Costo_Id
					,No_Agrupa_Items	=	0
					,Largo				=	@Largo
					,Alto				=	@Alto
					,Ancho				=	@Ancho
					,Unidad_Volumen	=	'M3'
					,Volumen_Unitario	=	0
					,Peso				=	@Peso
					,Unidad_peso		=	'KG'
					,Peso_Unitario		=	0
					,Lote_Automatico	=	ISNULL(@Lote_Automatico,'1')
					,Pallet_Automatico	=	ISNULL(@Pallet_Automatico,'1')
					,Ingreso				=	ISNULL(@IngresoT,'ING_PT')
					,Egreso				=	ISNULL(@EgresoT,'PICK_PT')
					,Inventario			=	ISNULL(@InventarioT,'INVENTARIO')
					,Transferencia		=	ISNULL(@Transferencia,'TRANSFERENCIAS')
					,Tolerancia_Min		=	@Tolerancia_Min_Ingreso
					,Tolerancia_Max		=	@Tolerancia_Max_Ingreso
					,Back_Order			=	@Genera_Back_Order
					,Clasificacion_Cot	=	@Clasificacion_Cot
					,Codigo_Barra		=	@Codigo_Barra
					,Ing_Cat_log_Id		=	ISNULL(@Ing_Cat_log_idP,'CUA')
					,Egr_Cat_log_id		=	@Egr_Cat_log_idP
					,Sub_Familia_id		=	@SubFamilia_id
					,Tipo_Contenedora	=	@TipoContenedora
					,Grupo_Producto		=	IsNull(@GrupoProducto,'SG')
			WHERE 	Cliente_id=@Cliente_id AND Producto_id=@Producto_id
		End
		If @@error=0
		Begin
			update sys_int_producto set ingresado=1,fecha_carga=getdate() where cliente_id=@cliente_id and producto_id=@producto_id
		End

		Fetch Next From @CurIngProd into @Cliente_id,@Producto_id,@Codigo_producto,@SubCodigo_1,@SubCodigo_2
										,@Descripcion,@Marca,@Fraccionable,@Unidad_Fraccion,@Costo,@Unidad_id
										,@SubFamilia_id,@Familia_id,@Observaciones,@Posiciones_Puras,@Moneda_Costo_Id
										,@Largo,@Alto,@Ancho,@Unidad_Volumen,@Peso,@Unidad_peso,@Lote_Automatico
										,@Pallet_Automatico,@Tolerancia_Min_Ingreso,@Tolerancia_Max_Ingreso
										,@Genera_Back_Order,@Clasificacion_Cot,@Codigo_Barra,@Ing_Cat_log_id
										,@Egr_Cat_log_id,@Producto_activo,@Cod_Tipo_Producto
	End					
	Close @CurIngProd
	Deallocate @CurIngProd
End
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO

ALTER PROCEDURE [dbo].[TAREAS_PICKING_D]
	@USUARIO 			AS VARCHAR(30),
	@VIAJE_ID 			AS VARCHAR(100),
	@PALLET_I			AS VARCHAR(30),
	@RUTA_I				AS VARCHAR(50),
	@CLIENTE			AS VARCHAR(30)=NULL,
	@VH					AS VARCHAR(40)=NULL,
	@PALLETCOMPLETO		AS NUMERIC(10),
	@NAVECALLE			AS VARCHAR(50)=NULL
AS
	DECLARE @VERIFICACION 	AS NUMERIC(20)
	DECLARE @VIAJEID 		AS VARCHAR(100)
	DECLARE @PRODUCTO_ID	AS VARCHAR(50)
	DECLARE @DESCRIPCION	AS VARCHAR(200)
	DECLARE @QTY			AS NUMERIC(20,5)
	DECLARE @POSICION_COD	AS VARCHAR(45)
	DECLARE @PALLET			AS VARCHAR(100)
	DECLARE @RUTA			AS VARCHAR(50)--SE USA INTERNAMENTE Y SE DEVUELVE A LA APLICACION
	DECLARE @UNIDAD_ID		AS VARCHAR(5)
	DECLARE @TQUERY			AS VARCHAR(1)
	DECLARE @PICKING_ID		AS INT
	DECLARE @VAL_COD_EGR	AS CHAR(1)
	DECLARE @CLIENTE_ID		AS VARCHAR(15)
	DECLARE @NRO_LOTE		AS VARCHAR(50)
	DECLARE @TOMARUTA		AS CHAR(1)
	DECLARE @PALLETCOMP		AS CHAR(1)
	DECLARE @NRO_LINEA		AS NUMERIC(20,0)
	DECLARE @NRO_CONTENEDORA AS VARCHAR(50)
	DECLARE @DOCUMENTO_ID AS NUMERIC(20,0)
	DECLARE @LOTEPROVEEDOR	AS VARCHAR(100)
	DECLARE @NRO_PARTIDA	AS VARCHAR(100)
	DECLARE @NRO_SERIE		AS VARCHAR(50)
	DECLARE @NRO_SERIE_STOCK AS VARCHAR(50)

	SET TRANSACTION ISOLATION LEVEL REPEATABLE READ

	BEGIN

	--DETERMINO SI TOMO TODA LA RUTA.
	SELECT	@TOMARUTA=ISNULL(FLG_TOMAR_RUTA,'0')
	FROM	CLIENTE_PARAMETROS
	WHERE	CLIENTE_ID=@CLIENTE

	SELECT	@PALLETCOMP=ISNULL(FLG_ACTIVA_PC_PN,'0')
	FROM	CLIENTE_PARAMETROS
	WHERE	CLIENTE_ID=@CLIENTE

	IF @VIAJE_ID <> '0'	
	BEGIN
		SELECT @VERIFICACION= DBO.VERIFICA_FIN_VIAJES(@VIAJE_ID)
		IF @VERIFICACION=1	
		BEGIN
			RAISERROR ('1', 16, 1)
			Return(99)
		END
		ELSE
		BEGIN
			SELECT @VERIFICACION= Dbo.Fx_Fin_Viaje_Usuario(@VIAJE_ID,@USUARIO)
			IF @VERIFICACION=1	
			BEGIN
				RAISERROR ('1', 16, 1)
				Return(99)
			END
		END
		IF @RUTA_I<>'0' AND @RUTA_I IS NOT NULL
		BEGIN
			SELECT @VERIFICACION= DBO.FX_FIN_RUTA(@VIAJE_ID,@RUTA_I)
			IF @VERIFICACION=1	
			BEGIN
				RAISERROR('2',16,1)
				Return(99)
			END

			ELSE
			BEGIN
				SELECT @VERIFICACION= DBO.FX_FIN_RUTA_USUARIO(@VIAJE_ID,@RUTA_I,@USUARIO)
				IF (@VERIFICACION=1)
				BEGIN
					IF (@TOMARUTA='1')
					BEGIN
						SET @RUTA_I= NULL
					END
					ELSE
					BEGIN
						IF @TOMARUTA='0'
						BEGIN
							Set @RUTA_I=null
						END
						ELSE
						BEGIN
							RAISERROR('2',16,1)
							Return(99)
						END
					END
				END
			END	
		END
	END --FIN VERIFICACIONES.

 	IF @VIAJE_ID='0'	
		BEGIN	
			SET @TQUERY='1'
		END
	ELSE
		BEGIN
			IF @VIAJE_ID IS NOT NULL AND @RUTA_I IS NOT NULL BEGIN
					SET @TQUERY='2'
				END
			ELSE BEGIN
					IF @VIAJE_ID IS NOT NULL AND @RUTA_I IS NULL AND 0=0 --Fin Ruta
						BEGIN
							SET @TQUERY='3'
						END
			END
		END --FIN TQUERY

	IF @TQUERY='1' BEGIN--Por aca pase y termine
		
			SELECT 	TOP 1
					@VIAJEID=SP.VIAJE_ID, @PRODUCTO_ID=SP.PRODUCTO_ID,@DESCRIPCION=SP.DESCRIPCION, 
					@QTY=SUM(SP.CANTIDAD),@POSICION_COD= SP.POSICION_COD,@PALLET=SP.PROP1,@RUTA=SP.RUTA,
					@UNIDAD_ID=PROD.UNIDAD_ID, @VAL_COD_EGR=PROD.VAL_COD_EGR,@CLIENTE_ID=SP.CLIENTE_ID,
					@NRO_LOTE=CASE WHEN CP.FLG_SOLICITA_LOTE='1' THEN ISNULL(DD.PROP2,NULL) ELSE NULL END,
					@NRO_SERIE_STOCK = SP.NRO_SERIE,--@NRO_LINEA= SP.NRO_LINEA, --LO AGREGUE PARA QUE ACTUALICE POR NRO_LINEA Y NO TODAS LAS TAREAS
					@NRO_CONTENEDORA =DD.NRO_BULTO,@LOTEPROVEEDOR = DD.NRO_LOTE, @NRO_PARTIDA = DD.NRO_PARTIDA
					,@NRO_SERIE = DD.NRO_SERIE
			FROM 	PICKING SP
					LEFT JOIN POSICION POS ON(SP.POSICION_COD=POS.POSICION_COD)
					INNER JOIN PRIORIDAD_VIAJE SPV
					ON(LTRIM(RTRIM(UPPER(SPV.VIAJE_ID)))=LTRIM(RTRIM(UPPER(SP.VIAJE_ID))))
					INNER JOIN PRODUCTO PROD
					ON(PROD.CLIENTE_ID=SP.CLIENTE_ID AND PROD.PRODUCTO_ID=SP.PRODUCTO_ID)
					INNER JOIN RL_SYS_CLIENTE_USUARIO SU ON(SP.CLIENTE_ID=SU.CLIENTE_ID)
					INNER JOIN DET_DOCUMENTO DD ON(SP.DOCUMENTO_ID=DD.DOCUMENTO_ID AND SP.NRO_LINEA=DD.NRO_LINEA)
					INNER JOIN CLIENTE C ON(SP.CLIENTE_ID=C.CLIENTE_ID)
					INNER JOIN CLIENTE_PARAMETROS CP ON(C.CLIENTE_ID=CP.CLIENTE_ID)
			WHERE 	SPV.PRIORIDAD = (	SELECT 	MIN(PRIORIDAD)
										FROM	PRIORIDAD_VIAJE
										WHERE	LTRIM(RTRIM(UPPER(VIAJE_ID)))=LTRIM(RTRIM(UPPER(SP.VIAJE_ID)))											)								
												AND SU.USUARIO_ID=@USUARIO
					AND ((CP.FLG_ACTIVA_PC_PN='0') OR (DBO.VERIFICA_PALLET_FINAL(SP.POSICION_COD,SP.VIAJE_ID,SP.RUTA, SP.PROP1)=@PALLETCOMPLETO))
					AND SP.FLG_PALLET_HOMBRE = SP.TRANSF_TERMINADA -- Agregado Privitera Maximiliano 06/01/2010
					AND	SP.FECHA_INICIO IS NULL
					AND	SP.FECHA_FIN IS NULL			
					AND	SP.USUARIO IS NULL
					AND	SP.CANT_CONFIRMADA IS NULL 
					AND	SP.VIAJE_ID IN (SELECT 	VIAJE_ID
										FROM  	RL_VIAJE_USUARIO
										WHERE 	LTRIM(RTRIM(UPPER(VIAJE_ID)))=LTRIM(RTRIM(UPPER(SP.VIAJE_ID)))
												AND	LTRIM(RTRIM(UPPER(USUARIO_ID))) =LTRIM(RTRIM(UPPER(@USUARIO)))
					AND SP.NAVE_COD	IN(	SELECT 	NAVE_COD
										FROM 	NAVE N INNER JOIN RL_USUARIO_NAVE RLNU
												ON(N.NAVE_ID=RLNU.NAVE_ID)
										WHERE	N.NAVE_COD=SP.NAVE_COD
												AND LTRIM(RTRIM(UPPER(RLNU.USUARIO_ID)))=LTRIM(RTRIM(UPPER(@USUARIO)))
										)
										)
					AND SP.FIN_PICKING <>'2'
					AND ((@CLIENTE IS NULL) OR(SP.CLIENTE_ID=@CLIENTE))
					AND	((@VH IS NULL)OR(SP.POSICION_COD IN(SELECT 	POSICION_COD
															FROM 	RL_VEHICULO_POSICION V INNER JOIN POSICION P ON(V.POSICION_ID=P.POSICION_ID)
																	INNER JOIN CALLE_NAVE CN ON(P.CALLE_ID=CN.CALLE_ID)
																	INNER JOIN NAVE NAV ON(P.NAVE_ID=NAV.NAVE_ID)
															WHERE 	VEHICULO_ID=@VH
																	AND((CP.FLG_PICKING_CN='0')OR (CN.CALLE_COD=@NAVECALLE))
															UNION 
															SELECT 	NAVE_COD AS POSICION_COD
															FROM	RL_VEHICULO_POSICION V INNER JOIN NAVE N2
																	ON(V.NAVE_ID=N2.NAVE_ID)
															WHERE	VEHICULO_ID=@VH
																	AND((CP.FLG_PICKING_CN='0')OR(N2.NAVE_COD=@NAVECALLE))
																	)))
			GROUP BY	
					SP.VIAJE_ID, SP.PRODUCTO_ID,SP.DESCRIPCION, SP.RUTA,SP.POSICION_COD,SP.TIPO_CAJA,SP.PROP1,PROD.UNIDAD_ID,
					SPV.PRIORIDAD, PROD.VAL_COD_EGR,SP.CLIENTE_ID, POS.ORDEN_PICKING,CP.FLG_SOLICITA_LOTE, 
					CASE WHEN CP.FLG_SOLICITA_LOTE='1' THEN ISNULL(DD.PROP2,NULL) ELSE NULL END,SP.NRO_SERIE,DD.NRO_BULTO
					,DD.NRO_LOTE,DD.NRO_PARTIDA,DD.NRO_SERIE
			ORDER BY
					SPV.PRIORIDAD ASC,SP.RUTA, CAST(ISNULL(SP.TIPO_CAJA,0) AS NUMERIC(10,1)) DESC,POS.ORDEN_PICKING, SP.POSICION_COD ASC, SP.PRODUCTO_ID


			UPDATE 	PICKING SET FECHA_INICIO = GETDATE(),USUARIO=UPPER(LTRIM(RTRIM(@USUARIO))),PALLET_PICKING=@PALLET_I,
					VEHICULO_ID=@VH		
			FROM	PICKING P INNER JOIN DET_DOCUMENTO DD
					ON(P.DOCUMENTO_ID=DD.DOCUMENTO_ID AND P.NRO_LINEA=DD.NRO_LINEA)			
			WHERE  	LTRIM(RTRIM(UPPER(VIAJE_ID)))=LTRIM(RTRIM(UPPER(@VIAJEID )))
					AND LTRIM(RTRIM(UPPER(P.PRODUCTO_ID)))=LTRIM(RTRIM(UPPER(@PRODUCTO_ID)))
					AND LTRIM(RTRIM(UPPER(P.DESCRIPCION)))=LTRIM(RTRIM(UPPER(@DESCRIPCION)))
					AND FLG_PALLET_HOMBRE = TRANSF_TERMINADA -- Agregado Privitera Maximiliano 06/01/2010
					AND LTRIM(RTRIM(UPPER(P.POSICION_COD)))=LTRIM(RTRIM(UPPER(@POSICION_COD)))
					AND ((@PALLET IS NULL) OR(LTRIM(RTRIM(UPPER(P.PROP1))) = LTRIM(RTRIM(UPPER(@PALLET)))))
					AND LTRIM(RTRIM(UPPER(P.RUTA)))=LTRIM(RTRIM(UPPER(@RUTA)))
					AND ((@LOTEPROVEEDOR IS NULL OR @LOTEPROVEEDOR = '') OR (P.NRO_LOTE=@LOTEPROVEEDOR))
					AND ((@NRO_PARTIDA IS NULL OR @NRO_PARTIDA = '') OR (P.NRO_PARTIDA=@NRO_PARTIDA))
					AND ((@VH IS NULL OR @VH='') 
							OR(	POSICION_COD IN(	SELECT 	POSICION_COD
													FROM 	RL_VEHICULO_POSICION V INNER JOIN POSICION P ON(V.POSICION_ID=P.POSICION_ID)
															INNER JOIN CALLE_NAVE CN ON(P.CALLE_ID=CN.CALLE_ID)
															INNER JOIN NAVE NAV ON(P.NAVE_ID=NAV.NAVE_ID)
													WHERE 	VEHICULO_ID=@VH
													UNION 
													SELECT 	NAVE_COD AS POSICION_COD
													FROM	RL_VEHICULO_POSICION V INNER JOIN NAVE N2
															ON(V.NAVE_ID=N2.NAVE_ID)
													WHERE	VEHICULO_ID=@VH)))
					AND (@NRO_SERIE_STOCK IS NULL OR P.NRO_SERIE = @NRO_SERIE_STOCK)
					AND (@NRO_CONTENEDORA IS NULL OR DD.NRO_BULTO = @NRO_CONTENEDORA)

					
					--AND P.NRO_LINEA =@NRO_LINEA 
					--Catalina Castillo.Tracker 4741
					--AND P.PICKING_ID=@PICKING_ID 
			if @tomaruta='1'
			begin --Comienzo a tomar toda la ruta.
				DECLARE T_RUTA CURSOR FOR
				SELECT 	PICKING_ID
				FROM	PICKING P
				WHERE	((@PALLETCOMP='0') OR (DBO.VERIFICA_PALLET_FINAL(P.POSICION_COD,P.VIAJE_ID,P.RUTA, P.PROP1)=@PALLETCOMPLETO))
						AND P.NAVE_COD IN(	SELECT	NAVE_COD
											FROM 	NAVE N INNER JOIN RL_USUARIO_NAVE RLNU
													ON(N.NAVE_ID=RLNU.NAVE_ID)
											WHERE	N.NAVE_COD=P.NAVE_COD
													AND RLNU.USUARIO_ID=@USUARIO)
													AND LTRIM(RTRIM(UPPER(VIAJE_ID)))=LTRIM(RTRIM(UPPER(@VIAJEID)))
													AND LTRIM(RTRIM(UPPER(RUTA)))=LTRIM(RTRIM(UPPER(@RUTA)))
													AND FECHA_INICIO IS NULL AND FECHA_FIN  IS NULL AND USUARIO IS NULL
													AND	((@VH IS NULL) OR(	POSICION_COD IN(	SELECT 	POSICION_COD
																								FROM 	RL_VEHICULO_POSICION V INNER JOIN POSICION P ON(V.POSICION_ID=P.POSICION_ID)
																										INNER JOIN CALLE_NAVE CN ON(P.CALLE_ID=CN.CALLE_ID)
																										INNER JOIN NAVE NAV ON(P.NAVE_ID=NAV.NAVE_ID)
																								WHERE 	VEHICULO_ID=@VH
																								UNION 
																								SELECT 	NAVE_COD AS POSICION_COD
																								FROM	RL_VEHICULO_POSICION V INNER JOIN NAVE N2
																										ON(V.NAVE_ID=N2.NAVE_ID)
																								WHERE	VEHICULO_ID=@VH)))
				OPEN T_RUTA

				FETCH NEXT FROM T_RUTA INTO @PICKING_ID
				WHILE @@FETCH_STATUS=0 
					BEGIN
					If 0=0 
						Begin
							UPDATE	PICKING SET USUARIO =@USUARIO 
							FROM	PICKING P INNER JOIN DET_DOCUMENTO DD
									ON(P.DOCUMENTO_ID=DD.DOCUMENTO_ID AND P.NRO_LINEA=DD.NRO_LINEA)
							WHERE 	LTRIM(RTRIM(UPPER(VIAJE_ID)))=LTRIM(RTRIM(UPPER(@VIAJEID))) 
									AND LTRIM(RTRIM(UPPER(RUTA)))=LTRIM(RTRIM(UPPER(@RUTA))) 
									AND PICKING_ID=@PICKING_ID
									--AND (DBO.VERIFICA_PALLET_FINAL(@POSICION_COD,@VIAJEID,@RUTA, @PALLET)=@PALLETCOMPLETO)
									AND FECHA_INICIO IS NULL AND FECHA_FIN IS NULL AND CANT_CONFIRMADA IS NULL AND PALLET_PICKING IS NULL
									AND USUARIO IS NULL
									AND
									((@VH IS NULL) OR(	POSICION_COD IN(	SELECT 	POSICION_COD
																			FROM 	RL_VEHICULO_POSICION V INNER JOIN POSICION P ON(V.POSICION_ID=P.POSICION_ID)
																					INNER JOIN CALLE_NAVE CN ON(P.CALLE_ID=CN.CALLE_ID)
																					INNER JOIN NAVE NAV ON(P.NAVE_ID=NAV.NAVE_ID)
																			WHERE 	VEHICULO_ID=@VH
																			UNION 
																			SELECT 	NAVE_COD AS POSICION_COD
																			FROM	RL_VEHICULO_POSICION V INNER JOIN NAVE N2
																					ON(V.NAVE_ID=N2.NAVE_ID)
																			WHERE	VEHICULO_ID=@VH)))
							FETCH NEXT FROM T_RUTA INTO @PICKING_ID
						End
					END
				CLOSE T_RUTA
				DEALLOCATE T_RUTA
			End
			IF @PRODUCTO_ID IS NOT NULL 
			BEGIN
				SELECT 	@VIAJEID AS VIAJE_ID,@PRODUCTO_ID AS PRODUCTO_ID, @DESCRIPCION AS DESCRIPCION, 
						@QTY AS QTY, @POSICION_COD AS POSICION_COD, @PALLET AS PALLET,@RUTA AS RUTA,
						@UNIDAD_ID AS UNIDAD_ID,@VAL_COD_EGR AS VAL_COD_EGR,@CLIENTE_ID AS CLIENTE_ID,
						@NRO_LOTE AS NRO_LOTE,
						@NRO_SERIE_STOCK AS NRO_SERIE_STOCK,
						@NRO_CONTENEDORA AS NRO_CONTENEDORA,	
						@LOTEPROVEEDOR AS LOTE_PROVEEDOR,@NRO_PARTIDA AS NRO_PARTIDA,
						@NRO_SERIE AS NRO_SERIE
				RETURN
			END
		END --FIN TQUERY=1
	ELSE
		BEGIN
			IF @TQUERY='2'
				BEGIN
					SELECT 	TOP 1
							@VIAJEID=SP.VIAJE_ID, @PRODUCTO_ID=SP.PRODUCTO_ID, 
							@DESCRIPCION=SP.DESCRIPCION, @QTY=SUM(SP.CANTIDAD),@POSICION_COD= SP.POSICION_COD,
							@PALLET = SP.PROP1,@RUTA=SP.RUTA,@UNIDAD_ID=PROD.UNIDAD_ID, @VAL_COD_EGR=PROD.VAL_COD_EGR,
							@CLIENTE_ID = SP.CLIENTE_ID,
							@NRO_LOTE=CASE WHEN CP.FLG_SOLICITA_LOTE='1' THEN ISNULL(DD.PROP2,NULL) ELSE NULL END,
							@NRO_SERIE_STOCK = SP.NRO_SERIE,--@NRO_LINEA= SP.NRO_LINEA, --LO AGREGUE PARA QUE ACTUALICE POR NRO_LINEA Y NO TODAS LAS TAREAS
							@NRO_CONTENEDORA =DD.NRO_BULTO,@LOTEPROVEEDOR = DD.NRO_LOTE, @NRO_PARTIDA = DD.NRO_PARTIDA,
							@NRO_SERIE = DD.NRO_SERIE
					FROM 	PICKING SP 
							LEFT JOIN POSICION POS ON(SP.POSICION_COD=POS.POSICION_COD)
							INNER JOIN PRIORIDAD_VIAJE SPV
							ON(LTRIM(RTRIM(UPPER(SPV.VIAJE_ID)))=LTRIM(RTRIM(UPPER(SP.VIAJE_ID))))
							INNER JOIN PRODUCTO PROD
							ON(PROD.CLIENTE_ID=SP.CLIENTE_ID AND PROD.PRODUCTO_ID=SP.PRODUCTO_ID)
							INNER JOIN RL_SYS_CLIENTE_USUARIO SU ON(SP.CLIENTE_ID=SU.CLIENTE_ID)
							INNER JOIN DET_DOCUMENTO DD ON(SP.DOCUMENTO_ID=DD.DOCUMENTO_ID AND SP.NRO_LINEA=DD.NRO_LINEA)
							INNER JOIN CLIENTE C ON(SP.CLIENTE_ID=C.CLIENTE_ID)
							INNER JOIN CLIENTE_PARAMETROS CP ON(C.CLIENTE_ID=CP.CLIENTE_ID)
					WHERE 					
							SP.FECHA_INICIO IS NULL
							AND ((CP.FLG_ACTIVA_PC_PN='0') OR (DBO.VERIFICA_PALLET_FINAL(SP.POSICION_COD,SP.VIAJE_ID,SP.RUTA, SP.PROP1)=@PALLETCOMPLETO))
							AND	SP.FECHA_FIN IS NULL			
							AND SP.CANT_CONFIRMADA IS NULL
							AND SU.USUARIO_ID=@USUARIO
							AND SP.FLG_PALLET_HOMBRE = SP.TRANSF_TERMINADA -- Agregado Privitera Maximiliano 06/01/2010
							--AND UPPER(LTRIM(RTRIM(SP.USUARIO)))=Ltrim(Rtrim(Upper(@Usuario)))
							AND	UPPER(LTRIM(RTRIM(SP.VIAJE_ID)))=LTRIM(RTRIM(UPPER(@VIAJE_ID)))
							and
							SP.VIAJE_ID IN (SELECT 	VIAJE_ID
											FROM  	RL_VIAJE_USUARIO
											WHERE 	LTRIM(RTRIM(UPPER(VIAJE_ID)))=LTRIM(RTRIM(UPPER(SP.VIAJE_ID)))													AND
													LTRIM(RTRIM(UPPER(USUARIO_ID))) =LTRIM(RTRIM(UPPER(@USUARIO))))							AND SP.SALTO_PICKING = (	SELECT 	MIN(ISNULL(SALTO_PICKING,0))
														FROM 	PICKING 
														WHERE 	LTRIM(RTRIM(UPPER(VIAJE_ID)))=LTRIM(RTRIM(UPPER(@VIAJE_ID)))
																AND FECHA_INICIO IS NULL
																--AND USUARIO=SP.USUARIO
																AND FECHA_FIN IS NULL
																AND CANT_CONFIRMADA IS NULL
																AND LTRIM(RTRIM(UPPER(RUTA)))=LTRIM(RTRIM(UPPER(@RUTA_I)))
													)
		
							AND LTRIM(RTRIM(UPPER(RUTA)))=LTRIM(RTRIM(UPPER(@RUTA_I)))
							AND ((@CLIENTE IS NULL) OR (SP.CLIENTE_ID=@CLIENTE))
							AND
							((@VH IS NULL) OR(SP.POSICION_COD IN(	SELECT 	POSICION_COD
																	FROM 	RL_VEHICULO_POSICION V INNER JOIN POSICION P ON(V.POSICION_ID=P.POSICION_ID)
																			INNER JOIN CALLE_NAVE CN ON(P.CALLE_ID=CN.CALLE_ID)
																			INNER JOIN NAVE NAV ON(P.NAVE_ID=NAV.NAVE_ID)
																	WHERE 	VEHICULO_ID=@VH
																	UNION 
																	SELECT 	NAVE_COD AS POSICION_COD
																	FROM	RL_VEHICULO_POSICION V INNER JOIN NAVE N2
																			ON(V.NAVE_ID=N2.NAVE_ID)
																	WHERE	VEHICULO_ID=@VH)))

				GROUP BY	SP.VIAJE_ID, SP.PRODUCTO_ID,SP.DESCRIPCION, SP.RUTA,SP.POSICION_COD,SP.TIPO_CAJA,SP.PROP1,PROD.UNIDAD_ID, PROD.VAL_COD_EGR,SP.CLIENTE_ID,POS.ORDEN_PICKING,
							CP.FLG_SOLICITA_LOTE
							,CASE WHEN CP.FLG_SOLICITA_LOTE='1' THEN ISNULL(DD.PROP2,NULL) ELSE NULL END,SP.NRO_SERIE,DD.NRO_BULTO
							,DD.NRO_LOTE, DD.NRO_PARTIDA, DD.NRO_SERIE
				ORDER BY	CAST(SP.TIPO_CAJA AS NUMERIC(10,1)) DESC,POS.ORDEN_PICKING, SP.POSICION_COD ASC, SP.PRODUCTO_ID--,DD.PROP2
				

				UPDATE 	PICKING SET FECHA_INICIO = GETDATE(),USUARIO=UPPER(LTRIM(RTRIM(@USUARIO))),PALLET_PICKING=@PALLET_I,
						VEHICULO_ID=@VH	
				FROM	PICKING P INNER JOIN DET_DOCUMENTO DD
						ON(P.DOCUMENTO_ID=DD.DOCUMENTO_ID AND P.NRO_LINEA=DD.NRO_LINEA)
				WHERE  	LTRIM(RTRIM(UPPER(VIAJE_ID)))=LTRIM(RTRIM(UPPER(@VIAJEID))) AND P.PRODUCTO_ID=@PRODUCTO_ID 
						AND P.DESCRIPCION=@DESCRIPCION AND POSICION_COD=@POSICION_COD
						AND FLG_PALLET_HOMBRE = TRANSF_TERMINADA -- Agregado Privitera Maximiliano 06/01/2010
						AND ((@PALLET IS NULL) OR(LTRIM(RTRIM(UPPER(P.PROP1))) = LTRIM(RTRIM(UPPER(@PALLET)))))
						AND ((@LOTEPROVEEDOR IS NULL OR @LOTEPROVEEDOR = '') OR (P.NRO_LOTE=@LOTEPROVEEDOR))
						AND ((@NRO_PARTIDA IS NULL OR @NRO_PARTIDA = '') OR (P.NRO_PARTIDA=@NRO_PARTIDA))
						AND LTRIM(RTRIM(UPPER(RUTA)))=LTRIM(RTRIM(UPPER(@RUTA)))
						AND FECHA_INICIO IS NULL AND FECHA_FIN IS NULL AND CANT_CONFIRMADA IS NULL AND PALLET_PICKING IS NULL
						AND
						((@VH IS NULL OR @VH = '') OR(	POSICION_COD IN(	SELECT 	POSICION_COD
																FROM 	RL_VEHICULO_POSICION V INNER JOIN POSICION P ON(V.POSICION_ID=P.POSICION_ID)
																		INNER JOIN CALLE_NAVE CN ON(P.CALLE_ID=CN.CALLE_ID)
																		INNER JOIN NAVE NAV ON(P.NAVE_ID=NAV.NAVE_ID)
																WHERE 	VEHICULO_ID=@VH
																UNION 
																SELECT 	NAVE_COD AS POSICION_COD
																FROM	RL_VEHICULO_POSICION V INNER JOIN NAVE N2
																		ON(V.NAVE_ID=N2.NAVE_ID)
																WHERE	VEHICULO_ID=@VH)))
						AND (@NRO_SERIE_STOCK IS NULL OR P.NRO_SERIE = @NRO_SERIE_STOCK)
						AND (@NRO_CONTENEDORA IS NULL OR (DD.NRO_BULTO = @NRO_CONTENEDORA))
						--AND P.NRO_LINEA =@NRO_LINEA
						--Catalina Castillo.Tracker 4741
						--AND P.PICKING_ID=@PICKING_ID 


				IF @PRODUCTO_ID IS NOT NULL 
					BEGIN
						SELECT 	@VIAJEID AS VIAJE_ID,@PRODUCTO_ID AS PRODUCTO_ID, @DESCRIPCION AS DESCRIPCION, 
								@QTY AS QTY, @POSICION_COD AS POSICION_COD, @PALLET AS PALLET,@RUTA AS RUTA,
								@UNIDAD_ID AS UNIDAD_ID, @VAL_COD_EGR AS VAL_COD_EGR,@CLIENTE_ID AS CLIENTE_ID,
								@NRO_LOTE AS NRO_LOTE,
								@NRO_SERIE_STOCK AS NRO_SERIE_STOCK,	
								@NRO_CONTENEDORA AS NRO_CONTENEDORA,
								@LOTEPROVEEDOR AS LOTE_PROVEEDOR,
								@NRO_PARTIDA AS NRO_PARTIDA,
								@NRO_SERIE AS NRO_SERIE
						RETURN
					END
						
				END --FIN TQUERY=2
			ELSE 
				BEGIN
					IF @TQUERY='3'
						BEGIN
							SELECT 		TOP 1
										@VIAJEID=SP.VIAJE_ID, @PRODUCTO_ID=SP.PRODUCTO_ID, 
										@DESCRIPCION=SP.DESCRIPCION, @QTY=SUM(SP.CANTIDAD),@POSICION_COD= SP.POSICION_COD,
										@PALLET = SP.PROP1,@RUTA=SP.RUTA,@UNIDAD_ID=PROD.UNIDAD_ID, @VAL_COD_EGR=PROD.VAL_COD_EGR,
										@CLIENTE_ID = SP.CLIENTE_ID,
										@NRO_LOTE=CASE WHEN CP.FLG_SOLICITA_LOTE='1' THEN ISNULL(DD.PROP2,NULL) ELSE NULL END,
										@NRO_SERIE_STOCK = SP.NRO_SERIE,--@NRO_LINEA= SP.NRO_LINEA, --LO AGREGUE PARA QUE ACTUALICE POR NRO_LINEA Y NO TODAS LAS TAREAS
										@NRO_CONTENEDORA =DD.NRO_BULTO
										,@LOTEPROVEEDOR = DD.NRO_LOTE,@NRO_PARTIDA=DD.NRO_PARTIDA, @NRO_SERIE = DD.NRO_SERIE
							FROM 		PICKING SP
										LEFT JOIN POSICION POS ON(SP.POSICION_COD=POS.POSICION_COD)
										INNER JOIN PRIORIDAD_VIAJE SPV
										ON(LTRIM(RTRIM(UPPER(SPV.VIAJE_ID)))=LTRIM(RTRIM(UPPER(SP.VIAJE_ID))))
										INNER JOIN PRODUCTO PROD
										ON(PROD.CLIENTE_ID=SP.CLIENTE_ID AND PROD.PRODUCTO_ID=SP.PRODUCTO_ID)
										INNER JOIN RL_SYS_CLIENTE_USUARIO SU ON(SP.CLIENTE_ID=SU.CLIENTE_ID)
										INNER JOIN DET_DOCUMENTO DD ON(SP.DOCUMENTO_ID=DD.DOCUMENTO_ID AND SP.NRO_LINEA=DD.NRO_LINEA)
										INNER JOIN CLIENTE C ON(SP.CLIENTE_ID=C.CLIENTE_ID)
										INNER JOIN CLIENTE_PARAMETROS CP ON(C.CLIENTE_ID=CP.CLIENTE_ID)
							WHERE 		SP.FECHA_INICIO IS NULL
										AND ((CP.FLG_ACTIVA_PC_PN='0') OR (DBO.VERIFICA_PALLET_FINAL(SP.POSICION_COD,SP.VIAJE_ID,SP.RUTA, SP.PROP1)=@PALLETCOMPLETO))
										AND SP.FLG_PALLET_HOMBRE = SP.TRANSF_TERMINADA -- Agregado Privitera Maximiliano 06/01/2010
										AND	SP.FECHA_FIN IS NULL			
										AND	SP.USUARIO IS NULL
										AND	SP.CANT_CONFIRMADA IS NULL
										AND SU.USUARIO_ID=@USUARIO
										AND	SP.VIAJE_ID IN (SELECT 	VIAJE_ID
															FROM  	RL_VIAJE_USUARIO
															WHERE 	VIAJE_ID=SP.VIAJE_ID
																	AND
																	USUARIO_ID =@USUARIO)
										AND SP.NAVE_COD	IN(	SELECT 	NAVE_COD
															FROM 	NAVE N INNER JOIN RL_USUARIO_NAVE RLNU
																	ON(N.NAVE_ID=RLNU.NAVE_ID)
															WHERE	N.NAVE_COD=SP.NAVE_COD
																	AND RLNU.USUARIO_ID=@USUARIO
															)
										AND LTRIM(RTRIM(UPPER(SP.VIAJE_ID)))=UPPER(LTRIM(RTRIM(@VIAJE_ID)))
										AND ((@CLIENTE IS NULL) OR (SP.CLIENTE_ID=@CLIENTE))
										AND
										((@VH IS NULL) OR(SP.POSICION_COD IN(	SELECT 	POSICION_COD
																				FROM 	RL_VEHICULO_POSICION V INNER JOIN POSICION P ON(V.POSICION_ID=P.POSICION_ID)
																						INNER JOIN CALLE_NAVE CN ON(P.CALLE_ID=CN.CALLE_ID)
																						INNER JOIN NAVE NAV ON(P.NAVE_ID=NAV.NAVE_ID)
																				WHERE 	VEHICULO_ID=@VH
																				UNION 
																				SELECT 	NAVE_COD AS POSICION_COD
																				FROM	RL_VEHICULO_POSICION V INNER JOIN NAVE N2
																						ON(V.NAVE_ID=N2.NAVE_ID)
																				WHERE	VEHICULO_ID=@VH)))

							GROUP BY	SP.VIAJE_ID, SP.PRODUCTO_ID, SP.DESCRIPCION, SP.RUTA, SP.POSICION_COD, SP.TIPO_CAJA, SP.PROP1,PROD.UNIDAD_ID, PROD.VAL_COD_EGR, SP.CLIENTE_ID,POS.ORDEN_PICKING,
										CP.FLG_SOLICITA_LOTE, --DD.PROP2
										CASE WHEN CP.FLG_SOLICITA_LOTE='1' THEN ISNULL(DD.PROP2,NULL) ELSE NULL END,SP.NRO_SERIE,DD.NRO_BULTO
										,DD.NRO_LOTE,DD.NRO_PARTIDA,DD.NRO_SERIE
							ORDER BY	CAST(SP.TIPO_CAJA AS NUMERIC(10,1)) DESC,POS.ORDEN_PICKING, SP.POSICION_COD ASC, SP.PRODUCTO_ID--,DD.PROP2
							if @tomaruta='1'
							begin
							DECLARE T_RUTA CURSOR FOR
								SELECT 	PICKING_ID
								FROM	PICKING P
								WHERE	P.NAVE_COD IN(	SELECT 	NAVE_COD
														FROM 	NAVE N INNER JOIN RL_USUARIO_NAVE RLNU
																ON(N.NAVE_ID=RLNU.NAVE_ID)
														WHERE	N.NAVE_COD=P.NAVE_COD
																AND RLNU.USUARIO_ID=@USUARIO)
																AND LTRIM(RTRIM(UPPER(VIAJE_ID)))=LTRIM(RTRIM(UPPER(@VIAJEID)))
																AND LTRIM(RTRIM(UPPER(RUTA)))=LTRIM(RTRIM(UPPER(@RUTA)))
																AND ((@PALLETCOMP='0') OR (DBO.VERIFICA_PALLET_FINAL(P.POSICION_COD,P.VIAJE_ID,P.RUTA, P.PROP1)=@PALLETCOMPLETO))
																AND	((@VH IS NULL) OR(	POSICION_COD IN(SELECT 	POSICION_COD
																										FROM 	RL_VEHICULO_POSICION V INNER JOIN POSICION P ON(V.POSICION_ID=P.POSICION_ID)
																												INNER JOIN CALLE_NAVE CN ON(P.CALLE_ID=CN.CALLE_ID)
																												INNER JOIN NAVE NAV ON(P.NAVE_ID=NAV.NAVE_ID)
																										WHERE 	VEHICULO_ID=@VH
																										UNION 
																										SELECT 	NAVE_COD AS POSICION_COD
																										FROM	RL_VEHICULO_POSICION V INNER JOIN NAVE N2
																												ON(V.NAVE_ID=N2.NAVE_ID)
																										WHERE	VEHICULO_ID=@VH)))
				
							OPEN T_RUTA
							FETCH NEXT FROM T_RUTA INTO @PICKING_ID
							WHILE @@FETCH_STATUS=0 
								BEGIN
								If 0=0 
									Begin
										UPDATE PICKING SET USUARIO =@USUARIO 
										WHERE 	LTRIM(RTRIM(UPPER(VIAJE_ID)))=LTRIM(RTRIM(UPPER(@VIAJEID)))
												AND LTRIM(RTRIM(UPPER(RUTA)))=LTRIM(RTRIM(UPPER(@RUTA)))
												AND PICKING_ID=@PICKING_ID
												AND
												((@VH IS NULL) OR(	POSICION_COD IN(	SELECT 	POSICION_COD
																						FROM 	RL_VEHICULO_POSICION V INNER JOIN POSICION P ON(V.POSICION_ID=P.POSICION_ID)
																								INNER JOIN CALLE_NAVE CN ON(P.CALLE_ID=CN.CALLE_ID)
																								INNER JOIN NAVE NAV ON(P.NAVE_ID=NAV.NAVE_ID)
																						WHERE 	VEHICULO_ID=@VH
																						UNION 
																						SELECT 	NAVE_COD AS POSICION_COD
																						FROM	RL_VEHICULO_POSICION V INNER JOIN NAVE N2
																								ON(V.NAVE_ID=N2.NAVE_ID)
																						WHERE	VEHICULO_ID=@VH)))

										FETCH NEXT FROM T_RUTA INTO @PICKING_ID
									End
								END
				
								CLOSE T_RUTA
								DEALLOCATE T_RUTA
							END
							UPDATE 	PICKING SET FECHA_INICIO = GETDATE(),USUARIO=UPPER(LTRIM(RTRIM(@USUARIO))),PALLET_PICKING=@PALLET_I,
									VEHICULO_ID=@VH	
							FROM	PICKING P INNER JOIN DET_DOCUMENTO DD
									ON(P.DOCUMENTO_ID=DD.DOCUMENTO_ID AND P.NRO_LINEA=DD.NRO_LINEA)
							WHERE  	LTRIM(RTRIM(UPPER(VIAJE_ID)))=LTRIM(RTRIM(UPPER(@VIAJEID)))
									AND FLG_PALLET_HOMBRE = TRANSF_TERMINADA -- Agregado Privitera Maximiliano 06/01/2010
									AND P.PRODUCTO_ID=@PRODUCTO_ID 
									AND P.DESCRIPCION=@DESCRIPCION 
									AND POSICION_COD=@POSICION_COD
									AND ((@LOTEPROVEEDOR IS NULL OR @LOTEPROVEEDOR = '') OR (P.NRO_LOTE=@LOTEPROVEEDOR))
									AND ((@NRO_PARTIDA IS NULL OR @NRO_PARTIDA = '') OR (P.NRO_PARTIDA=@NRO_PARTIDA))
									AND ((@PALLET IS NULL) OR(LTRIM(RTRIM(UPPER(P.PROP1))) = LTRIM(RTRIM(UPPER(@PALLET)))))
									AND LTRIM(RTRIM(UPPER(RUTA)))=LTRIM(RTRIM(UPPER(@RUTA)))
									AND
									((@VH IS NULL OR @VH='') OR(	POSICION_COD IN(	SELECT 	POSICION_COD
																			FROM 	RL_VEHICULO_POSICION V INNER JOIN POSICION P ON(V.POSICION_ID=P.POSICION_ID)
																					INNER JOIN CALLE_NAVE CN ON(P.CALLE_ID=CN.CALLE_ID)
																					INNER JOIN NAVE NAV ON(P.NAVE_ID=NAV.NAVE_ID)
																			WHERE 	VEHICULO_ID=@VH
																			UNION 
																			SELECT 	NAVE_COD AS POSICION_COD
																			FROM	RL_VEHICULO_POSICION V INNER JOIN NAVE N2
																					ON(V.NAVE_ID=N2.NAVE_ID)
																			WHERE	VEHICULO_ID=@VH)))
									AND (@NRO_SERIE_STOCK IS NULL OR P.NRO_SERIE = @NRO_SERIE_STOCK)
									AND (@NRO_CONTENEDORA IS NULL OR DD.NRO_BULTO = @NRO_CONTENEDORA)
									--AND P.PICKING_ID =@PICKING_ID


							IF @PRODUCTO_ID IS NOT NULL 
							BEGIN
								SELECT 	@VIAJEID AS VIAJE_ID,@PRODUCTO_ID AS PRODUCTO_ID, @DESCRIPCION AS DESCRIPCION, 
										@QTY AS QTY, @POSICION_COD AS POSICION_COD, @PALLET AS PALLET,@RUTA AS RUTA,
										@UNIDAD_ID AS UNIDAD_ID, @VAL_COD_EGR AS VAL_COD_EGR,@CLIENTE_ID AS CLIENTE_ID,
										@NRO_LOTE AS NRO_LOTE,
										@NRO_SERIE_STOCK AS NRO_SERIE_STOCK,	
										@NRO_CONTENEDORA AS NRO_CONTENEDORA
										,@LOTEPROVEEDOR AS LOTE_PROVEEDOR
										,@NRO_PARTIDA AS NRO_PARTIDA
										,@NRO_SERIE AS NRO_SERIE										
					END
				END
			END 
		END--END ELSE
	
END-- FIN PROCEDURE
GO

IF @@ERROR <> 0
BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   INSERT INTO #tmpErrors (Error) SELECT 1
   BEGIN TRANSACTION
END
GO

IF @@TRANCOUNT > 0
BEGIN
   IF EXISTS (SELECT * FROM #tmpErrors)
       ROLLBACK TRANSACTION
   ELSE
       COMMIT TRANSACTION
END
GO

DROP TABLE #tmpErrors
GO