/****** Object:  StoredProcedure [dbo].[GTW_EXTRACT#GEN_INT_COT]    Script Date: 11/18/2014 09:27:03 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[GTW_EXTRACT#GEN_INT_COT]') AND type in (N'P', N'PC'))
DROP PROCEDURE [dbo].[GTW_EXTRACT#GEN_INT_COT]
GO


CREATE procedure [dbo].[GTW_EXTRACT#GEN_INT_COT]
  @PCLIENTE varchar(20) OUTPUT,
  @PDESDE   varchar(10) OUTPUT,
  @PHASTA   varchar(10) OUTPUT
AS
BEGIN

	SELECT	D.CLIENTE_ID + ';'+ isnull(SD.CPTE_PREFIJO,'') +';'+ isnull(SD.CPTE_NUMERO,'') +';'+SDD.PRODUCTO_ID+';'
			+ REPLACE(SDD.DESCRIPCION,'','') + ';' + cast (SUM(SDD.CANTIDAD) as varchar) + ';' 
			+ CASE WHEN S.CATEGORIA_IMPOSITIVA_ID = 'CF' THEN '1' ELSE 
			(CASE WHEN S.TIPO_DOCUMENTO_ID = 'CUIT' THEN REPLACE(S.NRO_DOCUMENTO,'-','') ELSE '1' END) END + ';'
	FROM    DOCUMENTO D 
			INNER JOIN SUCURSAL S					ON(D.CLIENTE_ID=S.CLIENTE_ID AND D.SUCURSAL_DESTINO=S.SUCURSAL_ID)
			INNER JOIN SYS_DEV_DET_DOCUMENTO SDD	ON(SDD.DOCUMENTO_ID=D.DOCUMENTO_ID)
			INNER JOIN SYS_DEV_DOCUMENTO SD			ON(SDD.CLIENTE_ID=SD.CLIENTE_ID AND SDD.DOC_EXT=SD.DOC_EXT)
	WHERE   D.STATUS='D40' 
			AND d.CLIENTE_ID=@PCLIENTE
			AND D.TIPO_OPERACION_ID='EGR'
			AND SD.FECHA_ESTADO_GT >= CONVERT(datetime,@PDESDE , 103)
			AND SD.FECHA_ESTADO_GT < CONVERT (datetime,@PHASTA , 103)+1
			AND SD.CPTE_PREFIJO IS NOT NULL
			AND SD.CPTE_NUMERO IS NOT NULL
	GROUP BY
			D.CLIENTE_ID,  isnull(SD.CPTE_PREFIJO,''), isnull(SD.CPTE_NUMERO,''),SDD.PRODUCTO_ID,SDD.DESCRIPCION,S.CATEGORIA_IMPOSITIVA_ID,
			S.TIPO_COMPROBANTE_ID,S.NRO_DOCUMENTO,S.TIPO_DOCUMENTO_ID
	HAVING	SUM(SDD.CANTIDAD)>0
	ORDER BY  D.CLIENTE_ID,  isnull(SD.CPTE_PREFIJO,''), isnull(SD.CPTE_NUMERO,'');	
	
END
GO


