/****** Object:  StoredProcedure [dbo].[EMPAQUE_GET_SELECCIONADOS]    Script Date: 11/27/2014 16:32:16 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[EMPAQUE_GET_SELECCIONADOS]') AND type in (N'P', N'PC'))
DROP PROCEDURE [dbo].[EMPAQUE_GET_SELECCIONADOS]
GO

CREATE PROCEDURE [dbo].[EMPAQUE_GET_SELECCIONADOS]        
AS        
BEGIN        
	SELECT	NULL AS DETALLE        
			,D.NRO_REMITO        
			,P.NRO_UCDESCONSOLIDACION        
			,CONVERT(VARCHAR,MAX(FECHA_FIN),103)+ ' ' +[dbo].[FxTimebyDetime](MAX(FECHA_FIN)) AS FECHA_DESCONSOLIDACION        
			,DBO.Fx_EvaluateContenedoraDesconsolidacion(NRO_UCDESCONSOLIDACION,d.documento_id) Confirmado        
			,D.SUCURSAL_DESTINO        
			,D.CLIENTE_ID        
			,isnull(SD.IMPORTE_FLETE,0) AS IMPORTE_FLETE  
			,SD.TRANSPORTE_ID 
			,ISNULL(T.NOMBRE,'') AS NOMBRE
	FROM	PICKING P INNER JOIN DOCUMENTO D	ON(P.DOCUMENTO_ID=D.DOCUMENTO_ID)        
			LEFT JOIN SYS_INT_DOCUMENTO SD		ON D.NRO_REMITO = SD.DOC_EXT    
			LEFT JOIN TRANSPORTE T				ON SD.TRANSPORTE_ID = T.TRANSPORTE_ID  
	WHERE	EXISTS (	SELECT	1        
					FROM	#TMP_EMPAQUE_CAB T        
					WHERE	T.PEDIDO=D.NRO_REMITO)       
			--AND P.NRO_UCEMPAQUETADO IS NULL        
			AND P.CANT_CONFIRMADA > 0      
			AND P.NRO_UCDESCONSOLIDACION IS NOT NULL      
	GROUP BY        
			d.documento_id,D.NRO_REMITO, P.NRO_UCDESCONSOLIDACION,D.SUCURSAL_DESTINO,D.CLIENTE_ID,
			SD.IMPORTE_FLETE, SD.TRANSPORTE_ID,t.nombre  
END

GO


