
/****** Object:  StoredProcedure [dbo].[GET_TAREAS_INVENTARIO]    Script Date: 12/30/2014 12:23:31 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[GET_TAREAS_INVENTARIO]') AND type in (N'P', N'PC'))
DROP PROCEDURE [dbo].[GET_TAREAS_INVENTARIO]
GO

CREATE PROCEDURE [dbo].[GET_TAREAS_INVENTARIO]
@INVENTARIO_ID NUMERIC(20,0)
AS
BEGIN 
	DECLARE @TAREAS AS NUMERIC(20,0)
	DECLARE @CONTEO AS NUMERIC(20,0)
	DECLARE @USUARIO_ID AS VARCHAR(20)
	DECLARE @TAREAS_PENDIENTES AS NUMERIC(20,0)
	DECLARE @MARBETE AS NUMERIC(20,0)
	DECLARE @sql_str AS VARCHAR(MAX)
		
	--SET @USUARIO_ID = 'SGOMEZ'
	SELECT @USUARIO_ID=USUARIO_ID FROM #TEMP_USUARIO_LOGGIN
	SELECT @TAREAS = QTY_TASK_USER,@CONTEO = NRO_CONTEO FROM INVENTARIO WHERE INVENTARIO_ID = @INVENTARIO_ID
	
	SELECT @TAREAS_PENDIENTES = COUNT(*) 
	FROM RL_DET_CONTEO_USUARIO RL
	INNER JOIN DET_CONTEO DC ON (RL.INVENTARIO_ID = DC.INVENTARIO_ID AND RL.MARBETE = DC.MARBETE)
	WHERE RL.USUARIO_ID = @USUARIO_ID AND RL.INVENTARIO_ID = @INVENTARIO_ID AND RL.FECHA_FIN IS NULL
	AND (
			 (@CONTEO = 1 AND DC.CONTEO1 IS NULL) OR
			 (@CONTEO = 2 AND DC.CONTEO2 IS NULL) OR
			 (@CONTEO = 3 AND DC.CONTEO3 IS NULL))

	SET @TAREAS = @TAREAS - @TAREAS_PENDIENTES
	
	IF @TAREAS > 0
	BEGIN

		SET @sql_str = 'INSERT INTO RL_DET_CONTEO_USUARIO (INVENTARIO_ID, MARBETE,USUARIO_ID,NRO_CONTEO,FECHA_INICIO,FECHA_FIN) '
		SET @sql_str = @sql_str + 'SELECT TOP ' + STR(@TAREAS) 
		SET @sql_str = @sql_str + ' DC.INVENTARIO_ID, DC.MARBETE,'''+ @USUARIO_ID +''' AS USUARIO_ID,' 
		SET @sql_str = @sql_str + STR(@CONTEO)  + ' AS NRO_CONTEO ,GETDATE() AS FECHA_INICIO, NULL AS FECHA_FIN '  
		SET @sql_str = @sql_str + 'FROM DET_CONTEO DC ' 
		SET @sql_str = @sql_str + 'INNER JOIN DET_INVENTARIO DI ON (DC.INVENTARIO_ID = DI.INVENTARIO_ID AND DC.MARBETE = DI.MARBETE) '
		SET @sql_str = @sql_str + 'LEFT JOIN POSICION P ON (P.POSICION_ID = DC.POSICION_ID) '
		SET @sql_str = @sql_str + 'WHERE DC.MARBETE NOT IN '
		SET @sql_str = @sql_str + '(SELECT MARBETE FROM RL_DET_CONTEO_USUARIO '
		SET @sql_str = @sql_str + 'WHERE INVENTARIO_ID = ' + STR(@INVENTARIO_ID)+' AND FECHA_FIN IS NULL'
		SET @sql_str = @sql_str + ' AND NRO_CONTEO = ' + STR(@CONTEO) + ' ) AND DC.INVENTARIO_ID = ' +STR(@INVENTARIO_ID)   
		IF @CONTEO = 1 
		BEGIN
			SET @sql_str = @sql_str + ' AND CONTEO1 IS NULL '
		END
		IF @CONTEO = 2 
		BEGIN
			SET @sql_str = @sql_str + ' AND CONTEO2 IS NULL AND CONTEO1 <> DI.CANT_STOCK_CONT_1 '
		END
		IF @CONTEO = 3 
		BEGIN
			SET @sql_str = @sql_str + ' AND CONTEO3 IS NULL AND CONTEO2 <> CANT_STOCK_CONT_2 '
			SET @sql_str = @sql_str + ' AND CONTEO2 IS NOT NULL '
		END
		SET @sql_str = @sql_str + ' ORDER BY POSICION_COD '
		
		EXECUTE (@sql_str)

	END
	SELECT 
		DC.MARBETE,
		POSICION_COD AS POSICION,
		DC.CLIENTE_ID AS CLIENTE,
		DC.PRODUCTO_ID AS PRODUCTO,
		--MGR 20120312 Se muestra la descripcion del producto
        PR.DESCRIPCION AS DESCRIPCION, 
		UM.DESCRIPCION AS UNIDAD,
		CASE WHEN PR.ingLoteProveedor = '1' OR PR.LOTE_AUTOMATICO = '1' THEN DI.NRO_LOTE ELSE '' END AS NRO_LOTE,
		CASE WHEN PR.ingPartida = '1' OR PR.NRO_PARTIDA_AUTOMATICO = '1' THEN DI.NRO_PARTIDA ELSE '' END AS NRO_PARTIDA
		FROM RL_DET_CONTEO_USUARIO RL
		INNER JOIN DET_CONTEO DC ON(DC.MARBETE = RL.MARBETE AND DC.INVENTARIO_ID = RL.INVENTARIO_ID) 
		INNER JOIN DET_INVENTARIO DI ON (DI.INVENTARIO_ID = DC.INVENTARIO_ID AND DI.MARBETE = DC.MARBETE)
		INNER JOIN POSICION PS ON(DC.POSICION_ID = PS.POSICION_ID)
		INNER JOIN PRODUCTO PR ON(DC.PRODUCTO_ID = PR.PRODUCTO_ID AND PR.CLIENTE_ID = DC.CLIENTE_ID)
		INNER JOIN UNIDAD_MEDIDA UM ON(UM.UNIDAD_ID = PR.UNIDAD_ID)
		WHERE RL.USUARIO_ID = @USUARIO_ID AND RL.FECHA_FIN IS NULL AND RL.INVENTARIO_ID = @INVENTARIO_ID
			AND (
				 (@CONTEO = 1 AND DC.CONTEO1 IS NULL) OR
				 (@CONTEO = 2 AND DC.CONTEO2 IS NULL) OR
				 (@CONTEO = 3 AND DC.CONTEO3 IS NULL))

		--ORDER BY DC.MARBETE
	UNION ALL
	SELECT 
		DC.MARBETE,
		N.NAVE_COD AS POSICION,
		DC.CLIENTE_ID AS CLIENTE,
		DC.PRODUCTO_ID AS PRODUCTO,
		--MGR 20120312 Se muestra la descripcion del producto
        PR.DESCRIPCION AS DESCRIPCION, 
		UM.DESCRIPCION AS UNIDAD,
		CASE WHEN PR.ingLoteProveedor = '1' OR PR.LOTE_AUTOMATICO = '1' THEN DI.NRO_LOTE ELSE '' END AS NRO_LOTE,
		CASE WHEN PR.ingPartida = '1' OR PR.NRO_PARTIDA_AUTOMATICO = '1' THEN DI.NRO_PARTIDA ELSE '' END AS NRO_PARTIDA
		FROM RL_DET_CONTEO_USUARIO RL
		INNER JOIN DET_CONTEO DC ON(DC.MARBETE = RL.MARBETE AND DC.INVENTARIO_ID = RL.INVENTARIO_ID) 
		INNER JOIN DET_INVENTARIO DI ON (DI.INVENTARIO_ID = DC.INVENTARIO_ID AND DI.MARBETE = DC.MARBETE)
		INNER JOIN NAVE N ON(DC.NAVE_ID = N.NAVE_ID)
		INNER JOIN PRODUCTO PR ON(DC.PRODUCTO_ID = PR.PRODUCTO_ID AND PR.CLIENTE_ID = DC.CLIENTE_ID)
		INNER JOIN UNIDAD_MEDIDA UM ON(UM.UNIDAD_ID = PR.UNIDAD_ID)
		WHERE RL.USUARIO_ID = @USUARIO_ID AND RL.FECHA_FIN IS NULL AND RL.INVENTARIO_ID = @INVENTARIO_ID
			AND (
				 (@CONTEO = 1 AND DC.CONTEO1 IS NULL) OR
				 (@CONTEO = 2 AND DC.CONTEO2 IS NULL) OR
				 (@CONTEO = 3 AND DC.CONTEO3 IS NULL))

		ORDER BY DC.MARBETE



END

GO


