
/****** Object:  StoredProcedure [dbo].[INSERT_RLPC]    Script Date: 12/31/2014 12:21:37 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[INSERT_RLPC]') AND type in (N'P', N'PC'))
DROP PROCEDURE [dbo].[INSERT_RLPC]
GO

CREATE PROCEDURE [dbo].[INSERT_RLPC]
@CLIENTE_ID		VARCHAR(15)	OUTPUT,
@PRODUCTO_ID	VARCHAR(30)	OUTPUT,
@TIPO_CODIGO	VARCHAR(20)	OUTPUT,
@CODIGO			VARCHAR(50)	OUTPUT,
@CANTIDAD		VARCHAR(20)	OUTPUT,
@STATUS_LN		VARCHAR(10)	OUTPUT
AS
BEGIN

	DECLARE @CONTROL		AS FLOAT(1)
	
	SET @STATUS_LN='0'
	
	--CONTROLO EL CLIENTE
	SELECT 	@CONTROL=COUNT(*)
	FROM 	CLIENTE
	WHERE	CLIENTE_ID=LTRIM(RTRIM(UPPER(@CLIENTE_ID)))

	IF @CONTROL=0
	BEGIN
		SET @STATUS_LN='1';
		RETURN
	END

	--CONTROLO QUE EL PRODUCTO NO SEA VACIO
	IF (@PRODUCTO_ID IS NULL) OR (LTRIM(RTRIM(UPPER(@PRODUCTO_ID)))='')
	BEGIN
		SET @STATUS_LN='2';
		RETURN
	END

	--CONTROLO EL PRODUCTO
	SELECT 	@CONTROL=COUNT(*)
	FROM 	PRODUCTO
	WHERE	CLIENTE_ID=LTRIM(RTRIM(UPPER(@CLIENTE_ID)))
			AND PRODUCTO_ID=LTRIM(RTRIM(UPPER(@PRODUCTO_ID)))

	IF @CONTROL=0
	BEGIN
		SET @STATUS_LN='3';
		RETURN
	END

	-- CONTROL
	IF (@TIPO_CODIGO IS NULL) OR (@CODIGO IS NULL)OR (@TIPO_CODIGO = '') OR (@CODIGO = '')
	BEGIN
		SET @STATUS_LN='4';
		RETURN
	END

	-- CONTROLO QUE EL TIPO DE CODIGO SEA VALIDO
	IF (@TIPO_CODIGO <> 'EAN13') AND (@TIPO_CODIGO <> 'DUN14')
	BEGIN
		SET @STATUS_LN='5';
		RETURN
	END
	
	-- CONTROLO QUE EL CODIGO NO HAYA SIDO CARGADO ANTERIORMENTE
	
	SELECT 	@CONTROL=COUNT(*)
	FROM 	RL_PRODUCTO_CODIGOS
	WHERE	CLIENTE_ID=LTRIM(RTRIM(UPPER(@CLIENTE_ID)))
			AND PRODUCTO_ID=LTRIM(RTRIM(UPPER(@PRODUCTO_ID)))
			AND TIPO_CODIGO=LTRIM(RTRIM(UPPER(@TIPO_CODIGO)))

	IF @CONTROL <> 0
	BEGIN
		SET @STATUS_LN='6';
		RETURN
	END
	
	IF (@CANTIDAD = '')
	BEGIN
		SET @CANTIDAD=NULL;
	END

	--INSERTO EN LA TABLA
	INSERT INTO RL_PRODUCTO_CODIGOS (CLIENTE_ID, PRODUCTO_ID, TIPO_CODIGO, CODIGO, CANTIDAD) 
	VALUES(@CLIENTE_ID, @PRODUCTO_ID, @TIPO_CODIGO, @CODIGO, @CANTIDAD)

END


GO


