ALTER TABLE NAVE ADD ZONA_PRE_PICKING	VARCHAR(1) DEFAULT('0')
GO

UPDATE NAVE SET ZONA_PRE_PICKING='0'
GO

INSERT INTO SYS_TABCOLUMNS VALUES('NAVE',	'ZONA_PRE_PICKING',	22,	'CHAR',	'Y',	1,	NULL,	NULL,	1,	NULL)
GO

INSERT INTO SYS_DET_TABLA VALUES('NAVE',	'ZONA_PRE_PICKING',	'Zona Pre-Picking',	'S',	1,	0)