IF  EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[dbo].[PROCESO_EGRESO_RLBCK]') AND TYPE IN (N'P', N'PC'))
DROP PROCEDURE [dbo].[PROCESO_EGRESO_RLBCK]
GO
/*
	Tablas que toca el Locator de Egreso:
	-------------------------------------------------
	1.	CONSUMO_LOCATOR_EGR (LA ULTIMA EN TOCARSE)
	2.	DET_DOCUMENTO_AUX.							OK.
	3.	DET_DOCUMENTO
	4.	RL_DET_DOC_TRANS_POSICION
	5.	DOCXVIAJESPROCESADOS						OK.
	6.	DOCUMENTO_TRANSACCION			
	7.	DET_DOCUMENTO_TRANSACCION
	8.	DOCUMENTO.

*/
CREATE PROCEDURE [dbo].[PROCESO_EGRESO_RLBCK]
@DOCUMENTO_ID	NUMERIC(20,0)	OUTPUT,
@EJECUCION		NUMERIC(1)		OUTPUT
AS
BEGIN
	DECLARE @DOC_TRANS_ID	AS NUMERIC(20,0)
	DECLARE @DOC_EXT		AS VARCHAR(100)
	BEGIN TRY
		
		SELECT	@DOC_TRANS_ID =DOC_TRANS_ID FROM DET_DOCUMENTO_TRANSACCION WHERE DOCUMENTO_ID= @DOCUMENTO_ID

		SELECT @DOC_EXT=NRO_REMITO FROM DOCUMENTO WHERE DOCUMENTO_ID =@DOCUMENTO_ID 

		DELETE FROM DET_DOCUMENTO_AUX WHERE DOCUMENTO_ID=@DOCUMENTO_ID

		DELETE FROM DOCXVIAJESPROCESADOS WHERE DOCUMENTO_ID=@DOCUMENTO_ID
		
		DELETE FROM consumo_locator_egr WHERE DOCUMENTO_ID=@DOCUMENTO_ID 

		UPDATE	RL_DET_DOC_TRANS_POSICION 
		SET		DISPONIBLE ='1', 
				DOC_TRANS_ID_EGR=NULL, 
				NRO_LINEA_TRANS_EGR =NULL, 
				POSICION_ACTUAL =POSICION_ANTERIOR, 
				NAVE_ACTUAL =NAVE_ANTERIOR,
				POSICION_ANTERIOR =Null,
				NAVE_ANTERIOR =1,
				CAT_LOG_ID =ISNULL(RL.CAT_LOG_ID_FINAL,DD.CAT_LOG_ID_FINAL)
		FROM	RL_DET_DOC_TRANS_POSICION RL INNER JOIN DET_DOCUMENTO_TRANSACCION DDT	ON(DDT.DOC_TRANS_ID = RL.DOC_TRANS_ID_EGR AND DDT.NRO_LINEA_TRANS = RL.NRO_LINEA_TRANS_EGR )
				INNER JOIN DET_DOCUMENTO DD												ON(DDT.DOCUMENTO_ID =DD.DOCUMENTO_ID AND DDT.NRO_LINEA_DOC =DD.NRO_LINEA)
		WHERE	DD.DOCUMENTO_ID =@DOCUMENTO_ID

		DELETE FROM DET_DOCUMENTO_TRANSACCION WHERE DOC_TRANS_ID =@DOC_TRANS_ID

		DELETE FROM DOCUMENTO_TRANSACCION WHERE DOC_TRANS_ID=@DOC_TRANS_ID

		DELETE FROM PICKING WHERE DOCUMENTO_ID =@DOCUMENTO_ID 

		DELETE FROM DET_DOCUMENTO WHERE DOCUMENTO_ID =@DOCUMENTO_ID 

		DELETE FROM DOCUMENTO WHERE DOCUMENTO_ID=@DOCUMENTO_ID 

		UPDATE	SYS_INT_DET_DOCUMENTO SET ESTADO_GT=NULL, FECHA_ESTADO_GT =NULL, DOCUMENTO_ID=NULL WHERE DOC_EXT=@DOC_EXT

		UPDATE	SYS_INT_DOCUMENTO SET ESTADO_GT=NULL, FECHA_ESTADO_GT =NULL WHERE DOC_EXT=@DOC_EXT	

		SET @EJECUCION =1;
	END TRY
	BEGIN CATCH
		SET @EJECUCION =0;
	END CATCH
END
GO


