IF  EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[vguardado]'))
DROP VIEW [dbo].[vguardado]
GO

CREATE VIEW [dbo].[vguardado]
AS
SELECT 
D.CLIENTE_ID						AS CLIENTE_ID
,CLI.RAZON_SOCIAL					AS RAZON_SOCIAL
,D.TIPO_COMPROBANTE_ID				AS TIPO_COMPROBANTE
,D.FECHA_ALTA_GTW					AS FECHA_ALTA
,D.ORDEN_DE_COMPRA					AS ORDEN_COMPRA
,D.DOCUMENTO_ID						AS DOCUMENTO_ID
,D.SUCURSAL_ORIGEN					AS PROVEEDOR
,S.NOMBRE                 AS NOMBRE_PROVEEDOR
,P.PRODUCTO_ID						AS PRODUCTO_ID
,P.DESCRIPCION						AS DESCRIPCION
,DD.CANTIDAD						AS CANTIDAD_TOTAL_DOCUMENTO
,A.CANTIDAD							AS CANTIDAD_GUARDADO
,P.PESO_UNITARIO*A.CANTIDAD			AS PESO_KG
,(( isnull(P.largo,0) * isnull(p.alto,0) * isnull(p.ancho,0) )/1000000) * A.CANTIDAD		AS VOLUMEN_M3
,P.FAMILIA_ID						AS FLIA
,P.SUB_FAMILIA_ID					AS SUB_FLIA
,A.USUARIO_ID						AS USUARIO_INGRESO
,A.USUARIO_ID						AS USUARIO_GUARDADO
,A.FECHA_AUDITORIA					AS FECHA_GUARDADO
FROM DOCUMENTO D
		INNER JOIN DET_DOCUMENTO DD ON (D.DOCUMENTO_ID=DD.DOCUMENTO_ID)
		INNER JOIN PRODUCTO P ON (DD.CLIENTE_ID=P.CLIENTE_ID AND DD.PRODUCTO_ID=P.PRODUCTO_ID)
		INNER JOIN AUDITORIA_HISTORICOS A ON (DD.DOCUMENTO_ID=A.DOCUMENTO_ID AND DD.NRO_LINEA=A.NRO_LINEA_DOC AND A.TIPO_AUDITORIA_ID='1' AND A.CANTIDAD>0)
		INNER JOIN CLIENTE CLI ON (D.CLIENTE_ID=CLI.CLIENTE_ID)
		LEFT  JOIN SUCURSAL S ON (D.CLIENTE_ID = S.CLIENTE_ID AND D.SUCURSAL_ORIGEN = S.SUCURSAL_ID)
WHERE
	D.TIPO_OPERACION_ID='ING'

GO