CREATE TABLE PARAMETRICA_CONFIGURACION_DEFAULT(
	ID				NUMERIC(20,0) NOT NULL IDENTITY(1,1),
	TABLA			VARCHAR(100),
	COLUMNA			VARCHAR(100),
	REFERENCIA		VARCHAR(100),
	VALOR_DEFAULT	VARCHAR(1000)
)
GO

ALTER TABLE PARAMETRICA_CONFIGURACION_DEFAULT ADD CONSTRAINT PK_PARAMETRICA_CONFIGURACION_DEFAULT PRIMARY KEY(ID)
