INSERT INTO PARAMETRICA_CONFIGURACION_DEFAULT(TABLA, COLUMNA, VALOR_DEFAULT)
SELECT	TABLE_NAME, COLUMN_NAME, NULL
FROM	INFORMATION_SCHEMA.COLUMNS i
WHERE	TABLE_NAME = N'producto'
		AND COLUMN_NAME NOT IN('CLIENTE_ID','PRODUCTO_ID')
ORDER BY
		ORDINAL_POSITION