CREATE FUNCTION DBO.FX_GET_PARAM_CONF_DEFAULT(
	@TABLA		VARCHAR(100),
	@CAMPO		VARCHAR(100),
	@REF		VARCHAR(100),
	@VALOR		VARCHAR(1000)
)RETURNS VARCHAR(1000)
AS
BEGIN

	DECLARE @RETURN VARCHAR(1000)

	IF LTRIM(RTRIM(@VALOR))<>'' BEGIN

		SET @RETURN =@VALOR

	END ELSE BEGIN

		SELECT	@RETURN=VALOR_DEFAULT
		FROM	PARAMETRICA_CONFIGURACION_DEFAULT
		WHERE	TABLA=@TABLA
				AND COLUMNA=@CAMPO
				AND ((@REF IS NULL OR @REF='')OR(REFERENCIA=@REF))

	END

	RETURN @RETURN

END