/****** Object:  StoredProcedure [dbo].[SKU_CONTENEDORA_SERIE]    Script Date: 04/23/2014 13:14:36 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[SKU_CONTENEDORA_SERIE]') AND type in (N'P', N'PC'))
DROP PROCEDURE [dbo].[SKU_CONTENEDORA_SERIE]
GO

CREATE PROCEDURE [dbo].[SKU_CONTENEDORA_SERIE]
@CLIENTE		VARCHAR(15),
@CONTENEDORA	VARCHAR(50),
@RETORNO		VARCHAR(100)OUTPUT
AS
BEGIN
	
	DECLARE @RET	VARCHAR(2)
	DECLARE @CONT	NUMERIC
	

	SELECT	@RETORNO=P.PRODUCTO_ID +' - '+ P.DESCRIPCION
	FROM	DET_DOCUMENTO dd inner join DET_DOCUMENTO_TRANSACCION ddt
			on(dd.DOCUMENTO_ID=ddt.DOCUMENTO_ID and dd.NRO_LINEA=ddt.NRO_LINEA_DOC)
			inner join RL_DET_DOC_TRANS_POSICION rl
			on(ddt.DOC_TRANS_ID=rl.DOC_TRANS_ID and ddt.NRO_LINEA_TRANS=rl.NRO_LINEA_TRANS)
			inner join PRODUCTO p
			on(dd.CLIENTE_ID=p.CLIENTE_ID and dd.PRODUCTO_ID=p.PRODUCTO_ID)
	where	dd.CLIENTE_ID=@CLIENTE
			and dd.NRO_BULTO=@CONTENEDORA	
						
END

GO


