IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[GET_SERIES_TOMADAS]') AND type in (N'P', N'PC'))
DROP PROCEDURE [dbo].[GET_SERIES_TOMADAS]
GO

CREATE PROCEDURE DBO.GET_SERIES_TOMADAS
	@IDPROCESO			NUMERIC(20,0),
	@CLIENTE_ID			VARCHAR(15),
	@NRO_CONTENEDORA	VARCHAR(100)
as
begin

	SELECT	SERIE 	
	from	CargaSeriesLog
	where	IDPROCESO=@IDPROCESO
			and CLIENTE_ID=@CLIENTE_ID
			and NRO_BULTO=@NRO_CONTENEDORA
end