IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[CANT_SERIES_PENDIENTES]') AND type in (N'P', N'PC'))
DROP PROCEDURE [dbo].[CANT_SERIES_PENDIENTES]
GO

Create PROCEDURE DBO.CANT_SERIES_PENDIENTES
	@IDPROCESO		NUMERIC,
	@CLIENTE_ID		VARCHAR(15),
	@NRO_BULTO		VARCHAR(100),
	@CANTIDAD		NUMERIC OUTPUT
AS
BEGIN
	
	DECLARE @SERIES_TOTALES		NUMERIC(20,0)
	DECLARE @SERIES_CARGADAS	NUMERIC(20,0)


	SELECT	@SERIES_TOTALES=SUM(DD.CANTIDAD)
	FROM	DET_DOCUMENTO DD INNER JOIN DET_DOCUMENTO_TRANSACCION DDT
			ON(DD.DOCUMENTO_ID=DDT.DOCUMENTO_ID AND DD.NRO_LINEA=DDT.NRO_LINEA_DOC)
			INNER JOIN RL_DET_DOC_TRANS_POSICION RL
			ON(DDT.DOC_TRANS_ID=RL.DOC_TRANS_ID AND DDT.NRO_LINEA_TRANS=RL.NRO_LINEA_TRANS)
	WHERE	DD.CLIENTE_ID=@CLIENTE_ID
			AND DD.NRO_BULTO=@NRO_BULTO 
			AND DD.NRO_SERIE IS NULL

	SELECT	@SERIES_CARGADAS=COUNT(*)
	FROM	dbo.CargaSeriesLog
	WHERE	IDPROCESO=@IDPROCESO
			AND CLIENTE_ID=@CLIENTE_ID
			AND NRO_BULTO=@NRO_BULTO
			AND CARGADA=0

	SET @CANTIDAD=@SERIES_TOTALES-@SERIES_CARGADAS
				
END