IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[VALIDACION_SERIE]') AND type in (N'P', N'PC'))
DROP PROCEDURE [dbo].[VALIDACION_SERIE]
GO

CREATE PROCEDURE DBO.VALIDACION_SERIE
	@IDPROCESO		NUMERIC,
	@CLIENTE_ID		VARCHAR(15),
	@NRO_BULTO		VARCHAR(100),
	@NRO_SERIE		VARCHAR(50),
	@RETORNO		VARCHAR(2)	OUTPUT
AS
BEGIN
	/*
		1.	Serie incorrecta, no empieza con 1S.
		2.	Longitud de serie incorrecta.
		3.	Serie ingresada.
	*/
	DECLARE @CONT	NUMERIC
	DECLARE @SRI	VARCHAR(2)
	DECLARE @SKU	VARCHAR(50)
	
	--1.	ALGORITMO. SE QUE TIENE QUE COMENZAR CON 1S.
	SELECT	@SRI=SUBSTRING(@NRO_SERIE,1,2)
	IF @SRI<>'1S' BEGIN
		SET @RETORNO ='1'
		RETURN
	END
	
	--2.	LONGITUD DE SERIE
	select @CONT=LEN(@NRO_SERIE)
	IF @CONT<>14 BEGIN
		SET @RETORNO ='2'
		RETURN
	END
	
	--3.	SERIE REPETIDA.
	SELECT	@SKU=DD.PRODUCTO_ID
	FROM	DET_DOCUMENTO DD INNER JOIN DET_DOCUMENTO_TRANSACCION DDT
			ON(DD.DOCUMENTO_ID=DDT.DOCUMENTO_ID AND DD.NRO_LINEA=DDT.NRO_LINEA_DOC)
			INNER JOIN RL_DET_DOC_TRANS_POSICION RL
			ON(DDT.DOC_TRANS_ID=RL.DOC_TRANS_ID AND DDT.NRO_LINEA_TRANS=RL.NRO_LINEA_TRANS)
	WHERE	DD.CLIENTE_ID=@CLIENTE_ID
			AND DD.NRO_BULTO=@NRO_BULTO
				
	SELECT	@CONT=COUNT(*)
	FROM	DET_DOCUMENTO DD INNER JOIN DET_DOCUMENTO_TRANSACCION DDT
			ON(DD.DOCUMENTO_ID=DDT.DOCUMENTO_ID AND DD.NRO_LINEA=DDT.NRO_LINEA_DOC)
			INNER JOIN RL_DET_DOC_TRANS_POSICION RL
			ON(DDT.DOC_TRANS_ID=RL.DOC_TRANS_ID AND DDT.NRO_LINEA_TRANS=RL.NRO_LINEA_TRANS)
	WHERE	DD.CLIENTE_ID=@CLIENTE_ID
			AND DD.PRODUCTO_ID=@SKU
			AND DD.NRO_SERIE=@NRO_SERIE
	
	IF @CONT >0 BEGIN
		SET @RETORNO ='3'
		RETURN
	END 		

	SET @RETORNO ='0'

END --FIN PROCEDURE.


