IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[GET_SERIE_ESPECIFICA]') AND type in (N'P', N'PC'))
DROP PROCEDURE [dbo].[GET_SERIE_ESPECIFICA]
GO

CREATE PROCEDURE DBO.GET_SERIE_ESPECIFICA
	@CONTENEDORA	AS VARCHAR(100),
	@OUT			AS VARCHAR(1) OUTPUT
AS
BEGIN

	--Paso la contenedora por las dudas. Dejo abierta muchas posibilidades.
	SELECT	@OUT=VALOR
	FROM	SYS_PARAMETRO_PROCESO 
	WHERE	PROCESO_ID='WARP'
			AND SUBPROCESO_ID='PICKING'
			AND PARAMETRO_ID='SERIE_ESPECIFICA'

END