IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[MOB_CONFIRMA_SERIES_PALLET]') AND type in (N'P', N'PC'))
DROP PROCEDURE [dbo].[MOB_CONFIRMA_SERIES_PALLET]
GO
CREATE PROCEDURE DBO.MOB_CONFIRMA_SERIES_PALLET
	@VIAJE_ID		VARCHAR(100),
	@POSICION_COD	VARCHAR(45),
	@PALLET			VARCHAR(100),
	@PALLET_PICK	VARCHAR(100),
	@USUARIO		VARCHAR(100)
AS
BEGIN
	
	DECLARE @FECHA_INICIO	DATETIME
	DECLARE @CANTIDAD		NUMERIC
	DECLARE @DIF			NUMERIC
	
	SELECT	DISTINCT
			@FECHA_INICIO=FECHA_INICIO
	FROM	PICKING
	WHERE	VIAJE_ID=@VIAJE_ID 
			AND POSICION_COD=@POSICION_COD
			AND PROP1=@PALLET
			AND PALLET_PICKING =@PALLET_PICK
			AND USUARIO=@USUARIO
			AND FECHA_INICIO IS NOT NULL
			AND FECHA_FIN IS NULL
			AND CANT_CONFIRMADA IS NULL

	UPDATE	PICKING
	SET		FECHA_INICIO=@FECHA_INICIO, FECHA_FIN=GETDATE(), USUARIO=@USUARIO,CANT_CONFIRMADA=CANTIDAD, PALLET_PICKING=@PALLET_PICK 
	WHERE	VIAJE_ID=@VIAJE_ID 
			AND POSICION_COD=@POSICION_COD
			AND PROP1=@PALLET
			--AND USUARIO=@USUARIO


	SELECT 	@CANTIDAD=COUNT(PICKING_ID)
	FROM	PICKING
	WHERE 	LTRIM(RTRIM(UPPER(VIAJE_ID)))=LTRIM(UPPER(RTRIM(@VIAJE_ID)))


	SELECT 	@DIF=COUNT(PICKING_ID)
	FROM 	PICKING 
	WHERE 	LTRIM(RTRIM(UPPER(VIAJE_ID)))=LTRIM(UPPER(RTRIM(@VIAJE_ID)))
			AND FECHA_INICIO IS NOT NULL
			AND FECHA_FIN IS NOT NULL
			AND PALLET_PICKING IS NOT NULL
			AND USUARIO IS NOT NULL
			AND CANT_CONFIRMADA IS NOT NULL


	IF @CANTIDAD=@DIF
	BEGIN
		UPDATE PICKING SET FIN_PICKING='2' WHERE LTRIM(RTRIM(UPPER(VIAJE_ID)))=LTRIM(RTRIM(UPPER(@VIAJE_ID)))
	END			
END