/****** Object:  StoredProcedure [dbo].[VALIDA_TOMA_SERIES]    Script Date: 04/22/2014 12:28:51 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[VALIDA_TOMA_SERIES_PALLET]') AND type in (N'P', N'PC'))
DROP PROCEDURE [dbo].[VALIDA_TOMA_SERIES_PALLET]
GO


CREATE PROCEDURE [dbo].[VALIDA_TOMA_SERIES_PALLET]
	@NRO_PALLET		AS	VARCHAR(100),
	@RETORNO		AS	CHAR(1)	OUTPUT
	
AS
BEGIN
	DECLARE @CONT NUMERIC(20,0)
	
	SELECT	@CONT=COUNT(*)
	FROM	DOCUMENTO D INNER JOIN DET_DOCUMENTO DD
			ON(D.DOCUMENTO_ID=DD.DOCUMENTO_ID)
			INNER JOIN PRODUCTO P
			ON(P.CLIENTE_ID=DD.CLIENTE_ID AND P.PRODUCTO_ID=DD.PRODUCTO_ID)
	WHERE	D.TIPO_OPERACION_ID='ING'
			AND DD.PROP1=@NRO_PALLET
			AND ISNULL(P.SERIE_ING,'0')='1'
			AND DD.NRO_SERIE IS NULL

	IF @CONT=0 BEGIN
		SET @RETORNO=0
	END
	ELSE BEGIN
		SET @RETORNO=1
	END
END


GO


