/****** Object:  StoredProcedure [dbo].[TOLERANCIA_OC]    Script Date: 09/10/2014 12:40:43 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[TOLERANCIA_OC]') AND type in (N'P', N'PC'))
DROP PROCEDURE [dbo].[TOLERANCIA_OC]
GO

CREATE PROCEDURE [dbo].[TOLERANCIA_OC] --Control de tolerancia de productos Minima y Maxima
	@CLIENTE_ID		VARCHAR(15),
	@OC				VARCHAR(100),
	@PRODUCTO_ID	VARCHAR(30),
	@NRO_LOTE		VARCHAR(100),
	@NRO_PARTIDA	VARCHAR(100),
	@TolMax			Float output,
	@TolMin			Float output	
AS
BEGIN
	SET XACT_ABORT ON
	SET NOCOUNT ON
	
	DECLARE @ToleranciaMax		Float
	DECLARE @ToleranciaMin		Float
	DECLARE @DOC_EXT			VARCHAR(100)
	DECLARE @SUCURSAL_ORIGEN	VARCHAR(20)
	DECLARE @qtyBO				Float
	DECLARE @CANTIDADINGRESADA REAL
	DECLARE @USUARIO VARCHAR(20)  
	
	--SELECT @USUARIO=USUARIO_ID FROM #TEMP_USUARIO_LOGGIN  
		
	SELECT	@TOLERANCIAMAX=ISNULL(TOLERANCIA_MAX,0), 
			@TOLERANCIAMIN=ISNULL(TOLERANCIA_MIN,0) 
	FROM	PRODUCTO 
	WHERE	CLIENTE_ID=@CLIENTE_ID AND PRODUCTO_ID=@PRODUCTO_ID	

	SET		@CANTIDADINGRESADA = (	SELECT	ISNULL( SUM(IC.CANTIDAD),0)
									FROM	INGRESO_OC IC
									WHERE	IC.ORDEN_COMPRA = @OC
											AND IC.CLIENTE_ID = @CLIENTE_ID
											AND IC.PRODUCTO_ID = @PRODUCTO_ID 
											AND IC.PROCESADO = '0'
											--AND (((@NRO_LOTE = '' OR @NRO_LOTE IS NULL) AND (IC.NRO_LOTE = '' OR IC.NRO_LOTE IS NULL)) OR @NRO_LOTE = IC.NRO_LOTE)
											--AND (((@NRO_PARTIDA = '' OR @NRO_PARTIDA IS NULL) AND (IC.NRO_PARTIDA = '' OR IC.NRO_PARTIDA IS NULL)) OR @NRO_PARTIDA = IC.NRO_PARTIDA))
											AND ((IC.NRO_LOTE IS NULL OR IC.NRO_LOTE='' OR @NRO_LOTE IS NULL OR @NRO_LOTE='')OR(IC.NRO_LOTE=@NRO_LOTE))
											AND ((IC.NRO_PARTIDA IS NULL OR IC.NRO_PARTIDA='' OR @NRO_PARTIDA IS NULL OR @NRO_PARTIDA='')OR(IC.NRO_PARTIDA=@NRO_PARTIDA))
											)

	Select 	@qtyBO=sum(SS.cantidad_solicitada)
	from	sys_int_det_documento SS
			INNER JOIN SYS_INT_DOCUMENTO S ON (SS.CLIENTE_ID = S.CLIENTE_ID AND SS.DOC_EXT = S.DOC_eXT)
	where	S.ORDEN_DE_COMPRA=@OC
			AND SS.PRODUCTO_ID=@PRODUCTO_ID
			AND S.CLIENTE_ID=@CLIENTE_ID
			--AND (((@NRO_LOTE = '' OR @NRO_LOTE IS NULL) AND (SS.NRO_LOTE = '' OR SS.NRO_LOTE IS NULL)) OR @NRO_LOTE = SS.NRO_LOTE)
			--AND (((@NRO_PARTIDA = '' OR @NRO_PARTIDA IS NULL) AND (SS.NRO_PARTIDA = '' OR SS.NRO_PARTIDA IS NULL)) OR @NRO_PARTIDA = SS.NRO_PARTIDA)
			AND ((@NRO_LOTE IS NULL OR @NRO_LOTE='')OR(SS.NRO_LOTE=@NRO_LOTE))
			AND ((@NRO_PARTIDA IS NULL OR @NRO_PARTIDA='')OR(SS.NRO_PARTIDA=@NRO_PARTIDA))
			and SS.fecha_estado_gt is null
			and SS.estado_gt is null
			
	IF @qtyBO IS NULL BEGIN	
			
		Select 	@qtyBO=sum(SS.cantidad_solicitada)
		from	sys_int_det_documento SS
				INNER JOIN SYS_INT_DOCUMENTO S ON (SS.CLIENTE_ID = S.CLIENTE_ID AND SS.DOC_EXT = S.DOC_eXT)
		where	S.ORDEN_DE_COMPRA=@OC
				AND SS.PRODUCTO_ID=@PRODUCTO_ID
				AND S.CLIENTE_ID=@CLIENTE_ID
				AND ((SS.NRO_LOTE IS NULL OR SS.NRO_LOTE='' OR @NRO_LOTE IS NULL OR @NRO_LOTE='')OR(SS.NRO_LOTE=@NRO_LOTE))
				AND ((SS.NRO_PARTIDA IS NULL OR SS.NRO_PARTIDA='' OR @NRO_PARTIDA IS NULL OR @NRO_PARTIDA='')OR(SS.NRO_PARTIDA=@NRO_PARTIDA))
				and SS.fecha_estado_gt is null
				and SS.estado_gt is null
	END			
	set @ToleranciaMax= (@qtyBO - @CANTIDADINGRESADA) + ((@qtyBO * @ToleranciaMax)/100)  
	set @ToleranciaMin= @qtyBO - ((@qtyBO * @ToleranciaMin)/100)
	
	set @TolMax = isnull(@ToleranciaMax,0)
	set @TolMin	= isnull(@ToleranciaMin,0)

END


GO


