/****** OBJECT:  STOREDPROCEDURE [DBO].[INGRESO_OC_ALTA]    SCRIPT DATE: 09/10/2014 12:50:10 ******/
IF  EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[DBO].[INGRESO_OC_ALTA]') AND TYPE IN (N'P', N'PC'))
DROP PROCEDURE [DBO].[INGRESO_OC_ALTA]
GO


CREATE PROCEDURE [DBO].[INGRESO_OC_ALTA]
	@CLIENTE_ID			    VARCHAR(15),
	@PRODUCTO_ID		    VARCHAR(30),
	@ORDEN_COMPRA		    VARCHAR(100),
	@CANTIDAD			    NUMERIC(20,5),
	@CANT_CONTENEDORAS		NUMERIC(20,5)=NULL,
	@FECHA				    DATETIME,
	@PROCESADO			    CHAR(1),
	@LOTEPROVEEDOR			VARCHAR(100),
	@PARTIDA			    VARCHAR(100),
	@DOC_EXT				VARCHAR(100)
AS
BEGIN
	DECLARE @USUARIO		VARCHAR(50)
	DECLARE @TERMINAL		VARCHAR(100)
	DECLARE @CUR		    CURSOR
	DECLARE @VDOCEXT		VARCHAR(100)
	DECLARE @QTY_LIN		NUMERIC(20,5)
	DECLARE @VCANTIDAD		NUMERIC(20,5)
	DECLARE @NRO_PART_AT	CHAR(1)
	DECLARE @SEQ			NUMERIC(30,0)
	DECLARE @ISCONT			CHAR(1)
	DECLARE @VNRO_PARTIDA	VARCHAR(100)
	DECLARE @DOC_EXT_ACT	VARCHAR(100)
	DECLARE @ING_PARTIDA	CHAR(1)
	
	SELECT	@ING_PARTIDA=ingPartida
	FROM	PRODUCTO
	WHERE	CLIENTE_ID=@CLIENTE_ID
			AND PRODUCTO_ID=@PRODUCTO_ID
  
	IF(@FECHA IS NULL)BEGIN
		SET @FECHA=GETDATE();
	END
	
	SET @VCANTIDAD=@CANTIDAD;
  
	--SELECT @USUARIO=USUARIO_ID FROM #TEMP_USUARIO_LOGGIN
	SELECT @USUARIO='ADMIN'
	
	SELECT	@NRO_PART_AT = ISNULL(NRO_PARTIDA_AUTOMATICO,'0'),
			@ISCONT =ISNULL(FLG_CONTENEDORA,'0')
	FROM	PRODUCTO
	WHERE	CLIENTE_ID=@CLIENTE_ID 
			AND PRODUCTO_ID= @PRODUCTO_ID;
			
	IF (@PARTIDA IS NULL) OR (LTRIM(RTRIM(@PARTIDA))='')BEGIN
		IF @NRO_PART_AT ='1' AND @ISCONT='0' BEGIN
			EXEC DBO.GET_VALUE_FOR_SEQUENCE 'NRO_PARTIDA', @SEQ OUTPUT
			SET @PARTIDA =@SEQ;
		END
	END		
	
	UPDATE	SYS_INT_DET_DOCUMENTO SET NRO_LOTE=NULL 
	FROM	SYS_INT_DET_DOCUMENTO SDD INNER JOIN SYS_INT_DOCUMENTO SD
			ON(SDD.CLIENTE_ID=SD.CLIENTE_ID AND SDD.DOC_EXT=SD.DOC_EXT)
	WHERE	SDD.CLIENTE_ID=@CLIENTE_ID
			AND SD.ORDEN_DE_COMPRA=@ORDEN_COMPRA			
			AND SDD.NRO_LOTE=''
			
	UPDATE	SYS_INT_DET_DOCUMENTO SET NRO_PARTIDA=NULL 
	FROM	SYS_INT_DET_DOCUMENTO SDD INNER JOIN SYS_INT_DOCUMENTO SD
			ON(SDD.CLIENTE_ID=SD.CLIENTE_ID AND SDD.DOC_EXT=SD.DOC_EXT)
	WHERE	SDD.CLIENTE_ID=@CLIENTE_ID
			AND SD.ORDEN_DE_COMPRA=@ORDEN_COMPRA			
			AND SDD.NRO_PARTIDA=''
				
	SET @TERMINAL=HOST_NAME()
	
	IF @ING_PARTIDA=0 BEGIN
		SET @CUR=CURSOR FOR
		SELECT	SDD.DOC_EXT, (SDD.CANTIDAD_SOLICITADA + (ISNULL(P.TOLERANCIA_MAX,0)/100) * SDD.CANTIDAD_SOLICITADA) AS CANTIDAD_SOLICITADA
		FROM	SYS_INT_DOCUMENTO SD INNER JOIN SYS_INT_DET_DOCUMENTO SDD
				ON(SD.CLIENTE_ID=SDD.CLIENTE_ID AND SD.DOC_EXT=SDD.DOC_EXT)
				INNER JOIN PRODUCTO P
				ON(SDD.CLIENTE_ID=P.CLIENTE_ID AND SDD.PRODUCTO_ID=P.PRODUCTO_ID)				
		WHERE	SDD.CLIENTE_ID=@CLIENTE_ID
				AND SD.ORDEN_DE_COMPRA=@ORDEN_COMPRA
				AND SDD.PRODUCTO_ID=@PRODUCTO_ID
				AND ((SDD.NRO_PARTIDA IS NULL OR SDD.NRO_PARTIDA='')OR(SDD.NRO_PARTIDA=@PARTIDA))
				AND ((SDD.NRO_LOTE IS NULL OR SDD.NRO_LOTE='')OR(SDD.NRO_LOTE=@LOTEPROVEEDOR))
				AND SDD.ESTADO_GT IS NULL
				AND SDD.FECHA_ESTADO_GT IS NULL
				AND NOT EXISTS (SELECT	1
								FROM	INGRESO_OC I
								WHERE	SD.CLIENTE_ID=I.CLIENTE_ID
										AND SD.DOC_EXT=I.DOC_EXT
										AND I.procesado='0')
		ORDER BY
				SD.FECHA_CPTE, SD.DOC_EXT;
	END
	ELSE
	BEGIN
		SET @CUR=CURSOR FOR
		SELECT	SDD.DOC_EXT, (SDD.CANTIDAD_SOLICITADA + (ISNULL(P.TOLERANCIA_MAX,0)/100) * SDD.CANTIDAD_SOLICITADA) AS CANTIDAD_SOLICITADA
		FROM	SYS_INT_DOCUMENTO SD INNER JOIN SYS_INT_DET_DOCUMENTO SDD
				ON(SD.CLIENTE_ID=SDD.CLIENTE_ID AND SD.DOC_EXT=SDD.DOC_EXT)
				INNER JOIN PRODUCTO P
				ON(SDD.CLIENTE_ID=P.CLIENTE_ID AND SDD.PRODUCTO_ID=P.PRODUCTO_ID)				
		WHERE	SDD.CLIENTE_ID=@CLIENTE_ID
				AND SD.ORDEN_DE_COMPRA=@ORDEN_COMPRA
				AND SDD.PRODUCTO_ID=@PRODUCTO_ID
				AND ((SDD.NRO_PARTIDA IS NULL OR SDD.NRO_PARTIDA='')OR(SDD.NRO_PARTIDA=@PARTIDA))
				AND ((SDD.NRO_LOTE IS NULL OR SDD.NRO_LOTE='')OR(SDD.NRO_LOTE=@LOTEPROVEEDOR))
				AND SDD.ESTADO_GT IS NULL
				AND SDD.FECHA_ESTADO_GT IS NULL
				AND NOT EXISTS (SELECT	1
								FROM	INGRESO_OC I
								WHERE	SD.CLIENTE_ID=I.CLIENTE_ID
										AND SD.DOC_EXT=I.DOC_EXT
										AND I.PROCESADO='0')
		ORDER BY
				SD.FECHA_CPTE, SD.DOC_EXT;	
	END
	OPEN @CUR
	FETCH @CUR INTO @VDOCEXT,@QTY_LIN
	WHILE @@FETCH_STATUS=0 BEGIN
		
		PRINT('EVALUA LAS CANTIDADES.')
		
		SELECT	@VNRO_PARTIDA=NRO_PARTIDA
		FROM	SYS_INT_DET_DOCUMENTO
		WHERE	CLIENTE_ID=@CLIENTE_ID
				AND DOC_EXT=@VDOCEXT
				
		--IF (@VNRO_PARTIDA=@PARTIDA)OR(@VNRO_PARTIDA IS NULL) BEGIN
		
		IF @VCANTIDAD>=@QTY_LIN BEGIN 
		
			INSERT INTO INGRESO_OC(CLIENTE_ID, PRODUCTO_ID, ORDEN_COMPRA, CANTIDAD, CANT_CONTENEDORAS, USUARIO, TERMINAL, FECHA, PROCESADO, NRO_LOTE, NRO_PARTIDA, DOC_EXT)                    
			VALUES                (@CLIENTE_ID,@PRODUCTO_ID,@ORDEN_COMPRA,@QTY_LIN,@CANT_CONTENEDORAS,@USUARIO,@TERMINAL,@FECHA,@PROCESADO, @LOTEPROVEEDOR, @PARTIDA, @VDOCEXT);
			
			SET @VCANTIDAD=@VCANTIDAD-@QTY_LIN;       
			
			SET @DOC_EXT_ACT = @VDOCEXT
			
		END
		ELSE BEGIN
		
			INSERT INTO INGRESO_OC(CLIENTE_ID, PRODUCTO_ID, ORDEN_COMPRA, CANTIDAD, CANT_CONTENEDORAS, USUARIO, TERMINAL, FECHA, PROCESADO, NRO_LOTE, NRO_PARTIDA, DOC_EXT)                    
			VALUES                (@CLIENTE_ID,@PRODUCTO_ID,@ORDEN_COMPRA,@VCANTIDAD,@CANT_CONTENEDORAS,@USUARIO,@TERMINAL,@FECHA,@PROCESADO, @LOTEPROVEEDOR, @PARTIDA, @VDOCEXT);
			
			SET @DOC_EXT_ACT = @VDOCEXT
			
			SET @VCANTIDAD=0;
			
		END
			
		--END
		IF @VCANTIDAD=0 BEGIN
			BREAK;
		END
		
		FETCH @CUR INTO @VDOCEXT,@QTY_LIN  
		
	END
	CLOSE @CUR;
	DEALLOCATE @CUR;
	
	IF @VCANTIDAD>0 BEGIN

		UPDATE  INGRESO_OC SET CANTIDAD=CANTIDAD + @VCANTIDAD
		WHERE   CLIENTE_ID=@CLIENTE_ID
				AND PRODUCTO_ID=@PRODUCTO_ID
				AND DOC_EXT=@DOC_EXT_ACT;
		
	END
END


GO


