
CREATE TABLE C_ESTADISTICAS_RPT(
	C_STAT_ID			NUMERIC(20,0) NOT NULL IDENTITY(1,1),
	CLIENTE_ID			VARCHAR(15),
	CLIENTE				VARCHAR(50),
	FECHA				VARCHAR(20),
	Q_POS_OCUPADAS		NUMERIC(20,15),	
	Q_VOL_PROD			NUMERIC(20,15),
	QTY_DOC_ING			NUMERIC(20,15),
	PRODUCTOS_DIST_ING	NUMERIC(20,15),
	VOL_ING				NUMERIC(20,15),
	CANTIDAD_INGRESO	NUMERIC(20,15),
	QTY_DOC_EGR			NUMERIC(20,15),
	PRODUCTOS_DIST_EGR	NUMERIC(20,15),
	VOL_EGR				NUMERIC(20,15),
	CANTIDAD_EGRESO		NUMERIC(20,15),
	F_ORDENAMIENTO		DATETIME
)											

ALTER TABLE C_ESTADISTICAS_RPT
ADD CONSTRAINT PK_C_ESTADISTICAS_RPT PRIMARY KEY(C_STAT_ID)

CREATE NONCLUSTERED INDEX IDX_C_ESTADISTICAS_RPT ON C_ESTADISTICAS_RPT(CLIENTE_ID,F_ORDENAMIENTO) 

