
/****** Object:  StoredProcedure [dbo].[RPT_ESTADISTICA_CLIENTE]    Script Date: 09/03/2014 09:41:54 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[RPT_ESTADISTICA_CLIENTE]') AND type in (N'P', N'PC'))
DROP PROCEDURE [dbo].[RPT_ESTADISTICA_CLIENTE]
GO

CREATE PROCEDURE [dbo].[RPT_ESTADISTICA_CLIENTE]
	@CLIENTE_ID		VARCHAR(15)		OUTPUT,
	@FDESDE			VARCHAR(8)		OUTPUT,	--ANSI
	@FHASTA			VARCHAR(8)		OUTPUT	--ANSI		
AS
BEGIN
	

	SELECT	R.CLIENTE					AS CLIENTE,
			R.FECHA 					AS FECHA,
			R.Q_POS_OCUPADAS			AS Q_POS_OCUPADAS,	
			R.Q_VOL_PROD				AS Q_VOL_PROD,
			R.QTY_DOC_ING				AS QTY_DOC_ING,
			R.PRODUCTOS_DIST_ING		AS PRODUCTOS_DIST_ING,
			R.VOL_ING					AS VOL_ING,
			R.CANTIDAD_INGRESO			AS CANTIDAD_INGRESO,
			R.QTY_DOC_EGR				AS QTY_DOC_EGR,
			R.PRODUCTOS_DIST_EGR		AS PRODUCTOS_DIST_EGR,
			R.VOL_EGR					AS VOL_EGR,
			R.CANTIDAD_EGRESO			AS CANTIDAD_EGRESO,
			GETDATE()					AS F_IMP,
			HOST_NAME()					AS TERMINAL	
	FROM	C_ESTADISTICAS_RPT R
	WHERE	((@CLIENTE_ID IS NULL)OR(R.CLIENTE_ID=@CLIENTE_ID))	
			AND ((@FDESDE IS NULL)OR(R.F_ORDENAMIENTO BETWEEN @FDESDE AND @FHASTA))

END;













GO


