CREATE NONCLUSTERED INDEX [_dta_index_SNAP_EXISTENCIAS_13_802101898__K21_K2_K16_K13_K7_K4_K5_8] ON [dbo].[SNAP_EXISTENCIAS] 
(
	[CLIENTE_ID] ASC,
	[F_SNAP] ASC,
	[DISPONIBLE] ASC,
	[NAVE_ACTUAL] ASC,
	[POSICION_ACTUAL] ASC,
	[DOC_TRANS_ID] ASC,
	[NRO_LINEA_TRANS] ASC
)
INCLUDE ( [CANTIDAD]) WITH (SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF) ON [PRIMARY]
go

CREATE NONCLUSTERED INDEX [_dta_index_SNAP_EXISTENCIAS_13_802101898__K21_K2_K7_K4_K5_8] ON [dbo].[SNAP_EXISTENCIAS] 
(
	[CLIENTE_ID] ASC,
	[F_SNAP] ASC,
	[POSICION_ACTUAL] ASC,
	[DOC_TRANS_ID] ASC,
	[NRO_LINEA_TRANS] ASC
)
INCLUDE ( [CANTIDAD]) WITH (SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF) ON [PRIMARY]
go

CREATE NONCLUSTERED INDEX [_dta_index_SNAP_EXISTENCIAS_13_802101898__K7_K21_K2_K16] ON [dbo].[SNAP_EXISTENCIAS] 
(
	[POSICION_ACTUAL] ASC,
	[CLIENTE_ID] ASC,
	[F_SNAP] ASC,
	[DISPONIBLE] ASC
)WITH (SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF) ON [PRIMARY]
go

CREATE NONCLUSTERED INDEX [_dta_index_SNAP_EXISTENCIAS_13_802101898__K21_K2_K16_K7] ON [dbo].[SNAP_EXISTENCIAS] 
(
	[CLIENTE_ID] ASC,
	[F_SNAP] ASC,
	[DISPONIBLE] ASC,
	[POSICION_ACTUAL] ASC
)WITH (SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF) ON [PRIMARY]
go

CREATE NONCLUSTERED INDEX [_dta_index_SNAP_EXISTENCIAS_13_802101898__K16_K21_K2_K13] ON [dbo].[SNAP_EXISTENCIAS] 
(
	[DISPONIBLE] ASC,
	[CLIENTE_ID] ASC,
	[F_SNAP] ASC,
	[NAVE_ACTUAL] ASC
)WITH (SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF) ON [PRIMARY]
go

CREATE NONCLUSTERED INDEX [_dta_index_SNAP_EXISTENCIAS_13_802101898__K16] ON [dbo].[SNAP_EXISTENCIAS] 
(
	[DISPONIBLE] ASC
)WITH (SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF) ON [PRIMARY]
go

CREATE STATISTICS [_dta_stat_802101898_7_2] ON [dbo].[SNAP_EXISTENCIAS]([POSICION_ACTUAL], [F_SNAP])
go

CREATE STATISTICS [_dta_stat_802101898_4_5_21] ON [dbo].[SNAP_EXISTENCIAS]([DOC_TRANS_ID], [NRO_LINEA_TRANS], [CLIENTE_ID])
go

CREATE STATISTICS [_dta_stat_802101898_2_21_4] ON [dbo].[SNAP_EXISTENCIAS]([F_SNAP], [CLIENTE_ID], [DOC_TRANS_ID])
go

CREATE STATISTICS [_dta_stat_802101898_13_21_2] ON [dbo].[SNAP_EXISTENCIAS]([NAVE_ACTUAL], [CLIENTE_ID], [F_SNAP])
go

CREATE STATISTICS [_dta_stat_802101898_4_5_2_21] ON [dbo].[SNAP_EXISTENCIAS]([DOC_TRANS_ID], [NRO_LINEA_TRANS], [F_SNAP], [CLIENTE_ID])
go

CREATE STATISTICS [_dta_stat_802101898_7_4_5_2] ON [dbo].[SNAP_EXISTENCIAS]([POSICION_ACTUAL], [DOC_TRANS_ID], [NRO_LINEA_TRANS], [F_SNAP])
go

CREATE STATISTICS [_dta_stat_802101898_16_7_21_2_4] ON [dbo].[SNAP_EXISTENCIAS]([DISPONIBLE], [POSICION_ACTUAL], [CLIENTE_ID], [F_SNAP], [DOC_TRANS_ID])
go

CREATE STATISTICS [_dta_stat_802101898_21_2_16_4_5] ON [dbo].[SNAP_EXISTENCIAS]([CLIENTE_ID], [F_SNAP], [DISPONIBLE], [DOC_TRANS_ID], [NRO_LINEA_TRANS])
go

CREATE STATISTICS [_dta_stat_802101898_21_2_4_5_13] ON [dbo].[SNAP_EXISTENCIAS]([CLIENTE_ID], [F_SNAP], [DOC_TRANS_ID], [NRO_LINEA_TRANS], [NAVE_ACTUAL])
go

CREATE STATISTICS [_dta_stat_802101898_7_21_2_4_5_13] ON [dbo].[SNAP_EXISTENCIAS]([POSICION_ACTUAL], [CLIENTE_ID], [F_SNAP], [DOC_TRANS_ID], [NRO_LINEA_TRANS], [NAVE_ACTUAL])
go

CREATE STATISTICS [_dta_stat_802101898_21_2_13_16_4_5] ON [dbo].[SNAP_EXISTENCIAS]([CLIENTE_ID], [F_SNAP], [NAVE_ACTUAL], [DISPONIBLE], [DOC_TRANS_ID], [NRO_LINEA_TRANS])
go

CREATE STATISTICS [_dta_stat_802101898_7_4_5_21_2_16] ON [dbo].[SNAP_EXISTENCIAS]([POSICION_ACTUAL], [DOC_TRANS_ID], [NRO_LINEA_TRANS], [CLIENTE_ID], [F_SNAP], [DISPONIBLE])
go

CREATE STATISTICS [_dta_stat_802101898_7_21_2_13_16_4_5] ON [dbo].[SNAP_EXISTENCIAS]([POSICION_ACTUAL], [CLIENTE_ID], [F_SNAP], [NAVE_ACTUAL], [DISPONIBLE], [DOC_TRANS_ID], [NRO_LINEA_TRANS])
go

CREATE NONCLUSTERED INDEX [_dta_index_PRODUCTO_13_1351675863__K1_K2_23_24_25] ON [dbo].[PRODUCTO] 
(
	[CLIENTE_ID] ASC,
	[PRODUCTO_ID] ASC
)
INCLUDE ( [LARGO],
[ALTO],
[ANCHO]) WITH (SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF) ON [PRIMARY]
go

CREATE NONCLUSTERED INDEX [_dta_index_DET_DOCUMENTO_TRANSACCION_13_1776725382__K1_K2_K3_K4] ON [dbo].[DET_DOCUMENTO_TRANSACCION] 
(
	[DOC_TRANS_ID] ASC,
	[NRO_LINEA_TRANS] ASC,
	[DOCUMENTO_ID] ASC,
	[NRO_LINEA_DOC] ASC
)WITH (SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF) ON [PRIMARY]
go

CREATE STATISTICS [_dta_stat_1776725382_3_4_1_2] ON [dbo].[DET_DOCUMENTO_TRANSACCION]([DOCUMENTO_ID], [NRO_LINEA_DOC], [DOC_TRANS_ID], [NRO_LINEA_TRANS])
go

CREATE NONCLUSTERED INDEX [_dta_index_DET_DOCUMENTO_13_2052202361__K1_K2_K3_K4] ON [dbo].[DET_DOCUMENTO] 
(
	[DOCUMENTO_ID] ASC,
	[NRO_LINEA] ASC,
	[CLIENTE_ID] ASC,
	[PRODUCTO_ID] ASC
)WITH (SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF) ON [PRIMARY]
go

CREATE STATISTICS [_dta_stat_2052202361_3_4_1_2] ON [dbo].[DET_DOCUMENTO]([CLIENTE_ID], [PRODUCTO_ID], [DOCUMENTO_ID], [NRO_LINEA])
go

CREATE NONCLUSTERED INDEX [_dta_index_POSICION_13_1668200993__K2_K1_19_20_21] ON [dbo].[POSICION] 
(
	[NAVE_ID] ASC,
	[POSICION_ID] ASC
)
INCLUDE ( [LARGO],
[ALTO],
[ANCHO]) WITH (SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF) ON [PRIMARY]
go

CREATE NONCLUSTERED INDEX [_dta_index_POSICION_13_1668200993__K2_K1] ON [dbo].[POSICION] 
(
	[NAVE_ID] ASC,
	[POSICION_ID] ASC
)WITH (SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF) ON [PRIMARY]
go

CREATE NONCLUSTERED INDEX [_dta_index_POSICION_13_1668200993__K2] ON [dbo].[POSICION] 
(
	[NAVE_ID] ASC
)WITH (SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF) ON [PRIMARY]
go

CREATE STATISTICS [_dta_stat_1668200993_1_2] ON [dbo].[POSICION]([POSICION_ID], [NAVE_ID])
go

