/****** Object:  StoredProcedure [dbo].[DET_EGR_INSERT_CONSUMO_LOCATOR_EGR]    Script Date: 09/10/2014 15:14:12 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DET_EGR_INSERT_CONSUMO_LOCATOR_EGR]') AND type in (N'P', N'PC'))
DROP PROCEDURE [dbo].[DET_EGR_INSERT_CONSUMO_LOCATOR_EGR]
GO

CREATE     PROCEDURE [dbo].[DET_EGR_INSERT_CONSUMO_LOCATOR_EGR]
		@vDOC_ID			AS NUMERIC(20,0)	OUTPUT,
		@NRO_LINEA		AS NUMERIC(20,0)	OUTPUT,
		@vCLIENTE_ID 		AS VARCHAR(30)	OUTPUT,
		@vPRODUCTO_ID	AS VARCHAR(30)	OUTPUT,
		@vCANTIDAD		AS NUMERIC(20,5)	OUTPUT,
		@vRL_ID 			AS NUMERIC(20,0)	OUTPUT,
		@vSALDO			AS NUMERIC(20,5)	OUTPUT,
		@vTIPO				AS VARCHAR(20)	OUTPUT,
		@vPROCESADO		AS VARCHAR(1)		OUTPUT
AS
BEGIN
DECLARE @Qty_SALDO AS NUMERIC(20,5)

	IF (@vRL_ID IS NULL) OR (LTRIM(RTRIM(@vRL_ID))='') OR (@vRL_ID=0)
	BEGIN
		RAISERROR('El valor Rl no es valido',16,1)
		return
	END

	DELETE FROM CONSUMO_LOCATOR_EGR WHERE DOCUMENTO_ID = @vDOC_ID AND NRO_LINEA = @NRO_LINEA;
	DELETE FROM DET_DOCUMENTO_AUX WHERE DOCUMENTO_ID = @vDOC_ID AND NRO_LINEA = @NRO_LINEA;
	
	--Exec Dbo.Get_Qty_Stock @vCLIENTE_ID, @vPRODUCTO_ID, @Qty_SALDO Output
	
	SELECT @Qty_SALDO=CANTIDAD - @vCANTIDAD FROM RL_DET_DOC_TRANS_POSICION WHERE RL_ID=@vRL_ID
	
	IF @Qty_SALDO > 0
	BEGIN
		INSERT INTO RL_DET_DOC_TRANS_POSICION (DOC_TRANS_ID,NRO_LINEA_TRANS,
		POSICION_ANTERIOR,POSICION_ACTUAL,CANTIDAD,TIPO_MOVIMIENTO_ID,ULTIMA_ESTACION,
		ULTIMA_SECUENCIA,NAVE_ANTERIOR,NAVE_ACTUAL,DOCUMENTO_ID,NRO_LINEA,DISPONIBLE,
		DOC_TRANS_ID_EGR,NRO_LINEA_TRANS_EGR,DOC_TRANS_ID_TR,NRO_LINEA_TRANS_TR,
		CLIENTE_ID,CAT_LOG_ID,CAT_LOG_ID_FINAL,EST_MERC_ID)
        SELECT DOC_TRANS_ID,NRO_LINEA_TRANS,POSICION_ANTERIOR,POSICION_ACTUAL,@Qty_SALDO,
        TIPO_MOVIMIENTO_ID,ULTIMA_ESTACION,ULTIMA_SECUENCIA,NAVE_ANTERIOR,NAVE_ACTUAL,
        DOCUMENTO_ID,NRO_LINEA,DISPONIBLE,DOC_TRANS_ID_EGR,NRO_LINEA_TRANS_EGR,
        DOC_TRANS_ID_TR,NRO_LINEA_TRANS_TR,CLIENTE_ID,CAT_LOG_ID,CAT_LOG_ID_FINAL,EST_MERC_ID
        FROM RL_DET_DOC_TRANS_POSICION 
        WHERE RL_ID=@VRL_ID 	
        
        UPDATE RL_DET_DOC_TRANS_POSICION SET CANTIDAD=@VCANTIDAD WHERE RL_ID=@VRL_ID
	END

	INSERT INTO CONSUMO_LOCATOR_EGR (DOCUMENTO_ID,NRO_LINEA,CLIENTE_ID,PRODUCTO_ID, CANTIDAD, RL_ID, SALDO, TIPO, FECHA, PROCESADO)
	VALUES (@vDOC_ID, @NRO_LINEA, @vCLIENTE_ID, @vPRODUCTO_ID, @vCANTIDAD, @vRL_ID, 0, @vTIPO, GETDATE(), @vPROCESADO)
	
	insert into #tmp_consumo_locator_egr values (@vRL_ID, @VCANTIDAD)

	INSERT INTO DET_DOCUMENTO_AUX
	SELECT * FROM DET_DOCUMENTO WHERE DOCUMENTO_ID=@VDOC_ID AND NRO_LINEA=@NRO_LINEA
END

GO


