CREATE TABLE INTERFACES(
	INTERFAZ_ID		VARCHAR(10) NOT NULL,
	DESCRIPCION		VARCHAR(50) NOT NULL,
	ACTIVO			CHAR(1) DEFAULT '1',
);

GO

ALTER TABLE INTERFACES
ADD CONSTRAINT PK_INTERFACES PRIMARY KEY(INTERFAZ_ID);

GO

INSERT INTO INTERFACES VALUES('PROD','MAESTRO DE PRODUCTOS','1');
INSERT INTO INTERFACES VALUES('RL_PROD','RELACION PRODUCTO - POSICION','1');

GO

