
ALTER TABLE SYS_VERSION
ADD NOM_DLL VARCHAR(50) NOT NULL DEFAULT('TMP')

IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[fk_sys_version]') AND parent_object_id = OBJECT_ID(N'[dbo].[SYS_VERSION_DETALLE]'))
ALTER TABLE [dbo].[SYS_VERSION_DETALLE] DROP CONSTRAINT [fk_sys_version]
GO

/****** Object:  Index [pk_version]    Script Date: 04/22/2013 16:09:52 ******/
IF  EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[SYS_VERSION]') AND name = N'pk_version')
ALTER TABLE [dbo].[SYS_VERSION] DROP CONSTRAINT [pk_version]
GO

ALTER TABLE SYS_VERSION 
ADD CONSTRAINT PK_VERSION PRIMARY KEY (NOM_DLL, VER_ACTUAL_WARP)
GO

UPDATE SYS_VERSION SET NOM_DLL='WARP.EXE'
GO


INSERT INTO SYS_VERSION VALUES('9.07','9.07',GETDATE(),'Version de DLL','\\Domglo\global',0,'WARP_TPARAM');
INSERT INTO SYS_VERSION VALUES('9.06','9.06',GETDATE(),'Version de DLL','\\Domglo\global',0,'WARP_MAEDOC')
INSERT INTO SYS_VERSION VALUES('9.06','9.06',GETDATE(),'Version de DLL','\\Domglo\global',0,'WARP_EMP');
INSERT INTO SYS_VERSION VALUES('9.06','9.06',GETDATE(),'Version de DLL','\\Domglo\global',0,'WARP_ESTACION');
INSERT INTO SYS_VERSION VALUES('9.06','9.06',GETDATE(),'Version de DLL','\\Domglo\global',0,'WARP_FRONTERA');
INSERT INTO SYS_VERSION VALUES('9.06','9.06',GETDATE(),'Version de DLL','\\Domglo\global',0,'WARP_TRAN');
INSERT INTO SYS_VERSION VALUES('9.06','9.06',GETDATE(),'Version de DLL','\\Domglo\global',0,'WARP_DETAIL');
INSERT INTO SYS_VERSION VALUES('9.06','9.06',GETDATE(),'Version de DLL','\\Domglo\global',0,'WARP_DET_EGR');
INSERT INTO SYS_VERSION VALUES('9.06','9.06',GETDATE(),'Version de DLL','\\Domglo\global',0,'WARP_UBIC_MOV');
INSERT INTO SYS_VERSION VALUES('9.06','9.06',GETDATE(),'Version de DLL','\\Domglo\global',0,'WARP_INVENTARIO');
INSERT INTO SYS_VERSION VALUES('9.06','9.06',GETDATE(),'Version de DLL','\\Domglo\global',0,'WARP_ADMIN');
INSERT INTO SYS_VERSION VALUES('9.06','9.06',GETDATE(),'Version de DLL','\\Domglo\global',0,'WARP_IMPRESIONES');
INSERT INTO SYS_VERSION VALUES('9.06','9.06',GETDATE(),'Version de DLL','\\Domglo\global',0,'WARP_IMPO');
INSERT INTO SYS_VERSION VALUES('9.06','9.06',GETDATE(),'Version de DLL','\\Domglo\global',0,'WARP_BD');
INSERT INTO SYS_VERSION VALUES('9.06','9.06',GETDATE(),'Version de DLL','\\Domglo\global',0,'WARP_HK');
INSERT INTO SYS_VERSION VALUES('9.06','9.06',GETDATE(),'Version de DLL','\\Domglo\global',0,'WARP_ERROR');
INSERT INTO SYS_VERSION VALUES('9.06','9.06',GETDATE(),'Version de DLL','\\Domglo\global',0,'WARP_CONF');
INSERT INTO SYS_VERSION VALUES('9.06','9.06',GETDATE(),'Version de DLL','\\Domglo\global',0,'WARP_GEN');
INSERT INTO SYS_VERSION VALUES('9.06','9.06',GETDATE(),'Version de DLL','\\Domglo\global',0,'WARPKPA2');

INSERT INTO SYS_VERSION VALUES('9.06','9.06',GETDATE(),'Version de DLL','\\Domglo\global',0,'WARP_EXPO');
INSERT INTO SYS_VERSION VALUES('9.06','9.06',GETDATE(),'Version de DLL','\\Domglo\global',0,'WARP_EXPO_TXT');
INSERT INTO SYS_VERSION VALUES('9.06','9.06',GETDATE(),'Version de DLL','\\Domglo\global',0,'WARP_ETIQUETAS');
INSERT INTO SYS_VERSION VALUES('9.06','9.06',GETDATE(),'Version de DLL','\\Domglo\global',0,'WARP_INT');
INSERT INTO SYS_VERSION VALUES('9.06','9.06',GETDATE(),'Version de DLL','\\Domglo\global',0,'WARP_MAIL');

INSERT INTO SYS_VERSION VALUES('9.06','9.06',GETDATE(),'Version de DLL','\\Domglo\global',0,'UC_DESCRIPTION');
INSERT INTO SYS_VERSION VALUES('9.06','9.06',GETDATE(),'Version de DLL','\\Domglo\global',0,'WARP_UC_BUSCAR');
INSERT INTO SYS_VERSION VALUES('9.06','9.06',GETDATE(),'Version de DLL','\\Domglo\global',0,'WARPNAVIGATOR');
INSERT INTO SYS_VERSION VALUES('9.06','9.06',GETDATE(),'Version de DLL','\\Domglo\global',0,'WARPNAVIGATORENT');

