DROP TABLE PICKING_HISTORICO;

CREATE TABLE [dbo].[PICKING_HISTORICO](
	[PICKING_ID] [numeric](20, 0) NOT NULL,
	[DOCUMENTO_ID] [numeric](20, 0) NOT NULL,
	[NRO_LINEA] [numeric](10, 0) NULL,
	[CLIENTE_ID] [varchar](15) NULL,
	[PRODUCTO_ID] [varchar](30) NULL,
	[VIAJE_ID] [varchar](100) NULL,
	[TIPO_CAJA] [varchar](50) NULL,
	[DESCRIPCION] [varchar](200) NULL,
	[CANTIDAD] [numeric](20, 5) NULL,
	[NAVE_COD] [varchar](15) NULL,
	[POSICION_COD] [varchar](45) NULL,
	[RUTA] [varchar](50) NULL,
	[PROP1] [varchar](100) NULL,
	[FECHA_INICIO] [datetime] NULL,
	[FECHA_FIN] [datetime] NULL,
	[USUARIO] [varchar](20) NULL,
	[CANT_CONFIRMADA] [numeric](20, 5) NULL,
	[PALLET_PICKING] [numeric](20, 0) NULL,
	[SALTO_PICKING] [int] NULL,
	[PALLET_CONTROLADO] [char](1) NULL,
	[USUARIO_CONTROL_PICK] [varchar](20) NULL,
	[ST_ETIQUETAS] [char](1) NULL,
	[ST_CAMION] [char](1) NULL,
	[FACTURADO] [char](1) NULL,
	[FIN_PICKING] [char](1) NULL,
	[ST_CONTROL_EXP] [char](1) NULL,
	[FECHA_CONTROL_PALLET] [datetime] NULL,
	[TERMINAL_CONTROL_PALLET] [varchar](100) NULL,
	[FECHA_CONTROL_EXP] [datetime] NULL,
	[USUARIO_CONTROL_EXP] [varchar](20) NULL,
	[TERMINAL_CONTROL_EXP] [varchar](100) NULL,
	[FECHA_CONTROL_FAC] [datetime] NULL,
	[USUARIO_CONTROL_FAC] [varchar](20) NULL,
	[TERMINAL_CONTROL_FAC] [varchar](100) NULL,
	[VEHICULO_ID] [varchar](50) NULL,
	[PALLET_COMPLETO] [char](1) NULL,
	[HIJO] [numeric](20, 0) NULL,
	[QTY_CONTROLADO] [numeric](20, 0) NULL,
	[PALLET_FINAL] [numeric](20, 0) NULL,
	[PALLET_CERRADO] [char](1) NULL,
	[USUARIO_PF] [varchar](20) NULL,
	[TERMINAL_PF] [varchar](100) NULL,
	[REMITO_IMPRESO] [char](1) NULL,
	[NRO_REMITO_PF] [varchar](100) NULL,
	[PICKING_ID_REF] [numeric](20, 0) NULL,
	[BULTOS_CONTROLADOS] [varchar](8000) NULL,
	[BULTOS_NO_CONTROLADOS] [varchar](8000) NULL,
	[FLG_PALLET_HOMBRE] [varchar](1) NULL,
	[TRANSF_TERMINADA] [varchar](1) NULL,
	[NRO_LOTE] [varchar](100) NULL,
	[NRO_PARTIDA] [varchar](100) NULL,
	[NRO_SERIE] [varchar](50) NULL)
