--------------------------------------
--SYS_INT
--------------------------------------
ALTER TABLE SYS_INT_DOCUMENTO
ADD CUSTOMS_1 VARCHAR(4000);

ALTER TABLE SYS_INT_DOCUMENTO
ADD CUSTOMS_2 VARCHAR(4000);

ALTER TABLE SYS_INT_DOCUMENTO
ADD CUSTOMS_3 VARCHAR(4000);

ALTER TABLE SYS_INT_DET_DOCUMENTO
ADD CUSTOMS_1 VARCHAR(4000);

ALTER TABLE SYS_INT_DET_DOCUMENTO
ADD CUSTOMS_2 VARCHAR(4000);

ALTER TABLE SYS_INT_DET_DOCUMENTO
ADD CUSTOMS_3 VARCHAR(4000);

--------------------------------------
--SYS_INT HISTORICOS
--------------------------------------
ALTER TABLE SYS_INT_DOCUMENTO_HISTORICO
ADD CUSTOMS_1 VARCHAR(4000);

ALTER TABLE SYS_INT_DOCUMENTO_HISTORICO
ADD CUSTOMS_2 VARCHAR(4000);

ALTER TABLE SYS_INT_DOCUMENTO_HISTORICO
ADD CUSTOMS_3 VARCHAR(4000);

ALTER TABLE SYS_INT_DET_DOCUMENTO_HISTORICO
ADD CUSTOMS_1 VARCHAR(4000);

ALTER TABLE SYS_INT_DET_DOCUMENTO_HISTORICO
ADD CUSTOMS_2 VARCHAR(4000);

ALTER TABLE SYS_INT_DET_DOCUMENTO_HISTORICO
ADD CUSTOMS_3 VARCHAR(4000);

--------------------------------------
--SYS_DEV
--------------------------------------
ALTER TABLE SYS_DEV_DOCUMENTO
ADD CUSTOMS_1 VARCHAR(4000);

ALTER TABLE SYS_DEV_DOCUMENTO
ADD CUSTOMS_2 VARCHAR(4000);

ALTER TABLE SYS_DEV_DOCUMENTO
ADD CUSTOMS_3 VARCHAR(4000);

ALTER TABLE SYS_DEV_DET_DOCUMENTO
ADD CUSTOMS_1 VARCHAR(4000);

ALTER TABLE SYS_DEV_DET_DOCUMENTO
ADD CUSTOMS_2 VARCHAR(4000);

ALTER TABLE SYS_DEV_DET_DOCUMENTO
ADD CUSTOMS_3 VARCHAR(4000);

--------------------------------------
--SYS_DEV HISTORICOS
--------------------------------------
ALTER TABLE SYS_DEV_DOCUMENTO_HISTORICO
ADD CUSTOMS_1 VARCHAR(4000);

ALTER TABLE SYS_DEV_DOCUMENTO_HISTORICO
ADD CUSTOMS_2 VARCHAR(4000);

ALTER TABLE SYS_DEV_DOCUMENTO_HISTORICO
ADD CUSTOMS_3 VARCHAR(4000);

ALTER TABLE SYS_DEV_DET_DOCUMENTO_HISTORICO
ADD CUSTOMS_1 VARCHAR(4000);

ALTER TABLE SYS_DEV_DET_DOCUMENTO_HISTORICO
ADD CUSTOMS_2 VARCHAR(4000);

ALTER TABLE SYS_DEV_DET_DOCUMENTO_HISTORICO
ADD CUSTOMS_3 VARCHAR(4000);