CREATE FUNCTION DBO.GET_SID_CUSTOMS(@CLIENTE_ID	AS VARCHAR(15),
									@DOC_EXT	AS VARCHAR(100),
									@COLUMN		AS CHAR(1))RETURNS VARCHAR(4000)
AS
BEGIN
	DECLARE @RET	VARCHAR(4000)
	
	IF @COLUMN='1'
	BEGIN
		SELECT @RET=CUSTOMS_1 FROM SYS_INT_DOCUMENTO WHERE CLIENTE_ID=@CLIENTE_ID AND DOC_EXT=@DOC_EXT;
	END

	IF @COLUMN='2'
	BEGIN
		SELECT @RET=CUSTOMS_2 FROM SYS_INT_DOCUMENTO WHERE CLIENTE_ID=@CLIENTE_ID AND DOC_EXT=@DOC_EXT;
	END

	IF @COLUMN='3'
	BEGIN
		SELECT @RET=CUSTOMS_3 FROM SYS_INT_DOCUMENTO WHERE CLIENTE_ID=@CLIENTE_ID AND DOC_EXT=@DOC_EXT;
	END

	RETURN @RET;
END									