
--1.
CREATE TABLE DBO.MOB_DEVOLUCIONES_TMP (
	ID_DEVO					NUMERIC(20,0) IDENTITY(1,1),
	CLIENTE_ID				VARCHAR(15),
	PRODUCTO_ID				VARCHAR(15),
	PALLET_DEVOLUCION		VARCHAR(100),
	MOTIVO_ID				VARCHAR(100),
	NRO_LOTE				VARCHAR(100),
	NRO_PALLET				VARCHAR(100),
	NRO_PARTIDA				VARCHAR(100),
	NRO_SERIE				VARCHAR(100),
	CANTIDAD				NUMERIC(20,5),
	OBSERVACIONES			VARCHAR(200),
	DOCUMENTO_ID_EGRESO		NUMERIC(20,0),
	NRO_LINEA_EGRESO		NUMERIC(10,0),
	DOCUMENTO_ID_DEVOLUCION	NUMERIC(20,0),
	NRO_LINEA_DEVOLUCION	NUMERIC(20,0),
	USUARIO_ID				VARCHAR(100),
	FECHA_CREACION			DATETIME,
	ESTADO					VARCHAR(100),
	FECHA_ESTADO			DATETIME,
	OBS_ESTADO				VARCHAR(200)
)
GO

ALTER TABLE DBO.MOB_DEVOLUCIONES_TMP
ADD CONSTRAINT PK_MOB_DEVOLUCIONES_TMP PRIMARY KEY(ID_DEVO)