/****** Object:  StoredProcedure [dbo].[MOB_DEV_CONTENIDO_PALLET]    Script Date: 10/22/2015 17:15:28 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[MOB_DEV_CONTENIDO_PALLET]') AND type in (N'P', N'PC'))
DROP PROCEDURE [dbo].[MOB_DEV_CONTENIDO_PALLET]
GO

CREATE PROCEDURE [dbo].[MOB_DEV_CONTENIDO_PALLET]
	@PALLET_DEVOLUCION	VARCHAR(100)
AS
BEGIN
	SELECT	DISTINCT 
			D.NRO_REMITO	AS [NRO.PEDIDO],
			M.NRO_SERIE		AS [NRO.SERIE],
			P.PRODUCTO_ID	AS [COD.PRODUCTO],
			P.DESCRIPCION	AS [DESCRIPCION]
	FROM	MOB_DEVOLUCIONES_TMP M INNER JOIN vPICKING P
			ON(P.DOCUMENTO_ID=M.DOCUMENTO_ID_EGRESO AND P.NRO_LINEA=M.NRO_LINEA_EGRESO)
			INNER JOIN vDOCUMENTO D
			ON(P.DOCUMENTO_ID=D.DOCUMENTO_ID)
	WHERE	M.PALLET_DEVOLUCION=@PALLET_DEVOLUCION
END
GO


