
INSERT INTO SYS_DET_TABLA VALUES('NAVE',	'EN_ERROR',	'Virtual P/Error de Rececpión',	'S',	30,	0);
INSERT INTO SYS_DET_TABLA VALUES('NAVE',	'FLG_GARANTIA',	'Nave de Garantia',	'S',	1,	0);
INSERT INTO SYS_TABCOLUMNS VALUES('NAVE',	'EN_ERROR',	21,	'CHAR',	'Y',	1,	NULL,	NULL,	1,	NULL);
INSERT INTO SYS_TABCOLUMNS VALUES('NAVE',	'FLG_GARANTIA',	20,	'VARCHAR2',	'N',	1,	NULL,	NULL,	1,	NULL);