ALTER TABLE TIPO_AGENTE ADD [FLG_INGRESO] [char](1) NULL
go
ALTER TABLE TIPO_AGENTE ADD[FLG_EGRESO] [char](1) NULL
go
UPDATE TIPO_AGENTE SET FLG_INGRESO='0', FLG_EGRESO='1' WHERE TIPO_AGENTE_ID='CLIENTE';
UPDATE TIPO_AGENTE SET FLG_INGRESO='1', FLG_EGRESO='1' WHERE TIPO_AGENTE_ID='PROVEEDOR';
UPDATE TIPO_AGENTE SET FLG_INGRESO='1', FLG_EGRESO='1' WHERE TIPO_AGENTE_ID='SUCURSAL';