CREATE TABLE DBO.AUDITORIA_CAMBIO_DESPACHOS(
	AUDITORIA_ID	NUMERIC(20,0) NOT NULL IDENTITY(1,1),
	F_AUDITORIA		DATETIME,
	PARAMETROS		VARCHAR(4000),
	ERROR			CHAR(1),
	ERR_TECNICO		VARCHAR(4000),
	F_INFORMADO		DATETIME,
	OBSERVACIONES	VARCHAR(4000)
)

