IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[INS_AUDITORIA_CAMBIO_DESPACHOS]') AND type in (N'P', N'PC'))
DROP PROCEDURE [dbo].[INS_AUDITORIA_CAMBIO_DESPACHOS]
GO
CREATE PROCEDURE DBO.INS_AUDITORIA_CAMBIO_DESPACHOS
	@PARAMETROS		VARCHAR(4000),
	@ERROR			CHAR(1),
	@ERR_TECNICO	VARCHAR(4000),
	@OBSERVACIONES	VARCHAR(4000)
AS BEGIN

	INSERT INTO DBO.AUDITORIA_CAMBIO_DESPACHOS (F_AUDITORIA,PARAMETROS,ERROR,ERR_TECNICO,OBSERVACIONES)
	VALUES(GETDATE(),@PARAMETROS,@ERROR,@ERR_TECNICO,@OBSERVACIONES);

END;