
/****** Object:  UserDefinedFunction [dbo].[VERIFICA_FIN_VIAJES]    Script Date: 09/19/2013 12:07:47 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[VERIFICA_FIN_VIAJES]') AND type in (N'FN', N'IF', N'TF', N'FS', N'FT'))
DROP FUNCTION [dbo].[VERIFICA_FIN_VIAJES]
GO

CREATE      FUNCTION [dbo].[VERIFICA_FIN_VIAJES](@VIAJE AS VARCHAR(100))RETURNS INTEGER
AS
	
BEGIN
	DECLARE @CANT AS NUMERIC(20)
	DECLARE @RETORNO AS NUMERIC(20)

	SELECT 	@CANT=COUNT(*)
	FROM 	PICKING
	WHERE 	LTRIM(RTRIM(UPPER(VIAJE_ID))) = LTRIM(RTRIM(UPPER(@VIAJE)))
			AND FECHA_INICIO IS NULL
			AND FECHA_FIN IS NULL
			AND CANT_CONFIRMADA IS NULL
	IF @CANT >= 1
		BEGIN
			SET @RETORNO = 0
		END 
	ELSE
		BEGIN
			SET @RETORNO = 1
		END
	RETURN @RETORNO
END

GO


