/****** Object:  StoredProcedure [dbo].[GET_MOVIMIENTOS_BY_VIAJE_TRANSFPICKING]    Script Date: 02/01/2016 10:53:09 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[GET_MOVIMIENTOS_BY_VIAJE_TRANSFPICKING]') AND type in (N'P', N'PC'))
DROP PROCEDURE [dbo].[GET_MOVIMIENTOS_BY_VIAJE_TRANSFPICKING]
GO

CREATE Procedure [dbo].[GET_MOVIMIENTOS_BY_VIAJE_TRANSFPICKING]
@Viaje_id	varchar(50),
@Tipo		varchar(1)
as
Begin

DECLARE @USUARIO	VARCHAR(50)
	/*
		Tipos:
			-Tipo 1: Por Bultos.
			-Tipo 2: Por Pallet.
	*/
	
	SELECT @USUARIO=USUARIO_ID FROM #TEMP_USUARIO_LOGGIN
	--SET @USUARIO='MPRIVITERA'

	SELECT	 TOP 1
			 P.PROP1 AS PALLET
			,DD.NRO_BULTO AS CONTENEDORA
			,P.VIAJE_ID
			,P.PRODUCTO_ID
			,P.DESCRIPCION
			,P.POSICION_COD AS UBICACION_ORIGEN
	FROM	PICKING P INNER JOIN DET_DOCUMENTO DD
			ON(P.DOCUMENTO_ID=DD.DOCUMENTO_ID AND P.NRO_LINEA=DD.NRO_LINEA)
	WHERE	P.VIAJE_ID=@VIAJE_ID
			AND P.FLG_PALLET_HOMBRE = '1'
			AND P.TRANSF_TERMINADA = '0'
			--Control Por Tipo--
			AND ((@Tipo='1' AND DD.NRO_BULTO is not null)or(@Tipo='2' AND P.PROP1 IS NOT NULL))
			--------------------
			AND NOT EXISTS (SELECT	1 
							FROM	MOVIMIENTOSPREPICKING M
							WHERE	((M.PALLET IS NULL) OR (M.PALLET=P.PROP1))
									AND ((M.CONTENEDORA IS NULL)OR (M.CONTENEDORA=DD.NRO_BULTO)))
			AND P.NAVE_COD	IN(	SELECT 	NAVE_COD
								FROM 	NAVE N INNER JOIN RL_USUARIO_NAVE RLNU
										ON(N.NAVE_ID=RLNU.NAVE_ID)
								WHERE	N.NAVE_COD=P.NAVE_COD
										AND RLNU.USUARIO_ID=@USUARIO)
										
	GROUP BY P.PROP1 
			,DD.NRO_BULTO 
			,VIAJE_ID
			,P.PRODUCTO_ID
			,P.DESCRIPCION
			,P.POSICION_COD 
					


		
end


GO


