/****** Object:  StoredProcedure [dbo].[VERIFICA_CONTENEDORA_POS_TR]    Script Date: 02/01/2016 15:08:55 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[VERIFICA_CONTENEDORA_POS_TR]') AND type in (N'P', N'PC'))
DROP PROCEDURE [dbo].[VERIFICA_CONTENEDORA_POS_TR]
GO

CREATE     PROCEDURE [dbo].[VERIFICA_CONTENEDORA_POS_TR]
@POSICION_O		AS VARCHAR(45),
@CONTENEDORA	AS VARCHAR(100),
@PALLET			AS VARCHAR(100) OUTPUT
AS
BEGIN
	DECLARE @CONTROL 	AS INT
	DECLARE @EXISTE 	AS INT
	DECLARE @VPALLET	VARCHAR(100)
	DECLARE @MSG		VARCHAR(1000)
	

	SET @VPALLET =@PALLET 

	--SE AGREGAN ESTAS LINEAS PARA CONTROLAR LA EXISTENCIA DEL PALLET.

	SELECT	@EXISTE = COUNT(*)
	FROM	DET_DOCUMENTO DD INNER JOIN DET_DOCUMENTO_TRANSACCION DDT
			ON(DD.DOCUMENTO_ID=DDT.DOCUMENTO_ID AND DD.NRO_LINEA=DDT.NRO_LINEA_DOC)
			INNER JOIN RL_DET_DOC_TRANS_POSICION RL 
			ON(DDT.DOC_TRANS_ID=RL.DOC_TRANS_ID AND DDT.NRO_LINEA_TRANS=RL.NRO_LINEA_TRANS)
	WHERE 	((@CONTENEDORA IS NULL)OR(NRO_BULTO = LTRIM(RTRIM(UPPER(@CONTENEDORA)))))
			AND ((@PALLET IS NULL) OR (DD.PROP1=@PALLET))

	SELECT 	@PALLET=DD.PROP1
	FROM	DET_DOCUMENTO DD 
			INNER JOIN DET_DOCUMENTO_TRANSACCION DDT
			ON(DD.DOCUMENTO_ID=DDT.DOCUMENTO_ID AND DD.NRO_LINEA=DDT.NRO_LINEA_DOC)
			INNER JOIN RL_DET_DOC_TRANS_POSICION RL
			ON(DDT.DOC_TRANS_ID=RL.DOC_TRANS_ID AND DDT.NRO_LINEA_TRANS=RL.NRO_LINEA_TRANS)
	WHERE	((PROP1=LTRIM(RTRIM(UPPER(@PALLET ))))OR(NRO_BULTO = LTRIM(RTRIM(UPPER(@PALLET)))))
			AND RL.NAVE_ACTUAL=	(	SELECT 	NAVE_ID
									FROM 	NAVE
									WHERE	NAVE_COD=LTRIM(RTRIM(UPPER(@POSICION_O)))
								)
			OR RL.POSICION_ACTUAL=	(	SELECT 	TOP 1 POSICION_ID
										FROM 	POSICION
										WHERE	POSICION_COD=LTRIM(RTRIM(UPPER(@POSICION_O)))
									)
			AND RL.CANTIDAD >0

	IF @EXISTE =0
	BEGIN
		/*SET @EXISTE=NULL
		SELECT	@EXISTE = COUNT(DD.PROP1)
		FROM	DET_DOCUMENTO DD INNER JOIN DET_DOCUMENTO_TRANSACCION DDT
				ON(DD.DOCUMENTO_ID=DDT.DOCUMENTO_ID AND DD.NRO_LINEA=DDT.NRO_LINEA_DOC)
				INNER JOIN RL_DET_DOC_TRANS_POSICION RL 
				ON(DDT.DOC_TRANS_ID=RL.DOC_TRANS_ID AND DDT.NRO_LINEA_TRANS=RL.NRO_LINEA_TRANS)
		WHERE 	DD.PROP1 = LTRIM(RTRIM(UPPER(@CONTENEDORA)))*/
		RAISERROR('La contenedora ingresada no existe.',16,1)
		RETURN
	END

	SELECT 	@CONTROL=COUNT(RL.RL_ID)
	FROM	DET_DOCUMENTO DD 
			INNER JOIN DET_DOCUMENTO_TRANSACCION DDT
			ON(DD.DOCUMENTO_ID=DDT.DOCUMENTO_ID AND DD.NRO_LINEA=DDT.NRO_LINEA_DOC)
			INNER JOIN RL_DET_DOC_TRANS_POSICION RL
			ON(DDT.DOC_TRANS_ID=RL.DOC_TRANS_ID AND DDT.NRO_LINEA_TRANS=RL.NRO_LINEA_TRANS)
	WHERE	((@CONTENEDORA is null) or(NRO_BULTO=LTRIM(RTRIM(UPPER(@CONTENEDORA))) ))
			and ((@PALLET is null)or(DD.PROP1=@PALLET))
			AND RL.NAVE_ACTUAL=	(	SELECT 	NAVE_ID
									FROM 	NAVE
									WHERE	NAVE_COD=LTRIM(RTRIM(UPPER(@POSICION_O)))
								)
			OR RL.POSICION_ACTUAL=	(	SELECT 	TOP 1 POSICION_ID
										FROM 	POSICION
										WHERE	POSICION_COD=LTRIM(RTRIM(UPPER(@POSICION_O)))
									)
			AND RL.CANTIDAD >0


	IF @CONTROL=0
		BEGIN
			SET @CONTROL=NULL

			SELECT 	@CONTROL=COUNT(RL.RL_ID)
			FROM	DET_DOCUMENTO DD 
					INNER JOIN DET_DOCUMENTO_TRANSACCION DDT
					ON(DD.DOCUMENTO_ID=DDT.DOCUMENTO_ID AND DD.NRO_LINEA=DDT.NRO_LINEA_DOC)
					INNER JOIN RL_DET_DOC_TRANS_POSICION RL
					ON(DDT.DOC_TRANS_ID=RL.DOC_TRANS_ID AND DDT.NRO_LINEA_TRANS=RL.NRO_LINEA_TRANS)
			WHERE	PROP1=LTRIM(RTRIM(UPPER(@CONTENEDORA))) 
					AND RL.NAVE_ACTUAL=	(	SELECT 	NAVE_ID
											FROM 	NAVE
											WHERE	NAVE_COD=LTRIM(RTRIM(UPPER(@POSICION_O)))
										)
					OR RL.POSICION_ACTUAL=	(	SELECT 	TOP 1 POSICION_ID
												FROM 	POSICION
												WHERE	POSICION_COD=LTRIM(RTRIM(UPPER(@POSICION_O)))
											)
					AND RL.CANTIDAD >0


			IF @CONTROL=0
			BEGIN
				RAISERROR('1-La contenedora no esta en la posicion especificada.',16,1)
				RETURN
			END
			ELSE
			BEGIN
				SELECT 	@PALLET=DD.PROP1
				FROM	DET_DOCUMENTO DD 
						INNER JOIN DET_DOCUMENTO_TRANSACCION DDT
						ON(DD.DOCUMENTO_ID=DDT.DOCUMENTO_ID AND DD.NRO_LINEA=DDT.NRO_LINEA_DOC)
						INNER JOIN RL_DET_DOC_TRANS_POSICION RL
						ON(DDT.DOC_TRANS_ID=RL.DOC_TRANS_ID AND DDT.NRO_LINEA_TRANS=RL.NRO_LINEA_TRANS)
				WHERE	PROP1=LTRIM(RTRIM(UPPER(@CONTENEDORA))) 
						AND RL.NAVE_ACTUAL=	(	SELECT 	NAVE_ID
												FROM 	NAVE
												WHERE	NAVE_COD=LTRIM(RTRIM(UPPER(@POSICION_O)))
											)
						OR RL.POSICION_ACTUAL=	(	SELECT 	TOP 1 POSICION_ID
													FROM 	POSICION
													WHERE	POSICION_COD=LTRIM(RTRIM(UPPER(@POSICION_O)))
												)
						AND RL.CANTIDAD >0

			END
		END

	SET @CONTROL=0
	
	SELECT	@CONTROL=COUNT(P.PICKING_ID)
	FROM	PICKING P
			INNER JOIN DET_DOCUMENTO DD ON(P.DOCUMENTO_ID=DD.DOCUMENTO_ID AND P.NRO_LINEA = DD.NRO_LINEA)
	WHERE	P.CANT_CONFIRMADA IS NULL
			AND ((@CONTENEDORA IS NULL) OR(NRO_BULTO=LTRIM(RTRIM(UPPER(@CONTENEDORA))) ))
			AND ((@vPALLET IS NULL)OR(DD.PROP1 = @vPALLET))
			AND POSICION_COD = @POSICION_O

	IF (@CONTROL>0)
	BEGIN
		IF @CONTENEDORA IS NOT NULL BEGIN
			SET @MSG='1-La contenedora aun tiene tareas de picking pendientes.'-- CONTROL: ' + CAST(@CONTROL AS VARCHAR) + '| @CONTENEDOR: ' + ISNULL(@CONTENEDORA,'NULL') + '| @PALLET: ' + ISNULL(@vPALLET,'NULL') + '| POSICION_O: ' + ISNULL(@POSICION_O,'NULL')
			RAISERROR(@MSG,16,1)
			RETURN
		END ELSE BEGIN
			SET @MSG='1-El pallet aun tiene tareas de picking pendientes. '--CONTROL: ' + CAST(@CONTROL AS VARCHAR) + '| @CONTENEDOR: ' + ISNULL(@CONTENEDORA,'NULL') + '| @PALLET: ' + ISNULL(@vPALLET,'NULL') + '| POSICION_O: ' + ISNULL(@POSICION_O,'NULL')
			RAISERROR(@MSG,16,1)
			RETURN		
		END
	END
END


GO


