CREATE TABLE MOB_AUDITORIA_SERIES_2D(
	ID_AUDITORIA	NUMERIC(20,0) NOT NULL IDENTITY(1,1),
	CLIENTE_ID		VARCHAR(15),
	CODIGO_VIAJE	VARCHAR(100),
	PRODUCTO_ID		VARCHAR(30),
	LECTURA_2D		VARCHAR(100),
	USUARIO			VARCHAR(100),
	F_AUDITORIA		DATETIME
)
GO

ALTER TABLE MOB_AUDITORIA_SERIES_2D
ADD CONSTRAINT PK_MOB_AUDITORIA_SERIES_2D PRIMARY KEY (ID_AUDITORIA)