CREATE PROCEDURE MOB_INS_AUDITORIA_2D 
	@CLIENTE_ID			VARCHAR(15),
	@CODIGO_VIAJE		VARCHAR(100),
	@PRODUCTO_ID		VARCHAR(30),
	@LECTURA_2D			VARCHAR(100),
	@USUARIO			VARCHAR(100)
AS
BEGIN

	INSERT INTO MOB_AUDITORIA_SERIES_2D(CLIENTE_ID,CODIGO_VIAJE,PRODUCTO_ID,LECTURA_2D,USUARIO,F_AUDITORIA)
	VALUES(@CLIENTE_ID, @CODIGO_VIAJE, @PRODUCTO_ID, @LECTURA_2D, @USUARIO, GETDATE())

END		--FIN PROCEDURE.