
--PARA EL TRIGGER.
CREATE PROCEDURE DBO.MOB_CAMBIO_PEDIDO_SERIES_2D
@CLIENTE_ID			VARCHAR(15),
@CODIGO_VIAJE_OLD	VARCHAR(100),
@CODIGO_VIAJE_NEW	VARCHAR(100)
AS
BEGIN

	UPDATE	MOB_AUDITORIA_SERIES_2D
	SET		CODIGO_VIAJE=@CODIGO_VIAJE_NEW
	WHERE	CLIENTE_ID=@CLIENTE_ID
			AND CODIGO_VIAJE=@CODIGO_VIAJE_OLD

END