/****** Object:  Trigger [TRG_AUDITORIA_2D]    Script Date: 02/22/2016 16:46:16 ******/
IF  EXISTS (SELECT * FROM sys.triggers WHERE object_id = OBJECT_ID(N'[dbo].[TRG_AUDITORIA_2D]'))
DROP TRIGGER [dbo].[TRG_AUDITORIA_2D]
GO

CREATE TRIGGER [dbo].[TRG_AUDITORIA_2D]
ON [dbo].[PICKING]
AFTER UPDATE, INSERT
AS
BEGIN
	SET NOCOUNT ON
	DECLARE @CLIENTE_ID		VARCHAR(100)
	DECLARE @VIAJE_ID_NEW	VARCHAR(100)
	DECLARE @VIAJE_ID_OLD	VARCHAR(100)
	
	IF CURSOR_STATUS('global','TRG_CURSOR_2D')>=-1  BEGIN
		DEALLOCATE TRG_CURSOR_2D
	END
	
	SELECT TOP 1 @VIAJE_ID_OLD=VIAJE_ID,@CLIENTE_ID=CLIENTE_ID FROM DELETED 
	SELECT TOP 1 @VIAJE_ID_NEW=VIAJE_ID FROM INSERTED
	
	IF UPDATE(VIAJE_ID) BEGIN
		
		EXEC DBO.MOB_CAMBIO_PEDIDO_SERIES_2D @CLIENTE_ID, @VIAJE_ID_OLD, @VIAJE_ID_NEW
	
	END


END




GO


