ALTER TABLE CLIENTE_PARAMETROS ADD FLG_CONTROL_CANT_PALLET	VARCHAR(1) DEFAULT('0')
GO

UPDATE CLIENTE_PARAMETROS SET FLG_CONTROL_CANT_PALLET='0'
GO

INSERT INTO SYS_TABCOLUMNS VALUES('CLIENTE_PARAMETROS',	'FLG_CONTROL_CANT_PALLET',	27,	'CHAR',	'Y',	1,	NULL,	NULL,	1,	NULL)
GO

INSERT INTO SYS_DET_TABLA VALUES('CLIENTE_PARAMETROS',	'FLG_CONTROL_CANT_PALLET',	'Ingreso - Ctrl. Cant.Pallets',	'S',	1,	0)