ALTER TABLE NAVE ADD CANT_PALLET NUMERIC(10,0)
GO

INSERT INTO SYS_TABCOLUMNS VALUES('NAVE',	'CANT_PALLET',	23,	'NUMBER',	'Y',	10,	10,	0,	10,	NULL)
GO

INSERT INTO SYS_DET_TABLA VALUES('NAVE', 'CANT_PALLET', 'Cant. de Pallets', 'S', 5, 0)