CREATE FUNCTION DBO.GUARDADO_PALLET_INGRESO_CANT_PALLET_NAVE(
@CLIENTE_ID		VARCHAR(15),
@PRODUCTO_ID	VARCHAR(30),
@NAVE_ID		NUMERIC(20,0)
)RETURNS SMALLINT
BEGIN
	DECLARE @RET				AS SMALLINT
	DECLARE @CANT_RL			AS BIGINT
	DECLARE @EXISTE				AS VARCHAR(1)
	DECLARE @PALLETS_UBICACION	AS BIGINT
	DECLARE @CANT_UBICACION		AS BIGINT
	DECLARE @EVAL				AS BIGINT
	DECLARE @OTROS_PALLETS		AS BIGINT

	SET @RET=0

	SELECT	@CANT_RL=ISNULL(RL.CANT_PALLET,N.CANT_PALLET), @EXISTE='1'
	FROM	RL_PRODUCTO_POSICION_PERMITIDA  RL INNER JOIN NAVE N
			ON(RL.NAVE_ID=N.NAVE_ID)
	WHERE	RL.CLIENTE_ID=@CLIENTE_ID
			AND RL.PRODUCTO_ID=@PRODUCTO_ID
			AND RL.NAVE_ID=@NAVE_ID
			
	SELECT	@OTROS_PALLETS=COUNT(DISTINCT DD.PROP1)
	FROM	DET_DOCUMENTO DD INNER JOIN DET_DOCUMENTO_TRANSACCION DDT
			ON(DD.DOCUMENTO_ID=DDT.DOCUMENTO_ID AND DD.NRO_LINEA=DDT.NRO_LINEA_DOC)
			INNER JOIN RL_DET_DOC_TRANS_POSICION RL
			ON(DDT.DOC_TRANS_ID=RL.DOC_TRANS_ID AND DDT.NRO_LINEA_TRANS=RL.NRO_LINEA_TRANS)
			INNER JOIN NAVE N
			ON(RL.NAVE_ACTUAL = N.NAVE_ID)
	WHERE	N.NAVE_ID =@NAVE_ID		
			AND DD.PRODUCTO_ID NOT IN(@PRODUCTO_ID)	

	IF @OTROS_PALLETS>0 BEGIN
		SET @EXISTE='0'
	END

	SELECT	@PALLETS_UBICACION=COUNT(DISTINCT DD.PROP1)
	FROM	DET_DOCUMENTO DD INNER JOIN DET_DOCUMENTO_TRANSACCION DDT
			ON(DD.DOCUMENTO_ID=DDT.DOCUMENTO_ID AND DD.NRO_LINEA=DDT.NRO_LINEA_DOC)
			INNER JOIN RL_DET_DOC_TRANS_POSICION RL
			ON(DDT.DOC_TRANS_ID=RL.DOC_TRANS_ID AND DDT.NRO_LINEA_TRANS=RL.NRO_LINEA_TRANS)
			INNER JOIN NAVE N
			ON(RL.NAVE_ACTUAL = N.NAVE_ID)
	WHERE	N.NAVE_ID =@NAVE_ID

	IF @EXISTE='1' BEGIN

		SET @EVAL=@CANT_RL - @PALLETS_UBICACION

	END ELSE BEGIN

		SELECT	@CANT_UBICACION=ISNULL(N.CANT_PALLET,0)
		FROM	NAVE N
		WHERE	N.NAVE_ID =@NAVE_ID 

		SET @EVAL =@CANT_UBICACION - @PALLETS_UBICACION
	END

	IF @EVAL >0 BEGIN
		SET @RET =1 
	END ELSE BEGIN
		SET @RET =0
	END

	RETURN @RET

END

