BEGIN

	DECLARE @CONT NUMERIC;
	
	SELECT	@CONT=COUNT(*) FROM	sys_tabColumns WHERE TABLE_NAME='PRODUCTO' AND COLUMN_NAME ='INGPARTIDA';
	IF @CONT=0 BEGIN
		INSERT INTO SYS_TABCOLUMNS VALUES('PRODUCTO',	'INGPARTIDA',	59,	'VARCHAR2',	'N',	1,	NULL,	NULL,	1,	NULL);
	END
	
	SELECT	@CONT=COUNT(*) FROM	sys_tabColumns WHERE TABLE_NAME='PRODUCTO' AND COLUMN_NAME ='INGLOTEPROVEEDOR';
	IF @CONT=0 BEGIN
		INSERT INTO SYS_TABCOLUMNS VALUES('PRODUCTO',	'INGLOTEPROVEEDOR',	58,	'VARCHAR2',	'N',	1,	NULL,	NULL,	1,	NULL);
	END
	
	SELECT @CONT =COUNT(*) FROM SYS_DET_TABLA WHERE TABLA_ID='PRODUCTO' AND CAMPO='INGPARTIDA';
	IF @CONT=0 BEGIN
		INSERT INTO SYS_DET_TABLA VALUES('PRODUCTO',	'INGPARTIDA',	'Ingresa con Partida',	'S',	1,	0);
	END

	SELECT @CONT =COUNT(*) FROM SYS_DET_TABLA WHERE TABLA_ID='PRODUCTO' AND CAMPO='INGLOTEPROVEEDOR';
	IF @CONT=0 BEGIN	
		INSERT INTO SYS_DET_TABLA VALUES('PRODUCTO','INGLOTEPROVEEDOR','Ingresa con Lote de Proveedor','S',1,0);
	END
END