
/****** Object:  StoredProcedure [dbo].[INGRESO_OC_BORRAR]    Script Date: 03/19/2014 14:33:40 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[INGRESO_OC_BORRAR]') AND type in (N'P', N'PC'))
DROP PROCEDURE [dbo].[INGRESO_OC_BORRAR]
GO

/****** Object:  StoredProcedure [dbo].[INGRESO_OC_BORRAR]    Script Date: 03/19/2014 14:33:40 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[INGRESO_OC_BORRAR]
	@ING_ID	NUMERIC(20,0)
AS
BEGIN
	DECLARE @CLIENTE_ID		VARCHAR(15)
	DECLARE @PRODUCTO_ID	VARCHAR(30)
	DECLARE @ORDEN_COMPRA	VARCHAR(100)
	DECLARE @CANTIDAD		NUMERIC(20,5)
	DECLARE @PROCESADO		CHAR(1)
	DECLARE @NRO_LOTE		VARCHAR(100)
	DECLARE @NRO_PARTIDA	VARCHAR(100)
	
	SELECT	@CLIENTE_ID = CLIENTE_ID,
			@PRODUCTO_ID = PRODUCTO_ID,
			@ORDEN_COMPRA = ORDEN_COMPRA,
			@PROCESADO = PROCESADO,
			@NRO_LOTE = NRO_LOTE,
			@NRO_PARTIDA = NRO_PARTIDA	
	FROM	INGRESO_OC
	WHERE	ING_ID=@ING_ID;
	
	DELETE	FROM CONFIGURACION_CONTENEDORAS
	WHERE	CLIENTE_ID = @CLIENTE_ID AND PRODUCTO_ID = @PRODUCTO_ID
			AND ORDEN_COMPRA = @ORDEN_COMPRA AND PROCESADO = @PROCESADO
			AND NRO_LOTE = @NRO_LOTE AND NRO_PARTIDA = @NRO_PARTIDA;
	
	DELETE	FROM INGRESO_OC
	WHERE	ING_ID=@ING_ID;
END;


GO


