ALTER TABLE CATEGORIA_LOGICA ADD DISP_PRODUCCION VARCHAR(1)
GO

INSERT INTO sys_tabColumns VALUES('CATEGORIA_LOGICA',	'DISP_PRODUCCION',	9,	'CHAR',	'Y',	1,	NULL,	NULL,	1,	NULL)
GO

INSERT INTO SYS_DET_TABLA VALUES('CATEGORIA_LOGICA',	'DISP_PRODUCCION',	'Disp.Produccion',	'S',	'1',	'0') 