
CREATE TABLE DBO.MOB_EMPAQUE_UC_EMPAQUE(
	MOB_EMP_UC_ID	NUMERIC(20,0)NOT NULL IDENTITY(1,1),	
	DOCUMENTO_ID	NUMERIC(20,0),
	UC_EMPAQUE		VARCHAR(100),
	ESTADO			VARCHAR(100),
	F_CREACION		DATETIME,
)
