IF  EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[DBO].[MOB_EMPAQUETADO_QUITAR_CONTENEDORA]') AND TYPE IN (N'P', N'PC'))
DROP PROCEDURE [DBO].[MOB_EMPAQUETADO_QUITAR_CONTENEDORA]

GO

CREATE PROCEDURE [dbo].[MOB_EMPAQUETADO_QUITAR_CONTENEDORA]
	@VIAJE_ID	VARCHAR(100),
	@CONTENEDOR	VARCHAR(100)
AS
BEGIN
	
	DELETE FROM MOB_EMPAQUE_EN_PROGRESO WHERE VIAJE_ID=@VIAJE_ID AND CONTENEDOR=@CONTENEDOR

END