IF  EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[DBO].[MOB_EMPAQUE_GET_CONTENEDORAS]') AND TYPE IN (N'P', N'PC'))
DROP PROCEDURE [DBO].[MOB_EMPAQUE_GET_CONTENEDORAS]

GO

CREATE PROCEDURE DBO.MOB_EMPAQUE_GET_CONTENEDORAS
	@VIAJE_ID	AS VARCHAR(100)
AS
BEGIN

	SELECT	DISTINCT M.UC_EMPAQUE AS [CONT. EMPAQUE], D.NRO_REMITO AS [NRO. PEDIDO], M.ESTADO
	FROM	PICKING P INNER JOIN DOCUMENTO D		ON(P.DOCUMENTO_ID=D.DOCUMENTO_ID)
			INNER JOIN MOB_EMPAQUE_UC_EMPAQUE M		ON(D.DOCUMENTO_ID=M.DOCUMENTO_ID)
	WHERE	VIAJE_ID=@VIAJE_ID	
	
END	