CREATE TABLE DBO.IMPRESION_ETIQUETA_EMPAQUE(
	IMP_ID		NUMERIC(20,0) NOT NULL IDENTITY(1,1),
	CLIENTE_ID	VARCHAR(15),
	PEDIDO		VARCHAR(100),
	CONTENEDORA	BIGINT,
	REPORTE		VARCHAR(100),
	IMPRESO		VARCHAR(1) DEFAULT('0')
)
GO

ALTER TABLE IMPRESION_ETIQUETA_EMPAQUE
ADD CONSTRAINT PK_IMPRESION_ETIQUETA_EMPAQUE PRIMARY KEY(IMP_ID)