CREATE TABLE DBO.IMPRESION_PACKING(
	IMP_ID		NUMERIC(20,0) NOT NULL IDENTITY(1,1),
	CLIENTE_ID	VARCHAR(15),
	PEDIDO		VARCHAR(100),
	IMPRESO		VARCHAR(1) DEFAULT('0')
)
GO

ALTER TABLE IMPRESION_PACKING
ADD CONSTRAINT PK_IMPRESION_PACKING PRIMARY KEY(IMP_ID)