/****** Object:  StoredProcedure [dbo].[MOB_EMP_LIBERAR_TAREA_TOMADA]    Script Date: 08/17/2015 15:26:27 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[MOB_EMP_LIBERAR_TAREA_TOMADA]') AND type in (N'P', N'PC'))
DROP PROCEDURE [dbo].[MOB_EMP_LIBERAR_TAREA_TOMADA]
GO

CREATE PROCEDURE [dbo].[MOB_EMP_LIBERAR_TAREA_TOMADA]
	@VIAJE_ID		VARCHAR(100),
	@CLIENTE_ID		VARCHAR(15),
	@PRODUCTO_ID	VARCHAR(30),
	@CONTENEDORAS	VARCHAR(4000),
	@PEDIDO			VARCHAR(100),
	@CANTIDAD		BIGINT		,
	@SOLICITA_LP	VARCHAR(1)	,
	@LOTE			VARCHAR(100),
	@PARTIDA		VARCHAR(100),
	@NRO_SERIE		VARCHAR(100),
	@CONT_EMPAQUE	VARCHAR(100),
	@USUARIO		VARCHAR(100)
AS
BEGIN	

	DECLARE @CONT	NUMERIC(20,0)
	DECLARE @EX		NUMERIC(20,0)

	IF @SOLICITA_LP='1' BEGIN
	
		UPDATE	PICKING 
		SET		BULTOS_CONTROLADOS=NULL, USUARIO_PF=NULL
		FROM	PICKING P INNER JOIN DOCUMENTO D		ON(P.DOCUMENTO_ID=D.DOCUMENTO_ID)			
				INNER JOIN MOB_EMPAQUE_UC_EMPAQUE M1	ON(D.DOCUMENTO_ID=M1.DOCUMENTO_ID AND M1.ESTADO='ABIERTO')
				INNER JOIN CLIENTE_PARAMETROS CP		ON(P.CLIENTE_ID=CP.CLIENTE_ID)
		WHERE	P.VIAJE_ID=@VIAJE_ID
				AND P.CLIENTE_ID=@CLIENTE_ID 
				AND P.PRODUCTO_ID=@PRODUCTO_ID 
				AND D.NRO_REMITO =@PEDIDO	
				AND P.BULTOS_CONTROLADOS='1'
				AND P.USUARIO_PF =@USUARIO 
				AND ((@LOTE IS NULL AND P.NRO_LOTE IS NULL)OR(P.NRO_LOTE=@LOTE))
				AND ((@PARTIDA IS NULL AND P.NRO_PARTIDA IS NULL)OR(P.NRO_PARTIDA=@PARTIDA))
				AND ((@NRO_SERIE IS NULL AND P.NRO_SERIE IS NULL)OR(P.NRO_SERIE=@NRO_SERIE))
				
	END ELSE BEGIN
	
		UPDATE	PICKING 
		SET		BULTOS_CONTROLADOS=NULL, USUARIO_PF=NULL
		FROM	PICKING P INNER JOIN DOCUMENTO D		ON(P.DOCUMENTO_ID=D.DOCUMENTO_ID)			
				INNER JOIN MOB_EMPAQUE_UC_EMPAQUE M1	ON(D.DOCUMENTO_ID=M1.DOCUMENTO_ID AND M1.ESTADO='ABIERTO')
				INNER JOIN CLIENTE_PARAMETROS CP		ON(P.CLIENTE_ID=CP.CLIENTE_ID)
		WHERE	P.VIAJE_ID=@VIAJE_ID
				AND P.CLIENTE_ID=@CLIENTE_ID 
				AND P.PRODUCTO_ID=@PRODUCTO_ID 
				AND D.NRO_REMITO =@PEDIDO	
				AND P.BULTOS_CONTROLADOS='1'
				AND P.USUARIO_PF =@USUARIO 

	END			
END

