IF  EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[DBO].[FRONTERA_GET_TAREASPICKINGTOMADAS]') AND TYPE IN (N'P', N'PC'))
DROP PROCEDURE [DBO].[FRONTERA_GET_TAREASPICKINGTOMADAS]
GO

CREATE     PROCEDURE [DBO].[FRONTERA_GET_TAREASPICKINGTOMADAS]
@CLIENTE_ID		VARCHAR(15)		OUTPUT,
@PEDIDO	 		VARCHAR(100)	OUTPUT,
@TIPO			INT				OUTPUT	
AS
BEGIN
	--TAREAS EN CURSO
	IF @TIPO ='1' BEGIN
	
		SELECT	'0' AS [CHECK]
				,P.USUARIO
				,SU.NOMBRE
				,P.PRODUCTO_ID
				,P.NRO_LOTE
				,ISNULL(P.NRO_PARTIDA,DD.NRO_PARTIDA)AS NRO_PARTIDA
				,P.NRO_SERIE
				,P.DESCRIPCION
				,P.CANTIDAD AS QTY_PICK
				,P.POSICION_COD
				,P.FECHA_INICIO
				,P.PALLET_PICKING
				,P.TIPO_CAJA
				,P.RUTA
				,P.PROP1 AS PALLET_PICK
				,SALTO_PICKING
				,PICKING_ID
				,DD.PROP2
				,DD.NRO_BULTO
				,D.NRO_REMITO
		FROM	PICKING P (NOLOCK) INNER JOIN DET_DOCUMENTO DD (NOLOCK)
				ON(DD.DOCUMENTO_ID=P.DOCUMENTO_ID AND DD.NRO_LINEA=P.NRO_LINEA)
				INNER JOIN DOCUMENTO D (NOLOCK)
				ON(P.DOCUMENTO_ID=D.DOCUMENTO_ID)
				LEFT JOIN SYS_USUARIO SU (NOLOCK) 
				ON (P.USUARIO_PF=SU.USUARIO_ID)
		WHERE 	P.CLIENTE_ID=@CLIENTE_ID 
				AND D.NRO_REMITO=@PEDIDO
				AND P.BULTOS_CONTROLADOS='1'
				AND P.NRO_UCEMPAQUETADO IS NULL
				
	END --IF

	--TAREAS EN PENDIENTES
	IF @TIPO=2 BEGIN	 
		SELECT	'0' AS [CHECK] 
				,P.PRODUCTO_ID
				,P.NRO_LOTE
				,ISNULL(P.NRO_PARTIDA,DD.NRO_PARTIDA)AS NRO_PARTIDA
				,P.NRO_SERIE
				,P.DESCRIPCION
				,P.CANTIDAD AS QTY_PICK
				,P.POSICION_COD
				,P.TIPO_CAJA
				,P.RUTA
				,P.PROP1 AS PALLET_PICK
				,P.SALTO_PICKING
				,P.PICKING_ID
				,DD.PROP2
				,DD.NRO_BULTO
		FROM	PICKING P(NOLOCK) INNER JOIN DET_DOCUMENTO DD (NOLOCK)
				ON(P.DOCUMENTO_ID=DD.DOCUMENTO_ID AND P.NRO_LINEA=DD.NRO_LINEA)
				INNER JOIN DOCUMENTO D (NOLOCK)
				ON(P.DOCUMENTO_ID=D.DOCUMENTO_ID)
		WHERE 	P.CLIENTE_ID=@CLIENTE_ID 
				AND D.NRO_REMITO=@PEDIDO
				AND ISNULL(P.BULTOS_CONTROLADOS,'0')='0'
				
	END --IF

	--TAREAS FINALIZADAS
	IF @TIPO=3 BEGIN	 
		SELECT 	'0' AS [CHECK] 
				,P.USUARIO
				,SU.NOMBRE	
				,P.PRODUCTO_ID
				,P.NRO_LOTE
				,ISNULL(P.NRO_PARTIDA,DD.NRO_PARTIDA)AS NRO_PARTIDA
				,P.NRO_SERIE
				,P.DESCRIPCION
				,P.POSICION_COD	
				,P.CANTIDAD
				,P.CANT_CONFIRMADA
				,P.CANT_CONFIRMADA-P.CANTIDAD AS DIF
				,P.FECHA_INICIO
				,P.FECHA_FIN
				,P.PALLET_PICKING
				,P.TIPO_CAJA
				,P.RUTA
				,P.PROP1 AS PALLET_PICK
				,P.SALTO_PICKING
				,PICKING_ID
				,DD.PROP2
				,DD.NRO_BULTO
		FROM	PICKING P (NOLOCK)INNER JOIN DET_DOCUMENTO DD
				ON(P.DOCUMENTO_ID=DD.DOCUMENTO_ID AND P.NRO_LINEA=DD.NRO_LINEA)
				INNER JOIN SYS_USUARIO SU (NOLOCK) 
				ON(P.USUARIO_PF=SU.USUARIO_ID)	
				INNER JOIN DOCUMENTO D (NOLOCK)
				ON(P.DOCUMENTO_ID=D.DOCUMENTO_ID)
		WHERE 	P.CLIENTE_ID=@CLIENTE_ID 
				AND D.NRO_REMITO=@PEDIDO
				AND P.NRO_UCEMPAQUETADO IS NOT NULL
	END --IF

END