IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[MOB_EMPAQUE_GET_CONTENEDORAS]') AND type in (N'P', N'PC'))
DROP PROCEDURE [dbo].[MOB_EMPAQUE_GET_CONTENEDORAS]
GO

CREATE PROCEDURE DBO.MOB_EMPAQUE_GET_CONTENEDORAS
	@VIAJE_ID	AS VARCHAR(100)
AS
BEGIN

	SELECT	DISTINCT M.UC_EMPAQUE AS [CONT. EMPAQUE], D.NRO_REMITO AS [NRO. PEDIDO], M.ESTADO
	FROM	PICKING P INNER JOIN DOCUMENTO D		ON(P.DOCUMENTO_ID=D.DOCUMENTO_ID)
			INNER JOIN MOB_EMPAQUE_UC_EMPAQUE M		ON(D.DOCUMENTO_ID=M.DOCUMENTO_ID)
	WHERE	VIAJE_ID=@VIAJE_ID	
	ORDER BY
			D.NRO_REMITO,M.UC_EMPAQUE
	
END	