IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[MOB_GET_PENDIENTES]') AND type in (N'P', N'PC'))
DROP PROCEDURE [dbo].[MOB_GET_PENDIENTES]

GO

CREATE PROCEDURE DBO.MOB_GET_PENDIENTES
	@CLIENTE_ID	VARCHAR(15),
	@VIAJE_ID	VARCHAR(100)
AS
BEGIN	

	SELECT	P.PALLET_PICKING		AS [C.PICKING],
			P.PRODUCTO_ID			AS [COD.PRODUCTO],
			SUM(P.CANT_CONFIRMADA)	AS [CANT.PENDIENTE],
			P.DESCRIPCION			AS [DESCRIPCION]
	FROM	PICKING P(NOLOCK) INNER JOIN DET_DOCUMENTO DD (NOLOCK)
			ON(P.DOCUMENTO_ID=DD.DOCUMENTO_ID AND P.NRO_LINEA=DD.NRO_LINEA)
			INNER JOIN DOCUMENTO D (NOLOCK)
			ON(P.DOCUMENTO_ID=D.DOCUMENTO_ID)
	WHERE 	P.CLIENTE_ID=@CLIENTE_ID 
			AND P.VIAJE_ID=@VIAJE_ID
			AND ISNULL(P.BULTOS_CONTROLADOS,'0')='0'
			AND P.NRO_UCEMPAQUETADO IS NULL
	GROUP BY
			P.PALLET_PICKING, P.PRODUCTO_ID, P.DESCRIPCION 
	ORDER BY
			P.PALLET_PICKING, P.PRODUCTO_ID 			
END