
/****** Object:  StoredProcedure [dbo].[MOB_REGISTRA_TMP_PRODUCTO_EMPAQUE_2D]    Script Date: 08/26/2015 18:07:53 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[MOB_REGISTRA_TMP_PRODUCTO_EMPAQUE_2D]') AND type in (N'P', N'PC'))
DROP PROCEDURE [dbo].[MOB_REGISTRA_TMP_PRODUCTO_EMPAQUE_2D]
GO



CREATE PROCEDURE [dbo].[MOB_REGISTRA_TMP_PRODUCTO_EMPAQUE_2D]
	@CLIENTE_ID         as varchar(15)		OUTPUT,
	@PEDIDO_ID          as varchar(100)		OUTPUT,
	@PRODUCTO_ID        as varchar(30)		OUTPUT,
    @NRO_CONTENEDORA    as numeric(20)		OUTPUT,
    @CANT_CONTROLADA    as numeric(20,5)	OUTPUT,
	@NRO_LOTE			AS VARCHAR(100)		OUTPUT,
	@NRO_PARTIDA		AS VARCHAR(100)		OUTPUT,
	@DESDE				AS NUMERIC(20,0)	OUTPUT,
	@HASTA				AS NUMERIC(20,0)	OUTPUT,
	@CONTROLA_LP		AS VARCHAR(1)		OUTPUT
AS
BEGIN
	
	SET XACT_ABORT ON

	DECLARE @SERIE_INICIO		AS NUMERIC(20,0)
	DECLARE @E_SERIE			AS NUMERIC(20,0)
	DECLARE @NRO_SERIE			AS VARCHAR(100)
	DECLARE @SERIE_CONFORMADA	AS VARCHAR(100)
	DECLARE @CANT_SERIE			AS NUMERIC(20,0)

	SET @SERIE_INICIO=@DESDE

	SELECT	@CANT_SERIE=COUNT(P.NRO_SERIE)
	FROM	PICKING P
	WHERE	P.CLIENTE_ID=@CLIENTE_ID	
			AND P.PRODUCTO_ID=@PRODUCTO_ID 
			AND EXISTS (SELECT	1
						FROM	DOCUMENTO D
						WHERE	P.DOCUMENTO_ID=D.DOCUMENTO_ID
								AND D.NRO_REMITO=@PEDIDO_ID)

	IF @CANT_SERIE<@CANT_CONTROLADA BEGIN
		RAISERROR('LA CANTIDAD DE SERIES TOMADAS SUPERA A LA CANTIDAD DE SERIES A GUARDAR.',16,1)
		RETURN
	END

	WHILE (@SERIE_INICIO<=@HASTA) BEGIN
		
		
		SET @E_SERIE=0
		SET @SERIE_CONFORMADA=replicate('0', 9 - len(@SERIE_INICIO)) + cast (@SERIE_INICIO as varchar);

		--1.	VALIDO QUE LA SERIE EXISTA EN EL SET DE TRABAJO.
		SELECT	@E_SERIE=COUNT(*)
		FROM	PICKING P
		WHERE	P.CLIENTE_ID=@CLIENTE_ID	
				AND P.PRODUCTO_ID=@PRODUCTO_ID 
				AND P.NRO_SERIE=@SERIE_CONFORMADA
				AND EXISTS (SELECT	1
							FROM	DOCUMENTO D
							WHERE	P.DOCUMENTO_ID=D.DOCUMENTO_ID
									AND D.NRO_REMITO=@PEDIDO_ID)
		IF @E_SERIE=0 BEGIN
			RAISERROR('NO SE TOMO LA SERIE %s DENTRO DE LA OLA.',16,1,@SERIE_CONFORMADA)
			RETURN
		END
		
		--2.	MANDO A CONFIRMAR LA SERIE.
		--begin try
			EXEC [dbo].[MOB_REGISTRA_TMP_PRODUCTO_EMPAQUE]	@CLIENTE_ID,@PEDIDO_ID,@PRODUCTO_ID,@NRO_CONTENEDORA,1,@NRO_LOTE,@NRO_PARTIDA,@SERIE_CONFORMADA, @CONTROLA_LP
		--end try
		--begin catch
		--	EXECUTE usp_GetErrorInfo;
		--	return
		--end catch
		--3.	INCREMENTO EL NUMERO DE SERIE PARA QUE SE GUARDE CORRECTAMENTE.
		SET @SERIE_INICIO = @SERIE_INICIO+1

	END --FIN WHILE
END
GO


