/****** Object:  StoredProcedure [dbo].[MOB_EMP_GET_DESCRIPCION_CANTIDAD_2D]    Script Date: 08/28/2015 16:46:09 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[MOB_EMP_GET_DESCRIPCION_CANTIDAD_2D]') AND type in (N'P', N'PC'))
DROP PROCEDURE [dbo].[MOB_EMP_GET_DESCRIPCION_CANTIDAD_2D]
GO

CREATE PROCEDURE [dbo].[MOB_EMP_GET_DESCRIPCION_CANTIDAD_2D]
	@VIAJE_ID		VARCHAR(100),
	@CLIENTE_ID		VARCHAR(15),
	@PRODUCTO_ID	VARCHAR(30),
	@CONTENEDORAS	VARCHAR(4000),
	@PEDIDO			VARCHAR(100)	OUTPUT,
	@DESCRIPCION	VARCHAR(200)	OUTPUT,
	@CANTIDAD		BIGINT			OUTPUT,
	@SOLICITA_LP	VARCHAR(1)		OUTPUT,
	@LOTE			VARCHAR(100)	OUTPUT,
	@PARTIDA		VARCHAR(100)	OUTPUT,
	@NRO_SERIE		VARCHAR(4000)	OUTPUT,
	@CONT_EMPAQUE	VARCHAR(100)	OUTPUT,
	@USUARIO		VARCHAR(100)	OUTPUT
AS
BEGIN	

	DECLARE @CONT	NUMERIC(20,0)
	DECLARE @EX		NUMERIC(20,0)
	DECLARE @NRO_S	VARCHAR(4000)

	SET @NRO_S=@NRO_SERIE

	SELECT	TOP 1
			@CONT=COUNT(DISTINCT M1.UC_EMPAQUE) 
	FROM	PICKING P INNER JOIN DOCUMENTO D		ON(P.DOCUMENTO_ID=D.DOCUMENTO_ID)			
			INNER JOIN MOB_EMPAQUE_UC_EMPAQUE M1	ON(D.DOCUMENTO_ID=M1.DOCUMENTO_ID AND M1.ESTADO='ABIERTO')
			INNER JOIN CLIENTE_PARAMETROS CP		ON(P.CLIENTE_ID=CP.CLIENTE_ID)
	WHERE	P.VIAJE_ID=@VIAJE_ID
			AND P.CLIENTE_ID=@CLIENTE_ID 
			AND P.PRODUCTO_ID=@PRODUCTO_ID 
			AND P.BULTOS_CONTROLADOS IS NULL
			AND P.NRO_SERIE IN(SELECT STRING FROM dbo.Split(@NRO_SERIE,';'))

	IF @CONT>1 BEGIN
		RAISERROR('No se puede escanear el master pack ya que se guardara en empaques diferentes.',16,1)
		RETURN					
	END
	
	SELECT @EX=COUNT(*)
	FROM	PICKING P
	WHERE	P.CLIENTE_ID=@CLIENTE_ID
			AND P.VIAJE_ID=@VIAJE_ID
			AND P.PRODUCTO_ID=@PRODUCTO_ID

	IF @EX=0 BEGIN					
		RAISERROR('No se encontro el producto %s en la Ola de Picking.',16,1,@PRODUCTO_ID)
		RETURN
	END				
					
	SELECT @CONT=COUNT(*)
	FROM	PICKING P INNER JOIN DBO.SPLIT(@CONTENEDORAS,';') R
			ON(P.PALLET_PICKING=R.STRING)
	WHERE	P.VIAJE_ID=@VIAJE_ID
			AND P.CLIENTE_ID=@CLIENTE_ID
			AND P.PRODUCTO_ID=@PRODUCTO_ID
	GROUP BY
			P.DESCRIPCION	
			
	IF @CONT=0 BEGIN					
		RAISERROR('El producto %s no se encuentra dentro de las contenedoras seleccionadas o no existe en el pedido.',16,1,@PRODUCTO_ID)
		RETURN
	END				
		
	SELECT	TOP 1
			@PEDIDO=D.NRO_REMITO,
			@DESCRIPCION=P.DESCRIPCION,
			@CANTIDAD=SUM(P.CANT_CONFIRMADA),
			@SOLICITA_LP=CP.FLG_EMP_LOTE_PARTIDA,
			@LOTE=CASE CP.FLG_EMP_LOTE_PARTIDA WHEN '1' THEN P.NRO_LOTE ELSE NULL END, 
			@PARTIDA=CASE CP.FLG_EMP_LOTE_PARTIDA WHEN '1' THEN P.NRO_PARTIDA ELSE NULL END, 
			@CONT_EMPAQUE=M1.UC_EMPAQUE, 
			@NRO_SERIE=P.NRO_SERIE
	FROM	PICKING P INNER JOIN DOCUMENTO D		ON(P.DOCUMENTO_ID=D.DOCUMENTO_ID)			
			INNER JOIN MOB_EMPAQUE_UC_EMPAQUE M1	ON(D.DOCUMENTO_ID=M1.DOCUMENTO_ID AND M1.ESTADO='ABIERTO')
			INNER JOIN CLIENTE_PARAMETROS CP		ON(P.CLIENTE_ID=CP.CLIENTE_ID)
	WHERE	P.VIAJE_ID=@VIAJE_ID
			AND P.CLIENTE_ID=@CLIENTE_ID 
			AND P.PRODUCTO_ID=@PRODUCTO_ID 
			AND P.BULTOS_CONTROLADOS IS NULL
			AND P.NRO_SERIE IN(SELECT STRING FROM dbo.Split(@NRO_SERIE,';'))
	GROUP BY
			D.NRO_REMITO,P.DESCRIPCION,CP.FLG_EMP_LOTE_PARTIDA, 
			CASE CP.FLG_EMP_LOTE_PARTIDA WHEN '1' THEN P.NRO_LOTE ELSE NULL END,
			CASE CP.FLG_EMP_LOTE_PARTIDA WHEN '1' THEN P.NRO_PARTIDA ELSE NULL END, 
			M1.UC_EMPAQUE, P.NRO_SERIE

	SET @NRO_SERIE=@NRO_S

	IF @SOLICITA_LP='1' BEGIN			
		UPDATE	PICKING 
		SET		BULTOS_CONTROLADOS=1, USUARIO_PF=@USUARIO
		FROM	PICKING P INNER JOIN DOCUMENTO D		ON(P.DOCUMENTO_ID=D.DOCUMENTO_ID)			
				INNER JOIN MOB_EMPAQUE_UC_EMPAQUE M1	ON(D.DOCUMENTO_ID=M1.DOCUMENTO_ID AND M1.ESTADO='ABIERTO')
				INNER JOIN CLIENTE_PARAMETROS CP		ON(P.CLIENTE_ID=CP.CLIENTE_ID)
		WHERE	P.VIAJE_ID=@VIAJE_ID
				AND P.CLIENTE_ID=@CLIENTE_ID 
				AND P.PRODUCTO_ID=@PRODUCTO_ID 
				AND D.NRO_REMITO =@PEDIDO	
				AND ((@LOTE IS NULL AND P.NRO_LOTE IS NULL)OR(P.NRO_LOTE=@LOTE))
				AND ((@PARTIDA IS NULL AND P.NRO_PARTIDA IS NULL)OR(P.NRO_PARTIDA=@PARTIDA))
				AND P.NRO_SERIE IN(SELECT STRING FROM dbo.Split(@NRO_SERIE,';'))
				
		UPDATE	TMP_EMPAQUE_CONTENEDORA
		SET		BULTOS_CONTROLADOS=1,USUARIO_PF =@USUARIO
		WHERE	VIAJE_ID=@VIAJE_ID
				AND CLIENTE_ID=@CLIENTE_ID 
				AND PRODUCTO_ID=@PRODUCTO_ID 
				AND NRO_REMITO =@PEDIDO	
				AND ((@LOTE IS NULL AND NRO_LOTE IS NULL)OR(NRO_LOTE=@LOTE))
				AND ((@PARTIDA IS NULL AND NRO_PARTIDA IS NULL)OR(NRO_PARTIDA=@PARTIDA))
				AND NRO_SERIE IN(SELECT STRING FROM dbo.Split(@NRO_SERIE,';'))						
	END
	ELSE
	BEGIN
	
		UPDATE	PICKING 
		SET		BULTOS_CONTROLADOS=1, USUARIO_PF=@USUARIO
		FROM	PICKING P INNER JOIN DOCUMENTO D		ON(P.DOCUMENTO_ID=D.DOCUMENTO_ID)			
				INNER JOIN MOB_EMPAQUE_UC_EMPAQUE M1	ON(D.DOCUMENTO_ID=M1.DOCUMENTO_ID AND M1.ESTADO='ABIERTO')
				INNER JOIN CLIENTE_PARAMETROS CP		ON(P.CLIENTE_ID=CP.CLIENTE_ID)
		WHERE	P.VIAJE_ID=@VIAJE_ID
				AND P.CLIENTE_ID=@CLIENTE_ID 
				AND P.PRODUCTO_ID=@PRODUCTO_ID 
				AND D.NRO_REMITO =@PEDIDO	
				AND P.NRO_SERIE IN(SELECT STRING FROM dbo.Split(@NRO_SERIE,';'))

		UPDATE	TMP_EMPAQUE_CONTENEDORA
		SET		BULTOS_CONTROLADOS=1,USUARIO_PF =@USUARIO
		WHERE	VIAJE_ID=@VIAJE_ID
				AND CLIENTE_ID=@CLIENTE_ID 
				AND PRODUCTO_ID=@PRODUCTO_ID 
				AND NRO_REMITO =@PEDIDO	
				AND NRO_SERIE IN(SELECT STRING FROM dbo.Split(@NRO_SERIE,';'))					
	END					
	IF @CANTIDAD IS NULL BEGIN		
	
		SELECT	TOP 1
				@PEDIDO=D.NRO_REMITO,
				@DESCRIPCION=P.DESCRIPCION,
				@CANTIDAD=SUM(P.CANT_CONFIRMADA),
				@SOLICITA_LP=CP.FLG_EMP_LOTE_PARTIDA,
				@LOTE=CASE CP.FLG_EMP_LOTE_PARTIDA WHEN '1' THEN P.NRO_LOTE ELSE NULL END, 
				@PARTIDA=CASE CP.FLG_EMP_LOTE_PARTIDA WHEN '1' THEN P.NRO_PARTIDA ELSE NULL END, 
				@CONT_EMPAQUE=M1.UC_EMPAQUE, 
				@NRO_SERIE=P.NRO_SERIE
		FROM	TMP_EMPAQUE_CONTENEDORA P INNER JOIN DOCUMENTO D		ON(P.DOCUMENTO_ID=D.DOCUMENTO_ID)			
				INNER JOIN MOB_EMPAQUE_UC_EMPAQUE M1	ON(D.DOCUMENTO_ID=M1.DOCUMENTO_ID AND M1.ESTADO='ABIERTO')
				INNER JOIN CLIENTE_PARAMETROS CP		ON(P.CLIENTE_ID=CP.CLIENTE_ID)
		WHERE	P.VIAJE_ID=@VIAJE_ID
				AND P.CLIENTE_ID=@CLIENTE_ID 
				AND P.PRODUCTO_ID=@PRODUCTO_ID 
				AND ISNULL(P.PALLET_CONTROLADO,'0') ='0'
				AND P.NRO_SERIE IN(SELECT STRING FROM dbo.Split(@NRO_SERIE,';'))
		GROUP BY
				D.NRO_REMITO,P.DESCRIPCION,CP.FLG_EMP_LOTE_PARTIDA, 
				CASE CP.FLG_EMP_LOTE_PARTIDA WHEN '1' THEN P.NRO_LOTE ELSE NULL END,
				CASE CP.FLG_EMP_LOTE_PARTIDA WHEN '1' THEN P.NRO_PARTIDA ELSE NULL END, 
				M1.UC_EMPAQUE, P.NRO_SERIE	
							
		IF @CANTIDAD IS NULL BEGIN					
			RAISERROR('El producto %s ya ha sido empaquetado.',16,1,@PRODUCTO_ID)
		END
	END
	
END




GO


