/****** Object:  StoredProcedure [dbo].[MOB_VERIFICAR_EMPAQUE_COMPLETADO]    Script Date: 09/22/2015 12:47:18 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[MOB_VERIFICAR_EMPAQUE_COMPLETADO]') AND type in (N'P', N'PC'))
DROP PROCEDURE [dbo].[MOB_VERIFICAR_EMPAQUE_COMPLETADO]
GO

CREATE PROCEDURE [dbo].[MOB_VERIFICAR_EMPAQUE_COMPLETADO]
(
	 @CLIENTE_ID		VARCHAR(15)		OUTPUT
	,@VIAJE_ID		VARCHAR(100)	OUTPUT
	,@RESULTADO		INT				OUTPUT
)
AS
BEGIN
	DECLARE @CANT_EMPAQUE	AS NUMERIC(20,0)
	DECLARE @CANT_PICKING	AS NUMERIC(20,0)
	DECLARE @CANT_EMP_PIC	AS NUMERIC(20,0)
	DECLARE @RES			AS NUMERIC(20,0)

	/*
	SELECT	@CANT_EMPAQUE=SUM(CANT_CONFIRMADA) 
	FROM	TMP_EMPAQUE_CONTENEDORA 
	WHERE	CLIENTE_ID=@CLIENTE_ID 
			AND VIAJE_ID=@VIAJE_ID 
			AND ISNULL(PALLET_CONTROLADO,'0')='1' 
	*/
	SELECT	@CANT_EMPAQUE=SUM(CANT_CONFIRMADA)
	FROM	TMP_EMPAQUE_CONTENEDORA P
	WHERE	CLIENTE_ID=@CLIENTE_ID 
			AND VIAJE_ID=@VIAJE_ID
			AND ISNULL(PALLET_CONTROLADO,'0')='1' 
			AND EXISTS (	SELECT	1
							FROM	MOB_EMPAQUE_UC_EMPAQUE U
							WHERE	P.PALLET_PICKING=U.UC_EMPAQUE
									AND U.ESTADO='ABIERTO')

	/*
	SELECT	@CANT_EMP_PIC=SUM(CANT_CONFIRMADA) 
	FROM	PICKING 
	WHERE	CLIENTE_ID=@CLIENTE_ID 
			AND VIAJE_ID=@VIAJE_ID 
			AND ISNULL(PALLET_CONTROLADO,'0')='1' 
			*/
	SELECT	@CANT_EMP_PIC=SUM(CANT_CONFIRMADA)
	FROM	PICKING P
	WHERE	VIAJE_ID=@VIAJE_ID
			AND EXISTS (	SELECT	1
							FROM	MOB_EMPAQUE_UC_EMPAQUE U
							WHERE	P.PALLET_PICKING=U.UC_EMPAQUE)

	SET @RES=ISNULL(@CANT_EMPAQUE,0) + ISNULL(@CANT_EMP_PIC,0)

	SELECT @CANT_PICKING=SUM(CANT_CONFIRMADA) FROM PICKING WHERE CLIENTE_ID=@CLIENTE_ID AND VIAJE_ID=@VIAJE_ID

	IF @RES=@CANT_PICKING BEGIN

		SET @RESULTADO='1'

	END	ELSE BEGIN
		
		IF @RES>@CANT_PICKING BEGIN
			SET @RESULTADO='1'
		END ELSE BEGIN
			SET @RESULTADO='0'
		END

	END

END

