/****** Object:  StoredProcedure [dbo].[ACTUALIZA_POS_PICKING_TR_CONT]    Script Date: 09/30/2015 14:47:05 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[ACTUALIZA_POS_PICKING_TR_CONT]') AND type in (N'P', N'PC'))
DROP PROCEDURE [dbo].[ACTUALIZA_POS_PICKING_TR_CONT]
GO

CREATE    PROCEDURE [dbo].[ACTUALIZA_POS_PICKING_TR_CONT]
	@POSICION_O		AS VARCHAR(45),
	@POSICION_D		AS VARCHAR(45),
	@CONTENEDORA	AS VARCHAR(100)
AS
BEGIN
	DECLARE @NAVE_COD 	AS VARCHAR(15)

	SELECT 	@NAVE_COD=N.NAVE_COD
	FROM 	POSICION P INNER JOIN NAVE N
			ON(P.NAVE_ID=N.NAVE_ID)
	WHERE	POSICION_COD=LTRIM(RTRIM(UPPER(@POSICION_D)))

	UPDATE 	PICKING 
	SET		NAVE_COD=ISNULL(@NAVE_COD,@POSICION_D),
			POSICION_COD=@POSICION_D,
			SALTO_PICKING=0
	FROM	PICKING P INNER JOIN DET_DOCUMENTO DD 
			ON(P.DOCUMENTO_ID=DD.DOCUMENTO_ID AND P.NRO_LINEA=DD.NRO_LINEA)			
	WHERE	POSICION_COD=LTRIM(RTRIM(UPPER(@POSICION_O)))
			AND FECHA_FIN IS NULL
			AND CANT_CONFIRMADA IS NULL
			AND DD.NRO_BULTO=LTRIM(RTRIM(UPPER(@CONTENEDORA)))
					
END

GO


