/****** Object:  UserDefinedFunction [dbo].[MOB_TR_VERFICA_PALLET_POSICION_DESTINO]    Script Date: 09/30/2015 14:53:09 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[MOB_TR_VERFICA_PALLET_POSICION_DESTINO]') AND type in (N'FN', N'IF', N'TF', N'FS', N'FT'))
DROP FUNCTION [dbo].[MOB_TR_VERFICA_PALLET_POSICION_DESTINO]
GO

CREATE FUNCTION [dbo].[MOB_TR_VERFICA_PALLET_POSICION_DESTINO](
@POSICION_ORIGEN	VARCHAR(45),
@CONTENEDORA		VARCHAR(100)
)RETURNS SMALLINT
BEGIN

	DECLARE @PRODUCTO_ID	VARCHAR(30),
			@CLIENTE_ID		VARCHAR(15),
			@CONT			BIGINT,
			@RET			SMALLINT
			
	SELECT	@CLIENTE_ID=DD.CLIENTE_ID, @PRODUCTO_ID=DD.PRODUCTO_ID
	FROM	DET_DOCUMENTO DD INNER JOIN DET_DOCUMENTO_TRANSACCION DDT
			ON(DD.DOCUMENTO_ID=DDT.DOCUMENTO_ID AND DD.NRO_LINEA=DDT.NRO_LINEA_DOC)
			INNER JOIN RL_DET_DOC_TRANS_POSICION RL
			ON(DDT.DOC_TRANS_ID=RL.DOC_TRANS_ID AND DDT.NRO_LINEA_TRANS=RL.NRO_LINEA_TRANS)
	WHERE	DD.NRO_BULTO=@CONTENEDORA
	
	SELECT	@CONT=COUNT(RL.RL_ID)
	FROM	DET_DOCUMENTO DD INNER JOIN DET_DOCUMENTO_TRANSACCION DDT
			ON(DD.DOCUMENTO_ID=DDT.DOCUMENTO_ID AND DD.NRO_LINEA=DDT.NRO_LINEA_DOC)
			INNER JOIN RL_DET_DOC_TRANS_POSICION RL
			ON(DDT.DOC_TRANS_ID=RL.DOC_TRANS_ID AND DDT.NRO_LINEA_TRANS=RL.NRO_LINEA_TRANS)
			INNER JOIN POSICION P
			ON(RL.POSICION_ACTUAL=P.POSICION_ID)
	WHERE	DD.CLIENTE_ID=@CLIENTE_ID
			AND DD.PRODUCTO_ID=@PRODUCTO_ID
			AND P.POSICION_COD=@POSICION_ORIGEN
			
	IF @CONT>0 BEGIN
		SET @RET=1
	END ELSE BEGIN
		SET @RET=0
	END
	
	RETURN @RET
END
GO


