/****** Object:  StoredProcedure [dbo].[TR_BULTO_VALIDA_PALLET_CONTENEDORA]    Script Date: 10/05/2015 10:24:50 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[TR_BULTO_VALIDA_PALLET_CONTENEDORA]') AND type in (N'P', N'PC'))
DROP PROCEDURE [dbo].[TR_BULTO_VALIDA_PALLET_CONTENEDORA]
GO

CREATE PROCEDURE [dbo].[TR_BULTO_VALIDA_PALLET_CONTENEDORA]
@POSICION_DESTINO	VARCHAR(45),
@VALOR				VARCHAR(50),
@TIPO				VARCHAR(20),
@CONT				NUMERIC(20,0) OUTPUT
AS
BEGIN

	IF @TIPO='0' BEGIN
		--NRO. DE BULTO.
		SELECT	@CONT=COUNT(DD.NRO_BULTO)
		FROM	DET_DOCUMENTO DD INNER JOIN DET_DOCUMENTO_TRANSACCION DDT 
				ON(DD.DOCUMENTO_ID=DDT.DOCUMENTO_ID AND DD.NRO_LINEA=DDT.NRO_LINEA_DOC)
				INNER JOIN RL_DET_DOC_TRANS_POSICION RL
				ON(DDT.DOC_TRANS_ID=RL.DOC_TRANS_ID AND DDT.NRO_LINEA_TRANS=RL.NRO_LINEA_TRANS)
				LEFT JOIN POSICION P
				ON(RL.POSICION_ACTUAL=P.POSICION_ID)
				LEFT JOIN NAVE N 
				ON(RL.NAVE_ACTUAL=N.NAVE_ID)
		WHERE	((P.POSICION_COD=@POSICION_DESTINO)OR(N.NAVE_COD=@POSICION_DESTINO))
				AND DD.NRO_BULTO=@VALOR 				
			
	END
	
	IF @TIPO='1' BEGIN
		--NRO. DE PALLET.
		SELECT	@CONT=COUNT(DD.PROP1)
		FROM	DET_DOCUMENTO DD INNER JOIN DET_DOCUMENTO_TRANSACCION DDT 
				ON(DD.DOCUMENTO_ID=DDT.DOCUMENTO_ID AND DD.NRO_LINEA=DDT.NRO_LINEA_DOC)
				INNER JOIN RL_DET_DOC_TRANS_POSICION RL
				ON(DDT.DOC_TRANS_ID=RL.DOC_TRANS_ID AND DDT.NRO_LINEA_TRANS=RL.NRO_LINEA_TRANS)
				LEFT JOIN POSICION P
				ON(RL.POSICION_ACTUAL=P.POSICION_ID)
				LEFT JOIN NAVE N 
				ON(RL.NAVE_ACTUAL=N.NAVE_ID)
		WHERE	((P.POSICION_COD=@POSICION_DESTINO)OR(N.NAVE_COD=@POSICION_DESTINO))
				AND DD.PROP1=@VALOR 			
	END

END--FIN PROCEDURE.