CREATE PROCEDURE DBO.AUDITORIA_HIST_TR_CAMBIO_BULTO
	@RL_ID		AS NUMERIC(20,0),
	@USUARIO 	AS VARCHAR(30),
	@SIGNO		AS VARCHAR(1),
	@CANTIDAD	AS NUMERIC(20,5)
AS
BEGIN
	IF @SIGNO='-' BEGIN
		-- NRO DE BULTO.
		INSERT INTO AUDITORIA_HISTORICOS 
		SELECT	11
				,DD.CLIENTE_ID
				,D.NRO_DESPACHO_IMPORTACION
				,NULL
				,DD.DOCUMENTO_ID
				,DD.NRO_LINEA
				,RL.DOC_TRANS_ID
				,RL.NRO_LINEA_TRANS
				,DD.PRODUCTO_ID
				,DD.NRO_SERIE
				,DD.NRO_SERIE_PADRE
				,RL.EST_MERC_ID
				,RL.CAT_LOG_ID
				,DD.NRO_BULTO
				,DD.NRO_LOTE 
				,DD.FECHA_VENCIMIENTO
				,DD.NRO_DESPACHO
				,DD.NRO_PARTIDA
				,DD.UNIDAD_ID
				,DD.PESO 
				,DD.UNIDAD_PESO
				,DD.VOLUMEN 
				,DD.UNIDAD_VOLUMEN
				,DD.BUSC_INDIVIDUAL
				,DD.TIE_IN 
				,DD.NRO_TIE_IN_PADRE
				,DD.NRO_TIE_IN
				,DD.ITEM_OK 
				,RL.CAT_LOG_ID_FINAL
				,DD.MONEDA_ID
				,DD.COSTO
				,DD.PROP1
				,DD.PROP2
				,DD.PROP3
				,DD.LARGO
				,DD.ALTO 
				,DD.ANCHO
				,DD.VOLUMEN_UNITARIO
				,DD.PESO_UNITARIO
				,@CANTIDAD * -1
				,@RL_ID
				,@Usuario
				,HOST_NAME()
				,GETDATE()
				,NULL
				,NULL
				,RL.NAVE_ACTUAL
				,RL.POSICION_ACTUAL
		FROM 	DOCUMENTO D
				INNER JOIN DET_DOCUMENTO DD ON (D.DOCUMENTO_ID = DD.DOCUMENTO_ID)
				INNER JOIN DET_DOCUMENTO_TRANSACCION DDT ON (DD.DOCUMENTO_ID = DDT.DOCUMENTO_ID AND DD.NRO_LINEA = DDT. NRO_LINEA_DOC)
				INNER JOIN RL_DET_DOC_TRANS_POSICION RL ON (DDT.DOC_TRANS_ID = RL.DOC_TRANS_ID AND DDT.NRO_LINEA_TRANS = RL.NRO_LINEA_TRANS)
		WHERE 	RL.RL_ID=@RL_ID
	END
	
	IF @SIGNO='+' BEGIN
		--POSITIVO
		INSERT INTO AUDITORIA_HISTORICOS 
		SELECT	 11
				,DD.CLIENTE_ID
				,D.NRO_DESPACHO_IMPORTACION
				,NULL
				,DD.DOCUMENTO_ID
				,DD.NRO_LINEA
				,RL.DOC_TRANS_ID
				,RL.NRO_LINEA_TRANS
				,DD.PRODUCTO_ID
				,DD.NRO_SERIE
				,DD.NRO_SERIE_PADRE
				,RL.EST_MERC_ID
				,RL.CAT_LOG_ID
				,DD.NRO_BULTO
				,DD.NRO_LOTE 
				,DD.FECHA_VENCIMIENTO
				,DD.NRO_DESPACHO
				,DD.NRO_PARTIDA
				,DD.UNIDAD_ID
				,DD.PESO 
				,DD.UNIDAD_PESO
				,DD.VOLUMEN 
				,DD.UNIDAD_VOLUMEN
				,DD.BUSC_INDIVIDUAL
				,DD.TIE_IN 
				,DD.NRO_TIE_IN_PADRE
				,DD.NRO_TIE_IN
				,DD.ITEM_OK 
				,RL.CAT_LOG_ID_FINAL
				,DD.MONEDA_ID
				,DD.COSTO
				,DD.PROP1
				,DD.PROP2
				,DD.PROP3
				,DD.LARGO
				,DD.ALTO 
				,DD.ANCHO
				,DD.VOLUMEN_UNITARIO
				,DD.PESO_UNITARIO
				,@CANTIDAD
				,@RL_ID
				,@Usuario
				,HOST_NAME()
				,DATEADD(SS,1,GETDATE())
				,NULL
				,NULL
				,RL.NAVE_ACTUAL
				,RL.POSICION_ACTUAL
		FROM 	DOCUMENTO D
				INNER JOIN DET_DOCUMENTO DD ON (D.DOCUMENTO_ID = DD.DOCUMENTO_ID)
				INNER JOIN DET_DOCUMENTO_TRANSACCION DDT ON (DD.DOCUMENTO_ID = DDT.DOCUMENTO_ID AND DD.NRO_LINEA = DDT. NRO_LINEA_DOC)
				INNER JOIN RL_DET_DOC_TRANS_POSICION RL ON (DDT.DOC_TRANS_ID = RL.DOC_TRANS_ID AND DDT.NRO_LINEA_TRANS = RL.NRO_LINEA_TRANS)
		WHERE 	RL.RL_ID=@RL_ID
	END 
END