BEGIN

	SELECT * INTO #ING_OC FROM INGRESO_OC;

	DROP TABLE INGRESO_OC;

	CREATE TABLE [dbo].[INGRESO_OC](
		[ING_ID]			[numeric](20, 0) IDENTITY(1,1) NOT NULL,
		[CLIENTE_ID]		[varchar](15)	NOT NULL,
		[PRODUCTO_ID]		[varchar](30)	NOT NULL,
		[ORDEN_COMPRA]		[varchar](100)	NOT NULL,
		[CANTIDAD]			[numeric](20, 5)NULL,
		[USUARIO]			[varchar](50)	NULL,
		[TERMINAL]			[varchar](100)	NULL,
		[FECHA]				[datetime]		NULL,
		[PROCESADO]			[char](1)		NULL,
		[CANT_CONTENEDORAS] [numeric](20, 5)NULL,
		[NRO_LOTE]			[varchar](100)	NULL,
		[NRO_PARTIDA]		[varchar](100)	NULL,
		[DOC_EXT]			[varchar](100)	NULL
	);

	ALTER TABLE INGRESO_OC 
	ADD CONSTRAINT PK_INGRESO_OC PRIMARY KEY(ING_ID);

	INSERT INTO INGRESO_OC (CLIENTE_ID,PRODUCTO_ID,ORDEN_COMPRA,CANTIDAD,USUARIO,TERMINAL,FECHA,PROCESADO,
							CANT_CONTENEDORAS,NRO_LOTE,NRO_PARTIDA,DOC_EXT)
	SELECT	CLIENTE_ID,PRODUCTO_ID,ORDEN_COMPRA,CANTIDAD,USUARIO,TERMINAL,FECHA,PROCESADO,
			CANT_CONTENEDORAS,NRO_LOTE,NRO_PARTIDA,DOC_EXT
	FROM	#ING_OC;

	DROP TABLE #ING_OC;
END;