INSERT INTO SYS_PARAMETRO_PROCESO VALUES('WARP','GENERAR_SNAPSHOT','TO','soporte@globaltechsa.com.ar');
INSERT INTO SYS_PARAMETRO_PROCESO VALUES('WARP','GENERAR_SNAPSHOT','SUBJECT','Novedades Proceso ');
INSERT INTO SYS_PARAMETRO_PROCESO VALUES('WARP','GENERAR_SNAPSHOT','INSTALACION','DESARROLLO');