/****** Object:  StoredProcedure [dbo].[GENERAR_SNAPSHOT]    Script Date: 03/14/2013 15:43:02 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[RPT_STOCK_VOLUMEN]') AND type in (N'P', N'PC'))
DROP PROCEDURE [dbo].[RPT_STOCK_VOLUMEN]
GO
CREATE PROCEDURE [dbo].[RPT_STOCK_VOLUMEN]
	@FDESDE			DATETIME OUTPUT,
	@FHASTA			DATETIME OUTPUT,
	@CLIENTE_ID		VARCHAR(15)OUTPUT,
	@NAVE_ID		NUMERIC(20,0)OUTPUT
AS
BEGIN
	SELECT  DISTINCT  
			 CONVERT(VARCHAR,SE.F_SNAP,103)		AS FECHA
			,C.RAZON_SOCIAL						AS CLIENTE
			,N.NAVE_COD							AS NAVE_COD
			,QPOS.CTN							AS Q_POS_OCUPADAS
			,QVOL.VOL_POS						AS Q_VOL_POSICIONES
			,PVOL.PVOL							AS Q_VOL_PROD
			,(QVOL.VOL_POS - PVOL.PVOL)			AS Q_VOL_DISP_M3
			,GETDATE()							AS F_IMP
			,HOST_NAME()						AS TERMINAL
	FROM    SNAP_EXISTENCIAS SE INNER JOIN POSICION P 
			ON(SE.POSICION_ACTUAL=P.POSICION_ID)
			INNER JOIN NAVE N                         
			ON(P.NAVE_ID = N.NAVE_ID)
			INNER JOIN CLIENTE C                      
			ON(SE.CLIENTE_ID=C.CLIENTE_ID)
			-------------------------------------------------------------------------------------------------------------------
			LEFT JOIN ( SELECT  COUNT(DISTINCT S.POSICION_ACTUAL) CTN, S.CLIENTE_ID, S.F_SNAP, P.NAVE_ID
						FROM    SNAP_EXISTENCIAS S INNER JOIN POSICION P ON(S.POSICION_ACTUAL=P.POSICION_ID)
						WHERE   S.DISPONIBLE='1'
						GROUP BY S.CLIENTE_ID, S.F_SNAP,P.NAVE_ID)QPOS    
			ON(SE.CLIENTE_ID=QPOS.CLIENTE_ID AND SE.F_SNAP=QPOS.F_SNAP AND P.NAVE_ID=QPOS.NAVE_ID)
			-------------------------------------------------------------------------------------------------------------------
			LEFT JOIN ( SELECT  Y.CLIENTE_ID,Y.F_SNAP,Y.NAVE_ID,SUM(Y.VOL) AS VOL_POS
						FROM    (	SELECT  DISTINCT P.POSICION_ID,P.NAVE_ID, S.CLIENTE_ID, S.F_SNAP, (ISNULL(P.ALTO,0)*ISNULL(P.ANCHO,0)*ISNULL(P.LARGO,0))/1000000 AS VOL
								  FROM    SNAP_EXISTENCIAS S INNER JOIN POSICION P ON(S.POSICION_ACTUAL=P.POSICION_ID)
								  WHERE   S.DISPONIBLE='1'
								)Y
						GROUP BY Y.CLIENTE_ID,Y.F_SNAP,Y.NAVE_ID
					   )QVOL
	                    
			ON(SE.CLIENTE_ID=QVOL.CLIENTE_ID AND SE.F_SNAP=QVOL.F_SNAP AND P.NAVE_ID=QVOL.NAVE_ID) 
			-------------------------------------------------------------------------------------------------------------------
			LEFT JOIN (  SELECT  F.CLIENTE_ID,F.F_SNAP,F.NAVE_ID,SUM(F.PVOL) AS PVOL
						  FROM    ( SELECT  S.CLIENTE_ID, S.F_SNAP, P.NAVE_ID
											,S.CANTIDAD * ((ISNULL(PR.ALTO,0)*ISNULL(PR.ANCHO,0)*ISNULL(PR.LARGO,0))/1000000) AS PVOL
									FROM    SNAP_EXISTENCIAS S INNER JOIN POSICION P  ON(S.POSICION_ACTUAL=P.POSICION_ID)
											INNER JOIN DET_DOCUMENTO_TRANSACCION DDT  ON(DDT.DOC_TRANS_ID=S.DOC_TRANS_ID AND DDT.NRO_LINEA_TRANS=S.NRO_LINEA_TRANS)
											INNER JOIN DET_DOCUMENTO DD               ON(DDT.DOCUMENTO_ID=DD.DOCUMENTO_ID AND DDT.NRO_LINEA_DOC=DD.NRO_LINEA)
											INNER JOIN PRODUCTO PR                    ON(DD.CLIENTE_ID=PR.CLIENTE_ID AND DD.PRODUCTO_ID=PR.PRODUCTO_ID)
								  )F
						  GROUP BY
								  F.CLIENTE_ID,F.F_SNAP,F.NAVE_ID
					  )PVOL
			ON(SE.CLIENTE_ID=PVOL.CLIENTE_ID AND SE.F_SNAP=PVOL.F_SNAP AND N.NAVE_ID=PVOL.NAVE_ID)
			-------------------------------------------------------------------------------------------------------------------
	WHERE   SE.DISPONIBLE='1'
			AND ((@FDESDE IS NULL)OR(dbo.trunc(SE.F_SNAP) BETWEEN @FDESDE AND @FHASTA))
			AND ((@CLIENTE_ID IS NULL)OR(SE.CLIENTE_ID=@CLIENTE_ID))
			AND ((@NAVE_ID IS NULL)OR(N.NAVE_ID=@NAVE_ID))
	UNION ALL
	SELECT  DISTINCT  
			 CONVERT(VARCHAR,SE.F_SNAP,103)		AS FECHA
			,C.RAZON_SOCIAL						AS CLIENTE
			,N.NAVE_COD							AS NAVE_COD
			,NULL								AS Q_POS_OCUPADAS
			,NULL								AS Q_VOL_POSICIONES_M3
			,PVOL.PVOL							AS Q_VOL_PROD_M3
			,NULL								AS Q_VOL_DISP_M3
			,GETDATE()							AS F_IMP
			,HOST_NAME()						AS TERMINAL			
	FROM    SNAP_EXISTENCIAS SE INNER JOIN NAVE N                         
			ON(SE.NAVE_ACTUAL=N.NAVE_ID)
			INNER JOIN CLIENTE C                      
			ON(SE.CLIENTE_ID=C.CLIENTE_ID)
			-------------------------------------------------------------------------------------------------------------------
			LEFT JOIN ( SELECT  F.CLIENTE_ID,F.F_SNAP,F.NAVE_ID,SUM(F.PVOL) AS PVOL
						FROM    (	SELECT  S.CLIENTE_ID, S.F_SNAP, N.NAVE_ID
											,S.CANTIDAD * ((ISNULL(PR.ALTO,0)*ISNULL(PR.ANCHO,0)*ISNULL(PR.LARGO,0))/1000000) AS PVOL
									FROM    SNAP_EXISTENCIAS S INNER JOIN NAVE N	  ON(S.NAVE_ACTUAL=N.NAVE_ID AND NAVE_TIENE_LAYOUT='0')
											INNER JOIN DET_DOCUMENTO_TRANSACCION DDT  ON(DDT.DOC_TRANS_ID=S.DOC_TRANS_ID AND DDT.NRO_LINEA_TRANS=S.NRO_LINEA_TRANS)
											INNER JOIN DET_DOCUMENTO DD               ON(DDT.DOCUMENTO_ID=DD.DOCUMENTO_ID AND DDT.NRO_LINEA_DOC=DD.NRO_LINEA)
											INNER JOIN PRODUCTO PR                    ON(DD.CLIENTE_ID=PR.CLIENTE_ID AND DD.PRODUCTO_ID=PR.PRODUCTO_ID)
									WHERE	S.DISPONIBLE='1'
								)F
						GROUP BY
							  F.CLIENTE_ID,F.F_SNAP,F.NAVE_ID
					  )PVOL
			ON(SE.CLIENTE_ID=PVOL.CLIENTE_ID AND SE.F_SNAP=PVOL.F_SNAP AND N.NAVE_ID=PVOL.NAVE_ID)
			-------------------------------------------------------------------------------------------------------------------
	WHERE   SE.DISPONIBLE='1'
			AND ((@FDESDE IS NULL)OR(dbo.trunc(SE.F_SNAP) BETWEEN @FDESDE AND @FHASTA))
			AND ((@CLIENTE_ID IS NULL)OR(SE.CLIENTE_ID=@CLIENTE_ID))
			AND ((@NAVE_ID IS NULL)OR(N.NAVE_ID=@NAVE_ID))	
	ORDER BY 1,2,3
END;	