
/****** Object:  StoredProcedure [dbo].[CREATE_CHILD]    Script Date: 01/28/2015 15:05:24 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[CREATE_CHILD]') AND type in (N'P', N'PC'))
DROP PROCEDURE [dbo].[CREATE_CHILD]
GO

CREATE PROCEDURE [dbo].[CREATE_CHILD]
	@VIAJE_ID	AS VARCHAR(100)output
AS
BEGIN
	DECLARE @TIPO_OPERACION VARCHAR(5)
	DECLARE @CANT			AS INT
	DECLARE @TCUR			CURSOR
	DECLARE @VIAJEID		VARCHAR(100)
	DECLARE @PRODUCTO_ID	VARCHAR(30)
	DECLARE @POSICION_COD	VARCHAR(50)
	DECLARE @PALLET			VARCHAR(100)
	DECLARE @RUTA			VARCHAR(100)
	DECLARE @ID				NUMERIC(20,0)	

	SET @TCUR= CURSOR FOR
		SELECT 	SP.VIAJE_ID, SP.PRODUCTO_ID, SP.POSICION_COD, PROP1, RUTA, 
				DBO.GETPICKINGID(SP.VIAJE_ID, SP.PRODUCTO_ID, SP.POSICION_COD, PROP1, RUTA)
		FROM 	PICKING SP
				INNER JOIN PRIORIDAD_VIAJE SPV
				ON(LTRIM(RTRIM(UPPER(SPV.VIAJE_ID)))=LTRIM(RTRIM(UPPER(SP.VIAJE_ID))))
				INNER JOIN PRODUCTO PROD
				ON(PROD.CLIENTE_ID=SP.CLIENTE_ID AND PROD.PRODUCTO_ID=SP.PRODUCTO_ID)
				LEFT JOIN POSICION POS ON(SP.POSICION_COD=POS.POSICION_COD)
		WHERE 	SPV.PRIORIDAD = ( SELECT 	MIN(PRIORIDAD) FROM	PRIORIDAD_VIAJE	WHERE	LTRIM(RTRIM(UPPER(VIAJE_ID)))=LTRIM(RTRIM(UPPER(SP.VIAJE_ID))))								
				AND SP.VIAJE_ID=@VIAJE_ID
				AND	SP.FECHA_INICIO IS NULL
				AND	SP.FECHA_FIN IS NULL			
				AND	SP.USUARIO IS NULL
				AND	SP.CANT_CONFIRMADA IS NULL 
				AND SP.FIN_PICKING <>'2'

		GROUP BY 	
				SP.VIAJE_ID, SP.PROP1, SP.RUTA, SP.DOCUMENTO_ID ,SP.NRO_LINEA	,SP.PRODUCTO_ID,SPV.PRIORIDAD,SP.TIPO_CAJA, POS.ORDEN_PICKING, SP.POSICION_COD
		ORDER BY	SPV.PRIORIDAD ASC,SP.TIPO_CAJA DESC, POS.ORDEN_PICKING, SP.POSICION_COD ASC
	OPEN @TCUR
	FETCH NEXT FROM @TCUR INTO  @VIAJEID,	@PRODUCTO_ID, @POSICION_COD, @PALLET, @RUTA, @ID
	WHILE @@FETCH_STATUS=0
	BEGIN
		EXEC DBO.ACTUALIZA_RELACION_PICKING @VIAJEID, @PRODUCTO_ID, @POSICION_COD, @PALLET, @RUTA, @ID
		FETCH NEXT FROM @TCUR INTO  @VIAJEID,	@PRODUCTO_ID, @POSICION_COD, @PALLET, @RUTA, @ID
	END
	CLOSE @TCUR
	DEALLOCATE @TCUR

END--FIN PROCEDURE.

GO


