
/****** Object:  StoredProcedure [dbo].[Get_PickingForEtiquetas]    Script Date: 01/28/2015 15:06:07 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[Get_PickingForEtiquetas]') AND type in (N'P', N'PC'))
DROP PROCEDURE [dbo].[Get_PickingForEtiquetas]
GO

CREATE                    procedure [dbo].[Get_PickingForEtiquetas]
@VEHICULO_ID	as varchar(20) Output,
@TipoEti		as varchar(1) Output,
@Pedido		as varchar(50) output
As	
Begin
	SET XACT_ABORT ON
	SET NOCOUNT ON

	--DECLARE @VEHICULO_ID		VARCHAR(50)
	DECLARE @MARGH        		NUMERIC(6,2)
	DECLARE @MARGV        		NUMERIC(6,2)
	DECLARE @DISTANCIA    		NUMERIC(6,2)
	DECLARE @QTYXLINEA    		NUMERIC(2,0)
	DECLARE @ALTO         			NUMERIC(6,2)
	DECLARE @ANCHO        		NUMERIC(6,2)
	DECLARE @IMPRESORA    		VARCHAR(50)
	DECLARE @ETIQUETA_ID  		NUMERIC(20, 0)
	DECLARE @PRINTER			VARCHAR(200)

	DECLARE @TCUR				CURSOR
	DECLARE @VIAJEID			VARCHAR(100)
	DECLARE @PRODUCTO_ID		VARCHAR(30)
	DECLARE @POSICION_COD	VARCHAR(50)
	DECLARE @PALLET			VARCHAR(100)
	DECLARE @RUTA				VARCHAR(100)
	DECLARE @ID				NUMERIC(20,0)	

	TRUNCATE TABLE #TEMP_ETIQUETA

	SELECT @PRINTER=PRINTER_ID FROM SYS_PRINTER_DEFAULT_ETIQUETA WHERE TERMINAL_ID =HOST_NAME()
	
	SELECT 	 @MARGH		=MARGH
			,@MARGV		=MARGV
			,@DISTANCIA	=DISTENTREETIQUETAS
			,@QTYXLINEA	=QTYXLINEA
			,@ALTO			=ALTO
			,@ANCHO		=ANCHO
			,@IMPRESORA 	=IMPRESORA
			,@ETIQUETA_ID 	=ETIQUETA_ID
	FROM 	ETIQUETA_PRODUCTO 
	WHERE 	PRODUCTO_ID='ETI_BULTO_EGR'
	
	BEGIN TRANSACTION
	INSERT INTO #TEMP_ETIQUETA
	SELECT 	
			'1'
			,SP.DOCUMENTO_ID
			,SP.NRO_LINEA
			,SP.PRODUCTO_ID
			,SUM(SP.CANTIDAD)
			,SUM(SP.CANTIDAD)
			,SUM(SP.CANTIDAD)
			,@MARGH
			,@MARGV
			,@DISTANCIA
			,@QTYXLINEA
			,@ALTO
			,@ANCHO
			,ISNULL(@PRINTER,@IMPRESORA)
			,@ETIQUETA_ID
	FROM 	PICKING SP
			INNER JOIN PRIORIDAD_VIAJE SPV
			ON(LTRIM(RTRIM(UPPER(SPV.VIAJE_ID)))=LTRIM(RTRIM(UPPER(SP.VIAJE_ID))))
			INNER JOIN PRODUCTO PROD
			ON(PROD.CLIENTE_ID=SP.CLIENTE_ID AND PROD.PRODUCTO_ID=SP.PRODUCTO_ID)
			LEFT JOIN POSICION POS ON(SP.POSICION_COD=POS.POSICION_COD)
	WHERE 	SPV.PRIORIDAD = ( SELECT 	MIN(PRIORIDAD) FROM	PRIORIDAD_VIAJE	WHERE	LTRIM(RTRIM(UPPER(VIAJE_ID)))=LTRIM(RTRIM(UPPER(SP.VIAJE_ID))))								
			AND (DBO.VERIFICA_PALLET_FINAL(SP.POSICION_COD,SP.VIAJE_ID,SP.RUTA, SP.PROP1)=@TipoEti)
			AND SP.VIAJE_ID=@PEDIDO
			AND SP.FIN_PICKING <>'2'
			AND SP.POSICION_COD IN(	SELECT 	POSICION_COD
										FROM 	RL_VEHICULO_POSICION V INNER JOIN POSICION P ON(V.POSICION_ID=P.POSICION_ID)
												INNER JOIN CALLE_NAVE CN ON(P.CALLE_ID=CN.CALLE_ID)
												INNER JOIN NAVE NAV ON(P.NAVE_ID=NAV.NAVE_ID)
										WHERE 	VEHICULO_ID=@VEHICULO_ID 
												AND CN.CALLE_ID IN(SELECT CALLE_ID FROM #TEMP_PARAM_ETI WHERE NAVE_ID IS NULL)
									)
	GROUP BY 	
				SP.DOCUMENTO_ID ,SP.NRO_LINEA	,SP.PRODUCTO_ID,SPV.PRIORIDAD,SP.TIPO_CAJA, POS.ORDEN_PICKING, SP.POSICION_COD
	ORDER BY	SPV.PRIORIDAD ASC,SP.TIPO_CAJA DESC, POS.ORDEN_PICKING DESC, SP.POSICION_COD ASC

	COMMIT TRANSACTION

	--de aca saco la relacion padre - hijo del picking
	SET @TCUR= CURSOR FOR
		SELECT 	SP.VIAJE_ID, SP.PRODUCTO_ID, SP.POSICION_COD, PROP1, RUTA, 
				DBO.GETPICKINGID(SP.VIAJE_ID, SP.PRODUCTO_ID, SP.POSICION_COD, PROP1, RUTA)
		FROM 	PICKING SP
				INNER JOIN PRIORIDAD_VIAJE SPV
				ON(LTRIM(RTRIM(UPPER(SPV.VIAJE_ID)))=LTRIM(RTRIM(UPPER(SP.VIAJE_ID))))
				INNER JOIN PRODUCTO PROD
				ON(PROD.CLIENTE_ID=SP.CLIENTE_ID AND PROD.PRODUCTO_ID=SP.PRODUCTO_ID)
				LEFT JOIN POSICION POS ON(SP.POSICION_COD=POS.POSICION_COD)
		WHERE 	SPV.PRIORIDAD = ( SELECT 	MIN(PRIORIDAD) FROM	PRIORIDAD_VIAJE	WHERE	LTRIM(RTRIM(UPPER(VIAJE_ID)))=LTRIM(RTRIM(UPPER(SP.VIAJE_ID))))								
				AND	SP.FECHA_INICIO IS NULL
				AND	SP.FECHA_FIN IS NULL			
				AND	SP.USUARIO IS NULL
				AND	SP.CANT_CONFIRMADA IS NULL 
				AND SP.VIAJE_ID=@PEDIDO
				/*
				AND SP.NAVE_COD	IN(	SELECT 	NAVE_COD
										FROM 	NAVE N INNER JOIN RL_USUARIO_NAVE RLNU
												ON(N.NAVE_ID=RLNU.NAVE_ID)
										WHERE	N.NAVE_COD=SP.NAVE_COD
										) */
				AND SP.FIN_PICKING <>'2'
				AND SP.POSICION_COD IN(	SELECT 	POSICION_COD
											FROM 	RL_VEHICULO_POSICION V INNER JOIN POSICION P ON(V.POSICION_ID=P.POSICION_ID)
													INNER JOIN CALLE_NAVE CN ON(P.CALLE_ID=CN.CALLE_ID)
													INNER JOIN NAVE NAV ON(P.NAVE_ID=NAV.NAVE_ID)
											WHERE 	VEHICULO_ID=@VEHICULO_ID AND CN.CALLE_ID IN(SELECT CALLE_ID FROM #TEMP_PARAM_ETI WHERE NAVE_ID IS NULL)
										)
		GROUP BY 	
				SP.VIAJE_ID, SP.PROP1, SP.RUTA, SP.DOCUMENTO_ID ,SP.NRO_LINEA	,SP.PRODUCTO_ID,SPV.PRIORIDAD,SP.TIPO_CAJA, POS.ORDEN_PICKING, SP.POSICION_COD
		ORDER BY	SPV.PRIORIDAD ASC,SP.TIPO_CAJA DESC, POS.ORDEN_PICKING, SP.POSICION_COD ASC
	OPEN @TCUR
	FETCH NEXT FROM @TCUR INTO  @VIAJEID,	@PRODUCTO_ID, @POSICION_COD, @PALLET, @RUTA, @ID
	WHILE @@FETCH_STATUS=0
	BEGIN
		EXEC DBO.ACTUALIZA_RELACION_PICKING @VIAJEID, @PRODUCTO_ID, @POSICION_COD, @PALLET, @RUTA, @ID
		FETCH NEXT FROM @TCUR INTO  @VIAJEID,	@PRODUCTO_ID, @POSICION_COD, @PALLET, @RUTA, @ID
	END
	SELECT * FROM #TEMP_ETIQUETA

End

GO


