ALTER TABLE PRODUCTO ADD TRANSF_PICKING VARCHAR(1)

INSERT INTO sys_tabColumns VALUES('PRODUCTO','TRANSF_PICKING',61,'VARCHAR2',	'N',	1,	NULL,	NULL,	1,	NULL)

INSERT INTO SYS_DET_TABLA VALUES('PRODUCTO',	'TRANSF_PICKING',	'Requiere Transf. Picking',	'S',	50,	1)

DELETE FROM sys_tabColumns WHERE TABLE_NAME='PRODUCTO' AND COLUMN_NAME='SUBCODIGO_1'

DELETE FROM SYS_DET_TABLA WHERE TABLA_ID='PRODUCTO' AND CAMPO='SUBCODIGO_1'

UPDATE SYS_DET_TABLA SET VISIBLE='N' WHERE TABLA_ID='CLIENTE_PARAMETROS' AND CAMPO='FLG_PALLET_HOMBRE'