
/****** Object:  Trigger [Trigger_Tipo_Comprobante_Interfaz]    Script Date: 06/06/2014 14:48:57 ******/
IF  EXISTS (SELECT * FROM sys.triggers WHERE object_id = OBJECT_ID(N'[dbo].[Trigger_Tipo_Comprobante_Interfaz]'))
DROP TRIGGER [dbo].[Trigger_Tipo_Comprobante_Interfaz]
GO

CREATE TRIGGER [dbo].[Trigger_Tipo_Comprobante_Interfaz]    
      ON            [dbo].[TIPO_COMPROBANTE]     
   AFTER INSERT  
AS     
    
BEGIN

	DECLARE @TIPO_COMPROBANTE VARCHAR(5)
	DECLARE @DESCRIPCION VARCHAR(50)
	DECLARE @QTY AS NUMERIC(2,0)

	SELECT @TIPO_COMPROBANTE=TIPO_COMPROBANTE_ID, @DESCRIPCION=DESCRIPCION FROM INSERTED
	
	SELECT @QTY=COUNT(*) FROM SYS_INT_TIPO_DOCUMENTO WHERE TIPO_DOCUMENTO_ID = @TIPO_COMPROBANTE
	
	IF (@QTY = 0)
		BEGIN
		INSERT INTO SYS_INT_TIPO_DOCUMENTO (TIPO_DOCUMENTO_ID,DESCRIPCION) 
		VALUES (@TIPO_COMPROBANTE,@DESCRIPCION)
	END

END
GO


