/****** Object:  StoredProcedure [dbo].[INSERT_AGENTE_AT]    Script Date: 06/09/2014 15:18:58 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[INSERT_AGENTE_AT]') AND type in (N'P', N'PC'))
DROP PROCEDURE [dbo].[INSERT_AGENTE_AT]
GO

CREATE PROCEDURE [dbo].[INSERT_AGENTE_AT]
@CLIENTE_ID		VARCHAR(15)	OUTPUT,
@SUCURSAL_ID	VARCHAR(20)	OUTPUT,
@NOMBRE			VARCHAR(50) OUTPUT,
@CALLE			VARCHAR(30)	OUTPUT,
@NUMERO			VARCHAR(5)	OUTPUT,
@LOCALIDAD		VARCHAR(50)	OUTPUT,
@CONTACTO		VARCHAR(50) OUTPUT,
@NRO_DOCUMENTO	VARCHAR(20) OUTPUT
AS
BEGIN
	INSERT INTO SUCURSAL (	CLIENTE_ID, SUCURSAL_ID, NOMBRE, CALLE, NUMERO, LOCALIDAD, TIPO_AGENTE_ID,ACTIVA,
							GENERA_ING_AT,CLIENTE_INTERNO,CONTACTO,NRO_DOCUMENTO)
	VALUES(	LTRIM(RTRIM(UPPER(@CLIENTE_ID))),
			LTRIM(RTRIM(UPPER(@SUCURSAL_ID))),
			LTRIM(RTRIM(UPPER(@NOMBRE))),
			LTRIM(RTRIM(UPPER(@CALLE))),
			LTRIM(RTRIM(UPPER(@NUMERO))),
			LTRIM(RTRIM(UPPER(@LOCALIDAD))),
			'CLIENTE',
			'1',
			'0',
			'0',
			LTRIM(RTRIM(UPPER(@CONTACTO))),
			LTRIM(RTRIM(UPPER(@NRO_DOCUMENTO)))
	)
END


SELECT * FROM SUCURSAL
GO


