
EXEC sp_rename 'SYS_TRADUCTOR.[IDIOMA INGLES]', 'IDIOMA_INGLES', 'COLUMN';

INSERT INTO SYS_DET_TABLA VALUES ('criterio_asig_picking','CLIENTE_ID','CLIENTE','S',15,0)
INSERT INTO SYS_DET_TABLA VALUES ('criterio_asig_picking','PRODUCTO_ID','PRODUCTO','S',30,0)
INSERT INTO SYS_DET_TABLA VALUES ('criterio_asig_picking','PERMITE_CAMBIO','PERMITE CAMBIO','S',1,0)
INSERT INTO SYS_DET_TABLA VALUES ('criterio_asig_picking','FECHA_VTO','FECHA VTO','S',10,0)
INSERT INTO SYS_DET_TABLA VALUES ('criterio_asig_picking','POSICION','POSICION','S',20,0)
INSERT INTO SYS_DET_TABLA VALUES ('criterio_asig_picking','LOTE','LOTE','S',20,0)
INSERT INTO SYS_DET_TABLA VALUES ('criterio_asig_picking','FECHA_ING','FECHA ING','S',10,0)
INSERT INTO SYS_DET_TABLA VALUES ('criterio_asig_picking','LOTE_PROVEEDOR','LOTE PROVEEDOR','S',10,0)
INSERT INTO SYS_DET_TABLA VALUES ('criterio_asig_picking','NRO_DESPACHO','NRO DESPACHO','S',20,0)
