/****** Object:  UserDefinedFunction [dbo].[GET_CANT_BULTOS]    Script Date: 12/18/2013 16:03:01 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[GET_CANT_BULTOS]') AND type in (N'FN', N'IF', N'TF', N'FS', N'FT'))
DROP FUNCTION [dbo].[GET_CANT_BULTOS]
GO


/****** Object:  UserDefinedFunction [dbo].[GET_CANT_BULTOS]    Script Date: 12/18/2013 16:03:01 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


CREATE   FUNCTION [dbo].[GET_CANT_BULTOS](
	@CLIENTE_ID 	VARCHAR(15),
	@VIAJE_ID		VARCHAR(100)
)RETURNS NUMERIC
AS
BEGIN
	DECLARE @CANT_CAJAS	AS NUMERIC(20,5)
	DECLARE @RETORNO 	AS NUMERIC(20,5)


	SELECT	@CANT_CAJAS = COUNT(DISTINCT (ISNULL(NRO_UCEMPAQUETADO,0)))
	FROM	PICKING P 
				INNER JOIN DOCUMENTO D ON (P.DOCUMENTO_ID = D.DOCUMENTO_ID)			
	WHERE	P.CLIENTE_ID = @CLIENTE_ID AND P.VIAJE_ID =@VIAJE_ID

	IF @CANT_CAJAS = 0 OR @CANT_CAJAS IS NULL 
		BEGIN
			SELECT	@CANT_CAJAS = SUM(ISNULL(CANT_CONFIRMADA,0))
			FROM	PICKING P
						INNER JOIN DOCUMENTO D ON (D.DOCUMENTO_ID = P.DOCUMENTO_ID)						
			WHERE	P.CLIENTE_ID = @CLIENTE_ID AND P.VIAJE_ID =@VIAJE_ID						
		END 
	
	SET @RETORNO = @CANT_CAJAS
	RETURN 	@RETORNO
END




GO


