
/****** Object:  UserDefinedFunction [dbo].[GET_PESO_TOTAL]    Script Date: 12/18/2013 16:03:09 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[GET_PESO_TOTAL]') AND type in (N'FN', N'IF', N'TF', N'FS', N'FT'))
DROP FUNCTION [dbo].[GET_PESO_TOTAL]
GO


/****** Object:  UserDefinedFunction [dbo].[GET_PESO_TOTAL]    Script Date: 12/18/2013 16:03:09 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO



CREATE   FUNCTION [dbo].[GET_PESO_TOTAL](
	@CLIENTE_ID 	VARCHAR(15),
	@VIAJE_ID		VARCHAR(100)
)RETURNS numeric
AS
BEGIN
	DECLARE @CONT001	AS NUMERIC(10,0)
	DECLARE @PESO		AS NUMERIC(20,5)
	DECLARE @RETORNO 	AS NUMERIC(20,5)

	SELECT @PESO = SUM(ISNULL(X.UCEMPAQUETADO_PESO,0))
	FROM
		(SELECT	distinct(NRO_UCEMPAQUETADO), UCEMPAQUETADO_PESO
		FROM	PICKING P 
					INNER JOIN DOCUMENTO D ON (P.DOCUMENTO_ID = D.DOCUMENTO_ID)					
		WHERE	P.CLIENTE_ID = @CLIENTE_ID AND P.VIAJE_ID =@VIAJE_ID) AS X
		
	IF @PESO = 0 OR @PESO IS NULL 
		BEGIN		
			SELECT	@PESO = SUM(P.CANT_CONFIRMADA * ISNULL(PESO,0))
			FROM	PICKING P
						INNER JOIN DOCUMENTO D ON (D.DOCUMENTO_ID = P.DOCUMENTO_ID)
						INNER JOIN PRODUCTO PROD ON (P.CLIENTE_ID = PROD.CLIENTE_ID AND P.PRODUCTO_ID = PROD.PRODUCTO_ID)
			WHERE	P.CLIENTE_ID = @CLIENTE_ID AND P.VIAJE_ID =@VIAJE_ID						
		END 

	SET @RETORNO = @PESO
	RETURN 	@RETORNO
END


GO


