/****** Object:  StoredProcedure [dbo].[Frontera_GetPedidoporguia]    Script Date: 02/04/2014 16:04:07 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[Frontera_GetPedidoporguia]') AND type in (N'P', N'PC'))
DROP PROCEDURE [dbo].[Frontera_GetPedidoporguia]
GO

/****** Object:  StoredProcedure [dbo].[Frontera_GetPedidoporguia]    Script Date: 02/04/2014 16:04:07 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE     PROCEDURE [dbo].[Frontera_GetPedidoporguia]
	
	@GUIA	VARCHAR(100) OUTPUT
	
AS
BEGIN

SELECT	0								AS SELECCIONAR
		,SIDD.DOC_EXT					AS DOCUMENTO
		,SID.AGENTE_ID					AS COD_CLIENTE
		,S.NOMBRE						AS CLIENTE
		,SID.INFO_ADICIONAL_1			AS [GRUPO_PICKING/RUTA]
		,COUNT(DISTINCT DD.PRODUCTO_ID) AS QTY_PROD
		,SID.FECHA_CPTE					AS FECHA 
FROM	UC_EMPAQUE UC 
		INNER JOIN PICKING P 
			ON (P.NRO_UCEMPAQUETADO = UC.UC_EMPAQUE)
		INNER JOIN DET_DOCUMENTO DD 
			ON (P.DOCUMENTO_ID = DD.DOCUMENTO_ID AND DD.NRO_LINEA = P.NRO_LINEA)
		INNER JOIN SYS_INT_DET_DOCUMENTO SIDD 
			ON (SIDD.DOCUMENTO_ID = DD.DOCUMENTO_ID AND SIDD.NRO_LINEA = DD.NRO_LINEA)	
		INNER JOIN SYS_INT_DOCUMENTO SID
			ON (SID.DOC_EXT = SIDD.DOC_EXT AND SID.CLIENTE_ID = DD.CLIENTE_ID)
		INNER JOIN SUCURSAL S 
			ON (SID.AGENTE_ID = S.SUCURSAL_ID AND SID.CLIENTE_ID = S.CLIENTE_ID)
WHERE	NRO_GUIA = @GUIA

GROUP BY SIDD.DOC_EXT,SID.AGENTE_ID,S.NOMBRE,SID.INFO_ADICIONAL_1,SID.FECHA_CPTE

END


GO


