
/****** Object:  StoredProcedure [dbo].[RPT_ESTADISTICA_CLIENTE]    Script Date: 02/06/2014 17:59:59 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[RPT_ESTADISTICA_CLIENTE]') AND type in (N'P', N'PC'))
DROP PROCEDURE [DBO].[RPT_ESTADISTICA_CLIENTE]
GO

/****** Object:  StoredProcedure [dbo].[RPT_ESTADISTICA_CLIENTE]    Script Date: 02/06/2014 17:59:59 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


CREATE PROCEDURE [dbo].[RPT_ESTADISTICA_CLIENTE]
	@CLIENTE_ID		VARCHAR(15)		OUTPUT,
	@FDESDE			VARCHAR(8)		OUTPUT,	--ANSI
	@FHASTA			VARCHAR(8)		OUTPUT	--ANSI		
AS
BEGIN
	

	SELECT	ZZZ.CLIENTE						AS CLIENTE,
			CONVERT(VARCHAR,ZZZ.FECHA,103) 	AS FECHA,
			SUM(ZZZ.Q_POS_OCUPADAS)			AS Q_POS_OCUPADAS,	
			SUM(ZZZ.Q_VOL_PROD)				AS Q_VOL_PROD,
			SUM(ZZZ.QTY_DOC_ING)			AS QTY_DOC_ING,
			SUM(ZZZ.PRODUCTOS_DIST_ING)		AS PRODUCTOS_DIST_ING,
			SUM(ZZZ.VOL_ING)				AS VOL_ING,
			SUM(ZZZ.CANTIDAD_INGRESO)		AS CANTIDAD_INGRESO,
			SUM(ZZZ.QTY_DOC_EGR)			AS QTY_DOC_EGR,
			SUM(ZZZ.PRODUCTOS_DIST_EGR)		AS PRODUCTOS_DIST_EGR,
			SUM(ZZZ.VOL_EGR)				AS VOL_EGR,
			SUM(ZZZ.CANTIDAD_EGRESO)		AS CANTIDAD_EGRESO,
			GETDATE()						AS F_IMP,
			HOST_NAME()						AS TERMINAL			
	FROM	(
		
		SELECT  X.CLIENTE				AS CLIENTE,	
				CONVERT(VARCHAR,X.FECHA,103) AS FECHA,											
				0						AS QTY_DOC_ING,
				0						AS PRODUCTOS_DIST_ING,
				0						AS VOL_ING,
				0						AS CANTIDAD_INGRESO,
				0						AS QTY_DOC_EGR,
				0						AS PRODUCTOS_DIST_EGR,
				0						AS VOL_EGR,
				0						AS CANTIDAD_EGRESO,				
				SUM(X.Q_POS_OCUPADAS)	AS Q_POS_OCUPADAS,
				SUM(X.Q_VOL_PROD)		AS Q_VOL_PROD
		FROM
		(SELECT  DISTINCT  
					C.RAZON_SOCIAL						AS CLIENTE
					,CONVERT(VARCHAR,SE.F_SNAP,103)		AS FECHA
					,QPOS.CTN							AS Q_POS_OCUPADAS			
					,PVOL.PVOL							AS Q_VOL_PROD
			FROM    SNAP_EXISTENCIAS SE INNER JOIN POSICION P 
					ON(SE.POSICION_ACTUAL=P.POSICION_ID)
					INNER JOIN NAVE N                         
					ON(P.NAVE_ID = N.NAVE_ID)
					INNER JOIN CLIENTE C                      
					ON(SE.CLIENTE_ID=C.CLIENTE_ID)
					-------------------------------------------------------------------------------------------------------------------
					LEFT JOIN ( SELECT  COUNT(DISTINCT S.POSICION_ACTUAL) CTN, S.CLIENTE_ID, S.F_SNAP, P.NAVE_ID
								FROM    SNAP_EXISTENCIAS S INNER JOIN POSICION P ON(S.POSICION_ACTUAL=P.POSICION_ID)
								WHERE   S.DISPONIBLE='1' 
										AND ((@CLIENTE_ID IS NULL)OR(S.CLIENTE_ID= @CLIENTE_ID))										
								GROUP BY S.CLIENTE_ID, S.F_SNAP,P.NAVE_ID)QPOS    
					ON(SE.CLIENTE_ID=QPOS.CLIENTE_ID AND SE.F_SNAP=QPOS.F_SNAP AND P.NAVE_ID=QPOS.NAVE_ID)
					-------------------------------------------------------------------------------------------------------------------
					LEFT JOIN ( SELECT  Y.CLIENTE_ID,Y.F_SNAP,Y.NAVE_ID,SUM(Y.VOL) AS VOL_POS
								FROM    (	SELECT  DISTINCT P.POSICION_ID,P.NAVE_ID, S.CLIENTE_ID, S.F_SNAP, (ISNULL(P.ALTO,0)*ISNULL(P.ANCHO,0)*ISNULL(P.LARGO,0))/1000000 AS VOL
										  FROM    SNAP_EXISTENCIAS S INNER JOIN POSICION P ON(S.POSICION_ACTUAL=P.POSICION_ID)
										  WHERE   S.DISPONIBLE='1' 
										  AND ((@CLIENTE_ID IS NULL)OR(S.CLIENTE_ID= @CLIENTE_ID))
										)Y
								GROUP BY Y.CLIENTE_ID,Y.F_SNAP,Y.NAVE_ID
							   )QVOL
			                    
					ON(SE.CLIENTE_ID=QVOL.CLIENTE_ID AND SE.F_SNAP=QVOL.F_SNAP AND P.NAVE_ID=QVOL.NAVE_ID) 
					-------------------------------------------------------------------------------------------------------------------
					LEFT JOIN (  SELECT  F.CLIENTE_ID,F.F_SNAP,F.NAVE_ID,SUM(F.PVOL) AS PVOL
								  FROM    ( SELECT  S.CLIENTE_ID, S.F_SNAP, P.NAVE_ID
													,S.CANTIDAD * ((ISNULL(PR.ALTO,0)*ISNULL(PR.ANCHO,0)*ISNULL(PR.LARGO,0))/1000000) AS PVOL
											FROM    SNAP_EXISTENCIAS S INNER JOIN POSICION P  ON(S.POSICION_ACTUAL=P.POSICION_ID)
													INNER JOIN DET_DOCUMENTO_TRANSACCION DDT  ON(DDT.DOC_TRANS_ID=S.DOC_TRANS_ID AND DDT.NRO_LINEA_TRANS=S.NRO_LINEA_TRANS)
													INNER JOIN DET_DOCUMENTO DD               ON(DDT.DOCUMENTO_ID=DD.DOCUMENTO_ID AND DDT.NRO_LINEA_DOC=DD.NRO_LINEA)
													INNER JOIN PRODUCTO PR                    ON(DD.CLIENTE_ID=PR.CLIENTE_ID AND DD.PRODUCTO_ID=PR.PRODUCTO_ID)
											WHERE	NAVE_ACTUAL NOT IN (1,2) 
													AND ((@CLIENTE_ID IS NULL)OR(S.CLIENTE_ID= @CLIENTE_ID))																								
										  )F
								  GROUP BY
										  F.CLIENTE_ID,F.F_SNAP,F.NAVE_ID
							  )PVOL
					ON(SE.CLIENTE_ID=PVOL.CLIENTE_ID AND SE.F_SNAP=PVOL.F_SNAP AND N.NAVE_ID=PVOL.NAVE_ID)
					-------------------------------------------------------------------------------------------------------------------
			WHERE   SE.DISPONIBLE='1'											
					AND ((@CLIENTE_ID IS NULL)OR(SE.CLIENTE_ID= @CLIENTE_ID))			
					AND ((@FDESDE IS NULL)OR(dbo.trunc(SE.F_SNAP) BETWEEN @FDESDE AND @FHASTA))
			
			UNION ALL
			
			SELECT  DISTINCT  
					C.RAZON_SOCIAL						AS CLIENTE
					,CONVERT(VARCHAR,SE.F_SNAP,103)		AS FECHA						
					,0									AS Q_POS_OCUPADAS
					,X2.PVOL								AS Q_VOL_PROD
			FROM    SNAP_EXISTENCIAS SE 
						INNER JOIN CLIENTE C ON(SE.CLIENTE_ID=C.CLIENTE_ID)
					-------------------------------------------------------------------------------------------------------------------
						LEFT JOIN (
								SELECT	X1.CLIENTE_ID, X1.F_SNAP, X1.POSICION_ACTUAL, SUM(X1.PVOL) AS PVOL
								FROM	(SELECT	--DISTINCT
												S.CLIENTE_ID, 
												S.F_SNAP,
												S.POSICION_ACTUAL, 
												S.CANTIDAD * ((ISNULL(PR.ALTO,0)*ISNULL(PR.ANCHO,0)*ISNULL(PR.LARGO,0))/1000000) AS PVOL
										FROM	SNAP_EXISTENCIAS S
												INNER JOIN POSICION P ON (S.POSICION_ACTUAL = P.POSICION_ID)
												INNER JOIN DET_DOCUMENTO_TRANSACCION DDT  ON(DDT.DOC_TRANS_ID=S.DOC_TRANS_ID AND DDT.NRO_LINEA_TRANS=S.NRO_LINEA_TRANS)
												INNER JOIN DET_DOCUMENTO DD               ON(DDT.DOCUMENTO_ID=DD.DOCUMENTO_ID AND DDT.NRO_LINEA_DOC=DD.NRO_LINEA)
												INNER JOIN PRODUCTO PR                    ON(DD.CLIENTE_ID=PR.CLIENTE_ID AND DD.PRODUCTO_ID=PR.PRODUCTO_ID)
										WHERE	S.DISPONIBLE = '1'
												AND ((@CLIENTE_ID IS NULL)OR(S.CLIENTE_ID= @CLIENTE_ID))
												AND ((@FDESDE IS NULL)OR(DBO.TRUNC(S.F_SNAP) BETWEEN @FDESDE AND @FHASTA))													
										) X1
								GROUP BY 
									X1.CLIENTE_ID, X1.F_SNAP, X1.POSICION_ACTUAL
								) X2
						ON(SE.CLIENTE_ID=X2.CLIENTE_ID AND SE.F_SNAP=X2.F_SNAP)
					-------------------------------------------------------------------------------------------------------------------
			WHERE   SE.DISPONIBLE='1'						
					AND ((@CLIENTE_ID IS NULL)OR(SE.CLIENTE_ID= @CLIENTE_ID))
					AND ((@FDESDE IS NULL)OR(DBO.TRUNC(SE.F_SNAP) BETWEEN @FDESDE AND @FHASTA))							
	) X				
	GROUP BY X.FECHA, X.CLIENTE
			
	UNION ALL

	--CANTIDAD DE DOCUMENTOS DE INGRESO.
	SELECT	C.RAZON_SOCIAL AS CLIENTE,
			CONVERT(VARCHAR,D.FECHA_FIN_GTW,103)		AS FECHA,	
			COUNT(D.DOCUMENTO_ID) AS QTY_DOC_ING,
			0 AS PRODUCTOS_DIST_ING,
			0 AS VOL_ING,
			0 AS CANTIDAD_INGRESO,
			0 AS QTY_DOC_EGR,
			0 AS PRODUCTOS_DIST_EGR,
			0 AS VOL_EGR,
			0 AS CANTIDAD_EGRESO,
			0 AS Q_POS_OCUPADAS,
			0 AS Q_VOL_PROD
	FROM	DOCUMENTO D 
			--INNER JOIN DET_DOCUMENTO DD		ON(D.DOCUMENTO_ID=DD.DOCUMENTO_ID)
			--INNER JOIN DET_DOCUMENTO_TRANSACCION DDT	ON(DD.DOCUMENTO_ID=DDT.DOCUMENTO_ID AND DD.NRO_LINEA=DDT.NRO_LINEA_DOC)
			INNER JOIN CLIENTE C						ON(D.CLIENTE_ID = C.CLIENTE_ID)
	WHERE	TIPO_OPERACION_ID='ING'
			AND D.STATUS = 'D40'
			AND ((@CLIENTE_ID IS NULL)OR(D.CLIENTE_ID=@CLIENTE_ID))	
			AND ((@FDESDE IS NULL)OR(D.FECHA_FIN_GTW BETWEEN @FDESDE AND @FHASTA))	
	GROUP BY CONVERT(VARCHAR,D.FECHA_FIN_GTW,103), C.RAZON_SOCIAL

	UNION ALL	
	
	--VOLUMEN INGRESADO.
	SELECT	X.RAZON_SOCIAL AS CLIENTE,
			CONVERT(VARCHAR,x.FECHA_FIN_GTW,103)		AS FECHA,	
			0 AS QTY_DOC_ING,
			COUNT(DISTINCT X.PRODUCTO_ID) AS PRODUCTOS_DIST_ING,
			SUM(X.VOL_ING) AS VOL_ING, 
			SUM(X.CANTIDAD) AS CANTIDAD_INGRESO,
			0 AS QTY_DOC_EGR,
			0 AS PRODUCTOS_DIST_EGR,
			0 AS VOL_EGR,
			0 AS CANTIDAD_EGRESO,
			0 AS Q_POS_OCUPADAS,
			0 AS Q_VOL_PROD				
	FROM	(	SELECT	DD.PRODUCTO_ID, (ISNULL(P.ALTO,0)*ISNULL(P.LARGO,0)*ISNULL(P.ANCHO,0))/1000000 AS VOL_ING,DD.CANTIDAD, D.FECHA_FIN_GTW, C.RAZON_SOCIAL
				FROM	DOCUMENTO D INNER JOIN DET_DOCUMENTO DD		ON(D.DOCUMENTO_ID=DD.DOCUMENTO_ID)
						INNER JOIN DET_DOCUMENTO_TRANSACCION DDT	ON(DD.DOCUMENTO_ID=DDT.DOCUMENTO_ID AND DD.NRO_LINEA=DDT.NRO_LINEA_DOC)
						INNER JOIN PRODUCTO P						ON(DD.CLIENTE_ID=P.CLIENTE_ID AND DD.PRODUCTO_ID=P.PRODUCTO_ID)
						INNER JOIN CLIENTE C						ON(D.CLIENTE_ID = C.CLIENTE_ID)
				WHERE	TIPO_OPERACION_ID='ING'
						AND D.STATUS = 'D40' 
						AND ((@CLIENTE_ID IS NULL)OR(D.CLIENTE_ID=@CLIENTE_ID))	
						AND ((@FDESDE IS NULL)OR(D.FECHA_FIN_GTW BETWEEN @FDESDE AND @FHASTA))						
						)X	
	GROUP BY CONVERT(VARCHAR,x.FECHA_FIN_GTW,103), x.RAZON_SOCIAL
	
	UNION ALL		
					
	--CANTIDAD DE DOCUMENTOS DE EGRESO.
	SELECT	C.RAZON_SOCIAL AS CLIENTE,			
			CONVERT(VARCHAR,D.FECHA_FIN_GTW,103)		AS FECHA,			
			0 AS QTY_DOC_ING,
			0 AS PRODUCTOS_DIST_ING,
			0 AS VOL_ING,
			0 AS CANTIDAD_INGRESO,
			COUNT(D.DOCUMENTO_ID) AS QTY_DOC_EGR,
			0 AS PRODUCTOS_DIST_EGR,
			0 AS VOL_EGR,
			0 AS CANTIDAD_EGRESO,
			0 AS Q_POS_OCUPADAS,
			0 AS Q_VOL_PROD
	FROM	DOCUMENTO D 
			--INNER JOIN DET_DOCUMENTO DD		ON(D.DOCUMENTO_ID=DD.DOCUMENTO_ID)
			--INNER JOIN DET_DOCUMENTO_TRANSACCION DDT	ON(DD.DOCUMENTO_ID=DDT.DOCUMENTO_ID AND DD.NRO_LINEA=DDT.NRO_LINEA_DOC)
			--INNER JOIN PICKING P						ON(P.DOCUMENTO_ID=DD.DOCUMENTO_ID AND P.NRO_LINEA=DD.NRO_LINEA)
			INNER JOIN CLIENTE C						ON(D.CLIENTE_ID = C.CLIENTE_ID)
	WHERE	TIPO_OPERACION_ID='EGR'
			AND D.STATUS = 'D40'
			AND ((@CLIENTE_ID IS NULL)OR(D.CLIENTE_ID=@CLIENTE_ID))				
			AND ((@FDESDE IS NULL)OR(D.FECHA_FIN_GTW BETWEEN @FDESDE AND @FHASTA))									
	GROUP BY CONVERT(VARCHAR,D.FECHA_FIN_GTW,103), C.RAZON_SOCIAL
	
	UNION ALL		
	
	--VOLUMEN EGRESADO.
	SELECT	X.RAZON_SOCIAL AS CLIENTE,			
			CONVERT(VARCHAR,x.FECHA_FIN_GTW,103)		AS FECHA,			
			0 AS QTY_DOC_ING,
			0 AS PRODUCTOS_DIST_ING,
			0 AS VOL_ING, 
			0 AS CANTIDAD_INGRESO,
			0 AS QTY_DOC_EGR,
			COUNT(DISTINCT X.PRODUCTO_ID) AS PRODUCTOS_DIST_EGR,
			SUM(X.VOL_ING) AS VOL_EGR,
			SUM(X.CANTIDAD) AS CANTIDAD_EGRESO,
			0 AS Q_POS_OCUPADAS,
			0 AS Q_VOL_PROD				
	FROM	(	SELECT	DD.PRODUCTO_ID, (ISNULL(P.ALTO,0)*ISNULL(P.LARGO,0)*ISNULL(P.ANCHO,0))/1000000 AS VOL_ING,DD.CANTIDAD, D.FECHA_FIN_GTW, C.RAZON_SOCIAL
				FROM	DOCUMENTO D INNER JOIN DET_DOCUMENTO DD		ON(D.DOCUMENTO_ID=DD.DOCUMENTO_ID)
						INNER JOIN DET_DOCUMENTO_TRANSACCION DDT	ON(DD.DOCUMENTO_ID=DDT.DOCUMENTO_ID AND DD.NRO_LINEA=DDT.NRO_LINEA_DOC)
						INNER JOIN PRODUCTO P						ON(DD.CLIENTE_ID=P.CLIENTE_ID AND DD.PRODUCTO_ID=P.PRODUCTO_ID)
						INNER JOIN PICKING PIC						ON(PIC.DOCUMENTO_ID=DD.DOCUMENTO_ID AND PIC.NRO_LINEA=DD.NRO_LINEA)
						INNER JOIN CLIENTE C						ON(D.CLIENTE_ID = C.CLIENTE_ID)
				WHERE	TIPO_OPERACION_ID='EGR'
						AND D.STATUS = 'D40'
						AND ((@CLIENTE_ID IS NULL)OR(D.CLIENTE_ID=@CLIENTE_ID))	
						AND ((@FDESDE IS NULL)OR(D.FECHA_FIN_GTW BETWEEN @FDESDE AND @FHASTA))						
						)X	
	GROUP BY CONVERT(VARCHAR,x.FECHA_FIN_GTW,103), x.RAZON_SOCIAL
									
) ZZZ				
GROUP BY ZZZ.FECHA, ZZZ.CLIENTE
ORDER BY CONVERT(DATETIME,ZZZ.FECHA,103) ASC

END;












GO


