
/****** Object:  StoredProcedure [dbo].[RPT_OCUP_CLIENTE]    Script Date: 02/06/2014 14:45:07 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[RPT_OCUP_CLIENTE]') AND type in (N'P', N'PC'))
DROP PROCEDURE [dbo].[RPT_OCUP_CLIENTE]
GO


/****** Object:  StoredProcedure [dbo].[RPT_OCUP_CLIENTE]    Script Date: 02/06/2014 14:45:07 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO



CREATE PROCEDURE [dbo].[RPT_OCUP_CLIENTE]
	@CLIENTE_ID		VARCHAR(15)OUTPUT
AS
BEGIN


SELECT	W.CLIENTE AS CLIENTE, 
		W.NAVE AS NAVE,
		W.POSICIONES_OCUPADAS AS POS_OCUPADAS, 
		SUM(W.VOL_00) AS VOL_OCUPADO
FROM	(
		
		SELECT	Q.CLIENTE, Q.NAVE, COUNT(Q.POSICION) AS POSICIONES_OCUPADAS, SUM(Q.VOL_03) AS VOL_00
		FROM	(
					SELECT	Q1.CLIENTE AS CLIENTE, Q1.NAVE AS NAVE, Q1.POSICION AS POSICION , SUM(Q1.VOL_02) AS VOL_03
					FROM	(
						SELECT	C.RAZON_SOCIAL		AS CLIENTE, 						
								N.NAVE_COD			AS NAVE,
								RL.POSICION_ACTUAL	AS POSICION, 				
								RL.CANTIDAD			AS CANT,
								((ISNULL(P.LARGO,0) * ISNULL(P.ALTO,0) * ISNULL(P.ANCHO,0))/1000000) AS VOL_01,
								RL.CANTIDAD * ((ISNULL(P.LARGO,0) * ISNULL(P.ALTO,0) * ISNULL(P.ANCHO,0))/1000000) AS VOL_02
						FROM	RL_DET_DOC_TRANS_POSICION RL
								INNER JOIN DET_DOCUMENTO_TRANSACCION DDT ON (RL.DOC_TRANS_ID = DDT.DOC_TRANS_ID AND RL.NRO_LINEA_TRANS = DDT.NRO_LINEA_TRANS)
								INNER JOIN DET_DOCUMENTO DD ON (DDT.DOCUMENTO_ID = DD.DOCUMENTO_ID AND DDT.NRO_LINEA_DOC = DD.NRO_LINEA)
								INNER JOIN DOCUMENTO D ON (DD.DOCUMENTO_ID = D.DOCUMENTO_ID)
								INNER JOIN PRODUCTO P ON (P.PRODUCTO_ID = DD.PRODUCTO_ID AND P.CLIENTE_ID = DD.CLIENTE_ID)
								INNER JOIN CLIENTE C ON (DD.CLIENTE_ID = C.CLIENTE_ID)
								INNER JOIN POSICION POS ON (RL.POSICION_ACTUAL = POS.POSICION_ID)
								INNER JOIN NAVE N ON (POS.NAVE_ID = N.NAVE_ID)
						WHERE	RL.POSICION_ACTUAL IS NOT NULL 
								AND N.NAVE_TIENE_LAYOUT = 1								
								AND ((@CLIENTE_ID IS NULL)OR(DD.CLIENTE_ID=@CLIENTE_ID))		
							) Q1
					GROUP BY Q1.CLIENTE, Q1.NAVE, Q1.POSICION																				
				) Q			
		GROUP BY Q.CLIENTE, Q.NAVE		
		UNION ALL
		SELECT	Q1.CLIENTE AS CLIENTE, Q1.NAVE AS NAVE, Q1.POSICION AS POSICION , SUM(Q1.VOL_02) AS VOL_03
			FROM	(				
				SELECT	C.RAZON_SOCIAL					AS CLIENTE, 						
						N.NAVE_COD + ' (SIN LAYOUT)'	AS NAVE, 
						0								AS POSICION,
						RL.CANTIDAD						AS CANT,
						((ISNULL(P.LARGO,0) * ISNULL(P.ALTO,0) * ISNULL(P.ANCHO,0))/1000000)				AS VOL_01,
						RL.CANTIDAD * ((ISNULL(P.LARGO,0) * ISNULL(P.ALTO,0) * ISNULL(P.ANCHO,0))/1000000)	AS VOL_02
				FROM RL_DET_DOC_TRANS_POSICION RL
						INNER JOIN DET_DOCUMENTO_TRANSACCION DDT ON (RL.DOC_TRANS_ID = DDT.DOC_TRANS_ID AND RL.NRO_LINEA_TRANS = DDT.NRO_LINEA_TRANS)
						INNER JOIN DET_DOCUMENTO DD ON (DDT.DOCUMENTO_ID = DD.DOCUMENTO_ID AND DDT.NRO_LINEA_DOC = DD.NRO_LINEA)
						INNER JOIN DOCUMENTO D ON (DD.DOCUMENTO_ID = D.DOCUMENTO_ID)
						INNER JOIN PRODUCTO P ON (P.PRODUCTO_ID = DD.PRODUCTO_ID AND P.CLIENTE_ID = DD.CLIENTE_ID)
						INNER JOIN CLIENTE C ON (DD.CLIENTE_ID = C.CLIENTE_ID)
						INNER JOIN NAVE N ON (RL.NAVE_ACTUAL = N.NAVE_ID)
				WHERE	RL.NAVE_ACTUAL IS NOT NULL 
						AND RL.NAVE_ACTUAL NOT IN (1,2)
						AND N.NAVE_TIENE_LAYOUT = 0
						AND ((@CLIENTE_ID IS NULL)OR(DD.CLIENTE_ID=@CLIENTE_ID))									
				) Q1
			GROUP BY Q1.CLIENTE, Q1.NAVE, Q1.POSICION 
		) W
GROUP BY W.CLIENTE, W.NAVE, W.POSICIONES_OCUPADAS


	
END;




GO


