
/****** Object:  UserDefinedFunction [dbo].[GET_SALDO_INICIAL]    Script Date: 02/10/2014 15:29:29 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[GET_SALDO_INICIAL]') AND type in (N'FN', N'IF', N'TF', N'FS', N'FT'))
DROP FUNCTION [dbo].[GET_SALDO_INICIAL]
GO


/****** Object:  UserDefinedFunction [dbo].[GET_SALDO_INICIAL]    Script Date: 02/10/2014 15:29:29 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO




CREATE   FUNCTION [DBO].[GET_SALDO_INICIAL](
	@CLIENTE_ID 	VARCHAR(15),
	@PRODUCTO_ID	VARCHAR(30),
	@FECHA			VARCHAR(8),
	@FECHAD			VARCHAR(8)
)RETURNS FLOAT
AS
BEGIN
	DECLARE @RETORNO 	AS FLOAT
	DECLARE @MINDATE	AS DATETIME

	IF @FECHA IS NULL
	BEGIN
		SET @RETORNO=0
	END
	ELSE
	BEGIN

		SELECT 	@MINDATE=MIN(FECHA) 
		FROM 	PRODUCTO_AGRUPADO_HISTORICO (NOLOCK)
		WHERE 	CLIENTE_ID=@CLIENTE_ID
				AND PRODUCTO_ID=@PRODUCTO_ID
				AND ((@FECHA IS NULL) OR (DBO.TRUNC(FECHA) BETWEEN DBO.TRUNC(@FECHA) AND DBO.TRUNC(DATEADD(DD,1,@FECHAD))))

		SELECT  @RETORNO=CANTIDAD
		FROM	PRODUCTO_AGRUPADO_HISTORICO(NOLOCK)
		WHERE 	CLIENTE_ID=@CLIENTE_ID
				AND PRODUCTO_ID=@PRODUCTO_ID
				AND FECHA=@MINDATE

	END
	RETURN 	@RETORNO
END


GO

