insert into [dbo].[CATEGORIA_STOCK]([CATEG_STOCK_ID],[DESCRIPCION]) values ('INVENTARIO','MERCADERIA ASIGNADA A INVENTARIO')
insert into [dbo].[CATEGORIA_STOCK]([CATEG_STOCK_ID],[DESCRIPCION]) values ('STOCK','MERCADERIA EN STOCK')
insert into [dbo].[CATEGORIA_STOCK]([CATEG_STOCK_ID],[DESCRIPCION]) values ('TRAN_EGR','MERCADERIA EN TRANSITO DE EGRESO')
insert into [dbo].[CATEGORIA_STOCK]([CATEG_STOCK_ID],[DESCRIPCION]) values ('TRAN_ING','MERCADERIA EN TRANSITO DE INGRESO')