insert into [dbo].[PAIS]([PAIS_ID],[DESCRIPCION]) values ('AE','UNITED ARAB EMIRATES (UAE)')
insert into [dbo].[PAIS]([PAIS_ID],[DESCRIPCION]) values ('AR','ARGENTINA')
insert into [dbo].[PAIS]([PAIS_ID],[DESCRIPCION]) values ('BR','BRAZIL')
insert into [dbo].[PAIS]([PAIS_ID],[DESCRIPCION]) values ('CA','CANADA')
insert into [dbo].[PAIS]([PAIS_ID],[DESCRIPCION]) values ('CF','CENTRAL AFRICAN REPUBLIC')
insert into [dbo].[PAIS]([PAIS_ID],[DESCRIPCION]) values ('CH','SWITZERLAND')
insert into [dbo].[PAIS]([PAIS_ID],[DESCRIPCION]) values ('CL','CHILE')
insert into [dbo].[PAIS]([PAIS_ID],[DESCRIPCION]) values ('CO','COLOMBIA')
insert into [dbo].[PAIS]([PAIS_ID],[DESCRIPCION]) values ('CR.','CROACIA')
insert into [dbo].[PAIS]([PAIS_ID],[DESCRIPCION]) values ('CS','CZECH REPUBLIC')
insert into [dbo].[PAIS]([PAIS_ID],[DESCRIPCION]) values ('DE','GERMANY')
insert into [dbo].[PAIS]([PAIS_ID],[DESCRIPCION]) values ('ES','SPAIN')
insert into [dbo].[PAIS]([PAIS_ID],[DESCRIPCION]) values ('FR','FRANCE')
insert into [dbo].[PAIS]([PAIS_ID],[DESCRIPCION]) values ('GB','UNITED KINGDOM')
insert into [dbo].[PAIS]([PAIS_ID],[DESCRIPCION]) values ('GR','GREECE')
insert into [dbo].[PAIS]([PAIS_ID],[DESCRIPCION]) values ('HO','HOLANDA')
insert into [dbo].[PAIS]([PAIS_ID],[DESCRIPCION]) values ('IN','INDIA')
insert into [dbo].[PAIS]([PAIS_ID],[DESCRIPCION]) values ('IT','ITALY')
insert into [dbo].[PAIS]([PAIS_ID],[DESCRIPCION]) values ('JP','JAPAN')
insert into [dbo].[PAIS]([PAIS_ID],[DESCRIPCION]) values ('KR','SOUTH KOREA')
insert into [dbo].[PAIS]([PAIS_ID],[DESCRIPCION]) values ('LB','LEBANON')
insert into [dbo].[PAIS]([PAIS_ID],[DESCRIPCION]) values ('MX','MEXICO')
insert into [dbo].[PAIS]([PAIS_ID],[DESCRIPCION]) values ('NL','NETHERLANDS')
insert into [dbo].[PAIS]([PAIS_ID],[DESCRIPCION]) values ('NZ','NEW ZEALAND')
insert into [dbo].[PAIS]([PAIS_ID],[DESCRIPCION]) values ('PE','PERU')
insert into [dbo].[PAIS]([PAIS_ID],[DESCRIPCION]) values ('PY','PARAGUAY')
insert into [dbo].[PAIS]([PAIS_ID],[DESCRIPCION]) values ('RU','RUSSIA')
insert into [dbo].[PAIS]([PAIS_ID],[DESCRIPCION]) values ('SZ','SWAZILAND')
insert into [dbo].[PAIS]([PAIS_ID],[DESCRIPCION]) values ('TR','TURKEY')
insert into [dbo].[PAIS]([PAIS_ID],[DESCRIPCION]) values ('TW','TAIWAN')
insert into [dbo].[PAIS]([PAIS_ID],[DESCRIPCION]) values ('US','UNITED STATES')
insert into [dbo].[PAIS]([PAIS_ID],[DESCRIPCION]) values ('UY','URUGUAY')
insert into [dbo].[PAIS]([PAIS_ID],[DESCRIPCION]) values ('VE','VENEZUELA')
insert into [dbo].[PAIS]([PAIS_ID],[DESCRIPCION]) values ('ZA','SOUTH AFRICA')