insert into [dbo].[PROVINCIA]([PAIS_ID],[PROVINCIA_ID],[DESCRIPCION]) values ('AE','DUB','DUBAI')
insert into [dbo].[PROVINCIA]([PAIS_ID],[PROVINCIA_ID],[DESCRIPCION]) values ('AR','BA','BUENOS AIRES')
insert into [dbo].[PROVINCIA]([PAIS_ID],[PROVINCIA_ID],[DESCRIPCION]) values ('AR','CA','CALIFORNIA')
insert into [dbo].[PROVINCIA]([PAIS_ID],[PROVINCIA_ID],[DESCRIPCION]) values ('AR','CAT','CATAMARCA')
insert into [dbo].[PROVINCIA]([PAIS_ID],[PROVINCIA_ID],[DESCRIPCION]) values ('AR','CBA','CORDOBA')
insert into [dbo].[PROVINCIA]([PAIS_ID],[PROVINCIA_ID],[DESCRIPCION]) values ('AR','CF','CAPITAL FEDERAL')
insert into [dbo].[PROVINCIA]([PAIS_ID],[PROVINCIA_ID],[DESCRIPCION]) values ('AR','CHA','CHACO')
insert into [dbo].[PROVINCIA]([PAIS_ID],[PROVINCIA_ID],[DESCRIPCION]) values ('AR','CHU','CHUBUT')
insert into [dbo].[PROVINCIA]([PAIS_ID],[PROVINCIA_ID],[DESCRIPCION]) values ('AR','COR','CORRIENTES')
insert into [dbo].[PROVINCIA]([PAIS_ID],[PROVINCIA_ID],[DESCRIPCION]) values ('AR','ER','ENTRE RIOS')
insert into [dbo].[PROVINCIA]([PAIS_ID],[PROVINCIA_ID],[DESCRIPCION]) values ('AR','FOR','FORMOSA')
insert into [dbo].[PROVINCIA]([PAIS_ID],[PROVINCIA_ID],[DESCRIPCION]) values ('AR','JUJ','JUJUY')
insert into [dbo].[PROVINCIA]([PAIS_ID],[PROVINCIA_ID],[DESCRIPCION]) values ('AR','LAP','LA PAMPA')
insert into [dbo].[PROVINCIA]([PAIS_ID],[PROVINCIA_ID],[DESCRIPCION]) values ('AR','LAR','LA RIOJA')
insert into [dbo].[PROVINCIA]([PAIS_ID],[PROVINCIA_ID],[DESCRIPCION]) values ('AR','MIS','MISIONES')
insert into [dbo].[PROVINCIA]([PAIS_ID],[PROVINCIA_ID],[DESCRIPCION]) values ('AR','MZA','MENDOZA')
insert into [dbo].[PROVINCIA]([PAIS_ID],[PROVINCIA_ID],[DESCRIPCION]) values ('AR','NQN','NEUQUEN')
insert into [dbo].[PROVINCIA]([PAIS_ID],[PROVINCIA_ID],[DESCRIPCION]) values ('AR','RNG','RIO NEGRO')
insert into [dbo].[PROVINCIA]([PAIS_ID],[PROVINCIA_ID],[DESCRIPCION]) values ('AR','SAL','SALTA')
insert into [dbo].[PROVINCIA]([PAIS_ID],[PROVINCIA_ID],[DESCRIPCION]) values ('AR','SCR','SANTA CRUZ')
insert into [dbo].[PROVINCIA]([PAIS_ID],[PROVINCIA_ID],[DESCRIPCION]) values ('AR','SES','SANTIAGO DEL ESTERO')
insert into [dbo].[PROVINCIA]([PAIS_ID],[PROVINCIA_ID],[DESCRIPCION]) values ('AR','SFE','SANTA FE')
insert into [dbo].[PROVINCIA]([PAIS_ID],[PROVINCIA_ID],[DESCRIPCION]) values ('AR','SGO','SANTIAGO DE CHILE')
insert into [dbo].[PROVINCIA]([PAIS_ID],[PROVINCIA_ID],[DESCRIPCION]) values ('AR','SJN','SAN JUAN')
insert into [dbo].[PROVINCIA]([PAIS_ID],[PROVINCIA_ID],[DESCRIPCION]) values ('AR','SLU','SAN LUIS')
insert into [dbo].[PROVINCIA]([PAIS_ID],[PROVINCIA_ID],[DESCRIPCION]) values ('AR','TFU','TIERRA DEL FUEGO')
insert into [dbo].[PROVINCIA]([PAIS_ID],[PROVINCIA_ID],[DESCRIPCION]) values ('AR','TUC','TUCUMAN')
insert into [dbo].[PROVINCIA]([PAIS_ID],[PROVINCIA_ID],[DESCRIPCION]) values ('BR','','.')
insert into [dbo].[PROVINCIA]([PAIS_ID],[PROVINCIA_ID],[DESCRIPCION]) values ('BR','CF','CAPITAL FEDERAL')
insert into [dbo].[PROVINCIA]([PAIS_ID],[PROVINCIA_ID],[DESCRIPCION]) values ('BR','MG','CONTAGEM')
insert into [dbo].[PROVINCIA]([PAIS_ID],[PROVINCIA_ID],[DESCRIPCION]) values ('BR','QUA','QUATRO BARRAS')
insert into [dbo].[PROVINCIA]([PAIS_ID],[PROVINCIA_ID],[DESCRIPCION]) values ('BR','RJA','RIO DE JANEIRO')
insert into [dbo].[PROVINCIA]([PAIS_ID],[PROVINCIA_ID],[DESCRIPCION]) values ('BR','SP','SAO PAULO')
insert into [dbo].[PROVINCIA]([PAIS_ID],[PROVINCIA_ID],[DESCRIPCION]) values ('CA','','.')
insert into [dbo].[PROVINCIA]([PAIS_ID],[PROVINCIA_ID],[DESCRIPCION]) values ('CF','','.')
insert into [dbo].[PROVINCIA]([PAIS_ID],[PROVINCIA_ID],[DESCRIPCION]) values ('CH','02','ANTOFAGASTA')
insert into [dbo].[PROVINCIA]([PAIS_ID],[PROVINCIA_ID],[DESCRIPCION]) values ('CH','CF','CAPITAL FEDERAL')
insert into [dbo].[PROVINCIA]([PAIS_ID],[PROVINCIA_ID],[DESCRIPCION]) values ('CH','IX','NOVENA REGION')
insert into [dbo].[PROVINCIA]([PAIS_ID],[PROVINCIA_ID],[DESCRIPCION]) values ('CH','LS','LA SERENA')
insert into [dbo].[PROVINCIA]([PAIS_ID],[PROVINCIA_ID],[DESCRIPCION]) values ('CH','LUG','LUGANO')
insert into [dbo].[PROVINCIA]([PAIS_ID],[PROVINCIA_ID],[DESCRIPCION]) values ('CH','NYN','NYON')
insert into [dbo].[PROVINCIA]([PAIS_ID],[PROVINCIA_ID],[DESCRIPCION]) values ('CH','SA','SANTIAGO')
insert into [dbo].[PROVINCIA]([PAIS_ID],[PROVINCIA_ID],[DESCRIPCION]) values ('CH','VIII','OCTAVA REGION')
insert into [dbo].[PROVINCIA]([PAIS_ID],[PROVINCIA_ID],[DESCRIPCION]) values ('CL','','.')
insert into [dbo].[PROVINCIA]([PAIS_ID],[PROVINCIA_ID],[DESCRIPCION]) values ('CL','CF','CAPITAL FEDERAL')
insert into [dbo].[PROVINCIA]([PAIS_ID],[PROVINCIA_ID],[DESCRIPCION]) values ('CL','PA','PUNTA ARENA')
insert into [dbo].[PROVINCIA]([PAIS_ID],[PROVINCIA_ID],[DESCRIPCION]) values ('CL','SGO','SANTIAGO DE CHILE')
insert into [dbo].[PROVINCIA]([PAIS_ID],[PROVINCIA_ID],[DESCRIPCION]) values ('CO','','.')
insert into [dbo].[PROVINCIA]([PAIS_ID],[PROVINCIA_ID],[DESCRIPCION]) values ('CR.','CRO','CROACIA')
insert into [dbo].[PROVINCIA]([PAIS_ID],[PROVINCIA_ID],[DESCRIPCION]) values ('CS','PRA','PRAGA')
insert into [dbo].[PROVINCIA]([PAIS_ID],[PROVINCIA_ID],[DESCRIPCION]) values ('DE','','.')
insert into [dbo].[PROVINCIA]([PAIS_ID],[PROVINCIA_ID],[DESCRIPCION]) values ('ES','','.')
insert into [dbo].[PROVINCIA]([PAIS_ID],[PROVINCIA_ID],[DESCRIPCION]) values ('ES','ELC','ELCHE')
insert into [dbo].[PROVINCIA]([PAIS_ID],[PROVINCIA_ID],[DESCRIPCION]) values ('ES','MAD','MADRID')
insert into [dbo].[PROVINCIA]([PAIS_ID],[PROVINCIA_ID],[DESCRIPCION]) values ('ES','MAL','MALAGA')
insert into [dbo].[PROVINCIA]([PAIS_ID],[PROVINCIA_ID],[DESCRIPCION]) values ('FR','','.')
insert into [dbo].[PROVINCIA]([PAIS_ID],[PROVINCIA_ID],[DESCRIPCION]) values ('FR','CF','CAPITAL FEDERAL')
insert into [dbo].[PROVINCIA]([PAIS_ID],[PROVINCIA_ID],[DESCRIPCION]) values ('FR','PAR','PARIS')
insert into [dbo].[PROVINCIA]([PAIS_ID],[PROVINCIA_ID],[DESCRIPCION]) values ('FR','VEL','VELIZY')
insert into [dbo].[PROVINCIA]([PAIS_ID],[PROVINCIA_ID],[DESCRIPCION]) values ('GB','','.')
insert into [dbo].[PROVINCIA]([PAIS_ID],[PROVINCIA_ID],[DESCRIPCION]) values ('GB','CF','CAPITAL FEDERAL')
insert into [dbo].[PROVINCIA]([PAIS_ID],[PROVINCIA_ID],[DESCRIPCION]) values ('GB','MID','MIDDLESEX')
insert into [dbo].[PROVINCIA]([PAIS_ID],[PROVINCIA_ID],[DESCRIPCION]) values ('GR','ATH','ATENAS')
insert into [dbo].[PROVINCIA]([PAIS_ID],[PROVINCIA_ID],[DESCRIPCION]) values ('HO','','.')
insert into [dbo].[PROVINCIA]([PAIS_ID],[PROVINCIA_ID],[DESCRIPCION]) values ('IN','MUM','MUMBAI')
insert into [dbo].[PROVINCIA]([PAIS_ID],[PROVINCIA_ID],[DESCRIPCION]) values ('IT','','.')
insert into [dbo].[PROVINCIA]([PAIS_ID],[PROVINCIA_ID],[DESCRIPCION]) values ('IT','ALB','ALBINO (BG)')
insert into [dbo].[PROVINCIA]([PAIS_ID],[PROVINCIA_ID],[DESCRIPCION]) values ('IT','BIE','BIELLA')
insert into [dbo].[PROVINCIA]([PAIS_ID],[PROVINCIA_ID],[DESCRIPCION]) values ('IT','CF','CAPITAL FEDERAL')
insert into [dbo].[PROVINCIA]([PAIS_ID],[PROVINCIA_ID],[DESCRIPCION]) values ('IT','ROM','ROMA')
insert into [dbo].[PROVINCIA]([PAIS_ID],[PROVINCIA_ID],[DESCRIPCION]) values ('IT','SC','')
insert into [dbo].[PROVINCIA]([PAIS_ID],[PROVINCIA_ID],[DESCRIPCION]) values ('JP','JAP','JAPON')
insert into [dbo].[PROVINCIA]([PAIS_ID],[PROVINCIA_ID],[DESCRIPCION]) values ('KR','SEU','SEUL')
insert into [dbo].[PROVINCIA]([PAIS_ID],[PROVINCIA_ID],[DESCRIPCION]) values ('LB','BEI','BEIRUT')
insert into [dbo].[PROVINCIA]([PAIS_ID],[PROVINCIA_ID],[DESCRIPCION]) values ('MX','EXP','CLIENTES DE EXPORTACION')
insert into [dbo].[PROVINCIA]([PAIS_ID],[PROVINCIA_ID],[DESCRIPCION]) values ('MX','MEX','MEXICO')
insert into [dbo].[PROVINCIA]([PAIS_ID],[PROVINCIA_ID],[DESCRIPCION]) values ('NL','CF','CAPITAL FEDERAL')
insert into [dbo].[PROVINCIA]([PAIS_ID],[PROVINCIA_ID],[DESCRIPCION]) values ('NZ','','.')
insert into [dbo].[PROVINCIA]([PAIS_ID],[PROVINCIA_ID],[DESCRIPCION]) values ('PE','LIP','LIMA')
insert into [dbo].[PROVINCIA]([PAIS_ID],[PROVINCIA_ID],[DESCRIPCION]) values ('PE','VAL','VALDIVIESO')
insert into [dbo].[PROVINCIA]([PAIS_ID],[PROVINCIA_ID],[DESCRIPCION]) values ('PY','','.')
insert into [dbo].[PROVINCIA]([PAIS_ID],[PROVINCIA_ID],[DESCRIPCION]) values ('PY','ASP','ASUNCION')
insert into [dbo].[PROVINCIA]([PAIS_ID],[PROVINCIA_ID],[DESCRIPCION]) values ('PY','CF','CAPITAL FEDERAL')
insert into [dbo].[PROVINCIA]([PAIS_ID],[PROVINCIA_ID],[DESCRIPCION]) values ('RU','MCU','MOSCU')
insert into [dbo].[PROVINCIA]([PAIS_ID],[PROVINCIA_ID],[DESCRIPCION]) values ('SZ','BC','')
insert into [dbo].[PROVINCIA]([PAIS_ID],[PROVINCIA_ID],[DESCRIPCION]) values ('SZ','CF','CAPITAL FEDERAL')
insert into [dbo].[PROVINCIA]([PAIS_ID],[PROVINCIA_ID],[DESCRIPCION]) values ('TR','BUR','BURSA')
insert into [dbo].[PROVINCIA]([PAIS_ID],[PROVINCIA_ID],[DESCRIPCION]) values ('TR','EST','ESTAMBUL')
insert into [dbo].[PROVINCIA]([PAIS_ID],[PROVINCIA_ID],[DESCRIPCION]) values ('TW','','.')
insert into [dbo].[PROVINCIA]([PAIS_ID],[PROVINCIA_ID],[DESCRIPCION]) values ('US','','.')
insert into [dbo].[PROVINCIA]([PAIS_ID],[PROVINCIA_ID],[DESCRIPCION]) values ('US','CA','CALIFORNIA')
insert into [dbo].[PROVINCIA]([PAIS_ID],[PROVINCIA_ID],[DESCRIPCION]) values ('US','CF','CAPITAL FEDERAL')
insert into [dbo].[PROVINCIA]([PAIS_ID],[PROVINCIA_ID],[DESCRIPCION]) values ('US','FL','')
insert into [dbo].[PROVINCIA]([PAIS_ID],[PROVINCIA_ID],[DESCRIPCION]) values ('US','FLO','FLORIDA')
insert into [dbo].[PROVINCIA]([PAIS_ID],[PROVINCIA_ID],[DESCRIPCION]) values ('US','IL','')
insert into [dbo].[PROVINCIA]([PAIS_ID],[PROVINCIA_ID],[DESCRIPCION]) values ('US','IN','')
insert into [dbo].[PROVINCIA]([PAIS_ID],[PROVINCIA_ID],[DESCRIPCION]) values ('US','MI','MINEAPOLIS')
insert into [dbo].[PROVINCIA]([PAIS_ID],[PROVINCIA_ID],[DESCRIPCION]) values ('US','MIA','MIAMI')
insert into [dbo].[PROVINCIA]([PAIS_ID],[PROVINCIA_ID],[DESCRIPCION]) values ('US','NJ','NEW JERSEY')
insert into [dbo].[PROVINCIA]([PAIS_ID],[PROVINCIA_ID],[DESCRIPCION]) values ('US','OH','')
insert into [dbo].[PROVINCIA]([PAIS_ID],[PROVINCIA_ID],[DESCRIPCION]) values ('UY','','.')
insert into [dbo].[PROVINCIA]([PAIS_ID],[PROVINCIA_ID],[DESCRIPCION]) values ('UY','BA','BUENOS AIRES')
insert into [dbo].[PROVINCIA]([PAIS_ID],[PROVINCIA_ID],[DESCRIPCION]) values ('UY','CF','CAPITAL FEDERAL')
insert into [dbo].[PROVINCIA]([PAIS_ID],[PROVINCIA_ID],[DESCRIPCION]) values ('UY','MOV','MONTEVIDEO')
insert into [dbo].[PROVINCIA]([PAIS_ID],[PROVINCIA_ID],[DESCRIPCION]) values ('VE','CAR','CARACAS')
insert into [dbo].[PROVINCIA]([PAIS_ID],[PROVINCIA_ID],[DESCRIPCION]) values ('ZA','','.')
insert into [dbo].[PROVINCIA]([PAIS_ID],[PROVINCIA_ID],[DESCRIPCION]) values ('ZA','FRA','FRANKENWALD')