insert into [dbo].[TIPO_MOVIMIENTO]([TIPO_MOVIMIENTO_ID],[DESCRIPCION]) values ('1','Egreso de Unidades - Ingreso de Unidades')
insert into [dbo].[TIPO_MOVIMIENTO]([TIPO_MOVIMIENTO_ID],[DESCRIPCION]) values ('2','Egreso de Unidades - Ingreso de No Unidades Vacia')
insert into [dbo].[TIPO_MOVIMIENTO]([TIPO_MOVIMIENTO_ID],[DESCRIPCION]) values ('3','Egreso de Unidades - Ingreso de No Unidades No Vacia')
insert into [dbo].[TIPO_MOVIMIENTO]([TIPO_MOVIMIENTO_ID],[DESCRIPCION]) values ('4','Egreso de No Unidades Parcial - Ingreso de Unidades')
insert into [dbo].[TIPO_MOVIMIENTO]([TIPO_MOVIMIENTO_ID],[DESCRIPCION]) values ('5','Egreso de No Unidades Parcial - Ingreso de No Unidades Vacia')
insert into [dbo].[TIPO_MOVIMIENTO]([TIPO_MOVIMIENTO_ID],[DESCRIPCION]) values ('6','Egreso de No Unidades Parcial - Ingreso de No Unidades No Vacia')
insert into [dbo].[TIPO_MOVIMIENTO]([TIPO_MOVIMIENTO_ID],[DESCRIPCION]) values ('7','Egreso de No Unidades Total - Ingreso de Unidades')
insert into [dbo].[TIPO_MOVIMIENTO]([TIPO_MOVIMIENTO_ID],[DESCRIPCION]) values ('8','Egreso de No Unidades Total - Ingreso de No Unidades Vacia')
insert into [dbo].[TIPO_MOVIMIENTO]([TIPO_MOVIMIENTO_ID],[DESCRIPCION]) values ('9','Egreso de No Unidades Total - Ingreso de No Unidades No Vacia')