insert into [dbo].[INTERFACES]([INTERFAZ_ID],[DESCRIPCION],[ACTIVO]) values ('CLI','MAESTRO DE CLIENTES','1')
insert into [dbo].[INTERFACES]([INTERFAZ_ID],[DESCRIPCION],[ACTIVO]) values ('PROD','MAESTRO DE PRODUCTOS','1')
insert into [dbo].[INTERFACES]([INTERFAZ_ID],[DESCRIPCION],[ACTIVO]) values ('RL_PROD','RELACION PRODUCTO - POSICION','1')
insert into [dbo].[INTERFACES]([INTERFAZ_ID],[DESCRIPCION],[ACTIVO]) values ('SUC','MAESTRO DE SUCURSALES','1')