insert into [dbo].[PARAMETROS_AUDITORIA]([DESCRIPCION],[AUDITABLE]) values ('Ubicacion de Mercaderia','1')
insert into [dbo].[PARAMETROS_AUDITORIA]([DESCRIPCION],[AUDITABLE]) values ('Historico de Posiciones','1')
insert into [dbo].[PARAMETROS_AUDITORIA]([DESCRIPCION],[AUDITABLE]) values ('Historico de Existencias','1')
insert into [dbo].[PARAMETROS_AUDITORIA]([DESCRIPCION],[AUDITABLE]) values ('Ingresos','1')
insert into [dbo].[PARAMETROS_AUDITORIA]([DESCRIPCION],[AUDITABLE]) values ('Cambio Categoria Logica','1')
insert into [dbo].[PARAMETROS_AUDITORIA]([DESCRIPCION],[AUDITABLE]) values ('Cambio Estado Mercaderia','1')
insert into [dbo].[PARAMETROS_AUDITORIA]([DESCRIPCION],[AUDITABLE]) values ('Cambio Fecha Vencimiento','1')
insert into [dbo].[PARAMETROS_AUDITORIA]([DESCRIPCION],[AUDITABLE]) values ('Cambio Nro. Pallet','1')
insert into [dbo].[PARAMETROS_AUDITORIA]([DESCRIPCION],[AUDITABLE]) values ('Cambio Nro. Lote','1')
insert into [dbo].[PARAMETROS_AUDITORIA]([DESCRIPCION],[AUDITABLE]) values ('Cambio Nro. Lote Proveedor','1')
insert into [dbo].[PARAMETROS_AUDITORIA]([DESCRIPCION],[AUDITABLE]) values ('Cambio Nro. Bulto','1')
insert into [dbo].[PARAMETROS_AUDITORIA]([DESCRIPCION],[AUDITABLE]) values ('Cambio Property 3','1')
insert into [dbo].[PARAMETROS_AUDITORIA]([DESCRIPCION],[AUDITABLE]) values ('Historico Existencias','1')
insert into [dbo].[PARAMETROS_AUDITORIA]([DESCRIPCION],[AUDITABLE]) values ('Transferencias','1')
insert into [dbo].[PARAMETROS_AUDITORIA]([DESCRIPCION],[AUDITABLE]) values ('Ajustes','1')
insert into [dbo].[PARAMETROS_AUDITORIA]([DESCRIPCION],[AUDITABLE]) values ('Egresos','1')
insert into [dbo].[PARAMETROS_AUDITORIA]([DESCRIPCION],[AUDITABLE]) values ('Cambio Nro. Tie-In','1')
insert into [dbo].[PARAMETROS_AUDITORIA]([DESCRIPCION],[AUDITABLE]) values ('Cambio Nro. Tie-In Padre','1')
insert into [dbo].[PARAMETROS_AUDITORIA]([DESCRIPCION],[AUDITABLE]) values ('Repaletizado','1')