insert into [dbo].[SYS_MENU]([MENU_ID],[DESCRIPCION]) values ('ACERCADE','ACERCA DE...')
insert into [dbo].[SYS_MENU]([MENU_ID],[DESCRIPCION]) values ('AJUSTES','AJUSTES')
insert into [dbo].[SYS_MENU]([MENU_ID],[DESCRIPCION]) values ('AYUDA','AYUDA')
insert into [dbo].[SYS_MENU]([MENU_ID],[DESCRIPCION]) values ('CAMBIO_MASIVO.BTNAJUSTARQTY','BOTON AJUSTAR CANTIDADES')
insert into [dbo].[SYS_MENU]([MENU_ID],[DESCRIPCION]) values ('CAMBIO_MASIVO.BTNEXEC','BOTON OPERACIÓN')
insert into [dbo].[SYS_MENU]([MENU_ID],[DESCRIPCION]) values ('CASCADA','CASCADA')
insert into [dbo].[SYS_MENU]([MENU_ID],[DESCRIPCION]) values ('CBO_PROPIEDADES.CHK1','OPCION FECHA VTO.')
insert into [dbo].[SYS_MENU]([MENU_ID],[DESCRIPCION]) values ('CBO_PROPIEDADES.CHK2','OPCION PALLET')
insert into [dbo].[SYS_MENU]([MENU_ID],[DESCRIPCION]) values ('CBO_PROPIEDADES.CHK3','OPCION NRO. LOTE')
insert into [dbo].[SYS_MENU]([MENU_ID],[DESCRIPCION]) values ('CBO_PROPIEDADES.CHK4','OPCION NRO. LOTE PROV.')
insert into [dbo].[SYS_MENU]([MENU_ID],[DESCRIPCION]) values ('CBO_PROPIEDADES.CHK5','OPCION NRO. BULTO')
insert into [dbo].[SYS_MENU]([MENU_ID],[DESCRIPCION]) values ('CBO_PROPIEDADES.CHK6','OPCION PROP3')
insert into [dbo].[SYS_MENU]([MENU_ID],[DESCRIPCION]) values ('ConsolaSQL','CONSOLA SQL')
insert into [dbo].[SYS_MENU]([MENU_ID],[DESCRIPCION]) values ('DEVOLUCION_VIAJE.AGREGAR','BOTON AGREGAR')
insert into [dbo].[SYS_MENU]([MENU_ID],[DESCRIPCION]) values ('DEVOLUCION_VIAJE.CANCELAR','BOTON CANCELAR')
insert into [dbo].[SYS_MENU]([MENU_ID],[DESCRIPCION]) values ('DEVOLUCION_VIAJE.IMPRESORA PREDETERMINADA','BOTON IMPRESORA PREDETERMINADA')
insert into [dbo].[SYS_MENU]([MENU_ID],[DESCRIPCION]) values ('docInterfaz','Carga de Documentos por Interfaz')
insert into [dbo].[SYS_MENU]([MENU_ID],[DESCRIPCION]) values ('ESTACION.PICKING.TF.btnActualizar','BOTON ACTUALIZAR')
insert into [dbo].[SYS_MENU]([MENU_ID],[DESCRIPCION]) values ('ESTACION.PICKING.TF.btnAjustar','BOTON AJUSTAR')
insert into [dbo].[SYS_MENU]([MENU_ID],[DESCRIPCION]) values ('ESTACION.PICKING.TF.btnCancelar','BOTON CANCELAR')
insert into [dbo].[SYS_MENU]([MENU_ID],[DESCRIPCION]) values ('ESTACION.PICKING.TF.btnCantidades','BOTON CANTIDADES')
insert into [dbo].[SYS_MENU]([MENU_ID],[DESCRIPCION]) values ('ESTACION.PICKING.TF.btnRevertir','BOTON REVERTIR')
insert into [dbo].[SYS_MENU]([MENU_ID],[DESCRIPCION]) values ('ESTACION.PICKING.TP.btnActualizar','BOTON ACTUALIZAR')
insert into [dbo].[SYS_MENU]([MENU_ID],[DESCRIPCION]) values ('ESTACION.PICKING.TP.btnAjustar','BOTON AJUSTAR')
insert into [dbo].[SYS_MENU]([MENU_ID],[DESCRIPCION]) values ('ESTACION.PICKING.TP.btnCancelar','BOTON CANCELAR')
insert into [dbo].[SYS_MENU]([MENU_ID],[DESCRIPCION]) values ('ESTACION.PICKING.TP.btnConfSel','BOTON REVERTIR')
insert into [dbo].[SYS_MENU]([MENU_ID],[DESCRIPCION]) values ('ESTACION.PICKINGWAVE.a_Gen.tGenPickingWave','BOTON GENERAR OLA DE PICKING')
insert into [dbo].[SYS_MENU]([MENU_ID],[DESCRIPCION]) values ('ESTACION.PICKINGWAVE.a_Gen.tSalir','BOTON SALIR')
insert into [dbo].[SYS_MENU]([MENU_ID],[DESCRIPCION]) values ('ESTACION.PICKINGWAVE.Gen.tImprimir','BOTON IMPRIMIR OLA DE PICKING DESCONSOLIDADO')
insert into [dbo].[SYS_MENU]([MENU_ID],[DESCRIPCION]) values ('ESTACION.PICKINGWAVE.Gen.TImprimirC','BOTON IMPRIMIR OLA DE PICKING CONSOLIDADO')
insert into [dbo].[SYS_MENU]([MENU_ID],[DESCRIPCION]) values ('ESTACION.PICKINGWAVE.Gen.tSalir','BOTON SALIR')
insert into [dbo].[SYS_MENU]([MENU_ID],[DESCRIPCION]) values ('frmcar','Carga documento pedido')
insert into [dbo].[SYS_MENU]([MENU_ID],[DESCRIPCION]) values ('frmIngEgr','Ingreso por Egreso')
insert into [dbo].[SYS_MENU]([MENU_ID],[DESCRIPCION]) values ('FRONTERA.BUSCADORHISTORICOS.CERRAR','BOTON CERRAR')
insert into [dbo].[SYS_MENU]([MENU_ID],[DESCRIPCION]) values ('FRONTERA.BUSCADORHISTORICOS.CONTROL EXPEDICION','BOTON CONTROL EXPEDICION')
insert into [dbo].[SYS_MENU]([MENU_ID],[DESCRIPCION]) values ('FRONTERA.BUSCADORHISTORICOS.IMPRIMIR VALE','BOTON IMPRIMIR VALE')
insert into [dbo].[SYS_MENU]([MENU_ID],[DESCRIPCION]) values ('FRONTERA.BUSCADORHISTORICOS.PALLET PICKING','BOTON PALLET PICKING')
insert into [dbo].[SYS_MENU]([MENU_ID],[DESCRIPCION]) values ('FRONTERA.BUSCADORHISTORICOS.TAREAS','BOTON TAREAS')
insert into [dbo].[SYS_MENU]([MENU_ID],[DESCRIPCION]) values ('FRONTERA.BUSCADORHISTORICOS.VER DETALLE','BOTON VER DETALLE')
insert into [dbo].[SYS_MENU]([MENU_ID],[DESCRIPCION]) values ('FRONTERA.EGRESO.ACTUALIZAR DATOS','BOTON ACTUALIZAR DATOS')
insert into [dbo].[SYS_MENU]([MENU_ID],[DESCRIPCION]) values ('FRONTERA.EGRESO.CERRAR','BOTON CERRAR')
insert into [dbo].[SYS_MENU]([MENU_ID],[DESCRIPCION]) values ('FRONTERA.EGRESO.PICKEADORES','BOTON PICKEADORES')
insert into [dbo].[SYS_MENU]([MENU_ID],[DESCRIPCION]) values ('FRONTERA.EGRESO.PRIORIDAD','BOTON PRIORIDAD')
insert into [dbo].[SYS_MENU]([MENU_ID],[DESCRIPCION]) values ('FRONTERA.EGRESO.PROCESAR','BOTON PROCESAR')
insert into [dbo].[SYS_MENU]([MENU_ID],[DESCRIPCION]) values ('FRONTERA.EGRESO.VER DETALLE','BOTON VER DETALLE')
insert into [dbo].[SYS_MENU]([MENU_ID],[DESCRIPCION]) values ('FRONTERA.INGRESO.ACTUALIZAR DATOS','BOTON ACTU. DATOS')
insert into [dbo].[SYS_MENU]([MENU_ID],[DESCRIPCION]) values ('FRONTERA.INGRESO.BUSCAR','BOTON BUSCAR')
insert into [dbo].[SYS_MENU]([MENU_ID],[DESCRIPCION]) values ('FRONTERA.INGRESO.CERRAR','BOTON CERRAR')
insert into [dbo].[SYS_MENU]([MENU_ID],[DESCRIPCION]) values ('FRONTERA.INGRESO.ELIMINAR DOCUMENTO','BOTON ELIMINAR DOCUMENTO')
insert into [dbo].[SYS_MENU]([MENU_ID],[DESCRIPCION]) values ('FRONTERA.INGRESO.RECIBIR','BOTON RECIBIR')
insert into [dbo].[SYS_MENU]([MENU_ID],[DESCRIPCION]) values ('FRONTERA.INGRESO.TAREAS','BOTON TAREAS')
insert into [dbo].[SYS_MENU]([MENU_ID],[DESCRIPCION]) values ('FRONTERA.INGRESO.VINCULAR DO','BOTON VINCULAR DO')
insert into [dbo].[SYS_MENU]([MENU_ID],[DESCRIPCION]) values ('FRONTERA.MONITORPOS.LIBERAR_POSICION','LIBERAR POSICION')
insert into [dbo].[SYS_MENU]([MENU_ID],[DESCRIPCION]) values ('FRONTERA.PICKFINALIZADOS.ACTUALIZAR DATOS','BOTON ACTUALIZAR DATOS')
insert into [dbo].[SYS_MENU]([MENU_ID],[DESCRIPCION]) values ('FRONTERA.PICKFINALIZADOS.CERRAR','BOTON CERRAR')
insert into [dbo].[SYS_MENU]([MENU_ID],[DESCRIPCION]) values ('FRONTERA.PICKFINALIZADOS.CERRAR PICKING','BOTON CERRAR PICKING')
insert into [dbo].[SYS_MENU]([MENU_ID],[DESCRIPCION]) values ('FRONTERA.PICKFINALIZADOS.CONTROL EXPEDICION','BOTON CONTROL EXPEDICION')
insert into [dbo].[SYS_MENU]([MENU_ID],[DESCRIPCION]) values ('FRONTERA.PICKFINALIZADOS.IMPRIMIR VALE','BOTON IMPRIMIR VALE')
insert into [dbo].[SYS_MENU]([MENU_ID],[DESCRIPCION]) values ('FRONTERA.PICKFINALIZADOS.PALLET PICKING','BOTON PALLET PICKING')
insert into [dbo].[SYS_MENU]([MENU_ID],[DESCRIPCION]) values ('FRONTERA.PICKFINALIZADOS.TAREAS','BOTON TAREAS')
insert into [dbo].[SYS_MENU]([MENU_ID],[DESCRIPCION]) values ('FRONTERA.PICKFINALIZADOS.VER DETALLE','BOTON VER DETALLE')
insert into [dbo].[SYS_MENU]([MENU_ID],[DESCRIPCION]) values ('FRONTERA.PICKPROCESO.ACTUALIZAR DATOS','BOTON ACTUALIZAR DATOS')
insert into [dbo].[SYS_MENU]([MENU_ID],[DESCRIPCION]) values ('FRONTERA.PICKPROCESO.CERRAR','BOTON CERRAR')
insert into [dbo].[SYS_MENU]([MENU_ID],[DESCRIPCION]) values ('FRONTERA.PICKPROCESO.PALLET PICKING','BOTON PALLET PICKING')
insert into [dbo].[SYS_MENU]([MENU_ID],[DESCRIPCION]) values ('FRONTERA.PICKPROCESO.PICKEADORES','BOTON PICKEADORES')
insert into [dbo].[SYS_MENU]([MENU_ID],[DESCRIPCION]) values ('FRONTERA.PICKPROCESO.PRIORIDAD','BOTON PRIORIDAD')
insert into [dbo].[SYS_MENU]([MENU_ID],[DESCRIPCION]) values ('FRONTERA.PICKPROCESO.TAREAS','BOTON TAREAS')
insert into [dbo].[SYS_MENU]([MENU_ID],[DESCRIPCION]) values ('FRONTERA.PICKPROCESO.VER DETALLE','BOTON VER DETALLE')
insert into [dbo].[SYS_MENU]([MENU_ID],[DESCRIPCION]) values ('HORIZONTAL','ORGANIZAR HORIZONTALMENTE')
insert into [dbo].[SYS_MENU]([MENU_ID],[DESCRIPCION]) values ('ICONOS','ARREGLAR ICONOS')
insert into [dbo].[SYS_MENU]([MENU_ID],[DESCRIPCION]) values ('INGRESOXEGRESO.CANCELAR','BOTON CANCELAR')
insert into [dbo].[SYS_MENU]([MENU_ID],[DESCRIPCION]) values ('INGRESOXEGRESO.DEVOLUCION DE PRODUCTOS','BOTON DEVOLUCION DE PRODUCTOS')
insert into [dbo].[SYS_MENU]([MENU_ID],[DESCRIPCION]) values ('INGRESOXEGRESO.ELIMINAR PRODUCTO','BOTON ELIMINAR PRODUCTO')
insert into [dbo].[SYS_MENU]([MENU_ID],[DESCRIPCION]) values ('INGRESOXEGRESO.IMPRIMIR ETIQUETAS','BOTON IMPRIMIR ETIQUETAS')
insert into [dbo].[SYS_MENU]([MENU_ID],[DESCRIPCION]) values ('INGRESOXEGRESO.PROCESAR DOCUMENTO','BOTON PROCESAR DOCUMENTO')
insert into [dbo].[SYS_MENU]([MENU_ID],[DESCRIPCION]) values ('INVENTARIOS','INVENTARIOS')
insert into [dbo].[SYS_MENU]([MENU_ID],[DESCRIPCION]) values ('LAYOUT','GENERACION DEL LAYOUT')
insert into [dbo].[SYS_MENU]([MENU_ID],[DESCRIPCION]) values ('LISTREP','LISTADO DE REPORTES')
insert into [dbo].[SYS_MENU]([MENU_ID],[DESCRIPCION]) values ('MBASE','Procesamiento Electrónico')
insert into [dbo].[SYS_MENU]([MENU_ID],[DESCRIPCION]) values ('mnConfAuditoria','Configuracion de Auditoria.')
insert into [dbo].[SYS_MENU]([MENU_ID],[DESCRIPCION]) values ('MNCONFINTERFAZ','Configuración de Interfaz')
insert into [dbo].[SYS_MENU]([MENU_ID],[DESCRIPCION]) values ('MNU_PROC_MENSAJES','Listas de Correos para Mensajes de Procesos')
insert into [dbo].[SYS_MENU]([MENU_ID],[DESCRIPCION]) values ('MNU1_1','GEOGRAFICAS')
insert into [dbo].[SYS_MENU]([MENU_ID],[DESCRIPCION]) values ('MNU1_2','DEL CLIENTE')
insert into [dbo].[SYS_MENU]([MENU_ID],[DESCRIPCION]) values ('MNU1_3','DEL PRODUCTO')
insert into [dbo].[SYS_MENU]([MENU_ID],[DESCRIPCION]) values ('MNU1_4','DEL STOCK')
insert into [dbo].[SYS_MENU]([MENU_ID],[DESCRIPCION]) values ('MNU1_5','DEL WAREHOUSE')
insert into [dbo].[SYS_MENU]([MENU_ID],[DESCRIPCION]) values ('MNU1_6','LOCATOR')
insert into [dbo].[SYS_MENU]([MENU_ID],[DESCRIPCION]) values ('MNU1_7','GENERALES')
insert into [dbo].[SYS_MENU]([MENU_ID],[DESCRIPCION]) values ('MNU1_8','OTRAS')
insert into [dbo].[SYS_MENU]([MENU_ID],[DESCRIPCION]) values ('MNU10','ESTADO DE LA MERCADERIA')
insert into [dbo].[SYS_MENU]([MENU_ID],[DESCRIPCION]) values ('MNU12','FAMILIAS DE PRODUCTOS')
insert into [dbo].[SYS_MENU]([MENU_ID],[DESCRIPCION]) values ('MNU14','MOTIVOS')
insert into [dbo].[SYS_MENU]([MENU_ID],[DESCRIPCION]) values ('MNU15','Naves')
insert into [dbo].[SYS_MENU]([MENU_ID],[DESCRIPCION]) values ('MNU16','PAISES')
insert into [dbo].[SYS_MENU]([MENU_ID],[DESCRIPCION]) values ('MNU18','PROVINCIAS')
insert into [dbo].[SYS_MENU]([MENU_ID],[DESCRIPCION]) values ('MNU19','REPORTES')
insert into [dbo].[SYS_MENU]([MENU_ID],[DESCRIPCION]) values ('MNU2','CATEGORIAS CLIENTES')
insert into [dbo].[SYS_MENU]([MENU_ID],[DESCRIPCION]) values ('MNU20','SUCURSALES')
insert into [dbo].[SYS_MENU]([MENU_ID],[DESCRIPCION]) values ('MNU22','TIPOS DE COMPROBANTES')
insert into [dbo].[SYS_MENU]([MENU_ID],[DESCRIPCION]) values ('MNU23','TIPOS DE CONTENEDORAS')
insert into [dbo].[SYS_MENU]([MENU_ID],[DESCRIPCION]) values ('MNU24','CAMPOS MANDATORIOS POR TIPO DOC')
insert into [dbo].[SYS_MENU]([MENU_ID],[DESCRIPCION]) values ('MNU25','TIPOS DE DOCUMENTOS')
insert into [dbo].[SYS_MENU]([MENU_ID],[DESCRIPCION]) values ('MNU26','TIPOS DE INVENTARIO')
insert into [dbo].[SYS_MENU]([MENU_ID],[DESCRIPCION]) values ('MNU27','TIPOS DE OPERACION')
insert into [dbo].[SYS_MENU]([MENU_ID],[DESCRIPCION]) values ('MNU28','TIPOS DE TRANSACCIONES')
insert into [dbo].[SYS_MENU]([MENU_ID],[DESCRIPCION]) values ('MNU29','UNIDADES CONTENEDORAS')
insert into [dbo].[SYS_MENU]([MENU_ID],[DESCRIPCION]) values ('MNU3','CATEGORIAS IMPOSITIVAS')
insert into [dbo].[SYS_MENU]([MENU_ID],[DESCRIPCION]) values ('MNU30','UNIDADES DE MEDIDA')
insert into [dbo].[SYS_MENU]([MENU_ID],[DESCRIPCION]) values ('MNU31','ZONAS')
insert into [dbo].[SYS_MENU]([MENU_ID],[DESCRIPCION]) values ('MNU32','ESTACION')
insert into [dbo].[SYS_MENU]([MENU_ID],[DESCRIPCION]) values ('MNU33','Personal')
insert into [dbo].[SYS_MENU]([MENU_ID],[DESCRIPCION]) values ('MNU34','TIPOS DE PRODUCTOS')
insert into [dbo].[SYS_MENU]([MENU_ID],[DESCRIPCION]) values ('MNU35','CARGA DE DOCUMENTO DEL CLIENTE DE INGRESO')
insert into [dbo].[SYS_MENU]([MENU_ID],[DESCRIPCION]) values ('MNU36','CARGA DE DOCUMENTO DEL CLIENTE DE EGRESO')
insert into [dbo].[SYS_MENU]([MENU_ID],[DESCRIPCION]) values ('MNU37','INTERFAZ DE INGRESOS X EGRESOS ')
insert into [dbo].[SYS_MENU]([MENU_ID],[DESCRIPCION]) values ('MNU38','Transporte')
insert into [dbo].[SYS_MENU]([MENU_ID],[DESCRIPCION]) values ('MNU4','CATEGORIAS LOGICAS')
insert into [dbo].[SYS_MENU]([MENU_ID],[DESCRIPCION]) values ('MNU45','Interfaz Transport')
insert into [dbo].[SYS_MENU]([MENU_ID],[DESCRIPCION]) values ('mnu48','Sub Familia')
insert into [dbo].[SYS_MENU]([MENU_ID],[DESCRIPCION]) values ('MNU5','CATEGORIAS STOCK')
insert into [dbo].[SYS_MENU]([MENU_ID],[DESCRIPCION]) values ('MNU6','CLIENTES')
insert into [dbo].[SYS_MENU]([MENU_ID],[DESCRIPCION]) values ('MNU7','CODIGOS POSTALES')
insert into [dbo].[SYS_MENU]([MENU_ID],[DESCRIPCION]) values ('MNU8','CRITERIOS LOCATOR')
insert into [dbo].[SYS_MENU]([MENU_ID],[DESCRIPCION]) values ('MNU9','DEPOSITO')
insert into [dbo].[SYS_MENU]([MENU_ID],[DESCRIPCION]) values ('MNUABMESTACIONES','ESTACIONES')
insert into [dbo].[SYS_MENU]([MENU_ID],[DESCRIPCION]) values ('MNUADMIN','ADMINISTRACION')
insert into [dbo].[SYS_MENU]([MENU_ID],[DESCRIPCION]) values ('mnuAltaExistencias','Alta de Existencias')
insert into [dbo].[SYS_MENU]([MENU_ID],[DESCRIPCION]) values ('mnuAltaMaestros','Alta de Maestros')
insert into [dbo].[SYS_MENU]([MENU_ID],[DESCRIPCION]) values ('MNUARMADOPALLETFINAL','Armado Pallet Final')
insert into [dbo].[SYS_MENU]([MENU_ID],[DESCRIPCION]) values ('mnuAsignaTR','Asignacion de Transacciones')
insert into [dbo].[SYS_MENU]([MENU_ID],[DESCRIPCION]) values ('mnuBuscaProd','Buscador de Productos')
insert into [dbo].[SYS_MENU]([MENU_ID],[DESCRIPCION]) values ('MNUCAMBIOESTADO','CAMBIO DE ESTADO DE LA MERCADERIA')
insert into [dbo].[SYS_MENU]([MENU_ID],[DESCRIPCION]) values ('MNUCARGDOCMAN','Carga de Documento Manual')
insert into [dbo].[SYS_MENU]([MENU_ID],[DESCRIPCION]) values ('MNUCATLOG','CATEGORIA LOGICA')
insert into [dbo].[SYS_MENU]([MENU_ID],[DESCRIPCION]) values ('MNUCNFCLIENTE','Conf. Cliente')
insert into [dbo].[SYS_MENU]([MENU_ID],[DESCRIPCION]) values ('MNUCNFIMPRESORAS','Impresoras')
insert into [dbo].[SYS_MENU]([MENU_ID],[DESCRIPCION]) values ('MNUCONTENEDORAS','ABM UNIDADES CONTENEDORAS')
insert into [dbo].[SYS_MENU]([MENU_ID],[DESCRIPCION]) values ('MNUCONVMEDIDAS','Medidas')
insert into [dbo].[SYS_MENU]([MENU_ID],[DESCRIPCION]) values ('MNUCONVMONEDAS','Monedas')
insert into [dbo].[SYS_MENU]([MENU_ID],[DESCRIPCION]) values ('MNUCSOP','Consola Soporte')
insert into [dbo].[SYS_MENU]([MENU_ID],[DESCRIPCION]) values ('mnuDelDocTrans','Del Documento Interno')
insert into [dbo].[SYS_MENU]([MENU_ID],[DESCRIPCION]) values ('MNUDELDOCUMENTO','DEL DOCUMENTO')
insert into [dbo].[SYS_MENU]([MENU_ID],[DESCRIPCION]) values ('MNUDELWHSE','DEL WAREHOUSE')
insert into [dbo].[SYS_MENU]([MENU_ID],[DESCRIPCION]) values ('MNUDEPEXTERNO','Depósito Externo')
insert into [dbo].[SYS_MENU]([MENU_ID],[DESCRIPCION]) values ('MNUDIVISAS','Divisas')
insert into [dbo].[SYS_MENU]([MENU_ID],[DESCRIPCION]) values ('MNUEMPAQUETADO','Empaquetado')
insert into [dbo].[SYS_MENU]([MENU_ID],[DESCRIPCION]) values ('MNUEMPAQUETADOITSA','Empaquetado ITSA')
insert into [dbo].[SYS_MENU]([MENU_ID],[DESCRIPCION]) values ('MNUEMPLAZ','EMPLAZAMIENTO')
insert into [dbo].[SYS_MENU]([MENU_ID],[DESCRIPCION]) values ('MNUESTACIONES','Estaciones')
insert into [dbo].[SYS_MENU]([MENU_ID],[DESCRIPCION]) values ('MNUETIQUETASPOSICION','ETIQUETADOR DE POSICIONES')
insert into [dbo].[SYS_MENU]([MENU_ID],[DESCRIPCION]) values ('mnuFTP','ENVIO DE ARCHIVOS POR FTP')
insert into [dbo].[SYS_MENU]([MENU_ID],[DESCRIPCION]) values ('mnuimp','Importaciones')
insert into [dbo].[SYS_MENU]([MENU_ID],[DESCRIPCION]) values ('MNUIMPETIPICK',' Impresión de Etiquetas Picking ')
insert into [dbo].[SYS_MENU]([MENU_ID],[DESCRIPCION]) values ('MNUIMPRESIONDEREMITOS','Impresión de Remitos')
insert into [dbo].[SYS_MENU]([MENU_ID],[DESCRIPCION]) values ('MNUIMPRESIONDEREMITOSTRANSF','Impresión de Remitos - Transferencia')
insert into [dbo].[SYS_MENU]([MENU_ID],[DESCRIPCION]) values ('MNUIMPRETIPROD',' Impresión Etiqueta de Producto ')
insert into [dbo].[SYS_MENU]([MENU_ID],[DESCRIPCION]) values ('MNUINICIARESTACION','INICIAR NUEVA ESTACION')
insert into [dbo].[SYS_MENU]([MENU_ID],[DESCRIPCION]) values ('mnuLibPallet','Cambio de Cat.Logica, Est. de la Merc. y Propiedades')
insert into [dbo].[SYS_MENU]([MENU_ID],[DESCRIPCION]) values ('MNULOCATOREGRESO',' Locator Egreso ')
insert into [dbo].[SYS_MENU]([MENU_ID],[DESCRIPCION]) values ('MNUMEDIDAS','Medidas')
insert into [dbo].[SYS_MENU]([MENU_ID],[DESCRIPCION]) values ('MNUMOTIVOLOCKEOPOSICION','Motivo del Lockeo de la Posición')
insert into [dbo].[SYS_MENU]([MENU_ID],[DESCRIPCION]) values ('MNUMP','MAESTRO DE PRODUCTOS')
insert into [dbo].[SYS_MENU]([MENU_ID],[DESCRIPCION]) values ('MNUNIVELROTACION','NIVEL DE ROTACION')
insert into [dbo].[SYS_MENU]([MENU_ID],[DESCRIPCION]) values ('MNUPERFIL','PERFIL')
insert into [dbo].[SYS_MENU]([MENU_ID],[DESCRIPCION]) values ('MNUPOSLOCK','MONITOR DE POSICIONES LOCKEADAS')
insert into [dbo].[SYS_MENU]([MENU_ID],[DESCRIPCION]) values ('mnuPosProh','Posiciones Prohibidas / Clientes')
insert into [dbo].[SYS_MENU]([MENU_ID],[DESCRIPCION]) values ('mnuProductos','De los Productos')
insert into [dbo].[SYS_MENU]([MENU_ID],[DESCRIPCION]) values ('MNUREIMPRESION','Re-Impresión')
insert into [dbo].[SYS_MENU]([MENU_ID],[DESCRIPCION]) values ('MNUREPORTES','REPORTES')
insert into [dbo].[SYS_MENU]([MENU_ID],[DESCRIPCION]) values ('MNURI_INF','MNURI_INF')
insert into [dbo].[SYS_MENU]([MENU_ID],[DESCRIPCION]) values ('MNUROL','ROLES')
insert into [dbo].[SYS_MENU]([MENU_ID],[DESCRIPCION]) values ('MNURUTATR','RUTA DE TRANSACCIONES')
insert into [dbo].[SYS_MENU]([MENU_ID],[DESCRIPCION]) values ('MNUSALIR','Salir')
insert into [dbo].[SYS_MENU]([MENU_ID],[DESCRIPCION]) values ('MNUSEPARADORESTACIONES','Separador Estaciones')
insert into [dbo].[SYS_MENU]([MENU_ID],[DESCRIPCION]) values ('MNUTIPOSMOVIMIENTO','TIPOS DE MOVIMIENTOS')
insert into [dbo].[SYS_MENU]([MENU_ID],[DESCRIPCION]) values ('MNUVEHICULOS','Vehículos')
insert into [dbo].[SYS_MENU]([MENU_ID],[DESCRIPCION]) values ('MUNNAVPOS','MUNNAVPOS')
insert into [dbo].[SYS_MENU]([MENU_ID],[DESCRIPCION]) values ('PROCESOS','PROCESOS')
insert into [dbo].[SYS_MENU]([MENU_ID],[DESCRIPCION]) values ('PRUEBA_1','ABASTECIMIENTO')
insert into [dbo].[SYS_MENU]([MENU_ID],[DESCRIPCION]) values ('REPORTES','REPORTES')
insert into [dbo].[SYS_MENU]([MENU_ID],[DESCRIPCION]) values ('SERIESEXCEL','Series Excel')
insert into [dbo].[SYS_MENU]([MENU_ID],[DESCRIPCION]) values ('SISTEMA','SISTEMA')
insert into [dbo].[SYS_MENU]([MENU_ID],[DESCRIPCION]) values ('TABLAS','TABLAS')
insert into [dbo].[SYS_MENU]([MENU_ID],[DESCRIPCION]) values ('TAREAS_CURSO.btnActualizar','Actualizar')
insert into [dbo].[SYS_MENU]([MENU_ID],[DESCRIPCION]) values ('TAREAS_CURSO.btnLiberar','Liberar Tarea')
insert into [dbo].[SYS_MENU]([MENU_ID],[DESCRIPCION]) values ('TAREAS_CURSO.btSaltoPick','Quitar Salto de Picking')
insert into [dbo].[SYS_MENU]([MENU_ID],[DESCRIPCION]) values ('TAREAS_FINALIZADAS.btnActualizar','Frontera Ajustar Cantidad Pickeada')
insert into [dbo].[SYS_MENU]([MENU_ID],[DESCRIPCION]) values ('TAREAS_FINALIZADAS.btnAjustar','Frontera Ajustar Cantidad Pickeada')
insert into [dbo].[SYS_MENU]([MENU_ID],[DESCRIPCION]) values ('TAREAS_PENDIENTES.btnActualizar','Actualizar')
insert into [dbo].[SYS_MENU]([MENU_ID],[DESCRIPCION]) values ('TAREAS_PENDIENTES.btnCambiarUbic','Frontera Cambiar Ubicacion')
insert into [dbo].[SYS_MENU]([MENU_ID],[DESCRIPCION]) values ('TAREAS_PENDIENTES.btnSkip','Frontera Quitar Salto de picking')
insert into [dbo].[SYS_MENU]([MENU_ID],[DESCRIPCION]) values ('TRANSFERENCIAS','TRANSFERENCIAS')
insert into [dbo].[SYS_MENU]([MENU_ID],[DESCRIPCION]) values ('VENTANA','VENTANA')
insert into [dbo].[SYS_MENU]([MENU_ID],[DESCRIPCION]) values ('VERTICAL','ORGANIZAR VERTICALMENTE')
insert into [dbo].[SYS_MENU]([MENU_ID],[DESCRIPCION]) values ('VISOROPERACIONES','VISOR DE OPERACIONES')
insert into [dbo].[SYS_MENU]([MENU_ID],[DESCRIPCION]) values ('XENCRYPT','Encriptación')
