insert into [dbo].[SYS_PERFIL_USUARIO]([USUARIO_ID],[EMPLAZAMIENTO_DEFAULT],[DEPOSITO_DEFAULT]) values ('ADMIN','1','DEFAULT')
insert into [dbo].[SYS_PERFIL_USUARIO]([USUARIO_ID],[EMPLAZAMIENTO_DEFAULT],[DEPOSITO_DEFAULT]) values ('USER','1','DEFAULT')
