insert into [dbo].[UNIDAD_MEDIDA]([UNIDAD_ID],[DESCRIPCION]) values ('BAL','BALDE')
insert into [dbo].[UNIDAD_MEDIDA]([UNIDAD_ID],[DESCRIPCION]) values ('BC','BC')
insert into [dbo].[UNIDAD_MEDIDA]([UNIDAD_ID],[DESCRIPCION]) values ('BID','BIDON')
insert into [dbo].[UNIDAD_MEDIDA]([UNIDAD_ID],[DESCRIPCION]) values ('BL','BLISTERS')
insert into [dbo].[UNIDAD_MEDIDA]([UNIDAD_ID],[DESCRIPCION]) values ('BO','BOBINA')
insert into [dbo].[UNIDAD_MEDIDA]([UNIDAD_ID],[DESCRIPCION]) values ('BOB','BOBINA')
insert into [dbo].[UNIDAD_MEDIDA]([UNIDAD_ID],[DESCRIPCION]) values ('BOL','BOLSA')
insert into [dbo].[UNIDAD_MEDIDA]([UNIDAD_ID],[DESCRIPCION]) values ('BOT','BOTELLA')
insert into [dbo].[UNIDAD_MEDIDA]([UNIDAD_ID],[DESCRIPCION]) values ('BULTO','BULTOS')
insert into [dbo].[UNIDAD_MEDIDA]([UNIDAD_ID],[DESCRIPCION]) values ('CA','CAJAS')
insert into [dbo].[UNIDAD_MEDIDA]([UNIDAD_ID],[DESCRIPCION]) values ('CJ','CAJONES')
insert into [dbo].[UNIDAD_MEDIDA]([UNIDAD_ID],[DESCRIPCION]) values ('CJI','CAJON IMPSAT')
insert into [dbo].[UNIDAD_MEDIDA]([UNIDAD_ID],[DESCRIPCION]) values ('CJN','CAJON')
insert into [dbo].[UNIDAD_MEDIDA]([UNIDAD_ID],[DESCRIPCION]) values ('CM','CENTIMETROS')
insert into [dbo].[UNIDAD_MEDIDA]([UNIDAD_ID],[DESCRIPCION]) values ('CS','CAJAS')
insert into [dbo].[UNIDAD_MEDIDA]([UNIDAD_ID],[DESCRIPCION]) values ('DOBL','PALLET DOBLE')
insert into [dbo].[UNIDAD_MEDIDA]([UNIDAD_ID],[DESCRIPCION]) values ('DZ','DOCENA')
insert into [dbo].[UNIDAD_MEDIDA]([UNIDAD_ID],[DESCRIPCION]) values ('EA','CADA UNO')
insert into [dbo].[UNIDAD_MEDIDA]([UNIDAD_ID],[DESCRIPCION]) values ('ET','ESTANTE')
insert into [dbo].[UNIDAD_MEDIDA]([UNIDAD_ID],[DESCRIPCION]) values ('ET1','ESTANTE VIRTUAL')
insert into [dbo].[UNIDAD_MEDIDA]([UNIDAD_ID],[DESCRIPCION]) values ('FPA','FUNA PAPEL')
insert into [dbo].[UNIDAD_MEDIDA]([UNIDAD_ID],[DESCRIPCION]) values ('FT','PIES')
insert into [dbo].[UNIDAD_MEDIDA]([UNIDAD_ID],[DESCRIPCION]) values ('G','GRAMOS')
insert into [dbo].[UNIDAD_MEDIDA]([UNIDAD_ID],[DESCRIPCION]) values ('KG','KILOGRAMO')
insert into [dbo].[UNIDAD_MEDIDA]([UNIDAD_ID],[DESCRIPCION]) values ('KN','KILOS NETOS')
insert into [dbo].[UNIDAD_MEDIDA]([UNIDAD_ID],[DESCRIPCION]) values ('LAT','LATA')
insert into [dbo].[UNIDAD_MEDIDA]([UNIDAD_ID],[DESCRIPCION]) values ('LB','LIBRAS')
insert into [dbo].[UNIDAD_MEDIDA]([UNIDAD_ID],[DESCRIPCION]) values ('LT','LITROS')
insert into [dbo].[UNIDAD_MEDIDA]([UNIDAD_ID],[DESCRIPCION]) values ('M3','METROS CÚBICOS')
insert into [dbo].[UNIDAD_MEDIDA]([UNIDAD_ID],[DESCRIPCION]) values ('ML','MILILITROS')
insert into [dbo].[UNIDAD_MEDIDA]([UNIDAD_ID],[DESCRIPCION]) values ('MP','MIL PIEZAS')
insert into [dbo].[UNIDAD_MEDIDA]([UNIDAD_ID],[DESCRIPCION]) values ('MT','METROS')
insert into [dbo].[UNIDAD_MEDIDA]([UNIDAD_ID],[DESCRIPCION]) values ('PACK','PRODUCTO POR PACK')
insert into [dbo].[UNIDAD_MEDIDA]([UNIDAD_ID],[DESCRIPCION]) values ('PAL','PALLET')
insert into [dbo].[UNIDAD_MEDIDA]([UNIDAD_ID],[DESCRIPCION]) values ('PAQ','PAQUETES')
insert into [dbo].[UNIDAD_MEDIDA]([UNIDAD_ID],[DESCRIPCION]) values ('PL','PALLET')
insert into [dbo].[UNIDAD_MEDIDA]([UNIDAD_ID],[DESCRIPCION]) values ('PLA','PLANCHA')
insert into [dbo].[UNIDAD_MEDIDA]([UNIDAD_ID],[DESCRIPCION]) values ('PLMZ','PALLET MEZCLA')
insert into [dbo].[UNIDAD_MEDIDA]([UNIDAD_ID],[DESCRIPCION]) values ('PQ','PAQUETE')
insert into [dbo].[UNIDAD_MEDIDA]([UNIDAD_ID],[DESCRIPCION]) values ('PR','PAR')
insert into [dbo].[UNIDAD_MEDIDA]([UNIDAD_ID],[DESCRIPCION]) values ('PZA','PIEZA')
insert into [dbo].[UNIDAD_MEDIDA]([UNIDAD_ID],[DESCRIPCION]) values ('RL','ROLLO')
insert into [dbo].[UNIDAD_MEDIDA]([UNIDAD_ID],[DESCRIPCION]) values ('RM','RESMA')
insert into [dbo].[UNIDAD_MEDIDA]([UNIDAD_ID],[DESCRIPCION]) values ('RO','ROLLO')
insert into [dbo].[UNIDAD_MEDIDA]([UNIDAD_ID],[DESCRIPCION]) values ('SAC','SACO')
insert into [dbo].[UNIDAD_MEDIDA]([UNIDAD_ID],[DESCRIPCION]) values ('SOB','SOBRE')
insert into [dbo].[UNIDAD_MEDIDA]([UNIDAD_ID],[DESCRIPCION]) values ('TAM','TAMBOR')
insert into [dbo].[UNIDAD_MEDIDA]([UNIDAD_ID],[DESCRIPCION]) values ('TB','TAMBOR')
insert into [dbo].[UNIDAD_MEDIDA]([UNIDAD_ID],[DESCRIPCION]) values ('U','UNIDADES')
insert into [dbo].[UNIDAD_MEDIDA]([UNIDAD_ID],[DESCRIPCION]) values ('UN','UNIDADES')
insert into [dbo].[UNIDAD_MEDIDA]([UNIDAD_ID],[DESCRIPCION]) values ('','')