insert into [dbo].[ZONA]([ZONA_ID],[DESCRIPCION]) values ('0','0')
insert into [dbo].[ZONA]([ZONA_ID],[DESCRIPCION]) values ('01','01')
insert into [dbo].[ZONA]([ZONA_ID],[DESCRIPCION]) values ('02','02')
insert into [dbo].[ZONA]([ZONA_ID],[DESCRIPCION]) values ('03','03')
insert into [dbo].[ZONA]([ZONA_ID],[DESCRIPCION]) values ('1','CALLAO')
insert into [dbo].[ZONA]([ZONA_ID],[DESCRIPCION]) values ('2','LAMPA')
insert into [dbo].[ZONA]([ZONA_ID],[DESCRIPCION]) values ('3','ÑUÑOA')
insert into [dbo].[ZONA]([ZONA_ID],[DESCRIPCION]) values ('4','NUEVA IMPERIAL')
insert into [dbo].[ZONA]([ZONA_ID],[DESCRIPCION]) values ('5','COBQUECURA')
insert into [dbo].[ZONA]([ZONA_ID],[DESCRIPCION]) values ('6','REGION METROPOLITANA')