

INSERT INTO STATUS_DOCUMENTO VALUES ('D05','DOCUMENTO CON CABECERA SIN ITEMS','1',NULL,'D10')
INSERT INTO STATUS_DOCUMENTO VALUES ('D10','DOCUMENTO CREADO','0','D05','D20')
INSERT INTO STATUS_DOCUMENTO VALUES ('D15','DOCUMENTO PENDIENTE','0','D10',NULL)
INSERT INTO STATUS_DOCUMENTO VALUES ('D20','DOCUMENTO CONFIRMADO','0','D10',NULL)
INSERT INTO STATUS_DOCUMENTO VALUES ('D30','DOCUMENTO CON TRANSACCIONES ASOCIADAS','0',NULL,NULL)
INSERT INTO STATUS_DOCUMENTO VALUES ('D35','DOCUMENTO PARCIALMENTE PROCESADO','0','D30','D40')
INSERT INTO STATUS_DOCUMENTO VALUES ('D40','DOCUMENTO FINALIZADO','0',NULL,NULL)
INSERT INTO STATUS_DOCUMENTO VALUES ('D99','DOCUMENTO CANCELADO','0',NULL,NULL)
INSERT INTO STATUS_DOCUMENTO VALUES ('T10','TRANSACCION ACTIVA','1',NULL,'T20')
INSERT INTO STATUS_DOCUMENTO VALUES ('T15','TRANSACCION CANCELADA','0','T10',NULL)
INSERT INTO STATUS_DOCUMENTO VALUES ('T20','TRANSACCION CON STOCK ACTUALIZADO','0','T10','T40')
INSERT INTO STATUS_DOCUMENTO VALUES ('T40','TRANSACCION FINALIZADA','0','T10',NULL)
