/****** Object:  Index [IDX_SIDD_ESTADOGT]    Script Date: 06/19/2013 14:18:40 ******/
IF  EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[SYS_INT_DET_DOCUMENTO]') AND name = N'IDX_SIDD_ESTADOGT')
DROP INDEX [IDX_SIDD_ESTADOGT] ON [dbo].[SYS_INT_DET_DOCUMENTO] WITH ( ONLINE = OFF )
GO

/****** Object:  Index [IDX_SIDD_ESTADOGT]    Script Date: 06/19/2013 14:18:42 ******/
CREATE NONCLUSTERED INDEX [IDX_SIDD_ESTADOGT] ON [dbo].[SYS_INT_DET_DOCUMENTO] 
(
	[ESTADO_GT] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = ON, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO