IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[ValidaProductoIngresadoEmpaque]') AND type in (N'P', N'PC'))
DROP PROCEDURE [dbo].[ValidaProductoIngresadoEmpaque]
GO

CREATE PROCEDURE [dbo].[ValidaProductoIngresadoEmpaque]
(@CLIENTE_ID		VARCHAR(15) OUTPUT
,@VIAJE_ID			VARCHAR(100) OUTPUT
,@PRODUCTO_ID		VARCHAR(30) OUTPUT
,@RESULTADO			int OUTPUT
,@NRO_LOTE			VARCHAR(100) OUTPUT
,@NRO_PARTIDA		VARCHAR(100) OUTPUT
,@NRO_SERIE			VARCHAR(50) OUTPUT)
AS
BEGIN
	DECLARE @CANT NUMERIC(20,0)

	SET @CANT=0
	
	IF (@NRO_PARTIDA='')BEGIN
		SET @NRO_PARTIDA='9999999'
	END
	
	IF (@NRO_LOTE='')BEGIN
		SET @NRO_LOTE='9999999'
	END
	
	IF (@NRO_SERIE='')BEGIN
		SET @NRO_SERIE='9999999'
	END	

	SELECT @CANT = COUNT(*) FROM
		(SELECT	DISTINCT P.PRODUCTO_ID, P.NRO_LOTE, P.NRO_PARTIDA, P.NRO_SERIE
		FROM	PICKING P
		INNER JOIN DET_DOCUMENTO DD ON (P.DOCUMENTO_ID = DD.DOCUMENTO_ID AND P.NRO_LINEA = DD.NRO_LINEA)
		INNER JOIN DOCUMENTO D ON (DD.DOCUMENTO_ID = D.DOCUMENTO_ID)
		WHERE	P.CLIENTE_ID = @CLIENTE_ID
				AND D.NRO_REMITO = @VIAJE_ID
				AND P.PRODUCTO_ID = @PRODUCTO_ID
				AND (isnull(P.NRO_LOTE,'9999999') = @NRO_LOTE or @NRO_LOTE='' or @NRO_LOTE IS NULL)
				AND (ISNULL(P.NRO_PARTIDA,'9999999') = @NRO_PARTIDA or @NRO_PARTIDA='' OR @NRO_PARTIDA IS NULL)
				AND (isnull(P.NRO_SERIE,'9999999') = @NRO_SERIE or @NRO_SERIE ='' OR @NRO_SERIE IS NULL)
				) X
	IF @CANT=1
		SET @RESULTADO=1
	ELSE
		SET @RESULTADO=0
END

GO


