ALTER TABLE TMP_EMPAQUE_CONTENEDORA
ADD ESTADO VARCHAR(100)
GO
ALTER TABLE TMP_EMPAQUE_CONTENEDORA
ADD NRO_UCDESCONSOLIDACION VARCHAR(100)
GO
ALTER TABLE TMP_EMPAQUE_CONTENEDORA
ADD FECHA_DESCONSOLIDACION DATETIME
GO
ALTER TABLE TMP_EMPAQUE_CONTENEDORA
ADD USUARIO_DESCONSOLIDACION VARCHAR(20)
GO
ALTER TABLE TMP_EMPAQUE_CONTENEDORA
ADD TERMINAL_DESCONSOLIDACION VARCHAR(20)
