--DROP PROCEDURE DBO.FRONTERA_VALIDACION_MULTICLIENTE
CREATE PROCEDURE DBO.FRONTERA_VALIDACION_MULTICLIENTE
	@VIAJE_ID	VARCHAR(100) OUTPUT
AS
BEGIN
	DECLARE @CONT	NUMERIC(20,0)
	
	SELECT	@CONT=COUNT(DISTINCT X.CONF)
	FROM	(	SELECT	CAST(ISNULL(FLG_DESCONSOLIDACION,'0')AS VARCHAR)
						+ CAST(ISNULL(TIPO_EMPAQUETADO_ID,'0')AS VARCHAR)
						+ CAST(ISNULL(FLG_EMPAQUETADO,'0')AS VARCHAR)
						+ CAST(ISNULL(FLG_DISTRIBUCION,'0')AS VARCHAR)
						+ CAST(ISNULL(FLG_CONTROL_EXP,'0')AS VARCHAR)CONF
				FROM	CLIENTE_PARAMETROS CP
				WHERE	EXISTS (SELECT	1
								FROM	SYS_INT_DOCUMENTO P
								WHERE	P.CODIGO_VIAJE=@VIAJE_ID
										AND CP.CLIENTE_ID=P.CLIENTE_ID))X
	IF @CONT>1 BEGIN										
		RAISERROR('Los clientes de la Ola %s, poseen diferentes configuraciones de egreso. Por favor verifique las mismas en la pantalla de Configuracion por Cliente.',16,1,@viaje_id)
	END
	IF @CONT=0 BEGIN										
		RAISERROR('No se encontro el Pedido: %s, presione Refrescar y vuelva a intentar la operacion.',16,1,@viaje_id)
	END	
END