ALTER TABLE RL_TRANSACCION_ESTACION
ADD	IMPRIMIR_COMP_INGRESO VARCHAR(1)
GO
INSERT INTO sys_tabColumns VALUES('RL_TRANSACCION_ESTACION',	'IMPRIMIR_COMP_INGRESO',	29,	'CHAR',	'Y',	1,	NULL,	NULL,	1,	NULL)

