BEGIN
	DECLARE @EX	NUMERIC;
	
	SELECT	@EX=COUNT(*)
	FROM	TIPO_COMPROBANTE
	WHERE	TIPO_COMPROBANTE_ID='E08'
	
	IF @EX=0 BEGIN
		INSERT INTO TIPO_COMPROBANTE VALUES('E08','EGRESO GARANTIAS','EGR','0','1');
	END;
END;