--TRANSACCIONAL INPUT.
ALTER TABLE SYS_INT_DOCUMENTO
ADD INFO_ADICIONAL_4 varchar(100);
GO
ALTER TABLE SYS_INT_DOCUMENTO
ADD INFO_ADICIONAL_5 varchar(100);
GO
ALTER TABLE SYS_INT_DOCUMENTO
ADD INFO_ADICIONAL_6 varchar(100);
GO
--HISTORICO INPUT.
ALTER TABLE SYS_INT_DOCUMENTO_HISTORICO
ADD INFO_ADICIONAL_4 varchar(100);
GO
ALTER TABLE SYS_INT_DOCUMENTO_HISTORICO
ADD INFO_ADICIONAL_5 varchar(100);
GO
ALTER TABLE SYS_INT_DOCUMENTO_HISTORICO
ADD INFO_ADICIONAL_6 varchar(100);
GO
--TRANSACCION OUTPUT.
ALTER TABLE SYS_DEV_DOCUMENTO
ADD INFO_ADICIONAL_4 varchar(100);
GO
ALTER TABLE SYS_DEV_DOCUMENTO
ADD INFO_ADICIONAL_5 varchar(100);
GO
ALTER TABLE SYS_DEV_DOCUMENTO
ADD INFO_ADICIONAL_6 varchar(100);
GO
--HISTORICO OUTPUT.
ALTER TABLE SYS_DEV_DOCUMENTO_HISTORICO
ADD INFO_ADICIONAL_4 varchar(100);
GO
ALTER TABLE SYS_DEV_DOCUMENTO_HISTORICO
ADD INFO_ADICIONAL_5 varchar(100);
GO
ALTER TABLE SYS_DEV_DOCUMENTO_HISTORICO
ADD INFO_ADICIONAL_6 varchar(100);
GO