/****** Object:  StoredProcedure [dbo].[GET_FLG_FRACCIONABLE]    Script Date: 06/06/2013 11:53:19 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[GET_FLG_FRACCIONABLE]') AND type in (N'P', N'PC'))
DROP PROCEDURE [dbo].[GET_FLG_FRACCIONABLE]
GO

/****** Object:  StoredProcedure [dbo].[GET_FLG_FRACCIONABLE]    Script Date: 06/06/2013 11:53:19 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[GET_FLG_FRACCIONABLE]
@CLIENTE_ID		 VARCHAR(15),
@PRODUCTO_ID	 VARCHAR(30),
@FLG_FRACCIONABLE VARCHAR(1) OUTPUT
AS
BEGIN
	SELECT	@FLG_FRACCIONABLE=isnull(FRACCIONABLE,'0')
	FROM	PRODUCTO
	WHERE	CLIENTE_ID = @CLIENTE_ID
			AND PRODUCTO_ID = @PRODUCTO_ID
END--FIN PROCEDURE


GO


