ALTER TABLE CLIENTE_PARAMETROS ADD FLG_VALIDA_RECEPCION_OC VARCHAR(1)DEFAULT('0')

GO
insert into sys_tabColumns values('CLIENTE_PARAMETROS',	'FLG_VALIDA_RECEPCION_OC',	26,	'CHAR',	'Y',	1,	NULL,	NULL,	1,	NULL)

GO
insert into SYS_DET_TABLA values('CLIENTE_PARAMETROS',	'FLG_VALIDA_RECEPCION_OC',	'Ingreso - Contra O.C.',	'S',	1,	0)
