CREATE VIEW DBO.view_web_egreso_cumplimiento
as
	SELECT	distinct
			SD.CLIENTE_ID				cliente_id,
			DOC.FECHA_ALTA_GTW			anio,
			doc.FECHA_ALTA_GTW			mes,
			SD.FECHA_CPTE 				fecha_pedido,
			SD.TIPO_DOCUMENTO_ID		tipo_egreso,
			SDD.DOC_EXT					pedido,
			SD.CODIGO_VIAJE				ola_viaje,
			S.NOMBRE					destinatario,
			SDD.PRODUCTO_ID				articulo,
			PR.DESCRIPCION				descripcion,
			SDD.CANTIDAD_SOLICITADA		cantidad_solitada,
			ISNULL(PIK.CANT,0)			cantidad_asignada,
			ISNULL(PIK.CANT,0)			cantidad_egresada,
			sdd.CANTIDAD_SOLICITADA-ISNULL(pik.cant,0)
										as diferencia
	FROM	SYS_INT_DOCUMENTO SD INNER JOIN SYS_INT_DET_DOCUMENTO SDD
			ON(SD.CLIENTE_ID=SDD.CLIENTE_ID AND SD.DOC_EXT=SDD.DOC_EXT)
			inner JOIN (SELECT	DOCUMENTO_ID,FECHA_ALTA_GTW
						FROM	DOCUMENTO 
						where	TIPO_OPERACION_ID='EGR'
			)DOC 
			ON(SDD.DOCUMENTO_ID=DOC.DOCUMENTO_ID)
			INNER JOIN SUCURSAL S
			ON(SD.CLIENTE_ID=S.CLIENTE_ID AND SD.AGENTE_ID=S.SUCURSAL_ID)
			INNER JOIN PRODUCTO PR
			ON(SDD.CLIENTE_ID=PR.CLIENTE_ID AND SDD.PRODUCTO_ID=PR.PRODUCTO_ID)
			INNER JOIN(	SELECT	DOCUMENTO_ID,PRODUCTO_ID,SUM(CANT_CONFIRMADA)AS CANT
						FROM	PICKING
						GROUP BY
								DOCUMENTO_ID,PRODUCTO_ID
			)PIK
			ON(SDD.DOCUMENTO_ID=PIK.DOCUMENTO_ID AND SDD.PRODUCTO_ID=PIK.PRODUCTO_ID)
