alter table producto add NRO_PARTIDA_AUTOMATICO CHAR(1) DEFAULT ('0');

INSERT INTO SYS_DET_TABLA VALUES('PRODUCTO','NRO_PARTIDA_AUTOMATICO','Nro. Partida Automatico','S','1','0');

INSERT INTO sys_tabColumns VALUES('PRODUCTO',	'NRO_PARTIDA_AUTOMATICO',	60,	'VARCHAR2',	'N',	1,	NULL,	NULL,	1,	NULL);

DELETE FROM SYS_DET_TABLA WHERE TABLA_ID='PRODUCTO' AND CAMPO='SUBCODIGO_2';
--PRODUCTO	SUBCODIGO_2	DUN 14	S	25	0

DELETE FROM sys_tabColumns WHERE TABLE_NAME='PRODUCTO' AND COLUMN_NAME ='SUBCODIGO_2';
--PRODUCTO	SUBCODIGO_2	5	VARCHAR2	Y	50	NULL	NULL	50	NULL

