/****** Object:  StoredProcedure [dbo].[VALIDAR_SERIE_INGRESADA]    Script Date: 10/07/2014 16:49:14 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[VALIDAR_SERIE_INGRESADA]') AND type in (N'P', N'PC'))
DROP PROCEDURE [dbo].[VALIDAR_SERIE_INGRESADA]
GO

CREATE PROCEDURE [dbo].[VALIDAR_SERIE_INGRESADA]
(@CLIENTE_ID VARCHAR(15), @PRODUCTO_ID VARCHAR(30),@NRO_SERIE VARCHAR(50),@VIAJE_ID VARCHAR(100), @OUT VARCHAR(1) OUTPUT)
AS
BEGIN

	IF EXISTS (	SELECT	1 
				FROM	PICKING P INNER JOIN DOCUMENTO D
						ON(P.DOCUMENTO_ID=D.DOCUMENTO_ID)
				WHERE	P.CLIENTE_ID = @CLIENTE_ID 
						AND P.NRO_SERIE = @NRO_SERIE 
						AND P.PRODUCTO_ID = @PRODUCTO_ID 
						AND P.FECHA_FIN IS NOT NULL 
						AND D.STATUS<>'D40'
				)
		SET @OUT = '0'
	ELSE
		SET @OUT = '1'
END

GO


