/****** OBJECT:  STOREDPROCEDURE [DBO].[INSERTARSERIELOG]    SCRIPT DATE: 10/09/2014 16:03:52 ******/
IF  EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[DBO].[MOB_INSERTARSERIELOG]') AND TYPE IN (N'P', N'PC'))
DROP PROCEDURE [DBO].[MOB_INSERTARSERIELOG]
GO


CREATE PROCEDURE [DBO].[MOB_INSERTARSERIELOG]
  (
      @IDPROCESO         NUMERIC(20,0) OUTPUT,
      @CLIENTE_ID        VARCHAR(15) OUTPUT,
      @NRO_BULTO         VARCHAR(100) OUTPUT,
      @PRODUCTO_ID       VARCHAR(30) OUTPUT,
      @SERIE             VARCHAR(50) OUTPUT,
      @TERMINAL          VARCHAR(100) OUTPUT,
      @USUARIO           VARCHAR(100) OUTPUT,
      @ARCHIVO           VARCHAR(100) OUTPUT
  )
  AS
  BEGIN
	
	DECLARE @CONT	NUMERIC(20,0)
	
	IF @PRODUCTO_ID IS NULL BEGIN
		SELECT	@PRODUCTO_ID=DD.PRODUCTO_ID 
		FROM	DET_DOCUMENTO DD
		WHERE	DD.CLIENTE_ID=@CLIENTE_ID 
				AND DD.NRO_BULTO =@NRO_BULTO;	
	END
	
	DELETE FROM CargaSeriesLog WHERE IDPROCESO=@IDPROCESO AND CLIENTE_ID=@CLIENTE_ID AND PRODUCTO_ID=@PRODUCTO_ID AND NRO_BULTO=@NRO_BULTO AND SERIE=@SERIE;
	
	/*CONTROLO LA SERIE*/
	SELECT	@CONT=COUNT(*)
	FROM	DET_DOCUMENTO DD INNER JOIN DET_DOCUMENTO_TRANSACCION DDT
			ON(DD.DOCUMENTO_ID=DDT.DOCUMENTO_ID AND DD.NRO_LINEA=DDT.NRO_LINEA_DOC)
			INNER JOIN RL_DET_DOC_TRANS_POSICION RL
			ON(DDT.DOC_TRANS_ID=RL.DOC_TRANS_ID AND DDT.NRO_LINEA_TRANS=RL.NRO_LINEA_TRANS)
	WHERE	DD.CLIENTE_ID=@CLIENTE_ID
			AND REPLACE(DD.PRODUCTO_ID,'-','')=REPLACE(@PRODUCTO_ID,'-','')
			AND DD.NRO_SERIE=@SERIE	
    
    IF @CONT>0 BEGIN
		RAISERROR('SERIE EXISTENTE.',16,1)
		RETURN
    END 
    
    IF (ISNULL(@IDPROCESO,0)<>0 AND ISNULL(@CLIENTE_ID,'')<>'' AND ISNULL(@NRO_BULTO,'')<>'' AND ISNULL(@PRODUCTO_ID,'')<>'' AND ISNULL(@SERIE,'')<>'' AND ISNULL(@TERMINAL,'')<>'' AND ISNULL(@USUARIO,'')<>'' AND ISNULL(@ARCHIVO,'')<>'')
    INSERT INTO CARGASERIESLOG VALUES
    (@IDPROCESO,@CLIENTE_ID,@NRO_BULTO,@PRODUCTO_ID,@SERIE,GETDATE(),@TERMINAL,@USUARIO,@ARCHIVO,'0','0')
  
  END


GO


