/****** Object:  StoredProcedure [dbo].[VERIFICA_CONTENEDORA_POS_TR]    Script Date: 10/10/2014 10:30:51 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[VERIFICA_CONTENEDORA_POS_TR]') AND type in (N'P', N'PC'))
DROP PROCEDURE [dbo].[VERIFICA_CONTENEDORA_POS_TR]
GO

CREATE     PROCEDURE [dbo].[VERIFICA_CONTENEDORA_POS_TR]
@POSICION_O		AS VARCHAR(45),
@CONTENEDORA	AS VARCHAR(100),
@PALLET			AS VARCHAR(100)OUTPUT
AS
BEGIN
	DECLARE @CONTROL 	AS INT
	DECLARE @EXISTE 	AS INT

	--SE AGREGAN ESTAS LINEAS PARA CONTROLAR LA EXISTENCIA DEL PALLET.

	SELECT	@EXISTE = COUNT(DD.NRO_BULTO)
	FROM	DET_DOCUMENTO DD INNER JOIN DET_DOCUMENTO_TRANSACCION DDT
			ON(DD.DOCUMENTO_ID=DDT.DOCUMENTO_ID AND DD.NRO_LINEA=DDT.NRO_LINEA_DOC)
			INNER JOIN RL_DET_DOC_TRANS_POSICION RL 
			ON(DDT.DOC_TRANS_ID=RL.DOC_TRANS_ID AND DDT.NRO_LINEA_TRANS=RL.NRO_LINEA_TRANS)
	WHERE 	NRO_BULTO = LTRIM(RTRIM(UPPER(@CONTENEDORA)))

	SELECT 	@PALLET=DD.PROP1
	FROM	DET_DOCUMENTO DD 
			INNER JOIN DET_DOCUMENTO_TRANSACCION DDT
			ON(DD.DOCUMENTO_ID=DDT.DOCUMENTO_ID AND DD.NRO_LINEA=DDT.NRO_LINEA_DOC)
			INNER JOIN RL_DET_DOC_TRANS_POSICION RL
			ON(DDT.DOC_TRANS_ID=RL.DOC_TRANS_ID AND DDT.NRO_LINEA_TRANS=RL.NRO_LINEA_TRANS)
	WHERE	((PROP1=LTRIM(RTRIM(UPPER(@CONTENEDORA))))OR(NRO_BULTO = LTRIM(RTRIM(UPPER(@CONTENEDORA)))))
			AND RL.NAVE_ACTUAL=	(	SELECT 	NAVE_ID
									FROM 	NAVE
									WHERE	NAVE_COD=LTRIM(RTRIM(UPPER(@POSICION_O)))
								)
			OR RL.POSICION_ACTUAL=	(	SELECT 	TOP 1 POSICION_ID
										FROM 	POSICION
										WHERE	POSICION_COD=LTRIM(RTRIM(UPPER(@POSICION_O)))
									)
			AND RL.CANTIDAD >0

	IF @EXISTE =0
	BEGIN
		/*SET @EXISTE=NULL
		SELECT	@EXISTE = COUNT(DD.PROP1)
		FROM	DET_DOCUMENTO DD INNER JOIN DET_DOCUMENTO_TRANSACCION DDT
				ON(DD.DOCUMENTO_ID=DDT.DOCUMENTO_ID AND DD.NRO_LINEA=DDT.NRO_LINEA_DOC)
				INNER JOIN RL_DET_DOC_TRANS_POSICION RL 
				ON(DDT.DOC_TRANS_ID=RL.DOC_TRANS_ID AND DDT.NRO_LINEA_TRANS=RL.NRO_LINEA_TRANS)
		WHERE 	DD.PROP1 = LTRIM(RTRIM(UPPER(@CONTENEDORA)))*/
		RAISERROR('La contenedora ingresada no existe.',16,1)
		RETURN
	END

	SELECT 	@CONTROL=COUNT(RL.RL_ID)
	FROM	DET_DOCUMENTO DD 
			INNER JOIN DET_DOCUMENTO_TRANSACCION DDT
			ON(DD.DOCUMENTO_ID=DDT.DOCUMENTO_ID AND DD.NRO_LINEA=DDT.NRO_LINEA_DOC)
			INNER JOIN RL_DET_DOC_TRANS_POSICION RL
			ON(DDT.DOC_TRANS_ID=RL.DOC_TRANS_ID AND DDT.NRO_LINEA_TRANS=RL.NRO_LINEA_TRANS)
	WHERE	NRO_BULTO=LTRIM(RTRIM(UPPER(@CONTENEDORA))) 
			AND RL.NAVE_ACTUAL=	(	SELECT 	NAVE_ID
									FROM 	NAVE
									WHERE	NAVE_COD=LTRIM(RTRIM(UPPER(@POSICION_O)))
								)
			OR RL.POSICION_ACTUAL=	(	SELECT 	TOP 1 POSICION_ID
										FROM 	POSICION
										WHERE	POSICION_COD=LTRIM(RTRIM(UPPER(@POSICION_O)))
									)
			AND RL.CANTIDAD >0


	IF @CONTROL=0
		BEGIN
			SET @CONTROL=NULL

			SELECT 	@CONTROL=COUNT(RL.RL_ID)
			FROM	DET_DOCUMENTO DD 
					INNER JOIN DET_DOCUMENTO_TRANSACCION DDT
					ON(DD.DOCUMENTO_ID=DDT.DOCUMENTO_ID AND DD.NRO_LINEA=DDT.NRO_LINEA_DOC)
					INNER JOIN RL_DET_DOC_TRANS_POSICION RL
					ON(DDT.DOC_TRANS_ID=RL.DOC_TRANS_ID AND DDT.NRO_LINEA_TRANS=RL.NRO_LINEA_TRANS)
			WHERE	PROP1=LTRIM(RTRIM(UPPER(@CONTENEDORA))) 
					AND RL.NAVE_ACTUAL=	(	SELECT 	NAVE_ID
											FROM 	NAVE
											WHERE	NAVE_COD=LTRIM(RTRIM(UPPER(@POSICION_O)))
										)
					OR RL.POSICION_ACTUAL=	(	SELECT 	TOP 1 POSICION_ID
												FROM 	POSICION
												WHERE	POSICION_COD=LTRIM(RTRIM(UPPER(@POSICION_O)))
											)
					AND RL.CANTIDAD >0


			IF @CONTROL=0
			BEGIN
				RAISERROR('1-La contenedora no esta en la posicion especificada.',16,1)
				RETURN
			END
			ELSE
			BEGIN
				SELECT 	@PALLET=DD.PROP1
				FROM	DET_DOCUMENTO DD 
						INNER JOIN DET_DOCUMENTO_TRANSACCION DDT
						ON(DD.DOCUMENTO_ID=DDT.DOCUMENTO_ID AND DD.NRO_LINEA=DDT.NRO_LINEA_DOC)
						INNER JOIN RL_DET_DOC_TRANS_POSICION RL
						ON(DDT.DOC_TRANS_ID=RL.DOC_TRANS_ID AND DDT.NRO_LINEA_TRANS=RL.NRO_LINEA_TRANS)
				WHERE	PROP1=LTRIM(RTRIM(UPPER(@CONTENEDORA))) 
						AND RL.NAVE_ACTUAL=	(	SELECT 	NAVE_ID
												FROM 	NAVE
												WHERE	NAVE_COD=LTRIM(RTRIM(UPPER(@POSICION_O)))
											)
						OR RL.POSICION_ACTUAL=	(	SELECT 	TOP 1 POSICION_ID
													FROM 	POSICION
													WHERE	POSICION_COD=LTRIM(RTRIM(UPPER(@POSICION_O)))
												)
						AND RL.CANTIDAD >0

			END
		END

	SET @CONTROL=NULL
	SELECT	@CONTROL=COUNT(P.PICKING_ID)
	FROM	PICKING P
			INNER JOIN DET_DOCUMENTO DD ON(P.DOCUMENTO_ID=DD.DOCUMENTO_ID AND P.NRO_LINEA = DD.NRO_LINEA)
	WHERE	CANT_CONFIRMADA IS NULL
			AND NRO_BULTO=LTRIM(RTRIM(UPPER(@CONTENEDORA))) 
			AND POSICION_COD = @POSICION_O

	IF (@CONTROL>0)
	BEGIN
		RAISERROR('1-La contenedora aun tiene tareas de picking pendientes.',16,1)
		RETURN
	END
END

GO


